### ISSUE TITLE
Expose TypeScript Enum containing icon types

### ISSUE THREAD

**Issue by rubenduiveman** [lucide-icons/lucide#1005]
(Using Vue)

When consuming icons via a generic component, like `<component :is="type" />`, icon is a string (so consuming the generic component like `<Icon type="Anchor" />`. This allows consumers to input anything they like, and the component won't resolve if an icon with the supplied name is not found. It would be great to have a TypeScript Enum containing all possible icons, so we could do `<component :is="LucideIcon.Anchor" />`. Is this possible?

**Comment by ericfennis** [comment]
You can achieve this with without using enums.

```vue
<script setup>
import { computed, defineProps } from 'vue';
import * as icons from "lucide-vue-next";

const props = defineProps({
  name: {
    type: String,
    required: true
  },
})

const icon = computed(() => icons[props.name]);
</script>

<template>
    <component :is="icon" />
</template>
```
See docs: 
https://lucide.dev/docs/lucide-vue-next#icon-component-example

**Comment by rubenduiveman** [comment]
Hi!

Thanks for your reply, and I already use the custom component. Maybe my question wasn't clear - I'll use the example you gave:

1. I would like type safety on the "name" property via an Enum. I could use the component with a name that does not exist, like `<icon name="idontexist" />`. I would like to use an Enum to limit the options, and I think this enum should be provided by the library the icons come from.
2. It's not clear how icon names are resolved. For example: I should use `name="MoreHorizontal"` when I want to use the ["more-horizontal" icon](https://lucide.dev/icon/more-horizontal). An enum would also help with that.

I hope that clears things up a bit :). Thanks!
