### ISSUE TITLE
Merge and Split (not code branches) Icons

### ISSUE THREAD

**Issue by pgbradbury** [lucide-icons/lucide#1006]
## Icon Request

* Icon name: Merge and Split
* Use case: We have companies in our system that we want to merge together into one and some companies that we need to split apart into two companies. but you could use it for merging or splitting anything (not git branches), the icons below are too angled to fit well with this icon set, ideally icons like these with the nice curves of the arrows in this set.
* _Screenshots_ of similar icons

<img src="https://user-images.githubusercontent.com/73958879/229204263-1497fe1c-0998-415a-932e-82d77824b5de.png" width="24"> <img src="https://user-images.githubusercontent.com/73958879/229204386-f4a6ce61-4918-49fb-a621-cbfb61d55f57.png" width="24">

**Comment by xnousnow** [comment]
Sounds good!

**Comment by karsa-mistmere** [comment]
Two alternate designs:
![image](https://user-images.githubusercontent.com/17746067/230012531-ea0da8ac-e26a-45f7-939d-5da08078a6fa.png)

**Comment by pgbradbury** [comment]
Sorry for the late reply. I was hoping for a more curved design as no angles just a swooping curve for the up lines rather than a 45 degree hard bend

**Comment by xnousnow** [comment]
@pgbradbury What do you think is the best?

**Comment by pgbradbury** [comment]
Sorry for the delayed response. I think the first iteration is probably better as the two icons I supplied are standard icons for merge and split on a phone system so having icons that are recognisable but work with this set is my preference (although I like the others as well)

**Comment by karsa-mistmere** [comment]
Thanks for the feedback, @pgbradbury, I've opened a PR post haste. :)
