### ISSUE TITLE
Show a model with download information

### ISSUE THREAD

**Issue by ashrafchowdury** [lucide-icons/lucide#1036]
## Description

To improve the user experience and make it more intuitive, I propose updating the functionality so that when a user clicks on an icon, a model is displayed with the downloading information for that icon. This way, you don't have to show the icon name in the URL.

The way we show the icon's download information right now is a bit **time-consuming**. We want to update it like this where the model will show automatically without playing with the URL.

### Now
![image](https://user-images.githubusercontent.com/87828904/231081320-9ca2a9f1-c979-40cf-a079-b164e76de41b.png)

### After Update
This way is faster and also improves the user experience.
![image](https://user-images.githubusercontent.com/87828904/231081515-55d776ce-e61c-41cf-b955-c8723484b6d4.png)

**Comment by ashrafchowdury** [comment]
I can work on this feature, can someone please assign me to work on this?

**Comment by karsa-mistmere** [comment]
@ashrafchowdury: A complete rewrite of the site is currently in progress dropping the currently used Chakra UI, so implementing this will no longer be necessary, but thank you for the idea (it gave us developers a lot of food for thought!) and for volunteering your time. 😊
