### ISSUE TITLE
Site : Allow changing the color of downloaded PNGs

### ISSUE THREAD

**Issue by locness3** [lucide-icons/lucide#110]
It's a bit unconvenient to download a PNG icon without being able to choose its color, you have to manually recolor the picture afterwards.
Please add a color picker, to change the color of the downloadable PNGs.

**Comment by ericfennis** [comment]
Maybe we can add a global color adjuster, like the feather site.

**Comment by aelfric** [comment]
Can I give this one a try?

**Comment by locness3** [comment]
Sure!
