### ISSUE TITLE
Write conventions for naming icons

### ISSUE THREAD

**Issue by locness3** [lucide-icons/lucide#112]

**Comment by ericfennis** [comment]
Good one.

We now use more of a mix. I think I like the idea of naming the icons what is is presenting, we already do for a lot of icons, instead of naming it to the function or purpose of the icon.

**Comment by delnyn** [comment]
that means we'll have to rename a lot of icons (e.g. `settings`, `edit`)

**Comment by ericfennis** [comment]
@delnyn sort of true. This solution can have a big impact

**Comment by delnyn** [comment]
or we can just write a naming convention without changing the name of the existing icons

**Comment by ericfennis** [comment]
Done in #1518.
See: https://lucide.dev/guide/design/icon-design-guide#naming-conventions
