### ISSUE TITLE
Leafy green 🥬 icon

### ISSUE THREAD

**Issue by xnousnow** [lucide-icons/lucide#1143]
## Icon Request

* Icon name: leafy-green
* Use case: to indicate various vegetables
* _Screenshots_ of similar icons: 🥬

**Comment by karsa-mistmere** [comment]
Based on `salad`, maybe something like this?
![image](https://user-images.githubusercontent.com/17746067/233833471-9ccdd0f1-7654-43a5-a9d9-e5910dbb8550.png)

**Comment by xnousnow** [comment]
Great! I prefer the middle one more.

**Comment by karsa-mistmere** [comment]
Dunno, the more I look at it, the more I hate it. 😄 

Based on the number of leaf segments, there should be three pairs of veins, my OCD is screaming at the top of its lungs.
_And_ it's also a bit too dense.

**Comment by xnousnow** [comment]
Yeah, that makes sense. I think we can add the right one(/or both with the `alt` suffix)
