### ISSUE TITLE
The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

### ISSUE THREAD

**Issue by bfovez** [lucide-icons/lucide#1148]
I post the issue here and in the Skeleton github.

## Prerequisites
* Version: lucide-svelte@0.176.0
* Are you running from source/main: No
* Are you using a released build: Yes
* Operating system: Win 10

## Step to reproduce

1. Create a bare bones Skeleton project : npm create skeleton-app@latest my-skeleton-app
2. Add lucide-svelte : npm i lucide-svelte
3. Add a icon on the +page.svelte (for instance \<LucideRefreshCw \/\>, along with "import { LucideRefreshCw } from 'lucide-svelte'" in the <script> section)
4. Launch the server: npm run:dev
5. Load the page in a browser
6. Quit the server (Ctrl-C / Cmd-C)

## Any message or error

> 10:59:41 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.
> lucide-svelte@0.176.0
> Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.

**Comment by bfovez** [comment]
The skeleton team was able to fix the same issue. It's a quick fix in the package.json file.
See: https://github.com/skeletonlabs/skeleton/issues/1359

**Comment by JanTrichter** [comment]
@ericfennis I think this issue can be closed due to #1499
