### ISSUE TITLE
Droplets

### ISSUE THREAD

**Issue by cjh9** [lucide-icons/lucide#115]
Three droplets, to use for air humidity in weather app.

**Comment by ericfennis** [comment]
@cjh9 Welcome to the Lucide community, good first issue!

**Comment by Andreto** [comment]
@cjh9 
![image](https://user-images.githubusercontent.com/28541538/98155897-46d38000-1ed7-11eb-8591-7ce1ea2f1ac3.png)

**Comment by ericfennis** [comment]
I think the right is more recognisable, maybe try one with the small drop more in the middle?

**Comment by Andreto** [comment]
@ericfennis This also follows the 2px spacing guidelines.
![image](https://user-images.githubusercontent.com/28541538/98443888-9fd92900-210e-11eb-9d3c-7a63f7565c88.png)

**Comment by ericfennis** [comment]
Whoa I like this one!

**Comment by cjh9** [comment]
@Andreto  Cool! I like both, maybe the three droplet a bit more. Maybe can keep both and name them two-droplets and three-droplets?

**Comment by ericfennis** [comment]
@Andreto Can you submit this icon? So we can close this issue.

**Comment by ericfennis** [comment]
closed by #248
