### ISSUE TITLE
Export Angular provider

### ISSUE THREAD

**Issue by R-Bower** [lucide-icons/lucide#1154]
## Prerequisites

* Version: `0.176.0`
* Are you running from source/main: no
* Are you using a released build: yes

## Step to reproduce

Try to import `LucideIconProvider` and `LUCIDE_ICONS` injection token from `lucide-angular`.

### Actual behavior

Error: `Module not found: Error: Package path ./lib/lucide-icon.provider is not exported from package`

## Notes

I have a custom directive which creates a `lucide-angular` icon.  I'd like to access the injected icons from the new provider.  To do that, I need the provider to be exported.

**Comment by karsa-mistmere** [comment]
Thanks for report, yeah, these definitely should've been exported and fell victim to refactoring.

I've pushed a fix, this should be resolved in v0.177.0 in a matter of minutes as soon as the release script finishes running.
