### ISSUE TITLE
Uv Index

### ISSUE THREAD

**Issue by cjh9** [lucide-icons/lucide#116]
Sun with the word UV written inside for use for UV index in weather map

**Comment by Andreto** [comment]
@cjh9 Does any of these matches what you are looking for?
![image](https://user-images.githubusercontent.com/28541538/98152366-e4c44c00-1ed1-11eb-9e4f-c618d34f0a7a.png)

**Comment by ericfennis** [comment]
Nice I like the right one. How does it look if the text: `uv` is centered?

**Comment by Andreto** [comment]
@ericfennis
![image](https://user-images.githubusercontent.com/28541538/98443628-c5fdc980-210c-11eb-8a76-98ab2d3c45d8.png)

**Comment by ericfennis** [comment]
hmm, not sure yet.
Can you try to make the spacing in the letter U to be 2 px?

Also, I think we need to refactor the sun icon, it doesn't have the 1px safezone.
Can you try to make one with this icon?
![image](https://user-images.githubusercontent.com/11825403/98445700-5f32dd00-2119-11eb-9cd6-68546aca067b.png)
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12 2V4" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12 20V22" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M5.21997 5.21997L6.63997 6.63997" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M17.36 17.36L18.78 18.78" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M2 12H4" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M20 12H22" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M5.21997 18.78L6.63997 17.36" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M17.36 6.63997L18.78 5.21997" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by Andreto** [comment]
I'm not sure that we have to change the sun to have the right margin. I think that it was created with visual balance in mind. Of course the smaller sun would be better if you think it looks better but it shouldn't be changed just for the sake of it.
![image](https://user-images.githubusercontent.com/28541538/99154640-c02a5a00-26b1-11eb-8cff-ca8faa1df443.png) _ ![image](https://user-images.githubusercontent.com/28541538/99154667-ddf7bf00-26b1-11eb-8c4b-8663c06015bc.png)

**Some revisions:**
Small sun, othervise the same: ![image](https://user-images.githubusercontent.com/28541538/99154496-78ef9980-26b0-11eb-93fc-9c003e4acb9c.png)
Small sun, more spacing between U and V: ![image](https://user-images.githubusercontent.com/28541538/99154471-53629000-26b0-11eb-8815-7d3220e80720.png)
Big sun, more spacing in U: ![image](https://user-images.githubusercontent.com/28541538/99154591-50b46a80-26b1-11eb-9524-f1c224567317.png)
Smal sun, more spacing in U: ![image](https://user-images.githubusercontent.com/28541538/99154612-704b9300-26b1-11eb-8de0-7bcc887729db.png)

**Comment by locness3** [comment]
I don't think it would be a great idea to add this icon in Lucide, it is way too specific. Wouldn't simply using the text "UV" fit your use case?

**Comment by cjh9** [comment]
@Andreto Great! Exactly what I had in mind.

**Comment by mittalyashu** [comment]
Shouldn't there be some guidelines for working with alphabets in icons?

**Comment by locness3** [comment]
Yes!

**Comment by ericfennis** [comment]
I agree with @locness3 this icons is too specific.
I close this for now.
