### ISSUE TITLE
Rain in wind

### ISSUE THREAD

**Issue by cjh9** [lucide-icons/lucide#117]
To use for percipation probability

Three droplets that are going diagonally, from bottom left to top right. Will look like rain that is falling in the wind.

The rain icon is not very beautiful, and the droplets should go diagonally.

**Comment by ericfennis** [comment]
Do you maybe have an example, maybe from an other library?

**Comment by Andreto** [comment]
@cjh9 Is this what you mean?
![image](https://user-images.githubusercontent.com/28541538/98155957-64a0e500-1ed7-11eb-9514-a83c28aeba34.png)

**Comment by ericfennis** [comment]
@Andreto I think this is a better replacement for the `[cloud-rain](https://lucide.netlify.app/icon/cloud-rain)`. And the current one `cloud-rain` is more for heavy rain.

For the rain in wind, maybe we need to combine it with the current `wind` icon.

**Comment by Andreto** [comment]
@ericfennis Maybe something a bit more like this then?
![image](https://user-images.githubusercontent.com/28541538/99154982-4e9fdb00-26b4-11eb-8511-2aebdc479873.png)

![image](https://user-images.githubusercontent.com/28541538/99154942-fa94f680-26b3-11eb-826d-c51ab29455ee.png)

**Comment by ericfennis** [comment]
@Andreto to me it looks a bit weird, because the wind is above the cloud. I think it is more obvious that the wind is under the cloud.

**Comment by cjh9** [comment]
@Andreto Rain in wind looks great! This is what I had in mind. 
![Screenshot from 2020-11-21 23-50-36](https://user-images.githubusercontent.com/18718330/99889413-220c3600-2c55-11eb-8b2b-3e0bf5fce5ec.png)
