### ISSUE TITLE
GitHub release actions fail to generate changelog and attach assets

### ISSUE THREAD

**Issue by ScottKillen** [lucide-icons/lucide#1175]
## Prerequisites

* Version: All current releaes
* Operating system:  Github

## Step to reproduce

1. Look at the latest GitHub release
2. Notice that release notes are malformed.
3. Notice that the icon and font assets are not attached.

![image](https://user-images.githubusercontent.com/1509989/235282287-f0bb838c-f76a-4a6f-ab5e-e3d823575599.png)

**Comment by karsa-mistmere** [comment]
There weren't any icon changes in that release I'm afraid, it just fixed an error within the repository and that change erroneously created a new release: #1174 

What's done is done, it's better not to "unrelease" what's already out there, but I'll add a short release note manually.

**Comment by ScottKillen** [comment]
Of course. I agree that you can't go back and fix the releases; however, note that release 0.186.0 adds a new icon, and the downloadable font and icon packages are not attached. (and have not been for many releases now.)

**Comment by ScottKillen** [comment]
Also, I discovered today that this breaks the availability of the font via CDN—`https://www.npmjs.com/package/lucide-static` gives 404 ("Cannot find "/font/Lucide.ttf" in lucide-static@0.224.0")

**Comment by ScottKillen** [comment]
Apparently, this has happened due to making `main` a protected branch. 
![image](https://github.com/lucide-icons/lucide/assets/1509989/ea0d6e3a-85e6-4225-8d10-ad309e0bb122)
![image](https://github.com/lucide-icons/lucide/assets/1509989/26d3a615-df61-42d5-a1ea-36f1a995c2be)

See the GitHub community discussion [here](https://github.com/orgs/community/discussions/25305).
