### ISSUE TITLE
`align-justify` vs `menu`

### ISSUE THREAD

**Issue by danielbayley** [lucide-icons/lucide#1186]
These are almost exactly the same icon… Should one be removed?

If so, we should probably drop `menu`, since `align-justify` is part of the `align-*` subset… Then obviously add `menu` as a tag. Not sure about the `aliases` situation in this scenario…

**Comment by ericfennis** [comment]
hmm, not agree with this one. The menu icon is similar yes. But the width is a bit smaller and is commonly used in squares (for example menu buttons). We carefully changed this icon to look good in these squares. So I think we should keep it as it is.

**Comment by danielbayley** [comment]
> We carefully changed this icon to look good in these squares. So I think we should keep it as it is.

Ok cool, if it wasn't just an oversight…
