### ISSUE TITLE
Minor styling issues on the webpage.

### ISSUE THREAD

**Issue by Andreto** [lucide-icons/lucide#122]
### 1. Search input border-radius on dark mode.
**Issue**
The input field has a border-radius but the `chakra-input__group css-r27y85` element is poking out underneath. On light mode this is not an issue since the color of the element is the same as the body.
![image](https://user-images.githubusercontent.com/28541538/97800151-49ae4680-1c33-11eb-98f4-2a4defefea22.png)

**Solution**
Give the `chakra-input__group css-r27y85` element the same border-radius as the input.
or
Give the `chakra-input__group css-r27y85` element the same background-color as the body. (Maybe this messes up the color of the input.)

### 2. Color input box.
**Issue**
The color input elements have a border-radius on the bottom with no padding to the box below.
![image](https://user-images.githubusercontent.com/28541538/97551848-c7741700-19d3-11eb-85b7-47984666b0a5.png)

**Solution**
Maybe put no border-radius on the bottom corners. I also think that the color field could have a border around it. Looks a lot better on the bright side.
![image](https://user-images.githubusercontent.com/28541538/97551804-b88d6480-19d3-11eb-9765-31da27703ec5.png)

Alternatively, some margin between the input and color field. 
![image](https://user-images.githubusercontent.com/28541538/97552590-b972c600-19d4-11eb-9109-5ca6d65b44e7.png)

**Comment by ericfennis** [comment]
@Andreto (1) Wow didn't saw that, really sharp 😄 
(2) Good point, I think the color picker can improved, I noticed it's really laggy if you drag the color picker and heu slider as wel, I think it fires too much events. @aelfric Do you have time to take a look to it?

**Comment by aelfric** [comment]
Yes. I can take a look.
