### ISSUE TITLE
Reduce sharpness of accessibility icon.

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#1235]
It's the first icon you see when you visit lucide.dev, and it just doesn't transport the playfulness that makes lucide great.

Some ideas from playing around:

![accessibility (5)](https://user-images.githubusercontent.com/25524993/236885922-c36f9aa1-5e95-4d22-a189-724e477b80a2.svg) → ![icon (46)](https://user-images.githubusercontent.com/25524993/236885342-2924f8f9-d8db-4fd4-872e-740adf32bebf.svg)

<img width="48%" src="https://user-images.githubusercontent.com/25524993/236885208-a814b208-561c-42c7-9494-28b2f5687525.svg"/>

https://dribbble.com/shots/11133443-Wheelchair-Rugby-Animation

**Comment by karsa-mistmere** [comment]
The current icon is a recreation of [the Accessible Icon](https://accessibleicon.org), I think we should stick to it.

**Comment by jguddas** [comment]
Recreating icons does not feel great, same with #1110 and brand icons.

What about after renaming it to `wheelchair-user`, can I get you on board @karsa-mistmere?

We should also come up with guidelines for using other peoples work. #1224
