### ISSUE TITLE
Refactor Menu Icon

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#127]
When was designing the align icons I came across the menu icon.
I like the menu icon, but I think the current one look a bit too rectangular.
So made the length of the line a bit shorter, so it is more squared.
Also the menu icon is often displayed without text and used in an squared element.

![image](https://user-images.githubusercontent.com/11825403/98293450-a18bdb00-1fae-11eb-8c43-4409f7c62201.png)

I'm curious what you think of this change.

**Comment by Andreto** [comment]
Scaled up like in your image the new one looks a lot better. As an implementation, google uses something similar to the old one on their web and mobile-apps (about 3:2 ratio). The new one is more like what font awesome has.

![image](https://user-images.githubusercontent.com/28541538/98338102-edb83900-2009-11eb-9d7e-e4c332e4f700.png)

**Comment by ericfennis** [comment]
Yeah true, but that doesn't mean it's an old way.
If you look for example to figma, the design-tool I use often. 
They use it as well, I think it's just an question what looks better.
![image](https://user-images.githubusercontent.com/11825403/98440191-9d1f0980-20f7-11eb-824a-9b1e824feefa.png)

**Comment by delnyn** [comment]
I think the new one is better

**Comment by ericfennis** [comment]
Closed by #136
