### ISSUE TITLE
Reply, Reply All, and Forward

### ISSUE THREAD

**Issue by Andreto** [lucide-icons/lucide#128]
**What design direction should we go in for Reply, Reply All, and Forward?**
In the request issues on Feather, two example designs were given, similar to the icons in Outlook and Gmail.

**Requests from feather:** 
Reply: https://github.com/feathericons/feather/issues/380
Replay All: https://github.com/feathericons/feather/issues/381
Forward: https://github.com/feathericons/feather/issues/384

**Outlook (simple lines):**
![image](https://user-images.githubusercontent.com/28541538/98411182-e6c71000-2075-11eb-8574-2147aecc3ca2.png)
**Gmail (filled shapes):**
![image](https://user-images.githubusercontent.com/28541538/98411775-f6932400-2076-11eb-88d0-51aaf2e3faad.png)

I prefer the Gmail approach a bit more and I made icons for reply and reply all:
![image](https://user-images.githubusercontent.com/28541538/98414894-7c659e00-207c-11eb-8511-3dcdf72c39e3.png)
![image](https://user-images.githubusercontent.com/28541538/98414731-2f81c780-207c-11eb-9faf-16e916202cb3.png)

**Comment by ericfennis** [comment]
I think I like it more like this way: 
Reply & reply-all : https://github.com/feathericons/feather/pull/574/files
Forward : https://github.com/feathericons/feather/pull/578

It matches way better with the rest of the arrow icons

**Comment by Andreto** [comment]
I'm a bit skeptical about having the same icon for both reply and forward but in different directions. To me, it doesn't feel totally given that left should be reply and right should be forward. We already have normal arrows tough so maybe it's up to users to decide which icons to use.

**Comment by ericfennis** [comment]
Yeah true, I'm curious what other people think about it.

**Comment by delnyn** [comment]
I personally prefer the one-line icon. Also for the forward, the simple arrow (right or left whatever) works fine IMO (just like Outlook and Gmail).

**Comment by ericfennis** [comment]
I agree with @delnyn, looking at gmail for example it. Here a screenshot. ![Screenshot_20201111-125900.jpg](https://user-images.githubusercontent.com/11825403/98809419-cb655780-241d-11eb-99ec-4cf02ef75e5e.jpg)

**Comment by ericfennis** [comment]
@Andreto I think we can with both ideas. So designers have the choice to implement one. 
I think we can rename it to `arrow-big-corner-left`, `arrow-big-corner-left-double`. So we can create more big arrows as well.

**Comment by Andreto** [comment]
______________________
`arrow-big-corner-left` ![image](https://user-images.githubusercontent.com/28541538/99154186-1f866b00-26ae-11eb-90ff-836e57314cd5.png)

`arrow-big-corner-left-double` ![image](https://user-images.githubusercontent.com/28541538/99154189-2c0ac380-26ae-11eb-94b4-39f1e6629e21.png) / ![image](https://user-images.githubusercontent.com/28541538/99154228-74c27c80-26ae-11eb-95c7-748b69552c32.png)


`arrow-big-right` ![image](https://user-images.githubusercontent.com/28541538/99154106-9f600580-26ad-11eb-955c-b394cfe9b8a6.png)

**Comment by ericfennis** [comment]
@Andreto Nice I like them, make sure the double arrow has 2px spacing between the lines.

**Comment by Andreto** [comment]
@ericfennis Sorry for being a bit inactive lately, I've had a lot to do in school.
Two questions regarding the thin forward and reply icons.

**1.** How long should the line on the right be. I prefer the ones where it sticks out a bit. Looks more balanced in my opinion.
![image](https://user-images.githubusercontent.com/28541538/101173862-6a5b2900-3643-11eb-8521-8efc5c65d92f.png)

![image](https://user-images.githubusercontent.com/28541538/101173815-57e0ef80-3643-11eb-874e-a58baf284fc0.png)

**2.** What should they be named. If I'm not mistaken, naming it as what the icon represents was preferred over function.

**Comment by delnyn** [comment]
IMO the middle one is the best

**Comment by ericfennis** [comment]
@Andreto No problem, your education is always more important!

I'm like number one en number two. For the name, hmm, `arrow-corner-up-left` or `arrow-bend-up-left`? 
But `arrow-corner-up-left`is maybe too close to the `corner-**` icons. There is also an option maybe to replace the current `corner-**` but I'm not sure what the rest of the community will think about that idea.

**Comment by mittalyashu** [comment]
How about without joining this part?

![CleanShot 2021-01-14 at 10 06 53@2x](https://user-images.githubusercontent.com/29014463/104545544-577b4180-5650-11eb-81f8-910b2fe7e840.png)

**Comment by Andreto** [comment]
@mittalyashu How do you mean? Like this?
![image](https://user-images.githubusercontent.com/28541538/105526831-374c2200-5ce3-11eb-9b7f-322a1ea24cce.png)

**Comment by mittalyashu** [comment]
@Andreto Quite similar but the gap seems to be bit uneven.

An even spacing might look good for example:

<img width="109" alt="CleanShot 2021-01-22 at 23 26 49@2x" src="https://user-images.githubusercontent.com/29014463/105527219-6aa1a780-5d09-11eb-98e9-a25b21c81b5c.png">

<img width="119" alt="CleanShot 2021-01-22 at 23 26 32@2x" src="https://user-images.githubusercontent.com/29014463/105527223-6c6b6b00-5d09-11eb-8c42-60fad29122a2.png">

> You can ignore my suggestion for adding the gap too, since exceptions are allowed 😉.

**Comment by ericfennis** [comment]
Closes by #341
