### ISSUE TITLE
Lucide-svelte slow import of icon

### ISSUE THREAD

**Issue by lunatiqqc** [lucide-icons/lucide#1284]
## Prerequisites

* Version: Lucide-svelte 0.216.0
* Are you running from source/main: import using vite
* Operating system: win10
* Bits: 64

## Step to reproduce
- Install svelte-kit
  - npm create svelte@latest my-app
  - cd my-app
  - npm install
- Npm install lucide-svelte
- Import icon in svelte page
  - import { Edit } from 'lucide-svelte';
- Npm run dev
- In the browser navigate to the page where the icon is imported
- Notice how long it takes to reload the page presumably because vite takes a long time generate the server bundle

### Actual behavior
It shouldnt take this long to refresh the svelte page when an icon is imported in it.
Note this happens for both server and client bundles (when using dynamic import in svelte page)

## Any message or error

No console ouput

## Resources

No resources

**Comment by moritzhertler** [comment]
I'm still having the same issue in `0.275.0-beta.0`.  I didn't notice a substantial difference after  #1499.

In my case, there is a consistent ~30x difference in page load time between the same page with and without a lucide icon (e.g. 2.5s vs. 80ms). This is incredibly tedious when testing your app without javascript/csr (e.g. when optimizing for progressive enhancement), as every navigation results in a page load.

I'm still importing like this: 
```typescript 
import { Circle } from 'lucide-svelte';
```

Does this even make use of the conditional exports of #1499? 
I also tried

```typescript 
import { Circle } from 'lucide-svelte/icons';
import { Circle } from 'lucide-svelte/icons/Circle';
import { Circle } from 'lucide-svelte/icons/Circle.svelte';
```

which all could not be resolved.

**Comment by nekochan0122** [comment]
I'm also facing this issue.
![image](https://github.com/lucide-icons/lucide/assets/47508893/2fef5b31-e9be-4d94-96fc-16f42f42ada9)

**Comment by david-plugge** [comment]
This is a huge issue, the initial page load takes ages in dev mode.

**Comment by huntabyte** [comment]
Are you all willing to accept a PR to clean this up or provide alternative means to import a component that doesn't come from a path long enough to warrant an alias, rather something like `import Circle from 'lucide-svelte/icons/Circle.svelte'`

**Comment by ericfennis** [comment]
@huntabyte Yess plz do.
