### ISSUE TITLE
Spotify icon

### ISSUE THREAD

**Issue by fabio1079** [lucide-icons/lucide#1290]
## Icon Request

* Icon name: spotify
* Use case: On spotify people can create their own music libraries and share them, the icon would be used in cases of sharing their libraries.
* _Screenshots_ of similar icons:

Sample icon taken from https://simpleicons.org
```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Spotify</title><path d="M12 0C5.4 0 0 5.4 0 12s5.4 12 12 12 12-5.4 12-12S18.66 0 12 0zm5.521 17.34c-.24.359-.66.48-1.021.24-2.82-1.74-6.36-2.101-10.561-1.141-.418.122-.779-.179-.899-.539-.12-.421.18-.78.54-.9 4.56-1.021 8.52-.6 11.64 1.32.42.18.479.659.301 1.02zm1.44-3.3c-.301.42-.841.6-1.262.3-3.239-1.98-8.159-2.58-11.939-1.38-.479.12-1.02-.12-1.14-.6-.12-.48.12-1.021.6-1.141C9.6 9.9 15 10.561 18.72 12.84c.361.181.54.78.241 1.2zm.12-3.36C15.24 8.4 8.82 8.16 5.16 9.301c-.6.179-1.2-.181-1.38-.721-.18-.601.18-1.2.72-1.381 4.26-1.26 11.28-1.02 15.721 1.621.539.3.719 1.02.419 1.56-.299.421-1.02.599-1.559.3z"/></svg>
```

I know it can be considered a brand logo, but considering lucide has icons for twitter, youtube and facebook, why not add one for Spotify :grin:

**Comment by karsa-mistmere** [comment]
It not just "can be" considered a brand logo, it _is_ one, and [Spotify's brand guidelines](https://developer.spotify.com/documentation/design#using-our-logo) actually disallow us to "recreate or manipulate [...] the icon".

**Comment by JamesSingleton** [comment]
@karsa-mistmere so how does Font Awesome get around this? They have [Spotify](https://fontawesome.com/icons/spotify?f=brands&s=solid) along with a bunch of different brands.

**Comment by karsa-mistmere** [comment]
They do so by not altering the logo's appearance. Something we at Lucide are unable to do, since we are bound to using just strokes of a variable width.

**Comment by JamesSingleton** [comment]
Ah ok, thanks for explaining. I started using lucide because of https://ui.shadcn.com/ and switched from Heroicons (which has no branding) so I was hoping that Lucide was going to add more 😅

**Comment by karsa-mistmere** [comment]
Well, we're adding a lot of icons, just not brand ones. Again, simpleicons.org is a great icon library for this very purpose, that also operates on a 24by24 grid, so it works really well with Lucide.
