### ISSUE TITLE
Is there an icon for Lucide logo/brand itself?

### ISSUE THREAD

**Issue by razonyang** [lucide-icons/lucide#1299]
Similar to the feather icon https://feathericons.com/?query=feather. I want to display the brand of Lucide in the icon way, but didn't find one.

**Comment by karsa-mistmere** [comment]
I'm not sure our icon works in monochrome, and since it's practically a brand logo, we're unlikely to add it, here's an SVG that's used on the site that you may use: https://lucide.dev/logo.svg

**Comment by jguddas** [comment]
I think adding a `swirl` and `swirl-2` icon could be an idea.
