### ISSUE TITLE
Community Building

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#13]
Hey I thought maybe we can think about how we can build the community.
I wrote down some ideas, maybe you can help and share your ideas as wel.
Let me know what you think!

### For the community
- [x]  Slack or discord for faster feedback / sparring about icons and building the repo/community. [Link here](https://discord.gg/EH6nSts)

### For Contributing
- [x]  Update CONTRIBUTING markdown file
- [x]  Create a design guidelines markdown file, from  [#171](https://github.com/feathericons/feather/issues/171)
- [x]  Nice guide how to design icons in figma or other design programs
- [x]  Nice guide to work with the code.
- [x]  Documentation how to use those icons.

**Comment by jletey** [comment]
Thanks for opening this @ericfennis 🙏 I completely agree with everything you've said.

I've gone ahead and created a Discord server (IMO Discord is better than Slack for these type of things).

[Join Now](https://discord.gg/xYKnd9)

**Comment by locness3** [comment]
Yeah, Slack was never meant for communities

**Comment by lscheibel** [comment]
Hey guys, do you have a valid invite link to the discord? I think the current one is broken :sweat_smile:

**Comment by jletey** [comment]
@lscheibel Sorry about that, I accidentally created the previous link without saying to not expire 😅

Try [this](https://discord.gg/U7uRMq) 👈

**Comment by lscheibel** [comment]
I could try myself at some Figma and Illustrator Guidelines as well as how to cleanly export them from each of them.

**Comment by dgdavid** [comment]
@jletey 

> Try [this](https://discord.gg/U7uRMq) point_left

Still invalid. The same with the one used in README.

![Screenshot_2020-06-26 Discord - A New Way to Chat with Friends Communities](https://user-images.githubusercontent.com/1691872/85858111-f9ba0180-b7b2-11ea-8947-2d5030f1a9db.png)

**Comment by ericfennis** [comment]
@dgdavid Ah I see,, what the problem is. The invite link generated by Discord is valid for 1 day. I adjusted it with the settings. This link should work and never expire.

[Discord Invite](https://discord.gg/EH6nSts)

**Comment by locness3** [comment]
Also, we should update the figma library, but it's long to do by hand. Couldn't we have some script generate an svg file, then import that figma and create the compinents?

**Comment by locness3** [comment]
Hasn't anyone got an idea?

**Comment by ericfennis** [comment]
According to this [article](https://medium.com/@danhollick/a-designers-guide-to-the-figma-api-64f2785969d8), is currently not possible with the current api.
There are currently 10 endpoints available with the api.

<img src="https://user-images.githubusercontent.com/11825403/86122402-123e5a80-bad8-11ea-99e3-3df483b3f87b.png" width="560"/>

Only possible way is I think to generate a figma file in a sort of way, but can't find any information about that.
Just importing it in vscode gave me some strange encoded data.

**Comment by locness3** [comment]
What I thought of would be to make a shell script generating an svg, then importing that into figma
