### ISSUE TITLE
Whiteboard icon

### ISSUE THREAD

**Issue by sateeshsai** [lucide-icons/lucide#1303]
## Icon Request

* Icon name: Whiteboard
* Use case: To use in apps with a whiteboard or drawing canvas
* _Screenshots_ of similar icons:  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8qaDhTkDlrOMdt4MRYsWpX_x7HxKt7ExLDA&usqp=CAU

**Comment by xnousnow** [comment]
What about:
![image](https://github.com/lucide-icons/lucide/assets/119923091/0ec707e8-1603-4c90-8c2f-3733d7cbb6f1)
(added white background in the only preview image, there is none in the code)
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M22 9V18C22 19.1046 21.1046 20 20 20H4C2.89543 20 2 19.1046 2 18V6C2 4.89543 2.89543 4 4 4H13" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M19.8084 2.37602C19.9276 2.25681 20.0691 2.16224 20.2249 2.09772C20.3807 2.03321 20.5476 2 20.7162 2C20.8848 2 21.0517 2.03321 21.2075 2.09772C21.3632 2.16224 21.5048 2.25681 21.624 2.37602C21.7432 2.49523 21.8378 2.63676 21.9023 2.79251C21.9668 2.94827 22 3.11521 22 3.28381C22 3.4524 21.9668 3.61934 21.9023 3.7751C21.8378 3.93086 21.7432 4.07238 21.624 4.19159L15.4964 10.3192L13 11L13.6808 8.50358L19.8084 2.37602Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11 13L7 15L6 10" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by karsa-mistmere** [comment]
That doesn't really work with our guidelines. How about just a generic presentation screen shape?
![image](https://github.com/lucide-icons/lucide/assets/17746067/6c9a592b-c629-413d-be2c-dbd12c4331b8)

**Comment by xnousnow** [comment]
The icon looks great, although I'm not sure which specific type of whiteboard icon the OP is looking for.

**Comment by sateeshsai** [comment]
> That doesn't really work with our guidelines. How about just a generic presentation screen shape? ![image](https://user-images.githubusercontent.com/17746067/240205465-6c9a592b-c629-413d-be2c-dbd12c4331b8.png)
This looks great. But the "sticks" at the top and bottom makes it a presentation screen for projection than a drawing board/whiteboard. I like xnousnow's idea (Simple rounded rectangle as the overall shape)- may be it can be adjusted to make it work with Lucide's guidelines?

**Comment by xnousnow** [comment]
![image](https://github.com/lucide-icons/lucide/assets/119923091/9cae5ff8-a638-489b-aedc-5c6073a66659)
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none">
  <path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M22 10v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h8"/>
  <path stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.8 2.38a1.28 1.28 0 1 1 1.82 1.81l-6.12 6.13L13 11l.68-2.5 6.13-6.12ZM11 13l-4 2-1-5"/>
</svg>
```
I tried my best to stick with the guidelines, but I couldn't make a 2px gap between pen and line.

**Comment by danielbayley** [comment]
@sateeshsai @xnousnow See #1327.

**Comment by sateeshsai** [comment]
> @sateeshsai @xnousnow See #1327.

Thank you. But none of those seem to be whiteboard icons. Presentation screen and whiteboard are similar but feel like they are not interchangeable.

**Comment by danielbayley** [comment]
@sateeshsai See also alts: https://github.com/lucide-icons/lucide/pull/1327#issue-1737016830.
