### ISSUE TITLE
Hydration Failure: Unhandled Runtime Error

### ISSUE THREAD

**Issue by dinogomez** [lucide-icons/lucide#1308]
## Prerequisites

* Version: Lucide React: 0.220.0
* Operating system: Windows 11

## Step to reproduce

Hydration fails here, I do also use next-themes and I am not sure if its also a possible cause of the issue.
I am using shadcn-ui which comes with lucide.

1. After clicking a Next Link, and going back using the back arrow in the browser it will prompt the hydration error.

```tsx
"use client";
import { Sun, Moon, Ship } from "lucide-react";
import { useTheme } from "next-themes";
import Link from "next/link";
import { Button } from "./ui/button";
import { Separator } from "./ui/separator";

export function ProfileCard() {
  const { theme, setTheme } = useTheme();
  return (
    <div className="w-[35rem]">
      <div className="my-3">
        <div className=" flex justify-between">
          <div className="flex p-2 space-x-2">
            <Ship size={20} className="" />
            <span className="font-semibold ">Likas Crew</span>
          </div>
          <div className=" flex space-x-4 text-sm">
            <Button className="p-0">
              <Link className="space-x-0 m-0" href="">
                <div className="">Login</div>
              </Link>
            </Button>
            <Button
              className="p-0"
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
            >
              {theme === "light" ? <Sun size={20} /> : <Moon size={20} />}
            </Button>
          </div>
        </div>
      </div>
      <Separator className="my-3" />
    </div>
  );
}
```

### Actual behavior
When navigating back to the component after clicking a Next Link it will prompt the Hydation error.

## Any message or error

`Warning: Expected server HTML to contain a matching <circle> in <svg>.`
`./node_modules/lucide-react/dist/esm/createLucideIcon.js (19:8)`
## Resources

![image](https://github.com/lucide-icons/lucide/assets/41871666/21819ff7-ae31-4e9c-bc71-ead91a59a2d5)

**Comment by ericfennis** [comment]
@dinogomez Thanks for reporting, can you provide a repo for reproduction?

**Comment by ericfennis** [comment]
@dinogomez Thanks for you reply, good to hear it is resolved!

**Comment by poncianodiego** [comment]
I am experiencing "Warning: Expected server HTML to contain a matching <span> in <svg>" I am not using next-themes at all. This is happening with the Menu icon.

**Comment by ericfennis** [comment]
@poncianodiego Clear your `.next` directory. Sometimes the cache is outdated.

**Comment by dinogomez** [comment]
> Warning: Expected server HTML to contain a matching in

I encountered this before and clearing the .next cache and restarting the dev server as well. Side note double check as well whether the component needs to be a client component.

**Comment by ericfennis** [comment]
@dinogomez The Icon component is not dependent on client side rendering. All SVG elements are supported in SSR.

My assumption that hydration will cause when `lucide-react` has changes in the icon components. And you update it to a new version. The cache of next is not matching with the client side rendering with new version of lucide-react which causes hydration issues.

But this is something we need to check if this is true.
