### ISSUE TITLE
Add icon headset

### ISSUE THREAD

**Issue by KayleyHill** [lucide-icons/lucide#1316]
![callcenter-headset](https://github.com/lucide-icons/lucide/assets/135126101/09800915-a83f-43e4-99a0-391ab61268ee)

I really don't understand how to do a pull request. Keeps failing (really new to github), so i am putting the icon I created here. Any suggestions to improve would also be appreciated.

**Comment by karsa-mistmere** [comment]
> I really don't understand how to do a pull request. Keeps failing (really new to github), so i am putting the icon I created here.

You can find out in our [contributor's guide](https://github.com/lucide-icons/lucide/blob/main/CONTRIBUTING.md).

If you do not wish to bother with submitting PRs and working with code, just open an icon request issue and feel free to leave the dirty work to us. :)

Nonetheless, any icon design must stick to our [icon design guidelines](https://lucide.dev/docs/icon-design-guide).

**Comment by KayleyHill** [comment]
I want to work up to doing code, but that's a bit beyond me atm ^_^;... I think I have kept to your design guidelines from my read through, but apologies if I have made a mistake.

**Comment by KayleyHill** [comment]
![callcenter-headset](https://github.com/lucide-icons/lucide/assets/135126101/f8ab9709-20f0-48b6-82dc-1ff4b82f8dff)

@karsa-mistmere after reading the document again I realised I made a few mistakes. Hopefully this version will be in line with the standards now.

**Comment by jguddas** [comment]
Maybe we should switch to using 2px radii like this for the headphones icon? ![](https://github.com/lucide-icons/lucide/assets/25524993/1aefc2c6-f43b-4d78-9adb-151356a4e68b)
https://lucide-site-git-feat-added-edit-page-jguddas.vercel.app/edit?PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cmVjdCB4PSI5LjUiIHk9IjE4IiB3aWR0aD0iNSIgaGVpZ2h0PSI0IiByeD0iMiIgLz4KICA8cGF0aCBkPSJNMTQuNSAyMGgxYTQgNCAwIDAgMCA0LTRWOS41YTcuNSA3LjUgMCAwIDAtMTUgMFYxNGEyIDIgMCAxIDAgNCAwdi0yLjVhMiAyIDAgMCAwLTItMmgtMiIgLz4KICA8cGF0aCBkPSJNMTkuNSAxNGEyIDIgMCAxIDEtNCAwdi0yLjVhMiAyIDAgMCAxIDItMmgyIiAvPgo8L3N2Zz4=

**Comment by KayleyHill** [comment]
Prefer your edit @jguddas, opening up those speakers makes it look far more balanced.

**Comment by ericfennis** [comment]
@jguddas Nice work, feel free to open a PR!

**Comment by ericfennis** [comment]
Alternative with adjusted `headphones` icon. 

<img width="159" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/45244212-738a-4a07-b9f3-498e7f6fa2a6">

Adjusting the headphone icon also look better and more balanced and centered.

Comparison with @jguddas version (right one):
<img width="146" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/5e6928ff-254a-4639-a197-44d60ca39686">
