### ISSUE TITLE
Add money in hand icon

### ISSUE THREAD

**Issue by KayleyHill** [lucide-icons/lucide#1322]
![helping-hand-money](https://github.com/lucide-icons/lucide/assets/135126101/a85d91f8-1602-4ba4-82eb-6b58e1e4ec68)

Not sure if this really works, trying to create a icon based on helping hand for savings 

* Icon name: helping-hand-money
* Use case: offers, banking

Similar icons 
![moneyhand](https://github.com/lucide-icons/lucide/assets/135126101/0149664f-4a94-4fcc-a9ce-9469b683be9f)

**Comment by karsa-mistmere** [comment]
Things are a bit off grid:
![image](https://github.com/lucide-icons/lucide/assets/17746067/9f80148b-90ae-437c-a2a2-5370faecb50b)

I've recreated this in Figma as pixel perfect as I could manage:
![helping-hand-money](https://github.com/lucide-icons/lucide/assets/17746067/bd53f9d8-d822-46d5-b347-ecbe44cc3a3b)

**Comment by KayleyHill** [comment]
Sorry my work was sloppy @karsa-mistmere  will make sure to watch that more next time I submit anything. I am still not convinced though my idea works in concept. As I am not sure it looks like money, however I am not sure how that could be rectified within the guidelines.

**Comment by jguddas** [comment]
The current helping-hand icon does not feel awesome, not a fan of creating things based on that one even tho the use case is valid IMO.

**Comment by KayleyHill** [comment]
> The current helping-hand icon does not feel awesome, not a fan of creating things based on that one even tho the use case is valid IMO.

Maybe the solution is rethinking helping hand totally and creating a new one with different use cases in mind.

**Comment by xnousnow** [comment]
Or we could open another issue managing the helping-hand icon and come back when that's completed.

**Comment by danielbayley** [comment]
> trying to create a icon based on helping hand for savings

> The current helping-hand icon does not feel awesome, not a fan of creating things based on that one even tho the use case is valid IMO.

> Maybe the solution is rethinking helping hand totally and creating a new one with different use cases in mind.

@KayleyHill @karsa-mistmere @jguddas @xnousnow See #1328.

**Comment by KayleyHill** [comment]
> @KayleyHill @karsa-mistmere @jguddas @xnousnow See #1328.

Really like the hand-platter and the new coin one.
