### ISSUE TITLE
Icon Request: Speech

### ISSUE THREAD

**Issue by Doerge** [lucide-icons/lucide#1329]
## Icon Request

* Icon name: Speech
* Use case: For a11y where it's important to distinguish between audio and speech specifically.
* _Screenshots_ of similar icons: 
<img width="224" alt="image" src="https://github.com/lucide-icons/lucide/assets/3216279/92fee035-69f7-4dad-bc25-50369f058949">

🙏 Thanks for an awesome high quality project!

**Comment by AirOne01** [comment]
@ericfennis The PR was merged. Should we close?
