### ISSUE TITLE
Add "No brands" and "Not too specific" rules in Icon Design Guide

### ISSUE THREAD

**Issue by AirOne01** [lucide-icons/lucide#1336]
Today I made some icons for cryptocurrencies and posted an Issue, then a PR here.
It's my bad that I didn't read #670 but since the decision was taken one year ago, I would have expected to see it in the rules.

There is the question of icons that are too specific as well. Are they avoided because it's too much work or because they're banned ?
> [I like the icon, but the icon is too specific. The use case for pastry shops is kinda covered by the `croissant` icon.](https://github.com/lucide-icons/lucide/pull/1019#issuecomment-1529125584)

It would save time to new contributors such as myself to add these two rules to the [icon design guide](https://lucide.dev/guide/design/icon-design-guide):

```
- Icons must not be branded (link to #670)
- Icons uses must not be too specific
```

Btw I love this project and have been using your icons for a while now. They saved me a lot of time.
Thanks a bunch!

**Comment by jguddas** [comment]
Yes, this is super important!

Here is my WIP collection of stuff that should be included in the contribution guidelines https://github.com/lucide-icons/lucide/pull/1224#issue-1698657210

Getting this all into an understandable format will be quite an undertaking, any help much appreciated :heart:

**Comment by AirOne01** [comment]
Debate on #1224. Closing.
