### ISSUE TITLE
Feature request: Make default props customizable

### ISSUE THREAD

**Issue by Mhmdrza** [lucide-icons/lucide#1362]
Hello Everyone,

I often see myself set `size={16} strokeWidth={1.5}` to every Icon I use from lucid to be consistent with our design, I would like to request providing a way to change default prop for entire set.

I didn't find any recommended in docs Hence this opened this Issue.

Thanks in advance

**Comment by JanTrichter** [comment]
Hi @Mhmdrza, you could use the `createIcons` function for that [see documentation](https://lucide.dev/guide/packages/lucide#additional-options). You can either adjust the stroke width right there or apply a class that contains these changes. Is that what you're looking for?

**Comment by ericfennis** [comment]
Sorry for the late reply.

This could be easily done by defining a global CSS rule.
Every icon has a `lucide` class.

So in this case you should define it like this: 
```
.lucide {
  width: 16px;
  height: 16px;
  stroke-width: 1.5;
}
```

Hope this helps.
