### ISSUE TITLE
Pray Icon

### ISSUE THREAD

**Issue by pedrolucaslcosta** [lucide-icons/lucide#1365]
## Icon Request

* Icon name: pray
* Use case: pray group of church
* _Screenshots_ of similar icons:
* 
![image](https://github.com/lucide-icons/lucide/assets/81483545/6530f3d7-b105-4d40-819f-c17d164165a6)

**Comment by xnousnow** [comment]
🙏

**Comment by devlulcas** [comment]
Maybe it should be named `folded hands` or `praying hands`



👏 | Clapping hands | U+1F44F
-- | -- | --
🙌 | Raised hands | U+1F64C
👐 | Open hands | U+1F450
🤲 | Palms together hands | U+1F932
🤝 | Handshake | U+1F91D
🙏 | Praying hands | U+1F64F
✍ | Writing hands | U+270D

**Comment by karsa-mistmere** [comment]
Please fill out a proper icon request issue: https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&projects=&template=01_icon_request.yml
