### ISSUE TITLE
lucide.eot file missing in lucide-static

### ISSUE THREAD

**Issue by schmidt-oliver** [lucide-icons/lucide#1367]
## Prerequisites

* Version: V. 0.244.0
* Are you running from source/main: no
* Are you using a released build: lucide-static, import using parceljs
* Operating system: Unix
* Bits: 64 bits

## Step to reproduce

- `npm install lucide-static`
- Go to `node_modules/lucide-static/font/.`
- See that `lucide.eot` is missing.
- Try to `@import "~lucide-static/font/Lucide.css";`
- Getting error

### Actual behavior
- `npm install lucide-static`
- Go to `node_modules/lucide-static/font/.`
- Find the file `lucide.eot`
- Try to `@import "~lucide-static/font/Lucide.css";`
- File found, so no error occurs

## Any message or error

`@parcel/resolver-default: Cannot load file '../node_modules/lucide-static/font/lucide.eot' in './src'.`

## Resources

- No resources

##  Comment
Hello together, other packages like those from @fontsource only serve woff2 and woff files in their css, isn't that enough? Or is it possible to provide a css file with only the icon classes and their unicode content, so that you can add the rest yourself? Thank you.

**Comment by ericfennis** [comment]
@schmidt-oliver Thanks for pointing this out!

**Comment by schmidt-oliver** [comment]
I found out that you are using [fontcustom](https://github.com/FontCustom/fontcustom) based on ruby and python to create the font files. There is an interesting node package called [svgtofont](https://github.com/jaywcjlove/svgtofont). Eventually it is a great alternative. I will take a look and try it out.

**Comment by ericfennis** [comment]
Thanks for pointing out. Currenty I'm nog really happy with fontcustom. It's also not very well maintained. We currently have some open issues with the font. We really need stable hex values for the icons. We currently have some open issues about it: #514, #926 and #538. So a custom icon-codepoints map for the font bundler is a must.
I was looking at [fantasticon](https://github.com/tancredi/fantasticon)  but maybe svgtofont is also a good one to look at.

**Comment by schmidt-oliver** [comment]
Thank you and good to know. I will take this into account in my tests.

**Comment by schmidt-oliver** [comment]
Hey, I checked out the library `svgtofont`. The custom icon-codepoints wouldn't be a problem here. But there is a [huge problem with native shapes](https://github.com/jaywcjlove/svgtofont/issues/195). The converted icons look like crap. Eventually I missed something. Take a look if you want at my [test repo](https://github.com/PHKA-ZIM/lucide-static).

I will check out fantasticicon next.

**Comment by ericfennis** [comment]
@schmidt-oliver Thanks for digging into this. I think this is not really a problem. Ok, will try to explain why.
When we used fontcustom the icons looked crap as well, not because of the antive shapes but because of the stroke-widths we use in the icons.
We fixed this by outlining all the icons and use this to create the font.  See script: `build:outline-icons` in root package.json, the package and scripts are located under "tools/outline-svg".
This will create a directory called "outlined" in the root with all the icons with outlined vectors. And those we can use to make the fonts.

**Comment by schmidt-oliver** [comment]
@ericfennis I noticed that we missed to adjust the Github workflow for new releases. Can you please adapt it like the one for lucide-static? Thank you.

https://github.com/lucide-icons/lucide/blob/4cc4468d2f2832be31670f67216a4f73abd3f591/.github/workflows/release.yml#L188-L189C8

**Comment by ericfennis** [comment]
You're right, I thought we did this already. Yess I will.
I will reopen this one, to make sure we don't forget this one!
