### ISSUE TITLE
Icon request: Materials

### ISSUE THREAD

**Issue by balazsbarta** [lucide-icons/lucide#1369]
## Icon Request

* Icon name: `rock`
* Use case: Construction websites, apps 
* _Screenshots_ of similar icons:
![rock](https://github.com/lucide-icons/lucide/assets/8573183/e06109e8-c509-4ace-bd9e-47babcb42d3f)

* Icon name: `wood`
* Use case: Construction websites, apps 
* _Screenshots_ of similar icons:
![wood](https://github.com/lucide-icons/lucide/assets/8573183/f2a4f5d4-2c4f-4c64-87e2-8b2d0327915d)

* Icon name: `brick`
* Use case: Construction websites, apps 
* _Screenshots_ of similar icons:
![brick](https://github.com/lucide-icons/lucide/assets/8573183/be0e4cc4-bedc-4924-af05-a782eac4c266)

* Icon name: `metal`
* Use case: Construction websites, apps 
* _Screenshots_ of similar icons:
![metal](https://github.com/lucide-icons/lucide/assets/8573183/9eefa0cc-471d-49c4-9520-97d03d5dd1ca)

**Comment by danielbayley** [comment]
Related to https://github.com/lucide-icons/lucide/pull/1267#issuecomment-1546607632. `anvil` might work better though…?

> brick

@xenqtron Ha I already had something very similar drafted!

<img width="255" alt="Untitled" src="https://github.com/lucide-icons/lucide/assets/7797479/9ba34c72-8b8d-40b3-922f-59fb7fc1352c">
<br/>
<br/>

…and possibly for `wood`, I also have `fence`:

<img width="175" alt="Untitled" src="https://github.com/lucide-icons/lucide/assets/7797479/3db04a1a-ea74-4831-9c6c-8afe56aa63f0">

**Comment by jguddas** [comment]
Besides brick-wall, brick(singular) and bricks(multiple) would be awesome to have.

**Comment by danielbayley** [comment]
> Besides brick-wall, brick(singular) and bricks(multiple) would be awesome to have.

@jguddas I do also have `container` (for Docker etc), which is already basically a brick, minus a few details… Would the wall not cover brick**s** (plural)…?

**Comment by danielbayley** [comment]
@xenqtron @jguddas Just `push`ed `cuboid` (brick) to https://github.com/lucide-icons/lucide/pull/1142#issuecomment-1518581003
