### ISSUE TITLE
error: duplicate-react

### ISSUE THREAD

**Issue by schwamic** [lucide-icons/lucide#137]
I use `yarn workspaces`, and as I moved `lucide-react` to the root `package.json`, I got an error: [duplicate-react](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react). At the moment I fixed the problem via `yarn resolutions`, to make sure to install only one react version. I think, `react` a well as `prop-types` should be `peer-deps`.

lucide-react@0.1.2-beta.3

**Comment by ericfennis** [comment]
@schwamic Thank you for creating this issue, I will look in to it!

**Comment by ericfennis** [comment]
@schwamic I added `react` and `prop-types` as peer deps, I released it on `lucide-react@0.1.2-beta.5`
I'm curious you still experience this issue, let me know.

**Comment by schwamic** [comment]
@ericfennis thank you for the improvements! Now works without `yarn resolutions`.

**Comment by ericfennis** [comment]
@schwamic great to hear that, thanks for testing.
