### ISSUE TITLE
Absolute Stroke Width is not working

### ISSUE THREAD

**Issue by MertenHellmann** [lucide-icons/lucide#1375]
* Version: 0.244.0
* Are you running from source/main: main
* Are you using a released build: no
* Operating system: macOS Monterey 12.5.1
* Bits:

I try to keep stroke-width as it is defined in "stroke-width" by activating absolute-stroke-width (absolute-stroke-width="true"). But it hasn't any effect. The stroke of an 32x32px icon with 2px stroke is still being scaled to a bigger stroke than for the 24x24px icon with 2px stroke.  

My Code: https://jmp.sh/O2pzBPOy
My Result: https://jmp.sh/cK7nKWZg

**Comment by karsa-mistmere** [comment]
Apparently the [correct attribute names are in camelCase](https://github.com/lucide-icons/lucide/blob/main/packages/lucide-vue-next/src/createLucideIcon.ts#L6), e.g.:

```html
<Camera color="red" :size="48" :strokeWidth="4" :absoluteStrokeWidth="true" />
```

**Comment by MertenHellmann** [comment]
Now it works. Thank you so much! 👏
