### ISSUE TITLE
Shift + Click to copy icon as SVG doesn't work

### ISSUE THREAD

**Issue by glebsexy** [lucide-icons/lucide#1385]
It was a very convenient behavior that you could Shift + Click an icon and copy it as SVG. But it seems like this is not implemented on the new website at https://lucide.dev/icons/ 

Now I have to click the icon at the top of the window, bring the cursor to the very bottom of the window and carefully position it exactly on the “Copy as SVG” button to click it.

Ideally you could also choose which format to use when copying via Shift + Click but personally I don't need that — just thinking about other people who might more commonly use other formats.

Thanks everyone for all the awesome work on this project so far!

**Comment by ericfennis** [comment]
@glebsexy Thanks for pointing this out! I tried to implement all the features we had. But I think I forgot that one!
I will try to make a fix!

**Comment by schmidt-oliver** [comment]
@ericfennis "Shift + Click" on an icon worked for me. By the way the new website looks great.

**Comment by glebsexy** [comment]
Looks like the feature is added now, yay! Thank you for such a quick fix!

**Comment by ericfennis** [comment]
@schmidt-oliver Thank you, glad you like it!
@glebsexy Nice to hear!
