### ISSUE TITLE
Rubik's cube

### ISSUE THREAD

**Issue by xnousnow** [lucide-icons/lucide#1395]
## Icon Request

* Icon name: Rubik's cube / `rubiks-cube`
* Use case: To represent kind of twisty puzzles
* _Screenshots_ of similar icons:
![image](https://github.com/lucide-icons/lucide/assets/119923091/cc800cce-8237-42bf-a3d8-de24d80f4fe0)
![image](https://github.com/lucide-icons/lucide/assets/119923091/7438cc9f-3644-42ab-8f5c-78211d04344f)

**Comment by karsa-mistmere** [comment]
This is unfortunately impossible to have within Lucide, a 3 by 3 cube would require 7 vertical lines horizontally spaced, with 2px gaps and 2px strokes that's already a total of 26px, and we'd still need 1px padding on both sides, so there's no way we could fit those 28px pixels within a 24px grid.

**Comment by xnousnow** [comment]
Then what about 2x2? I think it can be made somewhat like this:
![image](https://github.com/lucide-icons/lucide/assets/119923091/8401dbee-0f23-489d-aef8-8dbfbb5ece36)
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21 16V8C20.9996 7.64927 20.9071 7.30481 20.7315 7.00116C20.556 6.69751 20.3037 6.44536 20 6.27L13 2.27C12.696 2.09446 12.3511 2.00205 12 2.00205C11.6489 2.00205 11.304 2.09446 11 2.27L4 6.27C3.69626 6.44536 3.44398 6.69751 3.26846 7.00116C3.09294 7.30481 3.00036 7.64927 3 8V16C3.00036 16.3507 3.09294 16.6952 3.26846 16.9988C3.44398 17.3025 3.69626 17.5546 4 17.73L11 21.73C11.304 21.9055 11.6489 21.9979 12 21.9979C12.3511 21.9979 12.696 21.9055 13 21.73L20 17.73C20.3037 17.5546 20.556 17.3025 20.7315 16.9988C20.9071 16.6952 20.9996 16.3507 21 16Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3.29 7L12 12L20.71 7" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12 22V12" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16.5 10V19.5M12 17L21 12" stroke="black" stroke-width="2"/>
<path d="M7.5 10V20M12 17.3684L3 12.1053" stroke="black" stroke-width="2"/>
<path d="M7.5 9.5L16.5 4M16.5 9.5L7.5 4" stroke="black" stroke-width="2"/>
</svg>
```
