### ISSUE TITLE
Theater/drama icon

### ISSUE THREAD

**Issue by MaxTechnics** [lucide-icons/lucide#1399]
## Icon Request

* Icon name: Theater/Theatre/Drama/Entertainment
* Use case: Filtering by entertainment type (similar as how Megaphone can be used for 'advertising' and Clapperboard for 'film/movie'
* _Screenshots_ of similar icons:
<img width="311" alt="image" src="https://github.com/lucide-icons/lucide/assets/58440941/5e3efacd-e990-43ec-9361-2787aef26973">

Something like this could also be nice, however i feel that this could get really dense on small sized icons
<img width="114" alt="image" src="https://github.com/lucide-icons/lucide/assets/58440941/ebd3784e-28b7-4541-a59c-7f5a298b1313">

**Comment by danielbayley** [comment]
@MaxTechnics Something like these?

![preview](https://github.com/lucide-icons/lucide/assets/7797479/68cfb964-b6cf-4e72-8917-c8ced96fbde1)

**Comment by MaxTechnics** [comment]
That looks great! I think out of the "drama" set the second one matches the most with the "industry standard" in terms of tilting the masks. 
Awesome on how that theater turned out as well.
