### ISSUE TITLE
Create documentation section in the site.

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#140]
I'm almost done with creating the react package, and for that I need to write some documentation as well. 
With that, maybe it is nice to centralize the documentation.

I got a bit inspired by the [ChakraUI website](https://chakra-ui.com/docs/getting-started), I think they have an great, simple and nice looking documentation site. I noticed they use their own UI + next.js, the same as we do. And they use enhanced markdown to generate documentation pages. (`.mdx` files), see their `[next.config.js](https://github.com/chakra-ui/chakra-ui/blob/develop/website/next.config.js)`.

So maybe we can use that as well.

**Comment by JanTrichter** [comment]
What exactly should be in the documentation?

**Comment by ericfennis** [comment]
@JanTrichter I created the first one https://github.com/lucide-icons/lucide/issues/378
