### ISSUE TITLE
Sveltekit runs out of memory.

### ISSUE THREAD

**Issue by weepy** [lucide-icons/lucide#1403]
Using sveltekit's "npm build" - all the icons need transforming - even if not used.
node_modules/.pnpm/lucide-svelte@0.252.0_svelte@3.59.2/node_modules/lucide-svelte/dist/svelte/icons/venetian-mask.svelte

Very slow of course, but also cause the builder to run out of memory :(

Steps To Reproduce

npm run build

**Comment by ericfennis** [comment]
@weepy Can you provide a repository to reproduce this?

**Comment by weepy** [comment]
```
npm create svelte@latest my-app
cd my-app
pnpm install
pnpm i lucide-svelte
```

```
<script>
    import { Trash2 } from "lucide-svelte"
</script>
<Trash2 size="50" />
```

```
npm run build
````

"transforming (396) node_modules/.pnpm/lucide-svelte@0.253.0_svelte@4.0.0/node_modules/lucide-svelte/dist/svelte/icons/codepen.svelte"
✓ 1267 modules transformed
then
✓ 1247 modules transformed.
```

The majority of these are lucide-svelte. It runs OK on my macbook pro, but takes much longer than expected. On my Linode it runs out of memory. Suspect it might not work on Vercel.

**Comment by weepy** [comment]
As a work around - converting the imports to `import Settings from "lucide-svelte/dist/svelte/icons/settings.svelte"` 
works ok.

**Comment by ericfennis** [comment]
Thanks for the extra information, this a related issue to #1284 .
This is something we need to look into, we had a time we all compiled and transpile all svelte files but that caused some issues in some compilers. So we switched to svelte components imports like they mention in the [SvelteKit docs](https://kit.svelte.dev/docs/packaging#anatomy-of-a-package-json-exports). But maybe better if we switch back and fix those issues. Not sure if it will fix the out-of-memory issue, but I assume this has something to do with the Vite transpiling jobs running parallel, vite has some issues with this.

**Comment by weepy** [comment]
I think b/c you have ```export * from './icons';``` then there can't be any tree shaking and so it ends up transforming every icon rather than just the ones you need.

**Comment by ericfennis** [comment]
@weepy That's maybe possible, we should validate this.

**Comment by weepy** [comment]
I think to do this like you are imagining you need a build step that
creates lucide-svelte.ts to look something like this

```
import X from "./icons/x/svelte"
export X
... etc
```

This would allow the treeshaking to work as expected.

**Comment by marvin-j97** [comment]
Same seems to be happening when using Astro (which is also based on Vite like SvelteKit).

**Comment by gusvianadev** [comment]
I'm having the same issue with Solid.js if it helps. I import one icon but it's importing every single one.

**Comment by ericfennis** [comment]
I created a beta release on `lucide-svelte@0.269.0-beta.0`.
In this release the conditional exports property is added, this probably also fixes this issue.

If someone can test this as well, that would be nice!
```
npm install lucide-svelte@0.269.0-beta.0
```

**Comment by ericfennis** [comment]
@rbozan Thanks for testing. Will take a look at this one!

**Comment by gyurielf** [comment]
I'm having the same issue nowadays.

```ts
import { ChevronDown, ChevronUp, Trash2 } from 'lucide-svelte';
```

On build transformed all of the modules(icons).
