### ISSUE TITLE
Icon request: compass (drawing tool)

### ISSUE THREAD

**Issue by giovannimalausa** [lucide-icons/lucide#1416]
## Icon Request

* Icon name: compass (drawing tool) / pair of compasses
* Use case: It can be used in association with the idea of "Design", it surely would in Italy where one of the most prestigious design awards is named "Compasso d'oro" (literally _Gold Compasses_). It would also be useful to indicate the concept of technical drawing.
* _Screenshots_ of similar icons:
* 
![image](https://github.com/lucide-icons/lucide/assets/83951798/9cea6c9f-8d3d-4d25-9ba1-473aca6195cf)
(something a little more minimal than this would be nice)

**Comment by ericfennis** [comment]
Nice request!

**Comment by karsa-mistmere** [comment]
![drawing-compass](https://github.com/lucide-icons/lucide/assets/17746067/6471a958-9b26-4154-826b-8576a74ac4cb)

**Comment by ericfennis** [comment]
Was added in https://github.com/lucide-icons/lucide/pull/1142
