### ISSUE TITLE
Request: Telegram

### ISSUE THREAD

**Issue by matthewmorek** [lucide-icons/lucide#1417]
## Icon Request

* Icon name: `Telegram`
* Use case: Social media icons in footers, headers, buttons, etc.
* _Screenshots_ of similar icons:
![CleanShot 2023-07-02 at 14 41 18](https://github.com/lucide-icons/lucide/assets/1137994/16371391-c3bc-45f1-813c-f988857d6b2f)
https://www.pngwing.com/en/free-png-pmbdt

Totally understand this would have to be an outline style, and there's a few good ones, such as this glyph:
```xml
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 32 32"><path d="M26.07 3.996a2.974 2.974 0 0 0-.933.223h-.004c-.285.113-1.64.683-3.7 1.547l-7.382 3.109c-5.297 2.23-10.504 4.426-10.504 4.426l.062-.024s-.359.118-.734.375a2.03 2.03 0 0 0-.586.567c-.184.27-.332.683-.277 1.11.09.722.558 1.155.894 1.394.34.242.664.355.664.355h.008l4.883 1.645c.219.703 1.488 4.875 1.793 5.836.18.574.355.933.574 1.207.106.14.23.257.379.351a1.119 1.119 0 0 0 .246.106l-.05-.012c.015.004.027.016.038.02.04.011.067.015.118.023.773.234 1.394-.246 1.394-.246l.035-.028 2.883-2.625 4.832 3.707.11.047c1.007.442 2.027.196 2.566-.238.543-.437.754-.996.754-.996l.035-.09 3.734-19.129c.106-.472.133-.914.016-1.343a1.807 1.807 0 0 0-.781-1.047 1.872 1.872 0 0 0-1.067-.27Zm-.101 2.05c-.004.063.008.056-.02.177v.011l-3.699 18.93c-.016.027-.043.086-.117.145-.078.062-.14.101-.465-.028l-5.91-4.531-3.57 3.254.75-4.79 9.656-9c.398-.37.265-.448.265-.448.028-.454-.601-.133-.601-.133l-12.176 7.543-.004-.02-5.836-1.965v-.004l-.015-.003a.27.27 0 0 0 .03-.012l.032-.016.031-.011s5.211-2.196 10.508-4.426c2.652-1.117 5.324-2.242 7.379-3.11 2.055-.863 3.574-1.496 3.66-1.53.082-.032.043-.032.102-.032Z"/></svg>
```
![CleanShot 2023-07-02 at 14 47 22](https://github.com/lucide-icons/lucide/assets/1137994/5d49ee9c-6e5c-4d0e-8b3f-4ef89bfed25f)

**Comment by karsa-mistmere** [comment]
Brand icons are no longer accepted, see: #94 #670

**Comment by webgodo** [comment]
But why do you have Linkedin and Instagram? @karsa-mistmere

**Comment by karsa-mistmere** [comment]
> But why do you have Linkedin and Instagram? [@karsa-mistmere](https://github.com/karsa-mistmere)

Purely because of backward compatibility reasons, but they will be removed in v1.0.0
