### ISSUE TITLE
Crossed arrows request

### ISSUE THREAD

**Issue by kacperwyczawski** [lucide-icons/lucide#1418]
## Icons requests

* Icon name:
* * `arrow-up-crossed` based on existing `arrow-up`
* * `arrow-down-crossed` based on existing `arrow-down`
* * `arrow-big-up-crossed` based on existing `arrow-big-up`
* * `arrow-big-down-crossed` based on existing `arrow-big-down`
* Use case:
* * Cancellation or removal of an upvote/downvote
* * Disabling updates
* ~~_Screenshots_~~ ugly sketch of similar icons:
![image](https://github.com/lucide-icons/lucide/assets/97523625/ee731596-f73e-488c-9600-e388f9eaae0a)

**Comment by ericfennis** [comment]
Similar to #922. But this is just bad UX if you want to use it for that usecase. It's better to use color to indicate if something is on or off. Or use the `fill` attribute. I close this one.
