### ISSUE TITLE
Icon Request: Tiktok

### ISSUE THREAD

**Issue by smartercow** [lucide-icons/lucide#1423]
## Icon Request

* Icon name: Tiktok
* Use case: Social media icon
* _Screenshots_ of similar icons: Just an outlined Tiktok icon like the rest of Lucide brand icons

**Comment by jguddas** [comment]
Sorry, we do not add brand icons.

**Comment by smartercow** [comment]
> 

Well, that's sad that one of the most popular social media, even popular than some on the list doesn't exist on my favorite icon package.

**Comment by smartercow** [comment]
> 

Well, that's sad that one of the most popular social media, even popular than some on the list doesn't exist on my favorite icon package.

**Comment by jguddas** [comment]
Maybe this is useful as a replacement
https://simpleicons.org/?q=tiktok

**Comment by pdrbrnd** [comment]
@jguddas I find that reasoning a bit strange given Lucide includes icons for brands like instagram, twitter, facebook, linkedin, etc.

**Comment by muneebkhan98** [comment]
fb, insta, linkedin, youtube, all are there, but we don't do brand icons, excuse me?
