### ISSUE TITLE
Discord Icon Request

### ISSUE THREAD

**Issue by anikdhabal** [lucide-icons/lucide#1434]
## Icon Request

* Icon name:Discord
* Use case:
* _Screenshots_ of similar icons:
![Screenshot 2023-07-15 232342](https://github.com/lucide-icons/lucide/assets/81948346/25a14560-06b6-443d-8688-6e1c95921686)

**Comment by jguddas** [comment]
Sorry, we are not adding brand icons.

**Comment by karsa-mistmere** [comment]
Yes, please also refer to #670
We recommend using [simple-icons](https://github.com/simple-icons/simple-icons) for any brand icon needs.

**Comment by Aaqu** [comment]
> Sorry, we are not adding brand icons.

Facebook and linked is better than discord? Remove this brands

**Comment by karsa-mistmere** [comment]
@Aaqu: there are still a few issues blocking the straightforward removal of these icons, see #670.

All of us maintaining this project have full time jobs with little time to spare, if you have the capacity, feel free to submit PRs solving these issues, in particular #1607.

**Comment by Lettable** [comment]
add discord bro you ualready have muuch brands add those also
