### ISSUE TITLE
All icons are loaded since 0.260.0

### ISSUE THREAD

**Issue by resah** [lucide-icons/lucide#1437]
## Prerequisites

* Version: 0.260.0
* Are you running from source/main: no
* Are you using a released build: from npm 0.260.0
* Operating system: Windows, Mac OSX, Ubuntu 22.04 LTS (Jammy Jellyfish)
* Bits: 64

## Step to reproduce

Using Remix 1.18.1 server-side-rendering, only icon-specific imports are used, no general `icons` import, also no `lazy` or `dynamicIconImports` commands used:

With version **0.259.0** I see a page loading 40 (chunks) in network panel.

After updating to version **0.260.0** (and changing nothing else) more than 1200 network requests cause a substantial increase in page loading time (~30seconds).

**Comment by nuno** [comment]
same here

**Comment by oMatheuss** [comment]
For me, version 0.258.0 just imports everything inside a js file whereas version 0.260.0 imports all modules separately.
I'm using React from Vite 4.4.0 with SWC. After build this doesnt happen.

**Comment by bastianccm** [comment]
Looking into this, one cause seems to be remix preloading all depencies. This is done by inspecting esbuilds import statements, and adding a preload link element.
From what I can tell, the dynamicIconImports.js having import references for all icons:
```js
const dynamicIconImports = {
  "accessibility": () => import('./icons/accessibility.js'),
  "activity-square": () => import('./icons/activity-square.js'),
  "activity": () => import('./icons/activity.js'),
  // ...
  ```
  This seems to cause esbuild to consider all icons as possible imports, which causes remix-run to compile them all in separate preload statements:
https://github.com/remix-run/remix/blob/f2c4edfc28f7427189e67f32f12628e1c45b6b69/packages/remix-dev/compiler/manifest.ts#L35-L37

https://github.com/remix-run/remix/blob/f2c4edfc28f7427189e67f32f12628e1c45b6b69/packages/remix-react/components.tsx#L1091-L1096

Manually removing `export { default as dynamicIconImports } from './dynamicIconImports.js';` from `node_modules/lucide-react/dist/esm/lucide-react.js` "resolves" this issue.

I am no expert in esbuild myself, but maybe this helps as a pointer in the right direction? Maybe it's possible to create a new module for dynamicIconImports?

**Comment by nuno** [comment]
seem to work fine now with "lucide-react": "^0.263.0

**Comment by P-de-Jong** [comment]
I'm stuck on this with Remix. Using version 0.274.0, but all icons are loaded. Anyone who can point me in the right direction? Currently using this in my component:

```typescript
import { lazy, Suspense } from 'react';
import dynamicIconImports from 'lucide-react/dynamicIconImports';

type IconProps = {
  name: keyof typeof dynamicIconImports;
  color?: string;
  size?: string;
};

const fallback = <div style={{ background: '#ddd', width: 24, height: 24 }} />;

const Icon = ({ name, ...props }: IconProps) => {
  const LucideIcon = lazy(dynamicIconImports[name]);

  return (
    <Suspense fallback={fallback}>
      <LucideIcon {...props} />
    </Suspense>
  );
};

export default Icon;
```

**Comment by nuno** [comment]
@P-de-Jong 
I use 0.265.0 or 0.276.0 and I have no issues with remix!

Now , I load my icons normally, not sure if your issue is related from the way you have that component setup.

`import { BookCopy, PlusCircle } from "lucide-react`

JSX:

```<div><PlusCircle className="mr-2 h-4 w-4" /></div>```

**Comment by P-de-Jong** [comment]
@nuno i'm trying to use a dynamic component so that users can select an icon in a CMS, instead of defining everything in advance. I got it to work now. I was mixing the `import { BookCopy, PlusCircle } from "lucide-react` style with the dynamic component i showed before. Now i'm just using the dynamic component everywhere and it correctly lazy loads the icons as expected 👍
