### ISSUE TITLE
playing card suit symbols

### ISSUE THREAD

**Issue by llaenowyd** [lucide-icons/lucide#144]
I put together a solitaire game for android. First I tried using the unicode symbols, but was surprised to learn that they commonly receive a fixed coloring when rendered as text (i.e. spades and clubs are black and diamonds and hearts rendered red, despite explicit application text styles). This was true in my case, due to whatever rendering engine treats Flutter `Text` elements.

So I looked for some SVG's for it, and found some that worked well enough.  I find after playing the game a bit though, at the scale of my phone's display, the spades icon (♠) and clubs icon (♣) are not differentiated well enough, causing some eye strain.

I did not see any great alternatives in other icon sets. I can try to submit a PR if it's a welcome addition here.

## Icon Request

* Icon name: playing card suits (hearts (filled), spades, clubs, diamonds)
* Use case: implementing or creating an icon for a card game
* Screenshots of similar icons:

in the app, without enough differentiability:
<img src="https://user-images.githubusercontent.com/41239783/99699094-941b2a00-2a5f-11eb-93ab-e9309b8ab1b8.png" width=300>

these clubs are visually different from the spades, the lobes (?) of the clubs are nearly completed circles:
![220px-4coloraces1](https://user-images.githubusercontent.com/41239783/99699279-c3319b80-2a5f-11eb-84c8-f16a4a359874.jpg)

standard cards showing similar style, good difference between clubs and spades
![bicycle_cards](https://user-images.githubusercontent.com/41239783/99716133-bd46b500-2a75-11eb-9a1a-81f9907af7a1.jpg)

this is an example of not-so-great difference spades/clubs, unfortunately prevalent among free icon svgs
![10236803_0](https://user-images.githubusercontent.com/41239783/99716497-2dedd180-2a76-11eb-8c11-232ea7f83701.jpg)

here's a vintage style clubs which seems to completely differentiate from spades, but it's less iconic, my preference would be similar to the standard cards above
![vintage-clubs](https://user-images.githubusercontent.com/41239783/99717184-12cf9180-2a77-11eb-82ce-ad8caf14e020.jpg)

**Comment by ericfennis** [comment]
@llaenowyd Nice request!!

**Comment by locness3** [comment]
I'm not sure we would be able to do better than other SVG icon sets, especially given the fact that Lucide has its own design style that icons all follow...

**Comment by llaenowyd** [comment]
Yes, the existing heart icon reminds me more of the "not-so-great" clubs example above, it's very mild.

Thus, the direction I want to take would probably arrive at a `suit-hearts.svg` that is differently shaped than the existing `heart.svg`, which I think might be where those stylistic concerns would be clearly in conflict.

I don't have much dog in the fight - at best I'd have to pick the SVG out of the set to use it in the Flutter app, I think, at least that's how I've approached it thus far.

**Comment by llaenowyd** [comment]
Another similar example, I need these to have square joins to get that sharper look I'm going for.

Ok good talk! 😄
