### ISSUE TITLE
lucide-react 0.262 failed to resolve in vite3

### ISSUE THREAD

**Issue by yjrhgvbn** [lucide-icons/lucide#1445]
## Prerequisites

* Version: 0.262.0
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system:  MacOS m2
* Bits: 64

## Step to reproduce

create vite3 project, select react and typescript
```
pnpm create vite@3
```
Install lucide-react
```
pnpm install lucide-react 
```
import example:
```
import { BoldIcon } from "lucide-react";

function App() {
  return <BoldIcon />;
}

export default App;

```
run vite server
```
pnpm dev
```

### Actual behavior

cannot run and shows an error

## Any message or error

`Failed to resolve entry for package "lucide-react". The package may have incorrect main/module/exports specified in its package.json.`
<img width="826" alt="image" src="https://github.com/lucide-icons/lucide/assets/32033682/08e5beb1-9bd4-4ec7-87f3-6967b257b052">

It can run normally in vite4

**Comment by alexbacanu** [comment]
I have a similar error in 0.262.0 and 0.263.0, from what I've seen it seems that `packages/lucide-react/package.json` is pointing to non existent files:

Should be:
```diff
{
...
-  "main": "dist/cjs/lucide-react.js",
+  "main": "dist/cjs/lucide-react.cjs",
   "main:umd": "dist/umd/lucide-react.js",
-  "module": "dist/esm/lucide-react.js",
+  "module": "dist/esm/lucide-react.mjs",
...
}
```
