### ISSUE TITLE
Fire icon (filled)

### ISSUE THREAD

**Issue by N-NeelPatel** [lucide-icons/lucide#1448]
## Icon Request

* Icon name: solid fire
* Use case: to show streak in applications like leetcode, duolingo
* _Screenshots_ of similar icons: 
![image](https://github.com/lucide-icons/lucide/assets/29038590/9e7db6f4-9520-4756-803f-3b9c7889a529)

**Comment by karsa-mistmere** [comment]
We do not currently support filled icons out of the box, although in this instance you can just set the fill attribute on `flame` manually, e.g. `<FlameIcon fill="currentColor" />`.

Once we do have support for filled icons, this definitely will be on the table, just not in the foreseeable future, see discussions in #458
