### ISSUE TITLE
firebase icon

### ISSUE THREAD

**Issue by N-NeelPatel** [lucide-icons/lucide#1449]
## Icon Request

* Icon name: firebase
* Use case: to show the use of firebase app
* _Screenshots_ of similar icons:
![image](https://github.com/lucide-icons/lucide/assets/29038590/bc04e958-c79c-48a0-898e-257aa06723b5)

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated, we recommend using simpleicons.org #670
