### ISSUE TITLE
NextJs Dynamic Loading Icon cause of reload whole page when clicking

### ISSUE THREAD

**Issue by sang-au** [lucide-icons/lucide#1450]
## Prerequisites

* Version: 0.262.0
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system: Debian 12
* Bits: 64 bits

## Step to reproduce

Follow the docs: https://lucide.dev/guide/packages/lucide-react, section NextJS Example

### Actual behavior

Whole page reload when clicking on any icon

## Any message or error

N/A

## Resources

N/A

## Workaround

Wrap Icon component with memo, or useMemo to wrap the dynamic import

```jsx
import { memo } from 'react';

import dynamic from 'next/dynamic';

import { LucideProps } from 'lucide-react';
import dynamicIconImports from 'lucide-react/dynamicIconImports';

type IconProps = LucideProps & {
  name: keyof typeof dynamicIconImports;
};

const Icon = memo(({ name, ...props }: IconProps) => {
  const LucideIcon = dynamic(dynamicIconImports[name]);

  return <LucideIcon {...props} />;
});

Icon.displayName = 'Icon';

export default Icon;

```

**Comment by ericfennis** [comment]
@sang-au Thanks for reporting.
I couldn't reproduce this, can you provide a repo with this issue?

**Comment by sang-au** [comment]
Ok, lets me try to move the code to new repository. I will give you link when I complete

**Comment by ericfennis** [comment]
I need a reproduction repo. I will reopen this issue if the repo is provided.

**Comment by arunavo4** [comment]
I had the same issue. Tried to replicate it on a new repo but it was working fine an did not have the issue, but on my original I kept having this issue. So I finally just slapped Memo on the Dynamic Icon component and called it a day.

```tsx
import React from "react";
import dynamic from "next/dynamic";
import { LucideProps } from "lucide-react";
import dynamicIconImports from "lucide-react/dynamicIconImports";

interface IconProps extends LucideProps {
  name: keyof typeof dynamicIconImports;
}

const _Icon = ({ name, ...props }: IconProps) => {
  const LucideIcon = dynamic(dynamicIconImports[name]);

  return <LucideIcon {...props} />;
};

// 🩹 Fix for unnecessary re-renders
const Icon = React.memo(_Icon);

export default Icon;
```
