### ISSUE TITLE
Vercel/Astro/React/Node 'too many open files' error

### ISSUE THREAD

**Issue by guysolan** [lucide-icons/lucide#1457]
This issue is similar to Issue [1446](https://github.com/lucide-icons/lucide/issues/1446). However, the issue is with Astro not NextJS, therefore the modularizeImports fix does not work.

Please note: I have never opened an issue before so apologies for any bad practice.

## Prerequisites

* Version: "lucide": "^0.261.0", "lucide-react": "^0.263.1",
* Are you running from source/main: Astro /dist directory
* Are you using a released build: Yes
* Operating system: Node.js 18.x
* Bits:

## Step to reproduce

npm create astro@latest

npx astro add react

npm install lucide-react

Deploy to  vercel using '@astrojs/vercel/serverless'

## Any message or error

Error message via Vercel logs:

```
Time
July 25 11:54:33.53 GMT+01:00
Status Code
500
Host

Request ID
4vpgm-1690282473526-b50ce645ed85
Request User Agent
Vercel Edge Functions
Level
Error

Cache
MISS
Type
Serverless Function

Function
/render
Location
Washington, D.C., USA (iad1)
Runtime
Node.js 18.x

Execution Duration / Limit
5ms / 10s
Memory Used / Limit
204 MB / 1024 MB
10:54:33 AM [ssr] Error: EMFILE: too many open files, open '/var/task/node_modules/lucide-react/dist/esm/icons/shirt.mjs' (x3)
```

## Resources

<img width="951" alt="image" src="https://github.com/lucide-icons/lucide/assets/56299900/fbb1fd74-01cf-4b35-9345-71b243d5e029">

**Comment by josephkruse** [comment]
I'm also getting this error in Vercel as of yesterday. The modularizeImports fix didn't work for me in either.

**Comment by ericfennis** [comment]
@guysolan Thanks for pointing this out.
Hmm, it looks like NodeJS module system with `.mjs` works differently and has a maximum of "open files". 
I will look if we can switch back to `.js` modules.. Will try if this fixes it.

**Comment by cstrnt** [comment]
Downgrading to `"0.261.0"` solved the issue for me without any configuration :)

**Comment by smolak** [comment]
> Downgrading to `"0.261.0"` solved the issue for me without any configuration :)

It might be a coincidence, as when I build the app locally, using that exact version and no additional configuration in next.config.js, I get 2119 modules compiled. Without the lucide icons usage whatsoever, I get ~1000 less. And I only use, in my app, ~10 icons, so the number of compiled modules should grow by that 10 number, not ~1000.

**Comment by cstrnt** [comment]
> > Downgrading to `"0.261.0"` solved the issue for me without any configuration :)
> 
> It might be a coincidence (you getting slightly below the max number of loaded modules limit, using the older version that has fewer icons etc.), as when I build the app locally, using that exact version and no additional configuration in next.config.js, I get 2119 modules compiled. Without the lucide icons usage whatsoever, I get ~1000 less. And I only use, in my app, ~10 icons, so the number of compiled modules should grow by that 10 number, not ~1000. Check the compiled modules number with and without lucide-react.

I actually don't think it's a coincidence. Version `0.262.0` changed the type to `"type": "module"` which is a different module resolution algorithm. I think the issue @ericfennis mentioned is related to this

**Comment by smolak** [comment]
Good news. NextJS PR just [got merged to canary](https://github.com/vercel/next.js/pull/53051).

**Comment by smolak** [comment]
@ericfennis But [there are some problems](https://github.com/vercel/next.js/pull/53051#issuecomment-1656211058) - could you guys cooperate to get this fixed on both sides? :) Would be cool.

**Comment by ericfennis** [comment]
@smolak Hmm interesting. Currently an icon with an alias are pointing out to the same icon module. To get these transformed imports working for aliases requires to adjust the build flow and create those "alias" modules. But that is not really a preferred solution, because it will create duplicated code and ghosted code (because it is not imported anywhere else in the library).

**Comment by ericfennis** [comment]
I made a draft PR #1471 to revert the change to ".mjs" files and the "conditional exports" package.json file. So will be the same as in 0.261.0. The `dynamicIconImports` file will be build to root of the package, so importing it from `lucide-react/dynamicIconImports` will still be possible.

I published a test version on `lucide-react@0.263.2-beta.0`.
Testing is welcome! If you find problems, please post them in #1471 

@smolak Regarding to problems you mentioned in https://github.com/vercel/next.js/pull/53051#issuecomment-1656211058.
I'm thinking of exposing an extra module in lucide-react called modularizeLucideImports which will include all the necessary import transforms including all the aliases. This file can be imported in the nextjs config to make modularizeImports work. 

So will be working something like this:
```js
// next.config.js
const modularizeLucideImports = require('lucide-react/modularizeLucideImports')

module.exports = {
  modularizeImports: {
    'lucide-react': modularizeLucideImports
  }
}
```

```js
// lucide-react/modularizeLucideImports.js
const modularizeLucideImports = {
  transform: [
    ['*', 'lucide/dist/esm/icons/{{lowerCase kebabCase member}}']
    // All necessary imports
    // ...
  ],
};
module.exports = modularizeLucideImports;
```

This idea is not included in #1471  will make a separate PR for it.

**Comment by ericfennis** [comment]
@guysolan Can you check if it is working fine on version `lucide-react@0.263.2-beta.0`?

**Comment by guysolan** [comment]
@ericfennis I can confirm all Vercel errors are resolved. Thank you very much.

**Comment by ericfennis** [comment]
@guysolan ah thanks for testing! Will release final release soon.
