### ISSUE TITLE
X (Twitter)

### ISSUE THREAD

**Issue by mohamed-azhar** [lucide-icons/lucide#1468]
## Icon Request

* Icon name: X (Twitter)
* Use case: Represent the new social media logo for Twitter
* _Screenshots_ of similar icons: 
![257061556-ea168e9a-bf1c-4d5a-9611-410e95681a3e](https://github.com/lucide-icons/lucide/assets/17266828/49b41c52-e067-4ed1-8cfb-13cbcaa268f3)

**Comment by jguddas** [comment]
https://lucide.dev/icons/x

**Comment by zardoy** [comment]
```tsx
import { SiX } from '@icons-pack/react-simple-icons'
```
