### ISSUE TITLE
Nautical dusk, astronomical dusk and dawn.

### ISSUE THREAD

**Issue by cjh9** [lucide-icons/lucide#147]
Super specific request, you may close this. I figure it could be possible to do a boat and telescope (tripod with a tube) in svg.

Nautical dusk: Sunset with a boat in the background.
Astronomical dusk: Sunset with a telescope in the background

Nautical dawn: Sunrise with a boat in the background. 
Astronomical dawn: Sunrise with a telescope in the background.

**Comment by ericfennis** [comment]
@cjh9 yeah sorry,  this way to specific for an icon library.
This is more of an illustration. 

But separate icons for a telescope and a boat can be good icon requests, but please open them in separate requests.
