### ISSUE TITLE
map-pin-home

### ISSUE THREAD

**Issue by Snailedlt** [lucide-icons/lucide#1476]
## Icon Request

* Icon name: map-pin-home
* Use case: When you want to select your location for your home, or for pinning a location related to a *home*, *house* or *building*.
* _Screenshots_ of similar icons: 
<img src="https://github.com/lucide-icons/lucide/assets/43886029/dafd9d9c-afba-408f-80a3-4125935dc52c" height="100px" />
<img src="https://github.com/lucide-icons/lucide/assets/43886029/d250d94a-48c9-44f9-b464-86ee186c01c0" height="100px" />
<img src="https://github.com/lucide-icons/lucide/assets/43886029/d0c04fef-8422-4045-b249-8828eced6a42" height="100px" />

There's a lot of different icons similar to this out there. Here's a few more: https://thenounproject.com/browse/icons/term/pin-home/

Code of similar icon (the first one):
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
  <path d="M9 13H11V10.25H13V13H15V8.25L12 6.25L9 8.25V13ZM12 19.35C14.0333 17.4833 15.5417 15.7875 16.525 14.2625C17.5083 12.7375 18 11.3833 18 10.2C18 8.38333 17.4208 6.89583 16.2625 5.7375C15.1042 4.57917 13.6833 4 12 4C10.3167 4 8.89583 4.57917 7.7375 5.7375C6.57917 6.89583 6 8.38333 6 10.2C6 11.3833 6.49167 12.7375 7.475 14.2625C8.45833 15.7875 9.96667 17.4833 12 19.35ZM12 21.325C11.7667 21.325 11.5333 21.2833 11.3 21.2C11.0667 21.1167 10.8583 20.9917 10.675 20.825C9.59167 19.825 8.63333 18.85 7.8 17.9C6.96667 16.95 6.27083 16.0292 5.7125 15.1375C5.15417 14.2458 4.72917 13.3875 4.4375 12.5625C4.14583 11.7375 4 10.95 4 10.2C4 7.7 4.80417 5.70833 6.4125 4.225C8.02083 2.74167 9.88333 2 12 2C14.1167 2 15.9792 2.74167 17.5875 4.225C19.1958 5.70833 20 7.7 20 10.2C20 10.95 19.8542 11.7375 19.5625 12.5625C19.2708 13.3875 18.8458 14.2458 18.2875 15.1375C17.7292 16.0292 17.0333 16.95 16.2 17.9C15.3667 18.85 14.4083 19.825 13.325 20.825C13.1417 20.9917 12.9333 21.1167 12.7 21.2C12.4667 21.2833 12.2333 21.325 12 21.325Z" fill="#002A11"/>
</svg>
```

**Comment by jguddas** [comment]
![icon (7)](https://github.com/lucide-icons/lucide/assets/25524993/2e073518-d226-4fa1-a224-dde6e970ceba)

**Comment by karsa-mistmere** [comment]
This is rather detailed to work well with our guidelines, I think something like these would be the best we could do, but I'm not sure any of these truly makes the cut:
![image](https://github.com/lucide-icons/lucide/assets/17746067/7c8e78e9-b01d-4d92-949f-5841e9f4335e)
![image](https://github.com/lucide-icons/lucide/assets/17746067/4e30f5ff-cbf7-4178-9c48-5092118fcf17)

**Comment by karsa-mistmere** [comment]
> ![icon (7)](https://user-images.githubusercontent.com/25524993/257997603-2e073518-d226-4fa1-a224-dde6e970ceba.svg)

Oh, I only just now see your reply, this issue was left open in my browser.
Your house shape is better than mine, although I think we would have to lose the chimney, and maybe add a bit of rounding:
![image](https://github.com/lucide-icons/lucide/assets/17746067/724cfebd-328a-4178-a2f9-19f5a78647b5)

**Comment by Snailedlt** [comment]
Can we use the original house svg perhaps?
https://lucide.dev/icons/home
<img src="https://github.com/lucide-icons/lucide/assets/43886029/8a4be509-7ae7-4581-b8fa-91f9c3755862"/>

Looks okey when it's small too:
<img src="https://github.com/lucide-icons/lucide/assets/43886029/8a4be509-7ae7-4581-b8fa-91f9c3755862" height="10px"/>

**Comment by Snailedlt** [comment]
Perhaps the roof can extend a bit past the walls so that it's more clear?
If we add a door like in the [Home](https://lucide.dev/icons/home) icon to the image you posted I think it looks quite a bit better @karsa-mistmere :
<img src="https://github.com/lucide-icons/lucide/assets/43886029/cb27551a-f928-496c-8136-08c5a11fb3fc" height="30rem"/>
<img src="https://github.com/lucide-icons/lucide/assets/43886029/19252d03-e77e-4364-a741-8546e87b6b22" height="30rem"/>

<img src="https://github.com/lucide-icons/lucide/assets/43886029/19252d03-e77e-4364-a741-8546e87b6b22" />

**Comment by karsa-mistmere** [comment]
The door violates one of our design guidelines I'm afraid, there must be a 2px gap between all elements.

**Comment by Snailedlt** [comment]
Sounds like a good rule in general, but bummer that it makes this design unviable.

I also think @jguddas design looks good though

**Comment by karsa-mistmere** [comment]
New idea:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15+22a1+1+0+0+1-1-1v-4a1+1+0+0+1+.445-.832l3-2a1+1+0+0+1+1.11+0l3+2A1+1+0+0+1+22+17v4a1+1+0+0+1-1+1z%22+/%3E%3Cpath+d=%22M18+10a8+8+0+0+0-16+0c0+4.993+5.539+10.193+7.399+11.799a1+1+0+0+0+.601.2%22+/%3E%3Cpath+d=%22M18+22v-3%22+/%3E%3Ccircle+cx=%2210%22+cy=%2210%22+r=%223%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUgMjJhMSAxIDAgMCAxLTEtMXYtNGExIDEgMCAwIDEgLjQ0NS0uODMybDMtMmExIDEgMCAwIDEgMS4xMSAwbDMgMkExIDEgMCAwIDEgMjIgMTd2NGExIDEgMCAwIDEtMSAxeiIgLz4KICA8cGF0aCBkPSJNMTggMTBhOCA4IDAgMCAwLTE2IDBjMCA0Ljk5MyA1LjUzOSAxMC4xOTMgNy4zOTkgMTEuNzk5YTEgMSAwIDAgMCAuNjAxLjIiIC8+CiAgPHBhdGggZD0iTTE4IDIydi0zIiAvPgogIDxjaXJjbGUgY3g9IjEwIiBjeT0iMTAiIHI9IjMiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>
