### ISSUE TITLE
Import bug in Next.js (v13.4.13)

### ISSUE THREAD

**Issue by gregberge** [lucide-icons/lucide#1482]
## Prerequisites

* Version: 0.264.0
* Are you running from source/main: nop
* Are you using a released build: nop
* Operating system: Mac OS
* Bits: -

## Step to reproduce

Import icon in a Next.js v13.4.13 (latest)

### Actual behavior

I see an error when importing the icon.

## Any message or error

```
Attempted import error: 'modularize-import-loader?name=CalendarDays&from=default&as=default&join=./icons/calendar-days!lucide-react' does not contain a default export (imported as 'CalendarDays').
```

--- 

It works well on v0.263.x, I suspect a bug in the new ESM export.

**Comment by ericfennis** [comment]
Can you post your nextjs config?

**Comment by abdelhameedhamdy** [comment]
error with 0.264.0
next 13.4.13

- error ./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve '/Users/abdelhameed/DevApps/vercel/my-app-shadcn/node_modules/lucide-react/dist/cjs/icons/chevron-left'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/ui/calendar.tsx
./app/page.tsx

next.config:
```
/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
```

**Comment by Jordaneisenburger** [comment]
Same for me, `Module not found: Can't resolve '/Users/jordan/project/node_modules/lucide-react/dist/cjs/icons/star'`

**Comment by spencer5051** [comment]
Just went to ncu --upgrade and I saw the issue occur when upgrading from / to the following versions.

 lucide-react  ^0.263.1  →  ^0.264.0

**Comment by nbahadori143** [comment]
same for me here the list of icons not found:

- arrow-right
- alert-triangle
- alert-circle

**Comment by jupcan** [comment]
same here, seems to happen with all icons, next 13.4.12 on my side

**Comment by nbahadori143** [comment]
I have just downgraded to `0.263.1`, and it works for now.

**Comment by ericfennis** [comment]
@abdelhameedhamdy I'm a bit surprised with your issue, after seeing your Nextjs Config.
But just found out that the NextJS repo hardcoded some modularize imports for the `lucide-react` package, which are outdated with the changes in `lucide-react@0.264.0`.
```jsx
transform: {
        // Special aliases
  '(SortAsc|LucideSortAsc|SortAscIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/arrow-up-narrow-wide!lucide-react',
  '(SortDesc|LucideSortDesc|SortDescIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/arrow-down-wide-narrow!lucide-react',
  '(Verified|LucideVerified|VerifiedIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/badge-check!lucide-react',
  '(Slash|LucideSlash|SlashIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/ban!lucide-react',
  '(CurlyBraces|LucideCurlyBraces|CurlyBracesIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/braces!lucide-react',
  '(CircleSlashed|LucideCircleSlashed|CircleSlashedIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/circle-slash-2!lucide-react',
  '(SquareGantt|LucideSquareGantt|SquareGanttIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/gantt-chart-square!lucide-react',
  '(SquareKanbanDashed|LucideSquareKanbanDashed|SquareKanbanDashedIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/kanban-square-dashed!lucide-react',
  '(SquareKanban|LucideSquareKanban|SquareKanbanIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/kanban-square!lucide-react',
  '(Edit3|LucideEdit3|Edit3Icon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/pen-line!lucide-react',
  '(Edit|LucideEdit|EditIcon|PenBox|LucidePenBox|PenBoxIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/pen-square!lucide-react',
  '(Edit2|LucideEdit2|Edit2Icon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/pen!lucide-react',
  '(Stars|LucideStars|StarsIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/sparkles!lucide-react',
  '(TextSelection|LucideTextSelection|TextSelectionIcon)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/text-select!lucide-react',
  // General rules
  'Lucide(.*)':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/{{ kebabCase memberMatches.[1] }}!lucide-react',
  '(.*)Icon':
    'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/{{ kebabCase memberMatches.[1] }}!lucide-react',
  '*': 'modularize-import-loader?name={{ member }}&from=default&as=default&join=./icons/{{ kebabCase member }}!lucide-react',
},
```
See: https://github.com/vercel/next.js/blob/5ea372d6421614bfa10cc81ca5b3e71d8c06cf27/packages/next/src/server/config.ts#L686

So we need to update this list, but I'm not sure if this hardcoding is the best way if I'm honest. 
Some icons can be renamed and aliased. It is likely that this issue will happen again in the future.

**Comment by jacobawebb** [comment]
As of writing, options to get around this are:
- Wait for Vercel to update the hardcoded list which shouldn't be hardcoded
- Downgrade Lucide Icons

Is this right @ericfennis?

**Comment by jacobawebb** [comment]
This is a Vercel issue, not a lucide issue.
Vercel's expecting static exports per icon instead of doing it using the output of https://github.com/lucide-icons/lucide/blob/main/tools/build-icons/building/generateDynamicImports.mjs
e.g.
```ts
export { default as ArrowUpNarrowWide } from './dist/esm/icons/arrow-up-narrow-wide.js';
```
But this would increase bundle size and load time which is a no brainer to avoid.

**Comment by shuding** [comment]
@jguddas It would be great if Lucide React can add these aliases. Otherwise we'll have to maintain a list in Next.js to optimize the imports.

**Comment by trace2798** [comment]
I am currently facing this issue with Next.js 13.4.13 and lucide-react version 0.264.0 

- error ./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve 'D:\grafbash_fullstack\node_modules\lucide-react\dist\cjs\icons\camera'

My workaround: Downgraded lucide react to version 0.263.1 and it is working like expected.

**Comment by imCorfitz** [comment]
If I import directly from the esm modules, I don't get the error:
```ts
import { Menu } from "lucide-react/dist/esm/lucide-react";
```

```json
"lucide-react": "^0.264.0",
"next": "13.4.13",
```

**Comment by ericfennis** [comment]
@jacobawebb Yes I think so.
I hoped it was possible to override the default config, but that's also not possible 😞

**Comment by ericfennis** [comment]
Created a fix: https://github.com/vercel/next.js/pull/53697

**Comment by juliusmarminge** [comment]
> Created a fix: https://github.com/vercel/next.js/pull/53697

That fix will break earlier versions of `lucide-react` though, won't it?

IMO this hard coded list of overrides is a mess for anyone to maintain...

**Comment by theDanielJLewis** [comment]
Adding my voice here. I would have never known the sweet spot is 0.263.1 without this discussion thread.

**Comment by KingBael09** [comment]
Seems like `v0.264.0` and above are causing import problems.

**Comment by ericfennis** [comment]
@juliusmarminge Only 3 versions won't work with these changes ([v0.262.0](https://github.com/lucide-icons/lucide/tree/v0.262.0), [v0.263.0](https://github.com/lucide-icons/lucide/tree/v0.263.0), [v0.263.1](https://github.com/lucide-icons/lucide/tree/v0.263.1)).
The solution from @jguddas is the best solution for the "aliases" imports problem, but still: the path is not correct because the "exports" property is removed in version `0.264.0`, that caused some other problems see #1446

**Comment by LoyallAmsterdam** [comment]
It will also break Sanity live previews and Serverless functions on Vercel.

**Comment by SonuKumar81800** [comment]
**Packages version**

`next: "^13.4.13"`
`lucide-ract : "^0.265.0"`

Getting Error while importing Icons

* Icons.tsx
```ts
import { PackageCheck, PackageMinus, type LucideIcon } from 'lucide-react';


export type Icon = LucideIcon


export const Icons = {
    logo: PackageMinus
}
```

* MainNav.tsx
```ts
"use client"
import Link from "next/link";
import { useSelectedLayoutSegment } from "next/navigation"
import { useState } from "react";
import { Icons } from "@/components/Icons";

interface MainNavProps {


}

export function MainNav() {
    const segment = useSelectedLayoutSegment()
    const [mobileMenu, setMobileMenu] = useState<boolean>(false)

    return (
        <div className="flex gap-6 md:gap-10">
            <Link href="/" className="hidden items-center space-x-2 md:flex">
                <Icons.logo />
            </Link>
        </div >
    )
}
```


***Error :*** 
```bash
Module not found: Can't resolve '/Users/sonu/Projects/NextJS/memoir/node_modules/lucide-react/dist/cjs/icons/package-minus'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/Icons.tsx
./components/MainNav.tsx
```

**Comment by Kvintus** [comment]
+1

**Comment by ericfennis** [comment]
PR https://github.com/vercel/next.js/pull/53697 got merged and will be available in canary versions first.

**Comment by ericfennis** [comment]
@jacobawebb I was thinking to wait for the next canary release. Until then this issue is still active with current NextJS versions.

**Comment by NandiyaLive** [comment]
@ericfennis How can I deploy a project that has this error?

**Comment by KingBael09** [comment]
> @ericfennis How can I deploy a project that has this error?

For now downgrade lucide-react to `0.263.1`

```bash
pnpm add lucide-react@0.263.1
```

**Comment by NandiyaLive** [comment]
> > @ericfennis How can I deploy a project that has this error?
> 
> For now downgrade lucide-react to `0.263.1`
> 
> ```shell
> pnpm add lucide-react@0.263.1
> ```

I've done that but it still give the error on Vercel

**Comment by KevinYouu** [comment]
Same problem

`next: 13.4.13`
`lucide-react: 0.265.0`

```
- error ./node_modules/.pnpm/lucide-react@0.265.0_react@18.2.0/node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve '/Users/zdy/Desktop/Project/Nextjs_Learn/node_modules/.pnpm/lucide-react@0.265.0_react@18.2.0/node_modules/lucide-react/dist/cjs/icons/check'
```

**Comment by arsnl** [comment]
> > > @ericfennis How can I deploy a project that has this error?
> > 
> > 
> > For now downgrade lucide-react to `0.263.1`
> > ```shell
> > pnpm add lucide-react@0.263.1
> > ```
> 
> I've done that but it still give the error on Vercel

You probably just let the `^` in your `package.json`. Make sure your dependencie for lucide-react is exactly like this.

```
"lucide-react": "0.263.1",
```

Even when you specify the version with npm/pnpm/yarn on the install command, and even if you add the `-save-exact`, if your previous package version have a `^`, it gonna keep it.

**Comment by ericfennis** [comment]
This issue will be resolved in next version of NextJS
Please wait for the next release … or downgrade to lucide-react version 0.263.1 using
`pnpm add lucide-react@0.263.1`
If you are still having issues, we are happy to help over at https://discord.gg/EH6nSts.

**Comment by ericfennis** [comment]
🎉  [`next@3.4.14-canary.2`](https://github.com/vercel/next.js/releases/tag/v13.4.14-canary.2) is released with the updated import map.
