### ISSUE TITLE
Missed icons after 0.264.0 was released

### ISSUE THREAD

**Issue by nbahadori143** [lucide-icons/lucide#1484]
## Prerequisites

Version: Release v0.264.0
Running from: Import using webpack
Operating system: Mac OSX
Bits: 64 bits

## Any message or error

Hey there, I'm using the latest package (0.264.0), but the following icons are missing or renamed. I checked the changelog but couldn't find them.

- alert-circle
- alert-triangle
- alert-triangle
- arrow-right
- arrow-right

**Comment by karsa-mistmere** [comment]
Hey @nbahadori143,

Can you provide a bit more context? Which package are you using? What is the exact error?

I've checked the repo, and the icons are still definitely there: https://github.com/lucide-icons/lucide/blob/main/icons/alert-circle.svg

Also in packages `lucide` + `lucide-react`:
https://unpkg.com/browse/lucide@0.264.0/dist/umd/lucide.js#L224
https://unpkg.com/browse/lucide-react@0.264.0/dist/umd/lucide-react.js#160

**Comment by nbahadori143** [comment]
Hey @karsa-mistmere,

Im using the ` lucide-react` `^0.264.0` package in my NextJS App `^13.4.10` and when I build the app, it gives me the following errors:

Module not found: Can't resolve these icons:

- node_modules/lucide-react/dist/cjs/icons/arrow-right
- node_modules/lucide-react/dist/cjs/icons/alert-triangle
- node_modules/lucide-react/dist/cjs/icons/ alert-circle
