### ISSUE TITLE
improve icon preview action

### ISSUE THREAD

**Issue by JanTrichter** [lucide-icons/lucide#1489]
Hi!
When using the dark mode for GitHub the icon preview is almost invisible:

<img width="928" alt="image" src="https://github.com/lucide-icons/lucide/assets/72730682/7afc6ade-bbb2-43f0-b48d-838beaec0bc9">

I think there should also be a light preview version for dark mode users. dark mode users will not see the dark version while light mode users won't see the light version of the icons.

**Comment by karsa-mistmere** [comment]
Hey @JanTrichter,

I believe this is an issue in Safari only: https://stackoverflow.com/questions/60561133/svg-dark-mode-styling-doesnt-work-in-safari

The dark mode previews work fine in Chrome: ![image](https://github.com/lucide-icons/lucide/assets/17746067/dcb6866e-fc40-4a87-8f56-06f6d6b1742d)

**Comment by JanTrichter** [comment]
@karsa-mistmere the screenshot I send is from Chrome. Maybe it's due to MacOS.

**Comment by JanTrichter** [comment]
Never mind, got the browsers mixed up, works in Chrome. Maybe there should be a note or something about that in the bots reply.

**Comment by jguddas** [comment]
Thank you for reporting this, it's totally possible to create a fallback for safari.
