### ISSUE TITLE
Icon Request: Signature

### ISSUE THREAD

**Issue by cabello** [lucide-icons/lucide#1494]
## Icon Request

* Icon name: signature
* Use case: I would like to use this besides a field that says "preferred name" meaning "how do you sign stuff".
* _Screenshots_ of similar icons: https://fontawesome.com/search?q=signature&o=r

![CleanShot 2023-08-11 at 12 15 05@2x](https://github.com/lucide-icons/lucide/assets/60936/d4cb0f66-9564-4c1f-810b-82c66e4802ea)

In the meantime I will use PenSquare, is good enough for a "Name" field.

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+9c.971+0+1-.943+1-1.914+0-1.019-.716-1.937-1.726-2.068-1.255-.163-2.108.8-2.274+1.982-.252+1.802+0+9-3+9a2+2+0+0+1-1.976-2.316c.153-.998+1.095-1.69+2.106-1.684+3.256.023+5.87+1+5.87+3a1+1+0+0+0+1+1h2v-2l2+2%22+/%3E%3Cpath+d=%22M3+20h18%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTQgOWMuOTcxIDAgMS0uOTQzIDEtMS45MTQgMC0xLjAxOS0uNzE2LTEuOTM3LTEuNzI2LTIuMDY4LTEuMjU1LS4xNjMtMi4xMDguOC0yLjI3NCAxLjk4Mi0uMjUyIDEuODAyIDAgOS0zIDlhMiAyIDAgMCAxLTEuOTc2LTIuMzE2Yy4xNTMtLjk5OCAxLjA5NS0xLjY5IDIuMTA2LTEuNjg0IDMuMjU2LjAyMyA1Ljg3IDEgNS44NyAzYTEgMSAwIDAgMCAxIDFoMnYtMmwyIDIiIC8+CiAgPHBhdGggZD0iTTMgMjBoMTgiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

I tried to make a signature icon with a cusive `L` but I'm not 100% sure about it yet

**Comment by jguddas** [comment]
That's such a fun idea ❤️

**Comment by karsa-mistmere** [comment]
Aaaaah. So that's the issue where this draft of mine came from. 😂
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15+17h7%22+/%3E%3Cpath+d=%22M2+17h.01%22+/%3E%3Cpath+d=%22M6.998+7.983C7+6+8.5+4+10+4c2.5+0+3+2.5+3+5+0+5.5-2+11-5+11-.947-.029-2.002-.51-2.002-2.5C5.998+12.5+11+9+14.5+9c2.482-.065+4+2+2+4H20%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTUgMTdoNyIgLz4KICA8cGF0aCBkPSJNMiAxN2guMDEiIC8+CiAgPHBhdGggZD0iTTYuOTk4IDcuOTgzQzcgNiA4LjUgNCAxMCA0YzIuNSAwIDMgMi41IDMgNSAwIDUuNS0yIDExLTUgMTEtLjk0Ny0uMDI5LTIuMDAyLS41MS0yLjAwMi0yLjVDNS45OTggMTIuNSAxMSA5IDE0LjUgOWMyLjQ4Mi0uMDY1IDQgMiAyIDRIMjAiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+9c.971+0+1-.943+1-1.914C15+6.067+14+5+13+5s-1.835.818-2+2c-.252+1.802+0+9-3+9-1.208+0-2-.741-2-2a2+2+0+0+1+2-2c4+0+6+1+6+3a1+1+0+0+0+1+1h2v-2l2+2%22+/%3E%3Cpath+d=%22M3+20h18%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTQgOWMuOTcxIDAgMS0uOTQzIDEtMS45MTRDMTUgNi4wNjcgMTQgNSAxMyA1cy0xLjgzNS44MTgtMiAyYy0uMjUyIDEuODAyIDAgOS0zIDktMS4yMDggMC0yLS43NDEtMi0yYTIgMiAwIDAgMSAyLTJjNCAwIDYgMSA2IDNhMSAxIDAgMCAwIDEgMWgydi0ybDIgMiIgLz4KICA8cGF0aCBkPSJNMyAyMGgxOCIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

Cleaned mine up a litttle bit

**Comment by AndreasSas** [comment]
> Aaaaah. So that's the issue where this draft of mine came from. 😂 [<img alt="icons" width="400" src="https://camo.githubusercontent.com/16d3f2bf39229b3e642fa39c702776b9e8f7f2f23e339ef815ff4b322a5598d4/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5455674d54646f4e7949674c7a344b49434138634746306143426b50534a4e4d6941784e3267754d4445694943382b4369416750484268644767675a443069545459754f546b34494463754f54677a517a63674e6941344c6a55674e4341784d434130597a49754e53417749444d674d69343149444d674e534177494455754e533079494445784c5455674d5445744c6a6b304e7930754d4449354c5449754d4441794c5334314d5330794c6a41774d6930794c6a56444e5334354f5467674d5449754e5341784d534135494445304c6a55674f574d794c6a51344d6930754d445931494451674d694179494452494d6a41694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M15+17h7%22+/%3E%3Cpath+d=%22M2+17h.01%22+/%3E%3Cpath+d=%22M6.998+7.983C7+6+8.5+4+10+4c2.5+0+3+2.5+3+5+0+5.5-2+11-5+11-.947-.029-2.002-.51-2.002-2.5C5.998+12.5+11+9+14.5+9c2.482-.065+4+2+2+4H20%22+/%3E&name=image)

yours looks awesome as well! I had the loop of my `L`also dip under the line, in a previous attempt, but then the cursive `L` started to look more like a cursive `f`

**Comment by jguddas** [comment]
A little bigger version.

> [<img alt="icons" width="120" src="https://camo.githubusercontent.com/9ddf029a6d7b4dddf9a678cd2cf583a2182d2cc504ba6175e6ef816e5aa77bf0/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5451674f574d754f546378494441674d5330754f54517a494445744d5334354d5451674d4330784c6a41784f5330754e7a45324c5445754f544d334c5445754e7a49324c5449754d4459344c5445754d6a55314c5334784e6a4d744d6934784d4467754f4330794c6a49334e4341784c6a6b344d6930754d6a5579494445754f444179494441674f53307a49446c684d694179494441674d4341784c5445754f5463324c5449754d7a4532597934784e544d744c6a6b354f4341784c6a41354e5330784c6a5935494449754d5441324c5445754e6a673049444d754d6a55324c6a41794d7941314c6a6733494445674e5334344e79417a595445674d534177494441674d4341784944466f4d6e59744d6d7779494449694943382b4369416750484268644767675a44306954544d674d6a426f4d5467694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+9c.971+0+1-.943+1-1.914+0-1.019-.716-1.937-1.726-2.068-1.255-.163-2.108.8-2.274+1.982-.252+1.802+0+9-3+9a2+2+0+0+1-1.976-2.316c.153-.998+1.095-1.69+2.106-1.684+3.256.023+5.87+1+5.87+3a1+1+0+0+0+1+1h2v-2l2+2%22+/%3E%3Cpath+d=%22M3+20h18%22+/%3E)
> 
> I tried to make a signature icon with a cusive `L` but I'm not 100% sure about it yet

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14.218+7.183a2.5+2.5+0+1+0-3.712-2.354c-.349+2.295-.853+12.217-5.006+12.217a1+1+0+0+1+0-5.091c4.509.03+8.516+1.676+8.516+4.221a1+1+0+0+0+.781.803l2.429.015a1+1+0+0+0+1.006-1v-.4a.5.5+0+0+1+.838-.368L21+17%22+/%3E%3Cpath+d=%22M3+21h18%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTQuMjE4IDcuMTgzYTIuNSAyLjUgMCAxIDAtMy43MTItMi4zNTRjLS4zNDkgMi4yOTUtLjg1MyAxMi4yMTctNS4wMDYgMTIuMjE3YTEgMSAwIDAgMSAwLTUuMDkxYzQuNTA5LjAzIDguNTE2IDEuNjc2IDguNTE2IDQuMjIxYTEgMSAwIDAgMCAuNzgxLjgwM2wyLjQyOS4wMTVhMSAxIDAgMCAwIDEuMDA2LTF2LS40YS41LjUgMCAwIDEgLjgzOC0uMzY4TDIxIDE3IiAvPgogIDxwYXRoIGQ9Ik0zIDIxaDE4IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>
