### ISSUE TITLE
Bad Imports in React / Next / Typescript

### ISSUE THREAD

**Issue by JakubCywinski** [lucide-icons/lucide#1502]
## Prerequisites

* Version: lucide-react 0.267.0
* Are you running from source/main: source
* Are you using a released build: yes
* Operating system: windows11
* Bits: 64

## Step to reproduce

1.Import Icon
2.Use Icon as component
3.
```bash
- error ./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve 'E:\...\node_modules\lucide-react\dist\cjs\icons\at-sign'
```

### Actual behavior

When I am trying to import icons (even trying with dynamic ones) all paths from where react tries to import it seems to be wrong

## Any message or error

1. Importing Icon
```bash
- error ./node_modules/lucide-react/dist/cjs/lucide-react.js:2:0
Module not found: Can't resolve 'E:\...\node_modules\lucide-react\dist\cjs\icons\at-sign'
```

2. Importing Dynamic imports
```bash
Module '"lucide-react"' has no exported member 'dynamicIconImports'.
```

## Resources

[Documentation lucide-react](https://lucide.dev/guide/packages/lucide-react)

<img width="773" alt="image" src="https://github.com/lucide-icons/lucide/assets/63851572/c7eb0726-8696-4cc0-aa4e-ab91f089f7da">

**Comment by hta218** [comment]
Same here, I have to roll back to `v0.263.1` to make it works

**Comment by karsa-mistmere** [comment]
You need to upgrade to https://github.com/vercel/next.js/releases/tag/v13.4.14-canary.2 which fixes the issue, see https://github.com/lucide-icons/lucide/issues/1482

**Comment by 72L** [comment]
@karsa-mistmere How does one upgrade? I tried 
```
"next": "13.4.14-canary.2",
```
in package.json but it did not work
