### ISSUE TITLE
Module not found: Can't resolve Module not found: Can't resolve '.../node_modules/lucide-react/dist/cjs/icons/arrow-right'

### ISSUE THREAD

**Issue by 72L** [lucide-icons/lucide#1503]
## Prerequisites

* Version: 0.268.0, next.js version 13.4.13
* Are you running from source/main: running locally after `npm install lucide-react`
* Are you using a released build: yes
* Operating system: Mac M1
* Bits: 64

## Step to reproduce

- Create a next.js project using the default settings with `create-next-app`
- install lucide with `npm install lucide-react -S`
- import into component `import { ArrowRight } from 'lucide-react';` and use it: `<ArrowRight />`
- go to localhost page that renders component and see error

### Actual behavior

```
Module not found: Can't resolve Module not found: Can't resolve '.../node_modules/lucide-react/dist/cjs/icons/arrow-right'
```

**Comment by karsa-mistmere** [comment]
Duplicates #1502
