### ISSUE TITLE
Migrate generated Svelte icons from `SvelteComponentTyped` to `SvelteComponent`

### ISSUE THREAD

**Issue by EdricChan03** [lucide-icons/lucide#1507]
## Prerequisites

* Version: 0.268.0
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system: macOS 12.6.5
* Bits: 64-bit

## Step to reproduce

1. Try to copy an existing icon's base type definition:

   ```ts
   import type { SvelteComponentTyped } from 'svelte';
   import { type IconProps, type IconEvents, Link2Icon } from 'lucide-svelte';

   const data: { example: string, icon: SvelteComponentTyped<IconProps, IconEvents, {}>, /* ... */ }[] = [
     { example: 'abc', icon: Link2Icon }, /* ... */
   ]
   ```
2. Note the deprecation from `SvelteComponentTyped`, with the following message:

   > `@deprecated` Use SvelteComponent instead. See PR for more information: https://github.com/sveltejs/svelte/pull/8512
3. Attempt to use `SvelteComponent` instead:

   ```diff
   -import type { SvelteComponentTyped } from 'svelte';
   +import type { SvelteComponent } from 'svelte';
   -{ example: string, icon: SvelteComponentTyped<IconProps, IconEvents, {}>, /* ... */ }
   +{ example: string, icon: SvelteComponent<IconProps, IconEvents, {}>, /* ... */ }
   ```

### Actual behavior

A TypeScript error is outputted as a result of performing step 3.

## Any message or error

> Type 'typeof Link2Icon' is missing the following properties from type 'SvelteComponent<IconProps, IconEvents, {}>': $$prop_def, $$events_def, $$slot_def, $capture_state, and 6 more.ts(2740)

## Resources

* [Migration guide](https://github.com/sveltejs/svelte/pull/8512)

EDIT: I see that this was noted here as well: https://github.com/lucide-icons/lucide/pull/1388#issuecomment-1605775698

---

On an unrelated note, could a TypeScript type that all icons can extend from be added as well? Perhaps something like the following:

```ts
export type LucideIconComponent = SvelteComponent<IconProps, IconEvents, {}>;
```

**Comment by EdricChan03** [comment]
On second thought, the same error also appears to happen with `SvelteComponentTyped`

**Comment by JanTrichter** [comment]
Thanks for reporting!
