### ISSUE TITLE
Mail off

### ISSUE THREAD

**Issue by mvrcelitos** [lucide-icons/lucide#1512]
## Icon Request

* Icon name: Mail off
* Use case: When some user don't have email
* _Screenshots_ of similar icons:  ![image](https://github.com/lucide-icons/lucide/assets/47905839/7329fbd1-446c-493b-9760-1c4182da6d7a)

**Comment by jguddas** [comment]
2px gap violation: ![icon - 2023-08-16T203835 827](https://github.com/lucide-icons/lucide/assets/25524993/45bf9561-4c16-4555-8e1b-434608a7acba)

not pretty but okayish: ![icon - 2023-08-16T203816 150](https://github.com/lucide-icons/lucide/assets/25524993/73126eb5-0d37-424e-9de6-42f54309ea2e)

**Comment by mvrcelitos** [comment]
Thanks

**Comment by danielbayley** [comment]
@mvrcelitos Unsubscribe would be the obvious use case… :)

**Comment by mvrcelitos** [comment]
> @mvrcelitos Unsubscribe would be the obvious use case… :)

thanks
