### ISSUE TITLE
Lucide Icons errors when deploy to vercel

### ISSUE THREAD

**Issue by messaddek** [lucide-icons/lucide#1513]
## Prerequisites

* Version: 0.263.1
* Are you running from source/main: main
* Are you using a released build: N/A
* Operating system: Vercel
* Bits: N/A

## Step to reproduce

*Deploy app to vercel, the build pass, but the page render fails*

### Actual behavior
The icons shows

## Any message or error

*[Error: EMFILE: too many open files, open '/var/task/node_modules/lucide-react/dist/esm/icons/send-horizonal.mjs'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/lucide-react/dist/esm/icons/send-horizonal.mjs',
  page: '/'
}*

## Resources

* Links
* Screenshots

**Comment by JanTrichter** [comment]
@messaddek Can you check if it's related to this ([#52646](https://github.com/vercel/next.js/issues/52646)) and if the provided solution there helps with your issue?

**Comment by abishekdevendran** [comment]
What would be the right syntax to use modularizeImports with Lucide-react?

**Comment by JanTrichter** [comment]
> What would be the right syntax to use modularizeImports with Lucide-react?

I'm not really familiar with React maybe @ericfennis can help?
