### ISSUE TITLE
X (Twitter)

### ISSUE THREAD

**Issue by rdwz** [lucide-icons/lucide#1528]
## Icon Request

* Icon name: X
* Use case: https://x.com 
* _Screenshots_ of similar icons: 
![255580473-e9e13421-89cf-445b-b2e2-e50e0864789f](https://github.com/lucide-icons/lucide/assets/8125196/ea7ae75d-fa82-4489-9d14-56c27c225fad)

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated, see our pinned issue.

**Comment by zovatrop** [comment]
X Twitter SVG icon code

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-x-twitter">
<path d="M8,2H3L16.7,22h5.1L8,2z"/>
<line x1="2.3" y1="22.1" x2="10.2" y2="12.8"/>
<line x1="19.8" y1="2" x2="13.3" y2="9.6"/>
</svg>`
