### ISSUE TITLE
Wheel / Tire Icons

### ISSUE THREAD

**Issue by RjManhas** [lucide-icons/lucide#1537]
### Icon name

Tire, Wheel, Rim, Car Tire, Plane Tire, Train Wheel, Think Wheel, etc

### Use cases

Hello, I have two needs for theses types of icons. 
1. I have a wheel selling site and I would like to have wheel / rim icons for the site and names, etc.
2. I have a car site and i want to have the rating instead of stars

### Design ideas

Some examples
would be nice to have some versions of each so we have more options
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc5SdzekzDoIaVyDiFXgz-6_zuu-3g05ssl-CoC3q0Xg&s
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGKm7VkxUCrpTkrfEA3vfCNm6yebumjMwMKfhNeMZd7g&s
here is the link to the google image search of tons of other ideas.
https://www.google.com/search?sca_esv=560734445&rlz=1C1UEAD_enCA1049CA1049&sxsrf=AB5stBjqeWe2BRR7wjQoLhZVzAE_Dr32pA:1693256290713&q=wheel+icon+svg&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjVx-Kdn4CBAxXWATQIHRUwDAMQ0pQJegQIDhAB&biw=1367&bih=769&dpr=1.65

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Hey @RjManhas,

Thanks for submitting an icon request.
Here you go, a tire and wheel icon: #1538 

The rest (train, plane etc) are far too specific and out of scope for us, I'm afraid. 🙂

**Comment by RjManhas** [comment]
@karsa-mistmere hello, when i said train, plane, etc i meant plane wheel, train wheel, other types of wheels such as bike wheels. I can provide a full list and example if needed.

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere hello, when i said train, plane, etc i meant plane wheel, train wheel, other types of wheels such as bike wheels. I can provide a full list and example if needed.

No, I understood correctly, but:
1) these are simply too specific and out of scope for us. I'm not saying there's no chance of adding any these, but we would need legitimate, non-wheel-webstore related use cases for them; if you can come up with these, feel free to open new icon requests.
2) our design guidelines don't leave much room for all of these to look markedly different, e.g. I'm afraid a classic bike wheel is just not going to be feasible with 2px strokes and 2px gaps between spokes on a 24px grid.

(Sidenote: if I were you, I'd probably use the car, plane, bike, train etc. icons instead of specific wheel shapes)

**Comment by RjManhas** [comment]
Ok thank you for reviewing the suggestion of icon. I will look into using the icon for the vehicle instead of a wheel and thank you for adding the _wheel_ icon.

**Comment by RjManhas** [comment]
This thread is done thank you
