### ISSUE TITLE
No git tags since v0.265.0

### ISSUE THREAD

**Issue by Gerschtli** [lucide-icons/lucide#1546]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [X] source/main
- [ ] other/not relevant

### Version

All versions after v0.265.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

There are no git tags set anymore for versions after v0.265.0. Is this intended? Currently only the GitHub Releases can be used to determine which commit belongs to which version.

### Steps to reproduce

Look at the git tags of this repository and compare to latest released version of lucide

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I can see the latest tags alright: https://github.com/lucide-icons/lucide/tags

**Comment by Gerschtli** [comment]
I am sorry, I did not notice that you removed the `v` prefix in the tag name. I was looking at an alphabetically sorted list of all tags, that is why the tags didn't appear.
