### ISSUE TITLE
 Breaking change: edit, edit-2, and edit-3 removed in 0.262.0

### ISSUE THREAD

**Issue by life4aiur** [lucide-icons/lucide#1553]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.262.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

The `edit`, `edit-2`, and `edit-3` icons were removed in version 0.262.0. Possibly as part of https://github.com/lucide-icons/lucide/pull/1286.

While this change may make sense, it is a breaking change and should have been versioned as a new [major version](https://semver.org/) and communicated as such.

Question 1: Can we get these icons back?
Question 2: Are there any guardrails or documentation that will prevent breaking changes from being introduced in minor versions?

### Steps to reproduce

1. Search for  `edit`, `edit-2`, and `edit-3` icons in a release > 0.261.0
2. Notice that the icons are missing

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
> Question 1: Can we get these icons back?

They have only been moved https://github.com/search?q=repo%3Alucide-icons%2Flucide%20edit-3&type=code

> Question 2: Are there any guardrails or documentation that will prevent breaking changes from being introduced in minor versions?

What we need to do:

1. Add alias support to that package.
2. https://github.com/lucide-icons/lucide/issues/1550

**Comment by life4aiur** [comment]
> > Question 1: Can we get these icons back?
> 
> They have only been moved https://github.com/search?q=repo%3Alucide-icons%2Flucide%20edit-3&type=code
> 
> > Question 2: Are there any guardrails or documentation that will prevent breaking changes from being introduced in minor versions?
> 
> What we need to do:
> 
> 1. Add alias support to that package.
> 2. [Build release workflow for after 1.0.0 #1550](https://github.com/lucide-icons/lucide/issues/1550)

"They have only been moved", I'm not sure what you mean by this. They are not present:
`<!doctype html>
<body>
  <i data-lucide="edit-2"></i>
  <script src="https://unpkg.com/lucide@latest"></script>
  <script>
    lucide.createIcons();
  </script>
</body>
`
Yields an empty page. This is a breaking change to anyone who was using these icons.

**Comment by ericfennis** [comment]
This it because we didn't implemented aliases in the lucide package yet.
I will make some time to implement the icon name aliases, after that this will work.

**Comment by ericfennis** [comment]
@life4aiur Nope `lucide-static` is something different. But we should work on that one as well!

**Comment by lovemorejokonya** [comment]
Also noticed this breaking change in a production application. Following for updates... for now I temporarily switched to a similar Fi icon.
