### ISSUE TITLE
Icon Request: at-sign-off

### ISSUE THREAD

**Issue by CarlosVergikosk** [lucide-icons/lucide#1554]
### Off version of the at-sign icon

**at-sign**

![image](https://github.com/lucide-icons/lucide/assets/45525595/d5e7570f-78b2-48e9-bdde-3cde352f68dc)

**Similar to megaphone-off**

![image](https://github.com/lucide-icons/lucide/assets/45525595/db8ca3a4-2bec-46b8-8012-7b76996b3b20)

### calendar-edit

**Replace the minus with a pencil**

![image](https://github.com/lucide-icons/lucide/assets/45525595/09493a4f-b423-465f-bd0f-c2ef7d582a22)

Thanks <3

**Comment by karsa-mistmere** [comment]
Please submit a [proper icon request issue](https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&projects=&template=01_icon_request.yml) for these providing the required information. I'm closing this as this information was not provided.
