### ISSUE TITLE
Astro + Solid + VS Code ->  Could not find a declaration file for module 'lucide-solid'

### ISSUE THREAD

**Issue by awhitford** [lucide-icons/lucide#1558]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.274.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

I am migrating a [SolidJS](https://solidjs.com) project to [Astro](https://astro.build) to get access to SSR.
This project uses Tailwind, Lucide, and Solid.

With the Astro project, I am getting this warning from VS Code from a Solid component that imports Lucide icons:
> Could not find a declaration file for module 'lucide-solid'. '/Users/anthony/project/node_modules/.pnpm/lucide-solid@0.274.0_solid-js@1.7.11/node_modules/lucide-solid/dist/esm/lucide-solid.js' implicitly has an 'any' type.
  There are types at '/Users/anthony/project/node_modules/lucide-solid/dist/types/lucide-solid.d.ts', but this result could not be resolved when respecting package.json "exports". The 'lucide-solid' library may need to update its package.json or typings.ts(7016)

Note that this code doesn't emit a warning from the old Solid project.
Also, this code seems to compile and run fine -- it just generates this annoying warning in VS Code.

The old Solid project used `node` [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) while the new Astro project uses `bundler`.

The Astro project is using [`strict`](https://github.com/withastro/astro/blob/main/packages/astro/tsconfigs/strict.json) mode.  If I use `base` instead, then this warning goes away.  Alternatively, I figured out that a workaround is to disable [`resolvePackageJsonExports`](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports):

```
"resolvePackageJsonExports": false
```

Having said that, I am wondering if there is a bug in `lucide-solid`'s `package.json` because I would ideally not disable `resolvePackageJsonExports`.  This may be related to #1431 .

### Steps to reproduce

1. Create a new Astro project:  `pnpm create astro@latest`
   - Specify TypeScript, Strict mode
2. Add _SolidJS_ to the Astro project:  `pnpm astro add solid`
3. Add _Lucide-Solid_ to the Astro project:  `pnpm install lucide-solid`
4. Add a simple Solid component:
```
import { Moon } from 'lucide-solid';

export default function LucideIcon() {
  return (
    <div>
      <Moon />
    </div>
  );
}
```
5. Now try to use that Solid component, like adding something basic to `index.astro`:
```
---
import LucideIcon from '../components/LucideIcon';
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<h1>Astro</h1>
		<LucideIcon client:only="solid" />
	</body>
</html>
```

Note that VS Code gives the warning on the `import { Moon } from 'lucide-solid';` line from Step 4.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by awhitford** [comment]
It would appear that the `exports` have issues:  https://publint.dev/lucide-solid@0.276.0

**Comment by ericfennis** [comment]
@awhitford Thanks for reporting this issue.
Can you provide us a reproduction repo?

**Comment by awhitford** [comment]
Does this help?  https://stackblitz.com/edit/github-wh46uq-p985ia?file=src%2Fcomponents%2FCounter.tsx
See line 3 of `Counter.tsx`.

**Comment by binyamin** [comment]
@ericfennis I found the problem. Because there's an "exports" field in the package.json, the "types" directory is not accessible. I can PR a fix.

**Comment by korybantes** [comment]
Reload extension on vscode helped me.
