### ISSUE TITLE
Svelte: Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by Huluti** [lucide-icons/lucide#1572]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.270 & 0.279

### Browser

- [ ] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

Upgrading from 0.269 to version >=0.270

### Steps to reproduce

Since introduced changes in 0.270 I can't do the upgrade to a newer version from 0.269.
![image](https://github.com/lucide-icons/lucide/assets/5782198/27fd9ccf-a4d0-4940-befd-f24a5fbc43a6)

https://github.com/lucide-icons/lucide/compare/0.269.0...0.270.0

Can't upgrade to lucide icons > 0.269 because of a breackage with svelte:

![image](https://github.com/lucide-icons/lucide/assets/5782198/0021f1f1-9cfa-49af-a271-ae2a4ee59a06)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
@Huluti You should upgrade to the latest version of `lucide-svelte`. This is fixed in #1548

**Comment by Huluti** [comment]
Already tried with [0.279.0](https://github.com/lucide-icons/lucide/releases/tag/0.279.0) and I have the same errors.
All versions > 0.269 have this problem for me.

**Comment by nathanfaucett** [comment]
@Huluti @ericfennis I have the same issue

**Comment by ericfennis** [comment]
Oke reopening this one then.
