### ISSUE TITLE
[lucide-static] Explored the possibility of utilizing variable fonts.

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#1575]
Have you explored the possibility of utilizing [variable fonts](https://fonts.google.com/knowledge/glossary/variable_fonts) by any chance?

_Originally posted by @HrBDev in https://github.com/lucide-icons/lucide-flutter/issues/2

**Comment by karsa-mistmere** [comment]
Yes! That would be a super cool feature to have.

**Comment by HrBDev** [comment]
Examples of variable fonts that work on Flutter:

**Comment by HrBDev** [comment]
Examples of variable icon fonts that already work on Flutter:
[Material Symbols](https://pub.dev/packages/material_symbols_icons)
[Anicons](https://typogram.github.io/Anicons/)
