### ISSUE TITLE
Using debounce effect on the search bar

### ISSUE THREAD

**Issue by johurul-haque** [lucide-icons/lucide#1579]
### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

When searching for an icon the site freezes for a moment, due to constant re-render on input change, thus making the site's user experience feel sluggish.

### Steps to reproduce

1. Typing something on the search input.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by lakshaybhushan** [comment]
I think it's fine on MacOS
