### ISSUE TITLE
Website jumping

### ISSUE THREAD

**Issue by bernaferrari** [lucide-icons/lucide#1583]
Chrome.

### Description

https://github.com/lucide-icons/lucide/assets/351125/294ea10a-72dc-4e52-ab68-f52a7d92a66c

### Steps to reproduce

Click on branding

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Wow that's extreme. Thanks for reporting!
