### ISSUE TITLE
lucide-react-native doesn't export "icons" for generic icon component

### ISSUE THREAD

**Issue by mfkrause** [lucide-icons/lucide#1584]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [X] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.279.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

While [the documentation for lucide-react-native](https://lucide.dev/guide/packages/lucide-react-native) states that you can import `icons` in order to get a list of all icons and create a generic component, the package does not in fact export this:

```'"lucide-react-native"' has no exported member named 'icons'. Did you mean 'Icon'?```

It's therefore not possible to create a generic icon component currently, as far as I can tell.

### Steps to reproduce

1. Install the latest version of lucide-react-native into a TypeScript project
2. Try to import `icons` as per the documentation

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by devMatheusR** [comment]
> ### Package
> 
>     * [ ]  lucide
> 
>     * [ ]  lucide-angular
> 
>     * [ ]  lucide-flutter
> 
>     * [ ]  lucide-preact
> 
>     * [ ]  lucide-react
> 
>     * [x]  lucide-react-native
> 
>     * [ ]  lucide-solid
> 
>     * [ ]  lucide-svelte
> 
>     * [ ]  lucide-vue
> 
>     * [ ]  lucide-vue-next
> 
>     * [ ]  Figma plugin
> 
>     * [ ]  source/main
> 
>     * [ ]  other/not relevant
> 
> 
> ### Version
> 
> 0.279.0
> ### Browser
> 
>     * [ ]  Chrome/Chromium
> 
>     * [ ]  Firefox
> 
>     * [ ]  Safari
> 
>     * [ ]  Edge
> 
>     * [ ]  iOS Safari
> 
>     * [ ]  Opera
> 
>     * [ ]  Other/not relevant
> 
> 
> ### Operating system
> 
>     * [ ]  Windows
> 
>     * [ ]  Linux
> 
>     * [ ]  macOS
> 
>     * [ ]  Other/not relevant
> 
> 
> ### Description
> 
> While [the documentation for lucide-react-native](https://lucide.dev/guide/packages/lucide-react-native) states that you can import `icons` in order to get a list of all icons and create a generic component, the package does not in fact export this:
> 
> `'"lucide-react-native"' has no exported member named 'icons'. Did you mean 'Icon'?`
> 
> It's therefore not possible to create a generic icon component currently, as far as I can tell.
> ### Steps to reproduce
> 
>     1. Install the latest version of lucide-react-native into a TypeScript project
> 
>     2. Try to import `icons` as per the documentation
> 
> 
> ### Checklist
> 
>     * [x]  I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

Same Issue
