### ISSUE TITLE
Baloon

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#1591]
### Icon name

Baloon

### Use cases

* Marking someone's birthday
* Baloons category in online toy store I guess?

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/5426427/6884c952-16bc-4b33-a0ac-b537fc2bed18)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
![icon - 2023-10-09T170328 674](https://github.com/lucide-icons/lucide/assets/25524993/7998eed9-5cb9-489c-bc14-254ac806f200)

**Comment by wojtekmaj** [comment]
This looks more like a "whoopee cushion" to me :D

**Comment by Yash-Soni7744** [comment]
hey what about this! i have made it as a svg. 
![BALLOON](https://github.com/lucide-icons/lucide/assets/120086351/4e0b8c88-069c-42ce-b538-c0ae83abc67e)

**Comment by peteruithoven** [comment]
3 more for inspiration
- ![TablerBalloon](https://github.com/user-attachments/assets/69280237-d490-49af-8c21-efeac594dad8)
  https://icones.js.org/collection/all?s=balloon&icon=tabler:balloon
- ![FluentBalloon24Regular](https://github.com/user-attachments/assets/f2bb7298-1871-479c-8d3e-f9c36ea76217)
  https://icones.js.org/collection/all?s=balloon&icon=fluent:balloon-24-regular
- ![IconParkOutlinePartyBalloon](https://github.com/user-attachments/assets/0eb6e510-6349-45ab-9b6a-92f9e8f42199)
  https://icones.js.org/collection/all?s=balloon&icon=icon-park-outline:party-balloon

**Comment by peteruithoven** [comment]
Based on those I made an alternative more in line with Lucide, using lines, 24px and 2px stroke width. 
![Balloon(1)](https://github.com/user-attachments/assets/48138183-ee1f-4353-afbb-f52a63827fdd)

**Comment by wojtekmaj** [comment]
Best one yet!
