### ISSUE TITLE
Documentation could be more clear on how to add custom icons

### ISSUE THREAD

**Issue by McMalloc** [lucide-icons/lucide#1596]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [X] site

### Description

The [documentation on `lucide-angular`](https://lucide.dev/guide/packages/lucide-angular) is the only place in the Guide section that mentions custom icons, but it is not very clear about it. E.g., how can I provide a valid `LucideIconData`? Right now it only says that at some point the SVG data needs to be converted to svgson.

edit: After a bit of experimenting, the output of the linked library to convert to svgson even seems to be incompatible with how the `createElement` function works.

### Use cases

This is the example given on the aforementioned page:
```
import { LUCIDE_ICONS, LucideIconProvider } from 'lucide-angular';
import { MyIcon } from './icons/my-icon';

// What does MyIcon look like exactly?
const myIcons = {MyIcon};

@NgModule({
  providers: [
    {provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(myIcons)},
  ]
})
export class AppModule { }
```

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
This is how svgson can be used to convert an SVG string to a `LucideIconData` object:
```tsx
function svgToLucideIconData(svgString: string): LucideIconData {
  const parsed = svgson.parseSync(svgString);
  return [parsed.name, parsed.attributes, parsed.children.map(n => [n.name, n.attributes])];
}
```

This is not _exactly_ how it's done [in our release workflow](https://github.com/lucide-icons/lucide/blob/main/tools/build-icons/render/renderIconsObject.mjs#L16), but the results are close enough.
I would advise to pre-convert your custom icons instead of adding a runtime dependency on svgson and storing the resulting JSON objects in separate .ts files as default exports.

**Comment by karsa-mistmere** [comment]
I would recommend structuring the icon files similar to how they are done by the library, e.g.:
https://cdn.jsdelivr.net/npm/lucide-angular@0.320.0/esm2020/icons/ampersand.mjs

```tsx
const MyIcon = [
  ['circle', { cx: '12', cy: '12', r: '10', key: '1mglay' }]
];
export default MyIcon;
 ```

**Comment by koddist** [comment]
It could be really helpful to provide detailed examples for the [Injecting Multiple Icon Providers](https://lucide.dev/guide/packages/lucide-angular#injecting-multiple-icon-providers) section in the documentation. I think you, as a developer, could start by following the required steps and documenting them. For instance, here: 

```javascript
import { MyIcon } from './icons/my-icon';
```

`MyIcon` is imported as a class, but I want to see an example of how the icon class should look.
