### ISSUE TITLE
waypoints icon is missing

### ISSUE THREAD

**Issue by arvinxx** [lucide-icons/lucide#1597]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.284.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Can't find waypoints

### Steps to reproduce

<img width="752" alt="image" src="https://github.com/lucide-icons/lucide/assets/28616219/02ca3ef9-7e18-4324-8139-12f875aae53c">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
There was an issue with the release workflow, this icon - amongst others - is now present in [v0.285.0](https://github.com/lucide-icons/lucide/releases/tag/0.285.0).
