### ISSUE TITLE
Contributors not shown correctly.

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#1623]
### Browser

- [x] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [x] macOS
- [ ] Other/not relevant

### Description

@kemie should be shown instead of @ericfennis 

 
<img width="1141" alt="Screenshot 2023-10-21 at 11 53 50" src="https://github.com/lucide-icons/lucide/assets/25524993/6a8b5740-35ba-49f7-bba7-d73aa0d5879e">

https://lucide.dev/icons/dog
https://github.com/lucide-icons/lucide/blob/49445aad3a3de655923fb96ab1a6634d8a4619f7/icons/dog.json#L4C6-L5

### Steps to reproduce

.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
I fixex in https://github.com/lucide-icons/lucide/commit/73d5bfc318d30ca4e5d76ae9f4cbcbb3472b1bb4
See: https://lucide.dev/icons/dog
