### ISSUE TITLE
Filled icons

### ISSUE THREAD

**Issue by FilipePfluck** [lucide-icons/lucide#1636]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

I want filled versions of the icons. 

### Use cases

This allows lucide icons to feat more nicely in different visual identities. In some projects, filled icons may work better than outline ones. 

Also, there are some use-cases where you may want to use both outline and filled icons. For example, a rating component using a Star icon. I can represent a rate of 3/5 with 3 filled stars and 2 outline ones. 

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
Closing this, as there's an ongoing discussion in #458
