### ISSUE TITLE
Alignment issue on Bigger Devices having width larger then 959px

### ISSUE THREAD

**Issue by myselfprincee** [lucide-icons/lucide#1637]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

<img width="959" alt="image" src="https://github.com/lucide-icons/lucide/assets/114233864/b12be561-1a18-42ad-9aa7-d2cfc86fd889">

This is the issue. I would love to solve this and soon will submit a PR to solve this.

### Steps to reproduce

Go to https://lucide.dev/

See Search Icon Bar <img width="959" alt="image" src="https://github.com/lucide-icons/lucide/assets/114233864/b12be561-1a18-42ad-9aa7-d2cfc86fd889">

### Checklist

- [ ] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by myselfprincee** [comment]
The similar issue has been created but The Person hasn't fixed it.

**Comment by myselfprincee** [comment]
Please assign me the issue.

**Comment by karsa-mistmere** [comment]
There's an open pull request addressing this: https://github.com/lucide-icons/lucide/pull/1627
