### ISSUE TITLE
user-2 feels a bit big

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#1639]
![image](https://github.com/lucide-icons/lucide/assets/25524993/28f32217-b25d-4457-ac1a-a15f0bf731d9)

**Comment by Sukomal07** [comment]
please explain the issue clearly

**Comment by karsa-mistmere** [comment]
I think it's actually `user-*-2` that are too small.

**Comment by jguddas** [comment]
> I think it's actually `user-*-2` that are too small.

True
