### ISSUE TITLE
Icon request: Running, Walking Icon

### ISSUE THREAD

**Issue by autribaghkhanian** [lucide-icons/lucide#1646]
### Icon name

running, walking

### Use cases

1. [Person crossing street](https://en.wikipedia.org/wiki/Road_signs_in_the_United_States#/media/File:MUTCD_W11-2.svg)
2. Commonly used for [exits in Europe](https://upload.wikimedia.org/wikipedia/commons/d/dc/European_Council_Exit_Sign_-_Right.svg)
3. Can indicate type of directions (walking instead of driving or transit)
4. Quickly indicate exercise for a video, article, tab on a fitness website, etc

### Design ideas

<img width="370" alt="image" src="https://github.com/lucide-icons/lucide/assets/31020776/16be629c-234c-4a6c-b05a-1e92a774ae62">
<img width="435" alt="image" src="https://github.com/lucide-icons/lucide/assets/31020776/887e11b8-9152-42db-9d00-c9854e543023">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Duplicates #609
