### ISSUE TITLE
Export the `IconNode` type

### ISSUE THREAD

**Issue by olaf-k** [lucide-icons/lucide#1654]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Hi! Thanks a lot for this great project.

As a user of Lucide in a component library, I want to add the possibility for our users to pass Lucide icon objects to some of the widgets `icon` property. Unfortunately, the `IconNode` seems to only be used internally. Would it possible to export it for TS projects?

(I also have [another question](https://github.com/lucide-icons/lucide/discussions/1594) if you feel like it 😁)

### Use cases

Consuming Lucide objects from projects.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by ericfennis** [comment]
Yeah we can do that, will work on that one!

**Comment by Sukomal07** [comment]
@ericfennis  hey , i want to work on this issue , can you guide me ? i did not understand properly

**Comment by olaf-k** [comment]
> Yeah we can do that, will work on that one!
Thanks @ericfennis that's great news!

@Sukomal07 my understanding is that `packages/lucide/src/types.ts` is not included in the lucide build, which means that its `export`s can't be consumed from code using the esm|cjs|umd package.

**Comment by Sukomal07** [comment]
@ericfennis please review my PR
