### ISSUE TITLE
Icon Design Guide - "Not Pixel Perfect" image text

### ISSUE THREAD

**Issue by zaaakher** [lucide-icons/lucide#1665]
### Browser

- [X] Chrome/Chromium

### Operating system

- [X] Windows

### Description

In [this section](https://lucide.dev/guide/design/icon-design-guide#_13-icons-should-aim-to-be-pixel-perfect-so-that-they-will-be-sharp-on-low-dpi-displays) of the Icon Design Guide it seems that the person who made the images forgot to change this to "**Don't**" (see attached image)

![image](https://github.com/lucide-icons/lucide/assets/46135573/8633351b-6f8c-4720-88cc-3b59dd5ffaf0)

### Steps to reproduce

Visit the following link in the icon design guide page 👇
https://lucide.dev/guide/design/icon-design-guide#_13-icons-should-aim-to-be-pixel-perfect-so-that-they-will-be-sharp-on-low-dpi-displays

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hey @zaaakher,

Thanks for bringing this to our attention. 🙏
I've made a PR fixing this issue and merged it post haste.
