### ISSUE TITLE
How to Use Lucide with Vanilla JS?

### ISSUE THREAD

**Issue by chessurisme** [lucide-icons/lucide#1669]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.291.0

### Browser

- [ ] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

After installing lucide according to Web(Vanilla) documentation using npm and use it in my script, console says:
```
Uncaught TypeError: The specifier “lucide” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../”, or “/”.
```

### Steps to reproduce

Code like those on the documentation didn't work in mine as expected

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Can you provide the actual steps to reproduce this error or a minimal reproduction in a sandbox?

(i.e. how you're actually trying to use it in your script)

**Comment by chessurisme** [comment]
Here's the minimal src code: 
[Sandbox.zip](https://github.com/lucide-icons/lucide/files/13276761/Sandbox.zip)

**Comment by karsa-mistmere** [comment]
Unfortunately, I still cannot reproduce the exact error message given, for that I would need further context as to how you're even trying to build this code, as the package.json provided includes no such information.
My first guess, however, is that you simply cannot use lucide as a devDependency, please install as `npm i lucide` as stated in the documentation, _not_ `npm i -D lucide`.

Here's a working reproduction of your code, I hope this helps:
https://codesandbox.io/s/silly-raman-chrywt?file=/package.json

**Comment by chessurisme** [comment]
Wow, I though it must be a dependency. Thank you! ❤️

**Comment by chessurisme** [comment]
Oh, as I searching more: it is because I use Live Server, and also I am in local development.

This article may help:
[How to handle ES6 bare module imports for local Development](https://dplatz.de/blog/2019/es6-bare-imports.html)
