### ISSUE TITLE
caret icon

### ISSUE THREAD

**Issue by moonRider** [lucide-icons/lucide#1672]
## shape
<img width="116" alt="image" src="https://github.com/lucide-icons/lucide/assets/6049820/5148d932-4624-4ea5-bf8b-801f57a6dd68">

## feature
`caret` icon also support direction(right, left, down, up)

**Comment by karsa-mistmere** [comment]
Please resubmit this via the proper icon request issue template and keep in mind that we do not yet support filled icons (see #458):
https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&projects=&template=01_icon_request.yml
