### ISSUE TITLE
Icon request: racket sport kit

### ISSUE THREAD

**Issue by sasafister** [lucide-icons/lucide#1678]
Hi could you please add icons for:

tennis
padel
badminton
tennis table

**Comment by karsa-mistmere** [comment]
Please submit icon requests via the [icon request form](https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&projects=&template=01_icon_request.yml), not circumventing the process.
No need to submit a request for these though, as we already have an ongoing PR for these: #1304
