### ISSUE TITLE
Google Icon

### ISSUE THREAD

**Issue by broisnischal** [lucide-icons/lucide#1679]
### Icon name

Google

### Use cases

I need this icon for login with google button. 

### Design ideas

It should be like the other minimal google icon logo

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
This is a brand icon

**Comment by jguddas** [comment]
Removing Icons is a breaking change, we are not rolling out breaking changes until the preparations for v1 are done.

https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M20.945+11a9+9+0+1+1-3.284-5.997l-2.655+2.392A5.5+5.5+0+1+0+17.125+14H13v-3z%22+/%3E%3C/svg%3E
