### ISSUE TITLE
The slash Icon is wrong

### ISSUE THREAD

**Issue by navanshu** [lucide-icons/lucide#1680]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.270.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Expected
![image](https://github.com/lucide-icons/lucide/assets/7664426/69d5f2d1-d4cb-46ee-86c0-5a6a30722835)
Actual
![image](https://github.com/lucide-icons/lucide/assets/7664426/dfe81e03-72a8-46da-8c9c-af5851caff6c)
![image](https://github.com/lucide-icons/lucide/assets/7664426/dbe33bc1-6b94-427a-ad95-0f2b702cd3d9)

### Steps to reproduce

Not important

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
This has already been resolved in #1555, please upgrade to a later version.
