### ISSUE TITLE
css file like iconoir for wordpress

### ISSUE THREAD

**Issue by ghostlexly** [lucide-icons/lucide#1690]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Hey,

Can we have something like iconoir, a css file to call to implement any icons like this:

```css
<i class="lucide-cart"></i>
```

The existent method today, calling the `lucide.createIcons();` function isn't working well with the ajax requests.
We have to call it each 200 ms to make it handle new icons on the page.. 

### Use cases

- Wordpress themes implementation

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
Lucide does support CSS only declarations via webfonts, see this fiddle on how to use this: https://jsfiddle.net/dtcwsr62/
Or https://lucide.dev/guide/packages/lucide-static for additional documentation.

Iconoir uses SVG data URIs in its CSS which is super bulky (compare https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css at 2.39MB with a standard WOFF webfont for Lucide at ~324kB in total).

> The existent method today, calling the lucide.createIcons(); function isn't working well with the ajax requests.
We have to call it each 200 ms to make it handle new icons on the page..

I'm not very familiar with Wordpress, but surely, there should be a way to subscribe to AJAX events and only run createIcons if and when the DOM changes (from what I gathered there's a Javascript hook system), if in doubt .
