### ISSUE TITLE
Flutter package stuck on v.0.257.0

### ISSUE THREAD

**Issue by shayant98** [lucide-icons/lucide#1692]
### Package

- [ ] lucide
- [ ] lucide-angular
- [X] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Is there a timeline when Flutter will be updated to at least 0.290.

### Use cases

Missing icons, id like to use in my project

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by ericfennis** [comment]
Hi @shayant98,

The development of the flutter package is discontinued see or achieved repo: https://github.com/lucide-icons/lucide-flutter

**Comment by Kvarzsiev** [comment]
> ⚠️ This package is not in active development anymore. Please use [iconify_flutter](https://pub.dev/packages/iconify_flutter) instead.

It seems like neither the package linked there is being maintained. Could someone please point to another solution?
