### ISSUE TITLE
Is it possible to make lucide angular work for Angular 17 ?

### ISSUE THREAD

**Issue by MisterCoookie** [lucide-icons/lucide#1695]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

I have seen in the git that package.json limit to Angular 16 is it possible to make it for angular 17 ?
I really like lucide library and it would be nice to be able to use it

### Use cases

Use Lucide icons in Angular 17

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by joandreiy** [comment]
I have problems using Lucide in new Angular 17 projects
