### ISSUE TITLE
The size of the icons is not consistent

### ISSUE THREAD

**Issue by doroved** [lucide-icons/lucide#1697]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [X] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

^0.292.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Why aren't the icons the same size, doesn't matter if it's 24, 20, etc.
Visually Plus is smaller than Settings and it is very annoying.
And it is not only with your icons such a problem, why so?
https://github.com/atisawd/boxicons/issues/647

<img width="254" alt="image" src="https://github.com/lucide-icons/lucide/assets/30116541/4f629c9a-c75d-4465-b197-8ce1b36b6847">

### Steps to reproduce

https://lucide.dev/guide/packages/lucide-vue-next

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Gonna close this in favor of #1192

**Comment by jguddas** [comment]
The definition for how icons are sized, square and circle are the baseline not gear.

https://lucide.dev/guide/design/icon-design-guide#_9-icons-should-have-a-similar-optical-volume-to-circle-and-square
