### ISSUE TITLE
Creative Commons (cc) icon request

### ISSUE THREAD

**Issue by keyilan** [lucide-icons/lucide#170]
## Icon Request

* Icon name: Creative Commons
* Use case: alternate version of copyright and copyleft for cases where the license is specifically a CC license.

Ideally, an icon for each of the possible license types, but at minimum just the cc enclosed in a circle. I will design them myself in the coming week or two if no one else does.

**Comment by locness3** [comment]
I'd kinda count this as a brand icon, but it can be useful beyond typical use cases for brand icons.

**Comment by keyilan** [comment]
the brand-iness did occur to me, but this seems like it's of a different type than twitter, since this is effectively a more specific sort of copyleft icon. so, if this is rejected due to being a brand, i get it and part of me predicted as much, but if people are open to it i'm happy to submit SVGs once they're designed.

**Comment by ericfennis** [comment]
I think we can create an icon for it, but also make it possible for multiple use cases.
For example for captions in video players or video conference call, like Google uses in Google Meet: 
![image](https://user-images.githubusercontent.com/11825403/104645289-29791a00-56af-11eb-8164-37bca8d5e6be.png)

**Comment by locness3** [comment]
meh, creative commons is a circle

**Comment by locness3** [comment]
Would like to mention that Simple Icons has one : https://simpleicons.org/?q=creative%20commons

**Comment by noobkid2411** [comment]
Hi,this is Sonakshi. I would like to work on this issue. Can you elaborate if you want a single icon or multiple icons?

**Comment by keyilan** [comment]
If it were up to me I'd love to see an icon for each of the different license flags, so multiple icons if my vote is the only one that matters.

**Comment by ericfennis** [comment]
See @locness3 response, for brand icons use simple icons.

I close this one for now.

**Comment by pauloxnet** [comment]
I don't think Creative Commons has to be considerate a typical brand icons like a for profit company with a logo with a trademark on it and they added it in Unicode 13
https://creativecommons.org/2020/03/18/the-unicode-standard-now-includes-cc-license-symbols/

**Comment by locness3** [comment]
Neat

**Comment by ericfennis** [comment]
Hmm I agree with @pauloxnet, let's open this issue.
