### ISSUE TITLE
extra space in svg class attribute

### ISSUE THREAD

**Issue by capaj** [lucide-icons/lucide#1701]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.293.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

we have some snapshot tests and they started to show extra space at the end on this classname:
![image](https://github.com/lucide-icons/lucide/assets/1305378/f538d868-a856-436b-8573-0b58869d0f32)

not a big problem, but if anyone could easily remove the space please do trim that

### Steps to reproduce

just render and see the html

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by zce** [comment]
This issue still exists in version `0.331.0`

https://github.com/lucide-icons/lucide/blob/42c1faed7597021baff4aed7f807483beb8971c6/packages/lucide-react/src/createLucideIcon.ts#L61
