### ISSUE TITLE
[Icon Request]: Icon for website or www

### ISSUE THREAD

**Issue by alamenai** [lucide-icons/lucide#1702]
### Icon name

Website, global, www

### Use cases

1. Website
2. WWW

### Design ideas

1. Global
2. Planet
3. WWW letters

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
https://lucide.dev/icons/globe

**Comment by MenaiAla** [comment]
Thank you so much. But I guess it would be better to have a `related to` section to support the search by the exact word.
