### ISSUE TITLE
Probably it's just me but a few icons don't work in React: Waypoints, Route even if I import it as { Route as RouteIcon }, and RouteOff neither

### ISSUE THREAD

**Issue by sebababi** [lucide-icons/lucide#1705]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Probably it's just me but a few icons don't work in React: Waypoints, Route even if I import it as { Route as RouteIcon }, and RouteOff neither

### Steps to reproduce

import { Waypoints } from 'lucide-react';

const App = () => {
  return (
    <Waypoints />
  );
};

export default App;

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Not sure why is not working for you. Maybe you ask in #help [Discord](https://discord.gg/EH6nSts) channel or in [Discussions](https://github.com/lucide-icons/lucide/discussions)
I've checked it in codesandbox and it's working there: https://codesandbox.io/p/sandbox/hopeful-spence-zv5hfk?file=%2Fsrc%2FApp.js%3A1%2C1
