### ISSUE TITLE
Add priority icons for support tool

### ISSUE THREAD

**Issue by DavidRouyer** [lucide-icons/lucide#1708]
### Icon name

priority-low, priority-medium, priority-high, priority-critical

### Use cases

I am building an open source customer/support tool like [Intercom](https://www.intercom.com/inbox) or [Plain](https://www.plain.com/) and I am looking for icons representing the level of priority of the tickets (low, medium, high, critical).

It would be a nice addition to the library. Thank you!

### Design ideas

You can take a look at Linear https://linear.app/docs/priority or Plain https://www.plain.com/docs/priorities for inspiration 

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Looks to me like something a monochrome icon set is simply unable to do. Do you have any design ideas that work in monochrome?

**Comment by ericfennis** [comment]
Maybe you could use:
- Critical: [`chevrons-up`](https://lucide.dev/icons/chevrons-up)
- high: [`chevron-up`](https://lucide.dev/icons/chevron-up)
- medium: [`equal`](https://lucide.dev/icons/equal)
- Low: [`chevron-down`](https://lucide.dev/icons/chevron-down)
- Lowest: [`chevrons-down`](https://lucide.dev/icons/chevrons-down)

Like JIRA does.
<img width="241" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/60a30449-22ab-4cc5-9e58-0ee28d14d2f2">

**Comment by ericfennis** [comment]
For critical you could also use some of the alert icons: https://lucide.dev/icons?search=alert.
If you want the linear style we also have the `signal-` icons you could use. https://lucide.dev/icons/?search=signal-

So plenty of options, don't think we should reinvent some new ones for this usecase.
If you think we should create new icons, feel free to reply in this thread.

**Comment by DavidRouyer** [comment]
Thank you for your answers!

I'm not a big fan of JIRA's approach
Signal icons would have been perfect with 3 bars instead of 5

I'll figure something out
