### ISSUE TITLE
Lucide Icon plugin for figma

### ISSUE THREAD

**Issue by ashdesigns** [lucide-icons/lucide#171]
luicide icons are soo underrated, why don't you guys develop a plugin for Figma?

**Comment by locness3** [comment]
> luicide icons are soo underrated,

Well, this is a still a pretty new project.

I agree that a Figma plugin would be nice (knowing that we mostly use figma for making the icons)

**Comment by delnyn** [comment]
yes I asked for that a long time ago  
  
I think we could get the icons using the Github REST API?  
https://docs.github.com/en/rest/reference/repos#contents

**Comment by ericfennis** [comment]
@ashdesigns I agree would be nice to have a figma plugin. Maybe we can port the feather one, and make some adjustments 🤔 .

**Comment by ashdesigns** [comment]
> @ashdesigns I agree would be nice to have a figma plugin. Maybe we can port the feather one, and make some adjustments 🤔 .

that's a great idea, the feather plugin is opensource.

**Comment by ericfennis** [comment]
Update about this project, I'm sort of done with the first version of the plugin.
I used the code of the feather project made some adjustments so it will work with Lucide.
I already submitted a first version to the figma team to review, so I hope very soon they will give some feadback or release it 😄 

**Sneak preview 👀 **
![image](https://user-images.githubusercontent.com/11825403/108762402-57743880-7550-11eb-8b90-96842fe1a5c4.png)

**Comment by ashdesigns** [comment]
> Update about this project, I'm sort of done with the first version of the plugin.
> I used the code of the feather project made some adjustments so it will work with Lucide.
> I already submitted a first version to the figma team to review, so I hope very soon they will give some feadback or release it 😄
> 
> **Sneak preview 👀**
> ![image](https://user-images.githubusercontent.com/11825403/108762402-57743880-7550-11eb-8b90-96842fe1a5c4.png)

This is really cool! Looking forward to use this plugin in my projects.

**Comment by ericfennis** [comment]
@ashdesigns Just got the email from the Figma team, the plugin is approved so you can now use it 😄 🔥 
![image](https://user-images.githubusercontent.com/11825403/108849591-99e65580-75e2-11eb-894c-d19d0b00bc05.png)

**Comment by ashdesigns** [comment]
> @ashdesigns Just got the email from the Figma team, the plugin is approved so you can now use it 😄 🔥
> ![image](https://user-images.githubusercontent.com/11825403/108849591-99e65580-75e2-11eb-894c-d19d0b00bc05.png)

Dude, I'm using the plugin It's super awesome. though I've some feedback I'll share it properly. Nice work bro.

**Comment by ericfennis** [comment]
@ashdesigns Thanks!!
Yeah let me know.
