### ISSUE TITLE
Figma plugin is not loading icons

### ISSUE THREAD

**Issue by mnlfischer** [lucide-icons/lucide#1716]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [X] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

8

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

The plugin is not loading the icons and stays in loading state. It shows only the loading skeleton. I'm using the Figma App on MacoS 14.1.1 (23B81).
![CleanShot 2023-12-07 at 13 39 59@2x](https://github.com/lucide-icons/lucide/assets/3883653/9ec52bdb-16bd-4394-93b6-26d9d6abc52e)

### Steps to reproduce

1. Open Figma
2. Run Lucide Figma Plugin
3. Icons not loading

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Works on my machine 🤷

**Comment by mnlfischer** [comment]
I got the feedback from my colleague first and then I tested it and got the same result. That was the first time I open the plugin but today it works. Maybe the initial load has an issue. I'm not able to find any way to remove the plugin to test it again.
