### ISSUE TITLE
Infinity

### ISSUE THREAD

**Issue by atar-axis** [lucide-icons/lucide#172]
## Icon Request

* Icon name: infinity
* Use case: for headlines
* Suggestion:
![105054324-26e14080-5a72-11eb-83c7-9e61d81cc14c](https://user-images.githubusercontent.com/11148588/105078540-733a7980-5a8e-11eb-98d7-a584cec05720.png)

**Comment by atar-axis** [comment]
[Hintergrund.pdf](https://github.com/lucide-icons/lucide/files/5837934/Hintergrund.pdf)
If this is ok, then I can upload whatever format you need :)

**Comment by ericfennis** [comment]
Nice suggestion!
