### ISSUE TITLE
Google icons

### ISSUE THREAD

**Issue by saurabh-sen** [lucide-icons/lucide#1727]
### Icon name

Google Icons

### Use cases

can be used for depicting google services

### Design ideas

it should look like G

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
It's a brand icon protected by copyright, we cannot modify it to be compliant with our design language, just use simpleicons.org
