### ISSUE TITLE
update. please

### ISSUE THREAD

**Issue by vqh2602** [lucide-icons/lucide#1731]
### Package

- [ ] lucide
- [ ] lucide-angular
- [X] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.257

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

<img width="554" alt="image" src="https://github.com/lucide-icons/lucide/assets/62917858/f30f1c63-9d39-40c7-9f5d-3e649e48ff1c">

### Steps to reproduce

<img width="554" alt="image" src="https://github.com/lucide-icons/lucide/assets/62917858/a66803a9-1c8d-4f1a-a80a-5654b16f23be">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I'm sorry to say that we've abandoned the Flutter package as there was no one to maintain it: #1593 😔
