### ISSUE TITLE
README should ask to import icons specifically, to avoid very large app bundles

### ISSUE THREAD

**Issue by benbucksch** [lucide-icons/lucide#1733]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.293.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Currently, the [official docs](https://github.com/lucide-icons/lucide/tree/main/packages/lucide-svelte#lucide-svelte) recommend to import lucide icons like this:
```
import { Video } from 'lucide-svelte'
```
This is also how VSCode will auto-import the icons.

However, this leads to the entire icon library of 7+ MB to be included in the app bundle, not only that icon that is actually used. That means, among other things, excessively long build times (e.g. rollup and vite), and in some cases even loads to build failures due to size. #1475 even states that the icons remain in the app bundle.

This is relatively easy to avoid (albeit very annoying and easy to forget), by directly importing the icons:
```
  import VideoIcon from 'lucide-svelte/icons/video'
```
(Of course, replace `Video`/`video` with the name of the icon you need.)
This works for me and avoids the excessively slow compile.

The README should be explicitly warning *against* using `import { Video } from 'lucide-svelte'`, and explaining why, so that developers to not run into this pitfall.

This problem is not specific to lucide. Other icon frameworks like Carbon Icons suffer the same problem. If there was a way to avoid the problem in the code and support the easy import without the speed and size penalty, that would be even better.

Relevant bugs: For the /icons/ path, see #1499. Issue #1559 is about TypeScript type errors.

### Steps to reproduce

```
import { Video } from 'lucide-svelte'
```
npm run dev

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by rafales** [comment]
Isn't there some plugin which can solve this? I remember that antd used a babel plugin to handle this kind of issue: https://www.npmjs.com/package/babel-plugin-import

Does anyone know anything similar for vite/sveltekit?

**Comment by ericfennis** [comment]
It's added to the docs in #1766 by @shyakadavis 🎉 , see docs: https://lucide.dev/guide/packages/lucide-svelte#example

**Comment by WanQuanXie** [comment]
I've try to implement a babel plugin for this kind of issue: https://github.com/WanQuanXie/babel-plugin-lucide-react-native. Welcome suggestions/issues/pr :)
