### ISSUE TITLE
Undocumented breaking change from lucide-angular v0.291.0 to v0.292.0

### ISSUE THREAD

**Issue by R-Bower** [lucide-icons/lucide#1735]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

v0.291.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [x] Other/not relevant

### Description

The data type of `LucideIconData` changed in 0.292.0.  This change was not documented.

`lucide-angular` is deeply integrated in our component library.  This change is technically breaking because it modifies the type of the Input properties on some of our components.

Example property:

```typescript
  /**
   * {@link https://lucide.dev/icons lucide-angular} icon, positioned after the label.
   * Can also be supplied as a TemplateRef.
   */
  @Input() endIcon?: LucideIconData | TemplateRef<any>
```

### 0.291.0

`export type LucideIconData = readonly [string, HtmlAttributes, LucideIconNode[]?];`

### 0.292.0

`export type LucideIconData = readonly LucideIconNode[];`

Are there plans to support semver? I'd like to avoid future breaking changes, if possible.  Thanks!

### Steps to reproduce

Inspect the change from 0.291.0 to 0.292.0

### 0.291.0
https://github.com/lucide-icons/lucide/blob/0.291.0/packages/lucide-angular/src/icons/types/index.ts#L3

### 0.292.0
https://github.com/lucide-icons/lucide/blob/0.292.0/packages/lucide-angular/src/icons/types/index.ts

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hey @R-Bower,
 
It was changed in https://github.com/lucide-icons/lucide/pull/1641 as part of us getting ready for Lucide v1 and a larger infrastructure based on the new format - a format that's already used by all our other packages.

But you're absolutely right, we could've added this to release notes. (even if third party usage of this format is not documented either).

**Comment by karsa-mistmere** [comment]
I retroactively added this to the release notes: https://github.com/lucide-icons/lucide/releases/tag/0.292.0
