### ISSUE TITLE
Regular `handshake` icon

### ISSUE THREAD

**Issue by TheMikeyRoss** [lucide-icons/lucide#1741]
### Icon name

handshake

### Use cases

Collaboration ,cooperation, teaming, assistance, introduction, meeting, interviews.

### Design ideas

Similar to the `heart-handshake` but without the heart.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Duplicate of #608
