### ISSUE TITLE
Source button on packages page navigates to 404 after external redirect

### ISSUE THREAD

**Issue by BlankParticle** [lucide-icons/lucide#1750]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [X] other/not relevant

### Version

0.302.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

When clicking the `Source` button for any package on https://lucide.dev/packages, it opens a new tab with the github page for the requested package, but the older tab itself navigates to a `404` page.

### Steps to reproduce

1. Go to https://lucide.dev/packages
2. Click on any `Source` button
3. A new tab opens with the requested github page
4. Open the older tab, it has redirect to a 404 page

[Screencast from 2023-12-25 19-48-12.webm](https://github.com/lucide-icons/lucide/assets/130567419/64ef7421-f94f-47c3-b9bc-0153917f3453)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
The source button works for me.

**Comment by karsa-mistmere** [comment]
I can confirm that it also redirects to a 404 page for me in both Safari, Brave, Chrome and Firefox.

**Comment by karsa-mistmere** [comment]
@BlankParticle: Thank you for reporting this bug, I've submitted a PR fixing this issue.
