### ISSUE TITLE
Lucide icon not imported in angular 17

### ISSUE THREAD

**Issue by ekta-rupareliya** [lucide-icons/lucide#1752]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.302.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

if we install lucide icon and import in angular 17 then import in standalone component

### Steps to reproduce

@Component({
  selector: 'app-topbar',
  standalone: true,
  imports: [DrawerModule,MnDropdownComponent,LucideAngularModule.pick(icons)],
  templateUrl: './topbar.component.html',
  styleUrl: './topbar.component.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
This has nothing to do with `lucide-angular` - you simply cannot use `ModuleWithProvider` import types for standalone components in Angular. Instead, you have to either use `providers` to provide the icons (see https://lucide.dev/guide/packages/lucide-angular#injecting-multiple-icon-providers) or pass the icons as data instead of names, e.g.:

```tsx
@Component({
  selector: 'app-topbar',
  standalone: true,
  imports: [CommonModule, RouterOutlet, LucideAngularModule],
  template: `<lucide-angular [img]="HomeIcon" />`,
})
export class AppComponent {
  protected readonly HomeIcon = HomeIcon;
}
```
