### ISSUE TITLE
lucide.d.ts gives me multiple errors

### ISSUE THREAD

**Issue by AetherDim** [lucide-icons/lucide#1760]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [X] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.302.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Type checking my project gives me multiple errors from `lucide-preact.d.ts`. 

<img width="604" alt="image" src="https://github.com/lucide-icons/lucide/assets/74829006/e0c92d36-a734-4163-aad1-def3bf0ca100">  

(This is a screenshot from my Jetbrains IDE, but my VSCode setup reports the issues as well)

### Steps to reproduce

Install lucide-preact.

Open the `lucide-preact.d.ts` and run a type check.

<img width="889" alt="image" src="https://github.com/lucide-icons/lucide/assets/74829006/038fa2e8-d040-47a3-b64b-2af318622891">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by Ashish1-Sharma** [comment]
import { ReactSVG } from 'some-library'; // Adjust based on your actual library

**Comment by AetherDim** [comment]
> import { ReactSVG } from 'some-library'; // Adjust based on your actual library
I don't think preact has an SVG type. Everything works fine when I choose to ignore the errors.

The ReactSVG error can be suppressed by doing something like:
```ts
type ReactSVG = {}
```

But the other type errors are not affected because the d.ts file has duplicate type definitions for some elements.

**Comment by ericfennis** [comment]
I've fixed this in #1773.
