### ISSUE TITLE
Failed to resolve "./.nitro/types/tsconfig.json" on starting docs server

### ISSUE THREAD

**Issue by esvyridov** [lucide-icons/lucide#1771]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [X] other/not relevant

### Version

latest

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Perhaps, I'm missing something, but I get:
> [plugin:vite:esbuild] failed to resolve "extends":"./.nitro/types/tsconfig.json" in ".../lucide/docs/tsconfig.json"

when I run `pnpm docs:dev`. The `.nitro` folder has been added to [.gitignore](https://github.com/lucide-icons/lucide/blob/main/.gitignore#L40)

### Steps to reproduce

1. Clone the repo
2. Go to /docs
3. Run `pnpm install` and `pnpm docs:dev`

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Thanks for letting us know. Nitro is the API server, the `.nitro` directory is generated when de API server is started `pnpm dev`. Currently this isn't clear according to the docs. 
We should check if we can build these types when running `pnpm docs:dev`

**Comment by esvyridov** [comment]
@ericfennis got it, thank you. Nitro suggests (https://nitro.unjs.io/guide/typescript) to run `nitro prepare` in the `postinstall` script. I tested it locally, the command generates only `/docs/.nitro/types` folder. I can create a PR if this solution sounds correct to you.
