### ISSUE TITLE
Icon request: markdown

### ISSUE THREAD

**Issue by boojack** [lucide-icons/lucide#1772]
### Icon name

markdown

### Use cases

* Indicates whether editor-related features support markdown syntax;

### Design ideas

It's just like the one shown in GitHub: `M` and a down arrow. 
<img width="177" alt="image" src="https://github.com/lucide-icons/lucide/assets/24653555/ff246cc1-55a0-4252-b71b-393129e321e3">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Duplicate of #1110
