### ISSUE TITLE
Module '"lucide-react"' has no exported member 'Vault'.

### ISSUE THREAD

**Issue by priska42** [lucide-icons/lucide#1785]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.294.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Looks like there's sonme mising icons in 0.294.0 version of lucide-react.

### Steps to reproduce

import { Vault } from 'lucide-react'

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Vault was only added in [v0.305.0](https://github.com/lucide-icons/lucide/releases/tag/0.305.0)
