### ISSUE TITLE
Toilet

### ISSUE THREAD

**Issue by staffanmowitz** [lucide-icons/lucide#1788]
### Icon name

toilet

### Use cases

Showing that a rental room or cottage has access to its own toilet

### Design ideas

![toilet](https://github.com/lucide-icons/lucide/assets/4193622/237aaac3-6d04-41fa-89a8-a61d1c1b32c5)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by EthanHazel** [comment]
Here's two designs I came up with, I'm not sure if I like the lid or not, it's hard to have the 2px offset without it look disconnected.
![image](https://github.com/lucide-icons/lucide/assets/134425461/bca8cb99-1735-457e-9e07-16e69245ff95)
