### ISSUE TITLE
Icon not imported

### ISSUE THREAD

**Issue by chk7964** [lucide-icons/lucide#1789]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.308.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

CodeSquare icon not import our project

### Steps to reproduce

import { Bold, Code, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6, Italic, Redo, Strikethrough, Undo, Underline as UnderlineIcon, CodeSquare } from "lucide-react";

'"lucide-react"' has no exported member named 'CodeSquare'. Did you mean 'LucideSquare'?

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
@chk7964: I can't reproduce this issue using react 18.2, can you make absolutely sure that your lucide-react is definitely at v0.308.0?

**Comment by timrittgers** [comment]
We are seeing a similar issue but our build reports that lucide has no exported member ‘PenSquare’

**Comment by karsa-mistmere** [comment]
Aliases are apparently not exported in the UMD builds of our `react`, `preact`, `vue` and `vue-next` packages, I've submitted a PR.

**Comment by timrittgers** [comment]
The PR linked closing this issue doesn’t appear to have fixed the issue for us. We are still getting the message that PenSquare is not an exported member of Lucide.

**Comment by ericfennis** [comment]
@timrittgers Not sure what is happening in your environment. I've tested this with 0.314.0, works here.  https://stackblitz.com/edit/stackblitz-starters-j3hphp?file=src%2FApp.tsx

**Comment by timrittgers** [comment]
Was able to determine that sometime the icon name PenSquare was changed to SquarePen, which was a breaking change for our code.

**Comment by ericfennis** [comment]
@timrittgers Hmm, that's weird. Both should work, see https://stackblitz.com/edit/stackblitz-starters-j3hphp?file=src%2FApp.tsx
