### ISSUE TITLE
Bluesky logo

### ISSUE THREAD

**Issue by diego-betto** [lucide-icons/lucide#1804]
### Icon name

bluesky

### Use cases

Bluesky social icon for blogs and sharing

### Design ideas

Reference https://blueskyweb.xyz/blog/12-21-2023-butterfly

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
Brand icon

**Comment by diego-betto** [comment]
Oh, why?

**Comment by karsa-mistmere** [comment]
> Oh, why?

When submitting this issue you should've seen the notice explaining why:

> Important note: No new brand logos are allowed, see https://github.com/lucide-icons/lucide/issues/670.
> Existing brand icons will also be phased out. For brand icons, consider using https://simpleicons.org/, which offers purpose-built SVGs that are also on a 24×24px grid.

**Comment by diego-betto** [comment]
Super, tnx!
