### ISSUE TITLE
Categories not showing icons

### ISSUE THREAD

**Issue by DefaultLP** [lucide-icons/lucide#1806]
### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

When clicking on a category (i.e. Layout, Design, etc) the icons won't load.
<img width="579" alt="brave_tX2CFoQTmb" src="https://github.com/lucide-icons/lucide/assets/29122114/4c6da804-765c-4560-965d-7329fed5af37">

The boxes can still be clicked to show the icon.

Tested on both Windows and Linux Debian using both Chrome and Firefox.

### Steps to reproduce

1. Visit lucide.dev [category](https://lucide.dev/icons/categories#layout) view

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Fixed in e3abcdbcc601f787ad8dd763dd245f35f0dd59b9
