### ISSUE TITLE
PanelsRgithtButtom is not exported from  lucide-react

### ISSUE THREAD

**Issue by MenaiAla** [lucide-icons/lucide#1810]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.292.1

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

I want to use `PanelsRightBottom` icon from `lucide-react`:

![image](https://github.com/lucide-icons/lucide/assets/20143684/3b3c30e3-7e39-4acc-8688-1665b503b650)

I copied the JSX and pasted it into the code:

![image](https://github.com/lucide-icons/lucide/assets/20143684/82682fec-7005-47dc-981a-a3a2cc5152b9)

But the other panels icons are exist:

![image](https://github.com/lucide-icons/lucide/assets/20143684/4e8ced50-9f17-4124-b747-5ed43c2b6902)

### Steps to reproduce

1. Copy and paster JSX.
2. Import the icon.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
@MenaiAla On which version are you? Did you updated to the latest version?

**Comment by MenaiAla** [comment]
> @MenaiAla On which version are you? Did you update to the latest version?

Version: 0.292.0

**Comment by jguddas** [comment]
Okay, upgrade to `v302` to fix this.

<img width="776" alt="image" src="https://github.com/lucide-icons/lucide/assets/25524993/d7220f5c-0bc7-4afe-a4f8-bb1762db6ce1">
