### ISSUE TITLE
Ethernet or Ethernet port icon

### ISSUE THREAD

**Issue by MarkLyck** [lucide-icons/lucide#1816]
### Icon name

ethernet

### Use cases

I'm working on a network Saas application which offers products related to network switches, ethernet and ethernet ports.

It could also be used by any application that has or manages internet connections, routers, network switches, networking in general etc.

### Design ideas

<img width="63" alt="Screenshot 2024-01-19 at 16 50 23" src="https://github.com/lucide-icons/lucide/assets/6841110/630dbae6-b401-4dca-9c60-073ba947d479">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by ericfennis** [comment]
Possible designs from @raphael141714 in #527. 

<img width="647" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/0f7e5635-cdea-4e00-bec9-814e3ca3c15f">

**Comment by karsa-mistmere** [comment]
> Possible designs from @raphael141714 in #527.
> 
> <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/11825403/298405237-0f7e5635-cdea-4e00-bec9-814e3ca3c15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTYwMjYsIm5iZiI6MTcwNTk5NTcyNiwicGF0aCI6Ii8xMTgyNTQwMy8yOTg0MDUyMzctMGY3ZTU2MzUtY2RlYS00ZTAwLWJlYzktODE0ZTNjYTNjMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3NDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMWE0MTAzY2I0MjY2YTY0MTcwMzA5NTdmY2MwZjZjNGNlZDUzMDRiNTVmMTA3M2UxNzZmYjM1NjgxMjliODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mb3cPkxL6QiZmh8U2ZiaYvZawRcthzBEcGIaj2_OOQ4">

If I'm not mistaken, none of these have a 1px padding horizontally.

**Comment by ericfennis** [comment]
@karsa-mistmere Only `ethernet-off` has no 1px padding.

<img width="237" alt="image" src="https://github.com/lucide-icons/lucide/assets/11825403/9f6287d7-754a-4137-ad95-75008bd5f32f">

**Comment by MarkLyck** [comment]
> Possible designs from @raphael141714 in #527.
> 
> <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/11825403/298405237-0f7e5635-cdea-4e00-bec9-814e3ca3c15f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDU3OTgsIm5iZiI6MTcwNjA0NTQ5OCwicGF0aCI6Ii8xMTgyNTQwMy8yOTg0MDUyMzctMGY3ZTU2MzUtY2RlYS00ZTAwLWJlYzktODE0ZTNjYTNjMTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIxMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NGZiOTBlZjRmMDY4MGUxYWM1ZWUyMzQ3MTY5ZjQwMTNmZDVhNTkyYzUyMGY0ZmI1Mzg5ZmVlZDM0NmNkMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0-dz3a33w4-5LibW2SWFVJNnaZWlWFb19ytvD_sD5Uo">

It would be fantastic to have these variants!
