### ISSUE TITLE
PanelRightOpen Icon is not working

### ISSUE THREAD

**Issue by hehuangz** [lucide-icons/lucide#1822]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.312.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

When I use  PanelRightOpen Icon that it's not working, and it's the error:
<img width="724" alt="image" src="https://github.com/lucide-icons/lucide/assets/32256818/29530fc8-ba41-44d7-84f8-25f48d10ee3e">
Other icons are working, but PanelRightOpen is especially not working.

### Steps to reproduce

1. @/components/shared/icons
import { PanelRightOpen, PanelLeftOpen } from "lucide-react";
export const Icons = {    
    open: PanelLeftOpen,
    fold: PanelRightOpen,
}
2. demo.tsx
import { Icons } from "@/components/shared/icons"
export default function Demo(){
    return (
       <>
           <Icons.open /> // working
           <Icons.fold /> // not working
       </>
    )
}

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Can't reproduce.

https://stackblitz.com/edit/stackblitz-starters-rjpkgi?file=src%2FApp.tsx
