### ISSUE TITLE
Skull

### ISSUE THREAD

**Issue by atar-axis** [lucide-icons/lucide#183]
## Icon Request

* Icon name: skull
* Use case: Headlines
* Suggestion:
![Hintergrund@3x](https://user-images.githubusercontent.com/11148588/106068959-ce5d1380-6101-11eb-8ed3-f334487cfb0a.jpg)

**Comment by atar-axis** [comment]
[Hintergrund.pdf](https://github.com/lucide-icons/lucide/files/5883777/Hintergrund.pdf)

**Comment by atar-axis** [comment]
[Skull2.pdf](https://github.com/lucide-icons/lucide/files/5883811/Hintergrund.pdf)
![Hintergrund@3x](https://user-images.githubusercontent.com/11148588/106069602-17619780-6103-11eb-90a0-92f289186f00.jpg)

**Comment by atar-axis** [comment]
Are those irregular shapes allowed?

**Comment by ericfennis** [comment]
@atar-axis Welcome to the the Lucide project!
Yeah it's prefered to use basic shapes if possible.

**Comment by ericfennis** [comment]
Maybe we can inspire some from this image 
![image](https://user-images.githubusercontent.com/11825403/106384001-0fd31480-63c9-11eb-99b0-07030124ce9b.png)

**Comment by atar-axis** [comment]
Oh I like those! Which one would you prefer?

**Comment by ericfennis** [comment]
I think the 3th one of the bottom row.

**Comment by ericfennis** [comment]
@atar-axis What do you think of this? 
![image](https://user-images.githubusercontent.com/11825403/109702791-fe7e5300-7b94-11eb-82a8-0ea851dca622.png)
