### ISSUE TITLE
Archaeological artifacts/museum objects

### ISSUE THREAD

**Issue by manuelpoelzl** [lucide-icons/lucide#1833]
### Icon name

silex, arrowhead, amphora

### Use cases

Especially if you are developing applications for museums or universities - in this case related to archaeology, it would be good to have icons for this.
These icons are specifically designed to represent archaeological finds.

I currently use the `coins` icon from Lucide to display archaeological discoveries, but this does not always seem to be suitable. 

### Design ideas

GameIcons has some neat designs for [Sillex/Flint](https://game-icons.net/1x1/delapouite/silex.html) and [Arrowhead](https://game-icons.net/1x1/lorc/arrowhead.html).

Also the discussed [amphora icon ](https://github.com/FortAwesome/Font-Awesome/issues/10022) in the FontAwesome repo is kinda nice.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Here's a (somewhat out of proportion, stylised) amphora:
![image](https://github.com/lucide-icons/lucide/assets/17746067/0ebb5058-495e-4375-8893-be87c647b619)
![image](https://github.com/lucide-icons/lucide/assets/17746067/2d2db1e6-bba1-4f24-807d-088eb71f5347)

**Comment by karsa-mistmere** [comment]
Some alternates. I really hate the first one, it looks like an aerial bomb. 😅

![image](https://github.com/lucide-icons/lucide/assets/17746067/12986376-2c91-4924-b4b9-c902d4677e3c)
![image](https://github.com/lucide-icons/lucide/assets/17746067/a1feaa17-6ae7-4c3f-943b-18d2a0f50115)
