### ISSUE TITLE
sports icons

### ISSUE THREAD

**Issue by MatsAndT** [lucide-icons/lucide#1845]
### Icon name

running, handball, soccer, swim, climbing, crossfit 

### Use cases

area of ​​use is for example in sports apps

### Design ideas

examples from Google icons
![image](https://github.com/lucide-icons/lucide/assets/23106882/f3e23f72-e461-4635-bc81-b7fdc80ebe71) ![image](https://github.com/lucide-icons/lucide/assets/23106882/eae1effb-38f6-49dc-acb7-08f71ffead53) ![image](https://github.com/lucide-icons/lucide/assets/23106882/2013f026-e341-41d1-a178-ab7a15b1a5cd) ![image](https://github.com/lucide-icons/lucide/assets/23106882/6ec0c0f7-f0da-4b61-89b0-9493a8e7b9c8) ![image](https://github.com/lucide-icons/lucide/assets/23106882/4f61dc51-1f43-4976-b1d7-1f28150049d1)

From iStock
![image](https://github.com/lucide-icons/lucide/assets/23106882/05720ddb-b92a-44ee-91ee-43bb60546d50)

From Shutterstock
![image](https://github.com/lucide-icons/lucide/assets/23106882/b699234e-6491-4d5b-9940-22d34a13d4f7)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Duplicates #1304
