### ISSUE TITLE
Images icon

### ISSUE THREAD

**Issue by stephannv** [lucide-icons/lucide#1851]
### Icon name

images

### Use cases

My use case: An icon for a menu  "Images" where user can manage multiple images

### Design ideas

Something like this: https://boxicons.com/?query=images

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Yeah, I already have this in my drafts, I'll open a PR tomorrow.
