### ISSUE TITLE
Telescope icon

### ISSUE THREAD

**Issue by fatihsever** [lucide-icons/lucide#1854]
### Icon name

telescope

### Use cases

- "Explore" menu icon (similar to GitHub mobile app)
- There is currently a microscope icon. It would be nice to have a telescope icon too.

> “The microscope reveals to man his significance. The telescope, his insignificance.” – Manly P Hall

### Design ideas

Something like Octicons' one:
https://primer.style/foundations/icons/telescope-24

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
> #1242 added a telescope icon to our `lab` branch: ![image](https://private-user-images.githubusercontent.com/17746067/302896804-18cc713f-0e36-44b9-913a-c87d954c68ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NDUsIm5iZiI6MTcwNzMwNjU0NSwicGF0aCI6Ii8xNzc0NjA2Ny8zMDI4OTY4MDQtMThjYzcxM2YtMGUzNi00NGI5LTkxM2EtYzg3ZDk1NGM2OGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YmMzYzYxYzBjOTU4ZDgyYTYzNzdiNjEwZDRiOTI5ZDM1NjQ0YzI4NzU3YTAzYmY4YTM3M2U5YjcxMmIzMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rfwbMqyEKbpAfuprOsVeSsJRSezVlBxbRM78-aOEZI8)
> 
> I've also had this alternate telescope icon in my drafts for ages: ![image](https://private-user-images.githubusercontent.com/17746067/302896642-8f89d304-aaef-4466-86e3-c53dcf8b705a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDY4NDUsIm5iZiI6MTcwNzMwNjU0NSwicGF0aCI6Ii8xNzc0NjA2Ny8zMDI4OTY2NDItOGY4OWQzMDQtYWFlZi00NDY2LTg2ZTMtYzUzZGNmOGI3MDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDExNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTI4OWMyNGVmOWVhNzIzNjZjMTVmMzIwNzVlNmQwMGFiNjdjOGU1ZjUzZTQwODg1ZjNlZTM1MzYwMDk0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lmb1_hUQxFKw36kymBGdbAs5zj7_3bDz9FQEdd6Jdx4)

The second one looks great!

**Comment by ericfennis** [comment]
@karsa-mistmere @chessurisme I like the second one as well. Let's create a PR.

**Comment by chessurisme** [comment]
Hi @karsa-mistmere, can I give this one a go? I try to recreate if you want to. I'll add you as a contributor too.

**Comment by karsa-mistmere** [comment]
> Hi @karsa-mistmere, can I give this one a go? I try to recreate if you want to. I'll add you as a contributor too.

I already have it cleaned up and ready to go, I think it would make more sense to tackle some other issue that doesn't have a solution yet, especially something from #119
