### ISSUE TITLE
[Icon Request]: Energy Autarky for house

### ISSUE THREAD

**Issue by alamenai** [lucide-icons/lucide#1855]
### Icon name

Autarky

### Use cases

1. For solar system generated electricity.
2. For electricity saving.

### Design ideas

1. House surrounded with electricity.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
Here's my proposal to this issue:
`home-plug` and `home-zap`
![image](https://github.com/lucide-icons/lucide/assets/137697011/52930d59-1623-4886-907b-3a61b4a146be)
![image](https://github.com/lucide-icons/lucide/assets/137697011/6cc45855-1a9d-414b-8b1a-e84d6cd4e957)

**Comment by karsa-mistmere** [comment]
Sidenote: Let's also keep in mind that #1841 might trigger a redesign of `home`, maybe we should do that first before adding this.

**Comment by chessurisme** [comment]
Okay, let's wait for the redesign. Thanks @karsa-mistmere.
