### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by uiuxarghya** [lucide-icons/lucide#186]
Can you please tell me where to put new icons to be visible on the site when it's deployed?

**Comment by mittalyashu** [comment]
Can you elaborate a bit didn't understood your question? @uiuxarghya

**Comment by uiuxarghya** [comment]
I want to make my icon collection like that so I am asking that where to place the icons in the code so it will be displayed on the site when the my site will be published.

**Comment by mittalyashu** [comment]
@uiuxarghya You can look into the codebase of Lucide site https://github.com/lucide-icons/lucide/tree/master/site

**Comment by mittalyashu** [comment]
@uiuxarghya does this answer your question?

**Comment by uiuxarghya** [comment]
> Can you elaborate a bit didn't understood your question? @uiuxarghya 

    No not at all. I am not getting it.

**Comment by mittalyashu** [comment]
@uiuxarghya So, I believe, you're asking how to show the icons (you have created) on the website.

Am I correct?

**Comment by uiuxarghya** [comment]
Ya sure I want to make a pack of icons of mine an to publish it in the site.

**Comment by mittalyashu** [comment]
Right.

That's why I shared the link to Lucide site source from where you can get the reference to build your own site.

**Comment by ericfennis** [comment]
If you made icons, you can export them to svgs.
For the implementation of svgs I suggest you to read this site: https://svgontheweb.com/#svg
If you have more problems or questions about svgs, I will refer you to: https://stackoverflow.com/questions/tagged/svg

I assume your issue has nothing do with the Lucide project or Lucide Community so I close this.
