### ISSUE TITLE
[icon request] Content square

### ISSUE THREAD

**Issue by zoharma** [lucide-icons/lucide#1860]
### Icon name

content-square

### Use cases

Essentially this is similar to the [Kanban Square icon ](https://lucide.dev/icons/kanban-square) but show at 90º and marked as content. Could be used for the outline version too

### Design ideas

Content-square
![kanban-square-90](https://github.com/lucide-icons/lucide/assets/10050573/9d1d99ad-6d2b-40b9-8411-c04fcb4601fd)

Kanban square
![kanban-square](https://github.com/lucide-icons/lucide/assets/10050573/9bf2a9d9-2d6a-42eb-99ec-ca50c093b6a9)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
We do already have https://lucide.dev/icons/gantt-chart-square

As well as a https://github.com/lucide-icons/lucide/blob/lab/icons/text-square.svg in our lab branch from https://github.com/lucide-icons/lucide/pull/1298.

**Comment by jevail** [comment]
Still would love to see this icon!

**Comment by zoharma** [comment]
Seems to be still in the lab... https://lucide.dev/icons/lab/text-square. Not sure about the progression

**Comment by jevail** [comment]
Thanks for the reply, didn’t know about labs!
