### ISSUE TITLE
Feminine / Masculine icons (♂, ♀ and ⚥)

### ISSUE THREAD

**Issue by rbozan** [lucide-icons/lucide#1862]
### Icon name

Feminine / Masculine icons, sometimes used for toilet signs

### Use cases

To specify gender, for an user profile
To specify grammatical gender (the gender of a word)

### Design ideas

From Wikipedia:

"The three standard sex symbols in biology are male ♂, female ♀ and hermaphroditic ⚥"

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
Duplicate issue [#27](https://github.com/feathericons/feather/issues/27) (See Also issue #119)

**Comment by karsa-mistmere** [comment]
Yeah, it's a duplicate, thanks @chessurisme
