### ISSUE TITLE
Why battery with 24px looks small to other icons with 24px?

### ISSUE THREAD

**Issue by alamenai** [lucide-icons/lucide#1863]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.292

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

I used the icon of [Battery Medium](https://lucide.dev/icons/battery-medium) with the size 24px and stroke 2 but it looks small to other icons with the same dimensions.

But when I change the size to 32 it looks the same as other icons.

### Case: default size

![image](https://github.com/lucide-icons/lucide/assets/20143684/0f040146-d680-4ad4-b845-a37837397573)

### Case: size 32

![image](https://github.com/lucide-icons/lucide/assets/20143684/9696c00c-6862-41dd-92f2-a4fbf9578af7)

### Steps to reproduce

1. Import Icon
2. Use it as JSX.

### Code

```jsx

 <Card className='flex items-center w-full rounded-2xl'>
                    <CardContent className='flex items-center'>
                      <div className='flex items-start justify-between'>
                        <div className='flex items-center'>
                          <ProgressCircle value={autarkyDegree} size='md' color='green' className='mt-2' showAnimation>
                            <span className='h-12 w-12 rounded-full bg-green-100 flex items-center justify-center text-sm text-green-600 font-medium'>
                              {autarkyDegree}%
                            </span>
                          </ProgressCircle>
                          <div className='flex flex-col ml-4'>
                            <CardTitle className='text-md'>Autarky</CardTitle>
                            <CardDescription className='mt-2'>
                              {100 - autarkyDegree}% kann von anderen Ressourcen generiert werden.
                            </CardDescription>
                          </div>
                        </div>
                        <BatteryMedium />
                      </div>
                    </CardContent>
                  </Card>
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I'm 99.9% sure that the cause of the issue is that your flex layout allows the shrinking of `battery`, so it does shrink.
You can demo this by replacing it with any other icon to see if it also shrinks (in my reproduction, they did).
If so, this is not Lucide related.

You can `flex-shrink: 0` to your icons (or a wrapper element) via `shrink-0` (if it's tailwindcss like it seems) to solve this.

**Comment by alamenai** [comment]
Yes @karsa-mistmere , you are right, when I set the position to absolute, the size looks similar. I appreciate your help.
