### ISSUE TITLE
Pickaxe

### ISSUE THREAD

**Issue by bernatfortet** [lucide-icons/lucide#1866]
### Icon name

pick-axe

### Use cases

This icon would be helpful to showcase 'in progress' status, mines, land worker, etc..

### Design ideas

There are other tools like hammer or drill, so it should look similar to those

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
How do you feel about this one?
![image](https://github.com/lucide-icons/lucide/assets/17746067/93a29a4f-b3c3-4629-8e91-960ef1f966ef)

**Comment by bernatfortet** [comment]
Awesome 👍
