### ISSUE TITLE
Facebook icon deprecated

### ISSUE THREAD

**Issue by webdiego** [lucide-icons/lucide#1867]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [X] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.323.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Hello, 
when I'm importing the facebook icon I get this:

```
'Facebook' is deprecated.ts(6385)
lucide-react-native.d.ts(6509, 4): The declaration was marked as deprecated here.
```

### Steps to reproduce

```
import { Facebook } from "lucide-react-native";

export default function Page() {
  return (
    <View className="h-full w-full px-2 py-10">
      <Text className="text-4xl text-gray-900 font-bold">Links</Text>

      <View className="mt-5">
        <Facebook color="#61A2EB" size={28} />
      </View>
    </View>
  );
}
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
We know, it's on purpose. #670 #94

**Comment by webdiego** [comment]
Ok, I get it, thanks

**Comment by khanakia** [comment]
@webdiego how do i create a custom social icon using Lucide then ?

**Comment by MahmoudKSultan** [comment]
> We know, it's on purpose. #670 #94

So, is it alright to use it?

**Comment by FredH2O** [comment]
Why its deprecated guys
