### ISSUE TITLE
Update flutter package (NEW ICONS)

### ISSUE THREAD

**Issue by iamrishan** [lucide-icons/lucide#1898]
### Package

- [ ] lucide
- [ ] lucide-angular
- [X] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Many new icons are not available in flutte package last update about 7 months ago.  please consider updating the package with latest icons

### Use cases

when i search icon in lucide and implement in my flutter app many icons in the site is not present in the flutter package

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
See #1593 #1692

**Comment by iamrishan** [comment]
bad choice from the team. why do they archived the repo, alteast others can make pull's

**Comment by karsa-mistmere** [comment]
> bad choice from the team. why do they archived the repo, alteast others can make pull's

We didn't archive it, we just moved it to a [separate repo](https://github.com/lucide-icons/lucide-flutter), so people still can submit pull requests.

**Comment by iamrishan** [comment]
yeah that's good, i misread
