### ISSUE TITLE
pix

### ISSUE THREAD

**Issue by maykon-oliveira** [lucide-icons/lucide#1899]
### Icon name

pix

### Use cases

It's a Brazilian payment method icon.

### Design ideas

![pix](https://github.com/lucide-icons/lucide/assets/27507681/82c1c93f-0281-4de8-994a-19bfd3fbec4e)

[Guide](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
Sorry, we are not accepting brand icons.

Pix brand guidelines: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf

https://github.com/lucide-icons/lucide/issues/670

**Comment by maykon-oliveira** [comment]
> Sorry, we are not accepting brand icons.
> 
> Pix brand guidelines: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf
> 
> #670

Pix isn't not a brand. It's a payment method, that have a icon. Like credit card, boleto, cash, pix.

Please, make a research about.

**Comment by karsa-mistmere** [comment]
> > Sorry, we are not accepting brand icons.
> > Pix brand guidelines: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/I_manual_uso_marca_pix.pdf
> > #670
> 
> Pix isn't not a brand. It's a payment method that has an icon. Like credit card, boleto, cash, pix.
> 
> Please, make a research about.

Which he very obviously not just did but also linked the guidelines, which clearly state that we cannot use outlines (see page 30, item 6), while Lucide's icon design guidelines prohibit fills, so we clearly cannot make it work.
