### ISSUE TITLE
Please update flutter icons similar to web version

### ISSUE THREAD

**Issue by chetannager** [lucide-icons/lucide#1931]
### Icon name

drama

### Use cases

In Web New icons version is 0.341.0. But in flutter have lucide_icons: ^0.257.0 pls update

### Design ideas

In Web New icons version is 0.341.0. But in flutter have lucide_icons: ^0.257.0 pls update

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Duplicates #1692 and #1898, please refer to #1593 as to why the Flutter package has not been updated lately, and also check out https://github.com/lucide-icons/lucide-flutter where @n-bernat is already working on updating it.
