### ISSUE TITLE
SquarePen doesn't exists in lucide-react

### ISSUE THREAD

**Issue by body20002** [lucide-icons/lucide#1932]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

^0.307.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

SquarePen icon doesn't exists in the package, https://lucide.dev/icons/square-pen

### Steps to reproduce

1. try to import it by using
```js
import { SquarePen } from 'lucide-react';
```
2. error the icon doesn't exists

eslint error:-
![image](https://github.com/lucide-icons/lucide/assets/33910565/22b2f3bb-9e78-4069-ae73-91774735ddb3)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by body20002** [comment]
it turned out I'm using old version, but it's odd that it doesn't exists on the version I had, because the website states that v 0.0.0 had it so 🤷🏻

**Comment by karsa-mistmere** [comment]
> it turned out I'm using old version, but it's odd that it doesn't exists on the version I had, because the website states that v 0.0.0 had it so 🤷🏻

Before v0.308.0 it used to be named `Edit2` I think.
