### ISSUE TITLE
Too many requests in dev mode

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#1933]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

^0.336.0

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

When I am using `lucide-solid` in my SolidStart project, I find that in the dev mode, it will request too many requests and let me must wait for > 1min. (I develop it in the remote machine, which is an Linux machine, and using Chrome / Arc / Firefox to interact with the project)

<img width="360" alt="截屏2024-02-29 19 06 56" src="https://github.com/lucide-icons/lucide/assets/25707198/a1376394-f223-4a42-a8bf-b128798e427e">

Here is the section of package.json of `lucide-solid`:

```json5
{
  // ...
  "exports": {
    ".": {
      "types": "./dist/types/lucide-solid.d.ts",
      "solid": "./dist/source/lucide-solid.js",
      "import": "./dist/esm/lucide-solid.js",
      "browser": "./dist/esm/lucide-solid.js",
      "require": "./dist/cjs/lucide-solid.js",
      "node": "./dist/cjs/lucide-solid.js"
    }
  }
  // ...
}
```

It looks like it just using the "./dist/source/lucide-solid.js", which has bad performance when in development.

### Steps to reproduce

* Using `lucide-solid` in any solid project.
* Import it like `import { CheckCircle, Circle, Trash2 } from 'lucide-solid';`.
* Run it in development mode.

Here I am using the SolidStart framework and Bun so you can:

```ts
bunx create-solid@latest
bun install
bun run dev
```

Then you can install the `lucide-solid` and import it in any file.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by PeterlitsZo** [comment]
Just a question: could we import a icon by `import ChevronDownSquare from "lucide-solid/chevron-down-square"`?

**Comment by ericfennis** [comment]
@PeterlitsZo Hmm not possible at the moment. Solid currently requires to have a bundled ESM file.

**Comment by mifreudenthaler** [comment]
any news on this? having the same problem.

**Comment by floratmin** [comment]
I have the same problem. As soon I load one icon all icons are loaded in dev mode and my computer starts to struggle.

**Comment by jguddas** [comment]
Closing in favor of #1944
