### ISSUE TITLE
Earth Continent Variations

### ISSUE THREAD

**Issue by bensaine** [lucide-icons/lucide#1934]
### Icon name

earth-europe, earth-americas, earth-africa, earth-asia, earth-oceania, earth-antartica

### Use cases

- Selecting timezones
- Filtering something by region 
- Travel application

### Design ideas

Should have same design style as our current earth icon,
<img width="255" alt="image" src="https://github.com/lucide-icons/lucide/assets/34781348/b552ffd5-5546-4257-ba09-db9a7dcc0309">

But depicting the respective continents clearly, here is some inspiration from font-awesome
<img width="690" alt="image" src="https://github.com/lucide-icons/lucide/assets/34781348/c1a2a536-3556-4c7a-ba5a-d3841c3be0e1">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
I'm afraid this is not at all feasible with Lucide's guidelines until we have support for fills, I've added the needs fills labels so that this can be reopened later on once we do, see the discussions at #458

**Comment by bensaine** [comment]
I think this can be achieved with lines only @karsa-mistmere.

<img width="130" alt="image" src="https://github.com/lucide-icons/lucide/assets/34781348/81c3a10f-b61c-48e6-8d79-5fd17e4e1e27">
<img width="385" alt="image" src="https://github.com/lucide-icons/lucide/assets/34781348/9b641f7e-05be-443a-a98c-76828823bae3">
<img width="125" alt="image" src="https://github.com/lucide-icons/lucide/assets/34781348/5af92749-777a-40c9-be8b-c2c0ff4b322c">

**Comment by karsa-mistmere** [comment]
> I think this can be achieved with lines only @karsa-mistmere.
> 
> <img alt="image" width="130" src="https://private-user-images.githubusercontent.com/34781348/310476977-81c3a10f-b61c-48e6-8d79-5fd17e4e1e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzY5NzctODFjM2ExMGYtYjYxYy00OGU2LThkNzktNWZkMTdlNGUxZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNmMzNTIzMjg4ZTFmOTk3ZGJkZmY2ZTM5MDNjNjQ4NjFkNjMxZDM2NGRjNzlhMzNkMmEyY2ZmMmNmYjRkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-17C83dmKGZMrtGotG9ewclfx-LjNPZUJdECETkPJw"> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/34781348/310477022-9b641f7e-05be-443a-a98c-76828823bae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzcwMjItOWI2NDFmN2UtMDViZS00NDNhLWE5OGMtNzY4Mjg4MjNiYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZjAxYjkwYjRkY2Y0OTMzMTMyZmI2MDlhNzZjYjk5ZmFkNTA3MjUyNWJhODJmYjlmNmIyMjA4ZmMzYjM3NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5jWG11suYW18eyxFMM5mn7AIEGI_ruzlrkrDXybjo4"> <img alt="image" width="125" src="https://private-user-images.githubusercontent.com/34781348/310477068-5af92749-777a-40c9-be8b-c2c0ff4b322c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzcwNjgtNWFmOTI3NDktNzc3YS00MGM5LWJlOGItYzJjMGZmNGIzMjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDNhNWY4YzgzNzIxMDBjOTZlYzEzMjk3Y2ViN2QwMDJiZDBlMTMyNmMzZGNjNjZjNTg1NDc2YTlhZDUwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3TYv8N18LF8AcPEnesKj4yy3lah5JPwVqwUkQckTXhU">

Yes, I'm very much aware of Fontawesome's Light icon set, unfortunately this won't work at all within our design system, since we'd need 2px strokes and 2px gaps, and FA Light uses much lighter strokes and allows for much thinner gaps.

**Comment by bensaine** [comment]
A

> > I think this can be achieved with lines only @karsa-mistmere.
> > <img alt="image" width="130" src="https://private-user-images.githubusercontent.com/34781348/310476977-81c3a10f-b61c-48e6-8d79-5fd17e4e1e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzY5NzctODFjM2ExMGYtYjYxYy00OGU2LThkNzktNWZkMTdlNGUxZTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNmMzNTIzMjg4ZTFmOTk3ZGJkZmY2ZTM5MDNjNjQ4NjFkNjMxZDM2NGRjNzlhMzNkMmEyY2ZmMmNmYjRkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-17C83dmKGZMrtGotG9ewclfx-LjNPZUJdECETkPJw"> <img alt="image" width="385" src="https://private-user-images.githubusercontent.com/34781348/310477022-9b641f7e-05be-443a-a98c-76828823bae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzcwMjItOWI2NDFmN2UtMDViZS00NDNhLWE5OGMtNzY4Mjg4MjNiYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZjAxYjkwYjRkY2Y0OTMzMTMyZmI2MDlhNzZjYjk5ZmFkNTA3MjUyNWJhODJmYjlmNmIyMjA4ZmMzYjM3NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5jWG11suYW18eyxFMM5mn7AIEGI_ruzlrkrDXybjo4"> <img alt="image" width="125" src="https://private-user-images.githubusercontent.com/34781348/310477068-5af92749-777a-40c9-be8b-c2c0ff4b322c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjQ5NjEsIm5iZiI6MTcwOTcyNDY2MSwicGF0aCI6Ii8zNDc4MTM0OC8zMTA0NzcwNjgtNWFmOTI3NDktNzc3YS00MGM5LWJlOGItYzJjMGZmNGIzMjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDExMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDNhNWY4YzgzNzIxMDBjOTZlYzEzMjk3Y2ViN2QwMDJiZDBlMTMyNmMzZGNjNjZjNTg1NDc2YTlhZDUwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3TYv8N18LF8AcPEnesKj4yy3lah5JPwVqwUkQckTXhU">
> 
> Yes, I'm very much aware of Fontawesome's Light icon set, unfortunately this won't work at all within our design system, since we'd need 2px strokes and 2px gaps, and FA Light uses much lighter strokes and allows for much thinner gaps.

Ah ok, thanks 😕

**Comment by jamiemlaw** [comment]
I'm not sure if here, too much detail is lost, and it becomes hard to perceive them as globes, but it still might be possible to suggest continents in the Lucide style.
![lucide-style-globes](https://github.com/lucide-icons/lucide/assets/956081/b0a5bce0-34f2-4539-b0de-ec794a9b24da)

**Comment by bensaine** [comment]
This would definitely be better than having nothing at the moment!

**Comment by jguddas** [comment]
> I'm not sure if here, too much detail is lost, and it becomes hard to perceive them as globes, but it still might be possible to suggest continents in the Lucide style. ![lucide-style-globes](https://private-user-images.githubusercontent.com/956081/320790970-b0a5bce0-34f2-4539-b0de-ec794a9b24da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTg4ODcsIm5iZiI6MTcxMjY5ODU4NywicGF0aCI6Ii85NTYwODEvMzIwNzkwOTcwLWIwYTViY2UwLTM0ZjItNDUzOS1iMGRlLWVjNzk0YTliMjRkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMTM2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzk0ZTgxMjUwODhlMzdlMjNlNzFlOTE0OTU4M2MwNmE2NGI3MDI2NDc5OTBhZTA0ZTQ5NjVlOWJkZDMwNjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p6GYFKKQD_Mn0HEfbtq7fRQEz4pRfWeL8BQY9Lf0zmg)

Those look pretty cute, don't count on me guessing which continents are which tho :P
