### ISSUE TITLE
idea: @deprecated for certain aliases

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#1957]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [X] all JS packages
- [ ] site

### Description

I would love to see aliases that are for example typos get an @deprecated.

Currently, we can only deprecate a whole icon but not an alias.

### Use cases

#1956 thank you @devjayprakash for bringing this to our attention.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by jguddas** [comment]
A solution could be to change the type of the `depracated` field from boolean to array or to add a new field called `depracatedAliases`.

**Comment by karsa-mistmere** [comment]
> A solution could be to change the type of the `depracated` field from boolean to array or to add a new field called `depracatedAliases`.

As I've stated on Discord, this doesn't really suffice, a description should also be provided why this alias was deprecated in the first place and what steps should be taken.

**Comment by jguddas** [comment]
> > A solution could be to change the type of the `deprecated` field from boolean to array or to add a new field called `deprecatedAliases`.
> 
> As I've stated on Discord, this doesn't really suffice, a description should also be provided why this icon/alias was deprecated in the first place and what steps should be taken.

What about this

```json5
{
  name: 'turtle',
  depracated: true,
  depracationReason: "I don't like turtles.",
  aliases: [
    {
      name: 'turdle',
      depracated: true,
      depracationReason: "Spelling mistake.",
    }
  ]
}
```

**Comment by karsa-mistmere** [comment]
Apart from the typos, yeah. We could even keep support for the current version:

```json5
{
  name: 'turtle',
  deprecated: true,
  deprecationReason: "I don't like turtles.",
  aliases: [
    'tortoise',
    {
      name: 'turdle',
      deprecated: true,
      deprecationReason: "Spelling mistake.",
    }
  ]
}
```
