### ISSUE TITLE
lucide-flutter icon not centered

### ISSUE THREAD

**Issue by lushangkan** [lucide-icons/lucide#1958]
### Package

- [ ] lucide
- [ ] lucide-angular
- [X] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.257.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Icon not centered，it's shifted a little to the left.

Lucide icon play:
![image](https://github.com/lucide-icons/lucide/assets/41252325/dbd6acb7-dbd8-4ffe-9d90-3c4f1db31431)

Material icon play_arrow:
![image](https://github.com/lucide-icons/lucide/assets/41252325/38a688a7-c3d1-4ec7-a56f-3cf95e330782)

### Steps to reproduce

1. Add the lucide-flutter dependency.
2. Add a Container with a different color than the background, so that it is easy to see.
3. Add an Icon class wrapped in Center to the Container's Child, and use the lucide icon.
4. You can see that the icon is not centered.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Seems like a CSS issue on your part: https://jsfiddle.net/ogzy2xju/

**Comment by lushangkan** [comment]
> Seems like a CSS issue on your part: https://jsfiddle.net/ogzy2xju/
> 
> Edit: sorry, I didn't see it was for Flutter. Our Flutter package is no longer maintained, although there is an effort to revive it at: https://github.com/lucide-icons/lucide-flutter

This seems to be caused by an irregular font file format, and I found a fix for a similar problem with the [URL](https://github.com/timmaffett/material_symbols_icons/tree/master/rawFontsUnfixed).
Are there any plans in the future to fix this directly in the font file, rather than making a patch specifically for flutter like the URL above?
