### ISSUE TITLE
Code samples does't show in the website

### ISSUE THREAD

**Issue by zaynOm** [lucide-icons/lucide#1965]
### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

All the code samples does not work as you can see in the video, I tried it on both Chrome and Firefox.

https://github.com/lucide-icons/lucide/assets/63248283/79cf7352-db56-4ef2-b0c1-aa5c6dd3aa62

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
What about switching to MDX?

https://mdxjs.com/docs/getting-started/#vue

**Comment by ericfennis** [comment]
@zaynOm thanks for reaching out.

For code example we use Sand Pack from code sandbox. I think something is not going well in that package. I will check.

@jguddas live code examples are different then the rest of the code examples on the website.
