### ISSUE TITLE
Error while using circle-check icon

### ISSUE THREAD

**Issue by pariyar07** [lucide-icons/lucide#1966]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.341.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

It seems the circle-check icon is not available and need to be updated

### Steps to reproduce

Using lucide-react:
- import { CircleCheck } from 'lucide-react';
- You'll get this error - '"lucide-react"' has no exported member named 'CircleCheck'. Did you mean 'FileCheck'?

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Upgrade `lucide-react`, and if you can reproduce this in the newest version, I will reopen this.
