### ISSUE TITLE
Icons are overlapping in Brave browser

### ISSUE THREAD

**Issue by s4shibam** [lucide-icons/lucide#1969]
### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

![image](https://github.com/lucide-icons/lucide/assets/100959421/9561db2e-af07-47e1-a522-1ed331fadee6)

My main web browser of choice is Brave. I have been seeing this view only in Brave for the past few days.

Browser details:
[Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (64-bit)]

### Steps to reproduce

1. Use Brave for browsing
2. Go to https://lucide.dev/icons/

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I also use Brave and cannot reproduce this: 
<img width="1501" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/8dcf1eb1-3fdb-4f64-ab5f-70768ec56d04">

Are you sure you don't have some plugin enabled that wreaks havoc?

**Comment by s4shibam** [comment]
Thanks! 😅
The culprit was an extension. everything is fine now! 👍
