### ISSUE TITLE
lucide is missing icons since 0.352.0

### ISSUE THREAD

**Issue by fxOne** [lucide-icons/lucide#1975]
### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [x] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [x] Other/not relevant

### Description

`lucide@0.352.0` is missing a bunch of icons in the `lucide.d.ts` like `PlusCircle` or `MinusCircle` while they are still available in `lucide-react@0.356.0`.
![image](https://github.com/lucide-icons/lucide/assets/5929640/66cf065a-adec-4384-8411-2be9537c3f63)

I guess that the issue is the namespaced alias export
![image](https://github.com/lucide-icons/lucide/assets/5929640/cc6d3039-9544-42d8-9279-b8ac0b25a998)
__

### Steps to reproduce

install the latest version of lucide and try to import PlusCircle ind a TypeScript file.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
352 is older than 356, are you sure you didn't mix up the versions when testing or writing the description?

**Comment by karsa-mistmere** [comment]
Hey @fxOne, thanks for bringing this to our attention. We seem to have forgotten to add the aliases as direct exports when implementing the aliases feature, I've just fixed this, please let me know if v0.357.0 has resolved your issue.

**Comment by fxOne** [comment]
@karsa-mistmere thanks for the quick fix, now everything works perfectly again
