### ISSUE TITLE
[ICON REQUEST] Straight plane icon

### ISSUE THREAD

**Issue by ruymon** [lucide-icons/lucide#1977]
### Icon name

plane-straight

### Use cases

A straight version of the current plane icon to be used in maps without having to calculate the tilt correction.

### Design ideas

Use the existing icon (https://lucide.dev/icons/plane) only make it straight LOL.

> [!NOTE]  
> Consider renaming the current plane icon to `plane-tilt` and this new icon to only `plane`. It seems to me like a better DX.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
That's such a fun use case.

To justify adding a variation of an icon you we need a stronger and distinct use case, better DX just doesn't cut it.

**Comment by ruymon** [comment]
Fair enough, I'll provide a solid example of a use-case: I'm developing a flight tracking app where I display planes on a map using icons that rotate according to each plane's heading. The current icon has a default tilt, so I had to create a straight version of it in Figma. To clarify, manually creating the upright icon is functional, but I believe there are others facing the same issue, and including a non-tilted version in Lucide would be advantageous for everyone. 

I kindly request reconsideration of this issue based on the points raised.

**Comment by karsa-mistmere** [comment]
> > That's such a fun use case.
> > To justify adding a variation of an icon, we need a stronger and distinct use case, better DX just doesn't cut it.
> 
> @jguddas
> 
> Fair enough, I'll provide a solid example of a use-case: I'm developing a flight tracking app where I display planes on a map using icons that rotate according to each plane's heading. The current icon has a default tilt, so I had to create a straight version of it in Figma. To clarify, manually creating the upright icon is functional, but I believe there are others facing the same issue, and including a non-tilted version in Lucide would be advantageous for everyone.
> 
> I kindly request reconsideration of this issue based on the points raised.

I'm not really convinced yet, for this purpose, wouldn't it make much more sense to simply rotate the icons via CSS transforms? 🤔

**Comment by ruymon** [comment]
> > > That's such a fun use case.
> > > To justify adding a variation of an icon, we need a stronger and distinct use case, better DX just doesn't cut it.
> > 
> > 
> > @jguddas
> > Fair enough, I'll provide a solid example of a use-case: I'm developing a flight tracking app where I display planes on a map using icons that rotate according to each plane's heading. The current icon has a default tilt, so I had to create a straight version of it in Figma. To clarify, manually creating the upright icon is functional, but I believe there are others facing the same issue, and including a non-tilted version in Lucide would be advantageous for everyone.
> > I kindly request reconsideration of this issue based on the points raised.
> 
> I'm not really convinced yet, for this purpose, wouldn't it make much more sense to simply rotate the icons via CSS transforms? 🤔

Rotating it 45deg doesn't align it 100% (something to do with the icon's grid)... Hence, no.

**Comment by jguddas** [comment]
> > > > That's such a fun use case.
> > > > To justify adding a variation of an icon, we need a stronger and distinct use case, better DX just doesn't cut it.
> > > 
> > > 
> > > @jguddas
> > > Fair enough, I'll provide a solid example of a use-case: I'm developing a flight tracking app where I display planes on a map using icons that rotate according to each plane's heading. The current icon has a default tilt, so I had to create a straight version of it in Figma. To clarify, manually creating the upright icon is functional, but I believe there are others facing the same issue, and including a non-tilted version in Lucide would be advantageous for everyone.
> > > I kindly request reconsideration of this issue based on the points raised.
> > 
> > 
> > I'm not really convinced yet, for this purpose, wouldn't it make much more sense to simply rotate the icons via CSS transforms? 🤔
> 
> Rotating it 45deg doesn't align it 100% (something to do with the icon's grid)... Hence, no.

Looks pretty straight to me https://jsbin.com/locafotatu
