### ISSUE TITLE
Balls icons of sports like basketball, football (soccer), volleyball...

### ISSUE THREAD

**Issue by eliabexp** [lucide-icons/lucide#1978]
### Icon name

basketball, volleyball, soccer-ball, tennis-ball

### Use cases

I want to use this icons to refer to those sports
Lucide doesn't have any ball icon yet

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/74092305/d4918359-9b4d-459a-840a-13d312d15bd8)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
All those icons exist in the lab branch

**Comment by eliabexp** [comment]
Oh, I just have noticed this. Thank you, gonna close the issue

**Comment by tmolitor002** [comment]
would also like to see all of these, as well as some other sports related icons such as:
- Football (American)
- Hockey
- Stadium
- Field
- Swimming/Swimmer

- Not a designer, but an Olympic sports series would also be pretty cool.
