### ISSUE TITLE
Cloud Upload does not exist in the react package

### ISSUE THREAD

**Issue by alamenai** [lucide-icons/lucide#1979]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

I used the [CloudUpload](https://lucide.dev/icons/cloud-upload) for the first time and it seems it does not exist in the react package.

I'm using the last version of `react-lucide`, though the cloud upload icons have existed since the first version.

### Steps to reproduce

1. Copy the JSX name
2. Paste it in the code

## Code

```tsx

import Image from "next/image"
import { useState } from "react"
import { Fragment } from "react"

import { Card, CardContent, CardDescription } from "@/components/ui/card"

export const UploadReport = () => {
  const [file, setFile] = useState<File>()

  const uploadReport = () => {}

  return (
    <Card
      className='flex items-center justify-center  p-0 w-full h-36 cursor-pointer hover:bg-slate-50'
      onClick={uploadReport}
    >
      <CardContent className='relative flex flex-col p-0 mb-0 items-center justify-center w-full h-full'>
        {file ? (
          <p>{file.name}</p> //   <Image src={imageURLs?.get("roof") as string} alt='image' layout='fill' objectFit='contain' />
        ) : (
          <Fragment>
          <CloudUpload />
            <CardDescription className='text-xs mt-4'>Bilder von Dach</CardDescription>
          </Fragment>
        )}
      </CardContent>
    </Card>
  )
}

```

### Screenshots

![image](https://github.com/lucide-icons/lucide/assets/20143684/d5498dde-22f2-437b-bcd4-342be7eea305)

![image](https://github.com/lucide-icons/lucide/assets/20143684/e0d9a651-2f0e-48af-b1b7-4e11161bf3e9)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
@alamenai On which version are you from `lucide-react`?

**Comment by karsa-mistmere** [comment]
Hi @alamenai, `CloudUpload` has recently been renamed from `UploadCloud`, since you haven't told us which version of lucide-react you're using, I'm having to assume that you're using an older version, so please either update to the latest one of use the old alias.
