### ISSUE TITLE
Lucide icons error when deploying to vercel

### ISSUE THREAD

**Issue by simond07** [lucide-icons/lucide#1986]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.358.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

When i'm directly import an icon
```svelte
<script lang="ts">
    import Sun from 'lucide-svelte/icons/Sun';
</script>

<Sun />
```
and deploy this to vercel, the build fails and gives the following error and hint on vercel:
```
Error: [vite]: Rollup failed to resolve import "lucide-svelte/icons/Sun" from "/vercel/path0/src/routes/+layout.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to `build.rollupOptions.external`
```
The error is resolved when indirectly importing the icon with
```svelte
<script lang="ts">
    import { Sun } from 'lucide-svelte';
</script>

<Sun />
```
But then the dev server build time is too long.
This maybe related to #1513 but this is a completly different error and the issue is using react.
I didn't try the hint from vercel, but I think it should not be necessary to deal with this error.

### Steps to reproduce

```svelte
<script lang="ts">
    import Sun from 'lucide-svelte/icons/Sun';
</script>

<Sun />
```
Deploy this to vercel.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I'm not able to check right now, but I believe you have to use the lower-kebab-case names when importing a single icon, so it should be `from "lucide-svelte/icons/sun"`.

**Comment by simond07** [comment]
Great, that solves the problem. Thank you. I didn't consider the camel-case as the potential problem.
Btw beautiful icons :)
