### ISSUE TITLE
Typescript shows `disabled` prop does not exists but still works displaying disabled color

### ISSUE THREAD

**Issue by deathemperor** [lucide-icons/lucide#1994]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.358.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Typescript shows `disabled` prop does not exists but still works displaying disabled color

### Steps to reproduce

Code:

```ts
<ZoomIn className="anticon" disabled={scale === 50} onClick={onZoomIn} size={20} />
```

Error:

```
Type '{ className: string; disabled: boolean; onClick: () => void; size: number; }' is not assignable to type 'IntrinsicAttributes & LucideProps'.
  Property 'disabled' does not exist on type 'IntrinsicAttributes & LucideProps'.
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
What do you mean by "disabled color"?

**Comment by MateoWartelle** [comment]
Isnt only these [props](https://lucide.dev/guide/packages/lucide-react#props) + any SVG props? Disabled is not listed.

**Comment by deathemperor** [comment]
> What do you mean by "disabled color"?

@karsa-mistmere the 2 left ones have "disabled color" which is less bright than the rightest one.

<img width="197" alt="image" src="https://github.com/lucide-icons/lucide/assets/4255482/acca3d96-b756-4a9e-8786-30b2225ad7a1">

**Comment by karsa-mistmere** [comment]
> > What do you mean by "disabled color"?
> 
> @karsa-mistmere the 2 left ones have "disabled color" which is less bright than the rightest one.
> 
> <img alt="image" width="197" src="https://private-user-images.githubusercontent.com/4255482/313542022-acca3d96-b756-4a9e-8786-30b2225ad7a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDMxMTQsIm5iZiI6MTcxMDc0MjgxNCwicGF0aCI6Ii80MjU1NDgyLzMxMzU0MjAyMi1hY2NhM2Q5Ni1iNzU2LTRhOWUtODc4Ni0zMGIyMjI1YWQ3YTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMDYyMDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA0YzhlMTU1YzIyMmU4ZWQxYjdiYzNkYTc2MTViNmIzMDJjOTUwMTI3YzEyNmM5MjFmYWUyM2Y1M2MxZGM4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.S-FlAKH5S1i6dk1DT-F-t3wR_1IFvhLzHThPcEtK80k">

Sorry, what I really meant is can you check what CSS declarations set this so called "disabled color", because Lucide has no such styling.

**Comment by deathemperor** [comment]
thanks for the question, I checked and it's a css in our stylesheet that does the job. sorry for the trouble, closing this now.

**Comment by karsa-mistmere** [comment]
> thanks for the question, I checked and it's a css in our stylesheet that does the job. sorry for the trouble, closing this now.

Yeah, I had a hunch it might have been that.
Be aware though, that `disabled` is not a valid property on `<svg>` elements: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#d
(That's why you get the error.)
