### ISSUE TITLE
Handshake icon is missing in lucide-react

### ISSUE THREAD

**Issue by kenn** [lucide-icons/lucide#1995]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.294.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

[Handshake](https://lucide.dev/icons/handshake) icon is missing.

Note that [HeartHandshake](https://lucide.dev/icons/heart-handshake) exists.

### Steps to reproduce

```ts
import { Handshake } from 'lucide-react'
=> Module '"lucide-react"' has no exported member 'Handshake'.
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
You need to update, as the site indicates, `handshake` was only added in v0.321.0

![image](https://github.com/lucide-icons/lucide/assets/17746067/0461b929-9b27-4ca0-8f56-bc635daa9dd7)

**Comment by kenn** [comment]
Ahh thanks! Somehow I assumed it was created before [HeartHandshake](https://lucide.dev/icons/heart-handshake) :)
