### ISSUE TITLE
Naming of certain icons is not coherent with the name on the website

### ISSUE THREAD

**Issue by cluk3** [lucide-icons/lucide#1996]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.344.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

When I look for a icon I need I go on the website search and when I find the icon name I expect the export to have same name the icon has on the website only CamelCased instead of kebab-cased. This works most of the times but sometimes it doesn't.
One example is the `Ellipsis` icon which is exported within its alias `More`. On the website I couldn't find any reference of the alias, so I had to find it out myself by going in the node module and open the json file.
I would expect the Icon to be exported with the name of the file AND  with the name of the alias, or at least for the alias to be referenced on the website

### Steps to reproduce

Try to import Ellipsis icon

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
`import { Ellipsis } from 'lucide-react'` works just fine.

**Comment by karsa-mistmere** [comment]
Please upgrade to the latest package.

**Comment by ajzbc** [comment]
Running into the same problem with `lucide-svelte` not exporting `Ellipsis`

Using `0.365.0`

**Comment by karsa-mistmere** [comment]
> Running into the same problem with `lucide-svelte` not exporting `Ellipsis`
> 
> Using `0.365.0`

I can definitely see it exported and can import it. Can you check if removing `node_modules` and reinstalling works?
![image](https://github.com/lucide-icons/lucide/assets/17746067/32c3a00f-4e12-4440-a524-0160e4cc9227)

**Comment by justuskilianwolff** [comment]
@karsa-mistmere I deleted my `node_modules`dir and ran `npm install`, `npm update`but still can't find ellipsis. That line you highlighted is not found in my aliases.d.ts. I am running 
```
"node_modules/lucide-svelte": {
			"version": "0.316.0",
			"resolved": "https://registry.npmjs.org/lucide-svelte/-/lucide-svelte-0.316.0.tgz",
			"integrity": "sha512-6mtBw/aU1IIVXfN6AXLSwsbeCFX/2/tTy84rrDTDsOq7BEijFbvObQsPEWPxJ0EyCjUXOYfAvfkZzMosYjyGqA==",
			"peerDependencies": {
				"svelte": ">=3 <5"
			}
		},
```

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere I deleted my `node_modules`dir and ran `npm install`, `npm update`but still can't find ellipsis. That line you highlighted is not found in my aliases.d.ts. I am running
> 
> ```
> "node_modules/lucide-svelte": {
> 			"version": "0.316.0",
> 			"resolved": "https://registry.npmjs.org/lucide-svelte/-/lucide-svelte-0.316.0.tgz",
> 			"integrity": "sha512-6mtBw/aU1IIVXfN6AXLSwsbeCFX/2/tTy84rrDTDsOq7BEijFbvObQsPEWPxJ0EyCjUXOYfAvfkZzMosYjyGqA==",
> 			"peerDependencies": {
> 				"svelte": ">=3 <5"
> 			}
> 		},
> ```
> 
> Also the paths look different in my version? ![Screenshot 2024-04-07 at 13 05 54](https://private-user-images.githubusercontent.com/41119166/320276329-25ebadd4-928d-403b-86d7-50a0f10ed39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODgyOTEsIm5iZiI6MTcxMjQ4Nzk5MSwicGF0aCI6Ii80MTExOTE2Ni8zMjAyNzYzMjktMjVlYmFkZDQtOTI4ZC00MDNiLTg2ZDctNTBhMGYxMGVkMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTU5NjlkNWM3YmRmMzg2MDQ4NzhjOTE3NTIyZWVlMzMwZjhkZjFhYzI5Y2I5NjljNGUxZTE0NzdhMmUzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5Cv8VRM3zTkeojw-BMHHqgOFksFHPukDA0kqg18i7U)

Please upgrade, you're like 50 subversions behind.

**Comment by justuskilianwolff** [comment]
> > @karsa-mistmere I deleted my `node_modules`dir and ran `npm install`, `npm update`but still can't find ellipsis. That line you highlighted is not found in my aliases.d.ts. I am running
> > ```
> > "node_modules/lucide-svelte": {
> > 			"version": "0.316.0",
> > 			"resolved": "https://registry.npmjs.org/lucide-svelte/-/lucide-svelte-0.316.0.tgz",
> > 			"integrity": "sha512-6mtBw/aU1IIVXfN6AXLSwsbeCFX/2/tTy84rrDTDsOq7BEijFbvObQsPEWPxJ0EyCjUXOYfAvfkZzMosYjyGqA==",
> > 			"peerDependencies": {
> > 				"svelte": ">=3 <5"
> > 			}
> > 		},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also the paths look different in my version? ![Screenshot 2024-04-07 at 13 05 54](https://private-user-images.githubusercontent.com/41119166/320276329-25ebadd4-928d-403b-86d7-50a0f10ed39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODgyOTEsIm5iZiI6MTcxMjQ4Nzk5MSwicGF0aCI6Ii80MTExOTE2Ni8zMjAyNzYzMjktMjVlYmFkZDQtOTI4ZC00MDNiLTg2ZDctNTBhMGYxMGVkMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTU5NjlkNWM3YmRmMzg2MDQ4NzhjOTE3NTIyZWVlMzMwZjhkZjFhYzI5Y2I5NjljNGUxZTE0NzdhMmUzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5Cv8VRM3zTkeojw-BMHHqgOFksFHPukDA0kqg18i7U)
> 
> Please upgrade, you're like 50 subversions behind. And `Ellipses` is exported from `icons.ts`, not `aliases.ts`.


It's probably my limited npm and svelte knowledge, however, I did upgrade and  and still can't find it...
![Screenshot 2024-04-07 at 13 17 56](https://github.com/lucide-icons/lucide/assets/41119166/5256d6be-100e-41fc-b80f-ed26bb3c4eb1)
I'd appreciate any additional hint (above is my file structure after again deleting the modules and reinstalling with 0.365.0).

**Comment by karsa-mistmere** [comment]
> > > @karsa-mistmere I deleted my `node_modules`dir and ran `npm install`, `npm update`but still can't find ellipsis. That line you highlighted is not found in my aliases.d.ts. I am running
> > > ```
> > > "node_modules/lucide-svelte": {
> > > 			"version": "0.316.0",
> > > 			"resolved": "https://registry.npmjs.org/lucide-svelte/-/lucide-svelte-0.316.0.tgz",
> > > 			"integrity": "sha512-6mtBw/aU1IIVXfN6AXLSwsbeCFX/2/tTy84rrDTDsOq7BEijFbvObQsPEWPxJ0EyCjUXOYfAvfkZzMosYjyGqA==",
> > > 			"peerDependencies": {
> > > 				"svelte": ">=3 <5"
> > > 			}
> > > 		},
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also the paths look different in my version? ![Screenshot 2024-04-07 at 13 05 54](https://private-user-images.githubusercontent.com/41119166/320276329-25ebadd4-928d-403b-86d7-50a0f10ed39b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODgyOTEsIm5iZiI6MTcxMjQ4Nzk5MSwicGF0aCI6Ii80MTExOTE2Ni8zMjAyNzYzMjktMjVlYmFkZDQtOTI4ZC00MDNiLTg2ZDctNTBhMGYxMGVkMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTU5NjlkNWM3YmRmMzg2MDQ4NzhjOTE3NTIyZWVlMzMwZjhkZjFhYzI5Y2I5NjljNGUxZTE0NzdhMmUzMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5Cv8VRM3zTkeojw-BMHHqgOFksFHPukDA0kqg18i7U)
> > 
> > 
> > Please upgrade, you're like 50 subversions behind. And `Ellipses` is exported from `icons.ts`, not `aliases.ts`.
> 
> It's probably my limited npm and svelte knowledge, however, I did upgrade and and still can't find it... ![Screenshot 2024-04-07 at 13 17 56](https://private-user-images.githubusercontent.com/41119166/320276970-5256d6be-100e-41fc-b80f-ed26bb3c4eb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODk0NjIsIm5iZiI6MTcxMjQ4OTE2MiwicGF0aCI6Ii80MTExOTE2Ni8zMjAyNzY5NzAtNTI1NmQ2YmUtMTAwZS00MWZjLWI4MGYtZWQyNmJiM2M0ZWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODBmNDk2ZDU1NWRmNmI0NWVjMmYxMGUxYzVjZTQ1ZjJlNzczZDRjZWE2NzQ1ZmI2YTM5MWEzYWIxNzE5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uaHgm8oMP4R6cxQq4vnprRYtaNj1q7k32-0ffNkHWzo) I'd appreciate any additional hint (above is my file structure after again deleting the modules and reinstalling with 0.365.0).
> 
> ![Screenshot 2024-04-07 at 13 20 36](https://private-user-images.githubusercontent.com/41119166/320277112-7a808d8d-7f72-47ac-b367-14a15d1e9f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODk0NjIsIm5iZiI6MTcxMjQ4OTE2MiwicGF0aCI6Ii80MTExOTE2Ni8zMjAyNzcxMTItN2E4MDhkOGQtN2Y3Mi00N2FjLWIzNjctMTRhMTVkMWU5ZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDYzOWY3NDA5NDdmZDk3ZjgyNWYxZDc5OWM3YWM3ZDgxMGEyNzkxOWMxOWNlMjRkOWIxOGNjYTRjZjI2ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-S5q6SJSxVorgmRJSjYzfAatlngt8eFUT19kGfgrW0)

It's within the icons folder.
