### ISSUE TITLE
Incorrect JSX name for ArrowUpRightFromSquareIcon

### ISSUE THREAD

**Issue by busybox11** [lucide-icons/lucide#2023]
### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

The defined JSX for `square-arrow-out-up-right` is wrong.
The website copies it as `<SquareArrowOutUpRight />`, but it is exported in `lucide-react` as `<ArrowUpRightFromSquare />`.

<img width="2056" alt="image" src="https://github.com/lucide-icons/lucide/assets/29630035/99d32da0-77b0-43ef-90ec-8dec64935384">

### Steps to reproduce

1) Search for `square-arrow-out-up-right`
2) Select the icon and click "Copy JSX"
3) The import will not resolve using `lucide-react`.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Update the package, and let me know if that fixes it.

**Comment by busybox11** [comment]
I am already on the latest version - I have already checked this, and it does not work with it (`lucide-react@0.363.0`).
<img width="223" alt="image" src="https://github.com/lucide-icons/lucide/assets/29630035/28f45e10-8b56-40fd-a908-992cf4d4d0e2">

Is there an ongoing update? This is also the same version reported by GitHub.

**Comment by jguddas** [comment]
Weird, it's there for me.

<img width="841" alt="image" src="https://github.com/lucide-icons/lucide/assets/25524993/7a56ce6c-6610-4b3f-a3ac-5810624507cf">

https://www.npmjs.com/package/lucide-react?activeTab=code

**Comment by busybox11** [comment]
Huh, installing the package again on another project does export it. No idea what happened here, I swear it wasn't there - maybe some module caching issue.. My apologies!
