### ISSUE TITLE
Arm muscle / strong bicep 💪 

### ISSUE THREAD

**Issue by SurSerious** [lucide-icons/lucide#2027]
### Icon name

Strong arm flexing 

### Use cases

As a way to depict strength, for a callout reminding to be strong/courageous, to be an apt icon for fitness/gym advice, to emphasize a key point, highlight a significant idea or concept. Similar designs are commonly apart of other emoji/icon packs. 

### Design ideas

![Screenshot_20240401_032125_Brave](https://github.com/lucide-icons/lucide/assets/157259511/da934f0a-a1ed-46f9-968d-a321944f0787)
![Screenshot_20240401_032257_Brave](https://github.com/lucide-icons/lucide/assets/157259511/a5d2b748-7314-4a69-8299-e54645d387ee)

Specifically, the outline one, for a key example (link to it in case it doesn't load https://iconscout.com/icon/arm-3807920) 

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by SurSerious** [comment]
Question: If I make an svg that's the same as the outline one, would it be able to be accepted? Idk how (I'm on a tablet), but if I did, would it be?

**Comment by jguddas** [comment]
> Question: If I make an svg that's the same as the outline one, would it be able to be accepted? Idk how (I'm on a tablet), but if I did, would it be?

You need to follow the guidelines: https://lucide.dev/guide/design/icon-design-guide

You can also ask in the discord for help.

**Comment by karsa-mistmere** [comment]
Here's a rough draft: 
![image](https://github.com/lucide-icons/lucide/assets/17746067/15ed5332-6bff-4ce1-b460-3ba4a4d81391)

**Comment by SurSerious** [comment]
I appreciate that demo, I'd be happy with that. I made this, It seems like the lines are doubled for some reason? Hopefully, this helps someone who is skilled enough to fix and lucidify it

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"><path d="M10.016 5.922a6 6 0 0 0 .199-.621m0 0A.325.325 0 0 0 9.652 5m5.411 7.633c-1.766-.754-3.5-.61-5.536.449m5.856-.312-.32-.137m.843-.215-.523.352m1.023 1.39c.555.356.645.375.828.195m-.656-.93c-.543-.308-.543-.304.3-.741m0 0c1.708-.88 3.446-1.2 4.884-.891m-4.528 2.562c.258-.257.086-.511-.656-.93m4.301-2.441c-1.719-.082-3.469.422-4.973 1.434m5.856-.625c.765.164.855.16.957-.031"/><path d="M22.719 11.762c.234-.438-.414-.715-1.84-.778M6.641 15.441c.199.2.132.23 1.687-.796M7.5 13.5c-.808.55-1.129 1.672-.859 1.941m1.687-.796c3.332-2.207 5.235-2.325 8.078-.485m-7.73-.781c.133-.34.386-1.8.644-3.691M8.766 8.48c-.618 4.66-.836 5.551-1.493 5.997M9.32 9.688c.325-2.36.47-3.153.696-3.766m-.489 7.16c-.945.492-.921.484-.851.297M9.652 5c-.304.305-.644 1.633-.886 3.48m4.836 9.915c1.34-.137 1.918-.344 1.918-.676 0-.36-.18-.399-.95-.211-1.48.363-2.863.21-4.324-.477-.902-.425-.98-.449-1.121-.273-.602.723 2.469 1.848 4.477 1.637"/><path d="M20.023 21.016c1.137 1.101 2.446 1.695 2.696 1.222q.198-.369-.477-.597c-.687-.23-1.285-.7-2.414-1.887-1.379-1.465-2.137-1.91-2.668-1.563-.367.243-.23.493.352.645.414.113 1.261.68 1.347.906.059.156-.05.219-1.164.582-5.175 1.695-8.847 1.281-13.894-1.566-2.032-1.149-2.078-1.215-1.883-2.805a165 165 0 0 0 .168-1.543c.242-2.406.855-3.61 4.426-8.676A132 132 0 0 0 8.43 2.945c.992-1.515.847-1.457 3.664-1.492 1.379-.016 2.27.004 2.363.055.262.14 1.336 2.316 1.242 2.52-.156.331-1.015 1.195-1.336 1.34-.863.398-1.492.148-3.336-1.306-.687-.539-.906-.628-1.09-.445-.167.168-.105.36.227.656 2.508 2.266 4.09 2.532 5.535.918.946-1.046.957-1.16.29-2.492-.735-1.472-.962-1.793-1.325-1.894-.281-.078-3.945-.106-4.543-.032-1.055.121-1.375.391-2.508 2.09a178 178 0 0 1-2.261 3.278c-3.266 4.625-3.774 5.722-4.075 8.898-.273 2.863-.277 2.848 1.364 3.875 5.468 3.43 10.382 3.988 16.062 1.824l.149-.056a1 1 0 0 1 1.049.216z"/></svg>

**Comment by SurSerious** [comment]
> Here's a rough draft of how this could work within Lucide's guidelines: 
> ![image](https://github.com/lucide-icons/lucide/assets/17746067/15ed5332-6bff-4ce1-b460-3ba4a4d81391)
> 

Could you add this to the pack?
