### ISSUE TITLE
Pipe/Vertical Line Icon

### ISSUE THREAD

**Issue by radeeyate** [lucide-icons/lucide#2031]
### Icon name

vertical-line, pipe

### Use cases

I need to separate sections on my navigation bar.

### Design ideas

It should look like a pipe symbol (|). It would be similair to `tally-1`, but centered horizontally.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Hi @radeeyate, can you come up with some alternate use cases? This one feels a bit weak, normally you would use borders, dividers or pseudoelements for such a task as they are much easier to style.

**Comment by radeeyate** [comment]
These are the other use cases I can come up with:
- Music notation (would be use do separate measures)
- Not sure how to explain this one, but see the video.
[Screencast from 04-03-2024 04:21:00 AM.webm](https://github.com/lucide-icons/lucide/assets/124477460/b8e5f4ed-c415-463c-9544-29778cc0cd01)
- Indicators for drag and drop editors (similar to discord has a horizontal green line indicator when moving channels)
![image](https://github.com/lucide-icons/lucide/assets/124477460/770be377-5560-455e-931e-1acbe532c403)

**Comment by radeeyate** [comment]
That's completely fair. I am just thinking that it would fit better than how I currently am separating navbar sections:
![image](https://github.com/lucide-icons/lucide/assets/124477460/1256344b-c25d-49da-9813-c7096db4f7af)

**Comment by karsa-mistmere** [comment]
I think in such a scenario it's even preferable for the divider to have a completely distinct style so as it's not mistaken for an icon or any other interactive element, e.g.:
![image](https://github.com/lucide-icons/lucide/assets/17746067/fcfea856-0fd0-420a-8212-c89189d1504a)

**Comment by karsa-mistmere** [comment]
Also correlate with GitHub's own editor toolbar:
<img width="547" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/3e733fe8-bf2d-4e32-b2a9-b6dbb84d3c24">

**Comment by radeeyate** [comment]
That's fair, thank you for the suggestion.
