### ISSUE TITLE
GIF icon

### ISSUE THREAD

**Issue by fatihsever** [lucide-icons/lucide#2041]
### Icon name

gif

### Use cases

- Social media post forms (for example Twitter or Threads post form has button with GIF icon)
- Text editors may have GIF buttons
- Comment boxes may have GIF buttons

### Design ideas

It can be a document icon with a GIF text, like in Threads. The [sticky-note](https://lucide.dev/icons/sticky-note) icon might be suitable. 
Something like this:
https://www.canva.com/design/DAGBW0PgKFc/9m4FjFpI1R88F_Arcnmksw/edit?utm_content=DAGBW0PgKFc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
There just isn't enough space for a border, but just the text is possible to do in a Lucide style:
![image](https://github.com/lucide-icons/lucide/assets/17746067/9f2ead6c-b6db-4b8a-b618-9b7db6445b00)

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13+16V8%22+/%3E%3Cpath+d=%22M17+12h3%22+/%3E%3Cpath+d=%22M17+16V8h5%22+/%3E%3Cpath+d=%22M7+12h2v2.646A4+4+0+1+1+6+8h2.5%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMgMTZWOCIgLz4KICA8cGF0aCBkPSJNMTcgMTJoMyIgLz4KICA8cGF0aCBkPSJNMTcgMTZWOGg1IiAvPgogIDxwYXRoIGQ9Ik03IDEyaDJ2Mi42NDZBNCA0IDAgMSAxIDYgOGgyLjUiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by fatihsever** [comment]
So how about adding a triangle shape (play) to the image icon?
For example, let's imagine that it is a triangle shape (like [square-play](https://lucide.dev/icons/square-play)) instead of the arrow shape in the [image-up](https://lucide.dev/icons/image-up) icon?

**Comment by karsa-mistmere** [comment]
Bottom left seems to be the only corner we can fit it into without any guideline violations: 
![image](https://github.com/lucide-icons/lucide/assets/17746067/d542fbfe-b69b-47f3-b145-c2d7da70866d)

**Comment by jguddas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m11+16-5+5%22+/%3E%3Cpath+d=%22M11+21H5a2+2+0+0+1-2-2V5a2+2+0+0+1+2-2h14a2+2+0+0+1+2+2v6.5%22+/%3E%3Cpath+d=%22M15.765+22a.5.5+0+0+1-.765-.424V13.38a.5.5+0+0+1+.765-.424l5.878+3.674a1+1+0+0+1+0+1.696z%22+/%3E%3Ccircle+cx=%229%22+cy=%229%22+r=%222%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTEgMTYtNSA1IiAvPgogIDxwYXRoIGQ9Ik0xMSAyMUg1YTIgMiAwIDAgMS0yLTJWNWEyIDIgMCAwIDEgMi0yaDE0YTIgMiAwIDAgMSAyIDJ2Ni41IiAvPgogIDxwYXRoIGQ9Ik0xNS43NjUgMjJhLjUuNSAwIDAgMS0uNzY1LS40MjRWMTMuMzhhLjUuNSAwIDAgMSAuNzY1LS40MjRsNS44NzggMy42NzRhMSAxIDAgMCAxIDAgMS42OTZ6IiAvPgogIDxjaXJjbGUgY3g9IjkiIGN5PSI5IiByPSIyIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

**Comment by fatihsever** [comment]
Both are pretty good. You decide. Thanks a lot.

**Comment by jguddas** [comment]
We can also flip the image icon and have the play icon on the right still.
