### ISSUE TITLE
[feat ⚡️] Discord Server icon 🐸

### ISSUE THREAD

**Issue by devlopersabbir** [lucide-icons/lucide#2042]
### Icon name

Discord

### Use cases

Since discord icon is missing so, I think we should add that icon the 

### Design ideas

We can simply copy the discord logo as correctly have

**Here is an image example**
![image](https://github.com/lucide-icons/lucide/assets/82939905/2bf9703f-d324-43f9-b7a8-a68ce4be6c1c)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
#670
