### ISSUE TITLE
Earth Icon does not exist

### ISSUE THREAD

**Issue by TanishqSharma2022** [lucide-icons/lucide#2056]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.289.1

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

The Earth and EarthLock icons do not exist in the library. They are at the website but no export exists.on

### Steps to reproduce

1. Import <Earth /> and <EarthLock /> from 'lucide-react'

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
`earth` was renamed from `globe-2` in [v0.341.0](https://github.com/lucide-icons/lucide/releases/tag/0.341.0), please upgrade.

**Comment by TanishqSharma2022** [comment]
<img width="1440" alt="Screenshot 2024-04-10 at 9 27 58 PM" src="https://github.com/lucide-icons/lucide/assets/123730739/a925e41f-7a46-4df0-839b-33bc660aa3b5">
I think they both are different

**Comment by karsa-mistmere** [comment]
In anyway, please upgrade and see if the "error" persists.
