### ISSUE TITLE
[icon request] calendar-repeat

### ISSUE THREAD

**Issue by Reund0** [lucide-icons/lucide#2071]
### Icon name

calendar-repeat

### Use cases

I need this icon to use it for `recurring events` like for example daily or weekly discount events.
it also
Here are some more use cases for a recurring events icon, in addition to daily or weekly discount events:
* **Cron jobs scheduling:** This could be scheduling a recurring job to handle invalid urls in database.
* **Recurring Events or Limited time offers or promotions:**  This could be a flash sale, a seasonal promotion, or a free trial offer.
* **Tasks or reminders that need to be repeated:** This could be taking medication, watering plants, or walking the dog.
* **Loan auto periodic payment** This could be for handling loan installments as reminder or auto.

### Design ideas

it can be done with combining the `calendar` icon and `repeat-2` icon. I wanted to do it myself but had some problem with size of both icons so I made this request.

somehow related to this [issue #1427](https://github.com/lucide-icons/lucide/issues/1427)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
I think `calendar-sync` could be good for this.

https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m+12,13.500048+1.535,-1.605+a+5,5+0+0+1+8,1.5%22+/%3E%3Cpath+d=%22m+12,9.500048+v+4+h+4%22+/%3E%3Cpath+d=%22m+22,17.500048+-1.535,1.605+a+5,5+0+0+1+-8,-1.5%22+/%3E%3Cpath+d=%22m+22,21.500048+v+-4+h+-4%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22M21+7.5V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h3.5%22+/%3E%3Cpath+d=%22M3+10h5%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E

**Comment by ericfennis** [comment]
@chessurisme Would you like to make a PR with your design?

**Comment by ericfennis** [comment]
@chessurisme Awesome!
