### ISSUE TITLE
'square-arrow-up-right' not loading

### ISSUE THREAD

**Issue by vexkiddy** [lucide-icons/lucide#2072]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.321.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

When I try to import `SquareArrowUpRight` in my svelte component I get this error in the console and the app fails to compile and load. Without importing it the app works fine.

```
app.js:30 SyntaxError: The requested module '/node_modules/.vite/deps/lucide-svelte.js?v=e67062dc' does not provide an export named 'SquareArrowUpRight' (at EventCard.svelte:2:40)
events:3364 ERR_SVELTE_HYDRATION_MISMATCH: Hydration failed because the initial UI does not match what was rendered on the server. DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Module.child (http://localhost:4000/node_modules/.vite/deps/chunk-TR3HW3QC.js?v=e67062dc:150:12)
    at Error (http://localhost:4000/node_modules/@sveltejs/kit/src/runtime/components/error.svelte?v=e67062dc:29:17)
    at http://localhost:4000/.svelte-kit/generated/root.svelte:88:45
    at Module.validate_dynamic_component (http://localhost:4000/node_modules/.vite/deps/chunk-5GYOHR6R.js?v=e67062dc:1980:22)
    at http://localhost:4000/.svelte-kit/generated/root.svelte:86:12
    at http://localhost:4000/node_modules/.vite/deps/chunk-TR3HW3QC.js?v=e67062dc:2823:11
    at execute_signal_fn (http://localhost:4000/node_modules/.vite/deps/chunk-5GYOHR6R.js?v=e67062dc:529:7)
    at execute_effect (http://localhost:4000/node_modules/.vite/deps/chunk-5GYOHR6R.js?v=e67062dc:658:31)
    at schedule_effect (http://localhost:4000/node_modules/.vite/deps/chunk-5GYOHR6R.js?v=e67062dc:733:7)
    at internal_create_effect (http://localhost:4000/node_modules/.vite/deps/chunk-5GYOHR6R.js?v=e67062dc:1238:5)
```

### Steps to reproduce

1. Import `SquareArrowUpRight` into a svelte component
2. Run the project with `npm run dev`
3. See errors in console and application fail to build

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by vexkiddy** [comment]
just adding to this, but it looks '`SquareArrowOutUpRight`' also causes issues, maybe its worth checking all of these ones ?

**Comment by karsa-mistmere** [comment]
Upgrade to our latest package, that will solve these issues.

**Comment by vexkiddy** [comment]
hiya @karsa-mistmere as reported, i am on the latest package version. the problems still persist. 

`"lucide-svelte": "^0.368.0"`

**Comment by karsa-mistmere** [comment]
@vexkiddy: Judging from the import path (`/node_modules/.vite/deps/lucide-svelte.js`), you're using a bundled version, make sure to delete the vite cache (`vite clean`).
I can confirm that v0.368.0 correctly exports `SquareArrowUpRight`, so this has something to do with your development environment, [see this codesandbox](https://codesandbox.io/p/devbox/svelte-todo-app-cloud-forked-plc3cp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv0kqrlz00053b6epu7x6n6b%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv0kqrlz00023b6e12khhmxl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv0kqrlz00033b6ettcc0sj9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv0kqrlz00043b6ehpagjfcb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B53.88528690415483%252C46.11471309584517%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv0kqrlz00023b6e12khhmxl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv0kqrlz00013b6er5rfb8if%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv0kqrlz00023b6e12khhmxl%2522%252C%2522activeTabId%2522%253A%2522clv0kqrlz00013b6er5rfb8if%2522%257D%252C%2522clv0kqrlz00043b6ehpagjfcb%2522%253A%257B%2522id%2522%253A%2522clv0kqrlz00043b6ehpagjfcb%2522%252C%2522activeTabId%2522%253A%2522clv0kr5bv00433b6ec20zqziv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clv0kr5bv00433b6ec20zqziv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clv0kqrlz00033b6ettcc0sj9%2522%253A%257B%2522id%2522%253A%2522clv0kqrlz00033b6ettcc0sj9%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clv0kr1sg00343b6ee3k3hozk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clv0kr1sg00343b6ee3k3hozk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by vexkiddy** [comment]
@karsa-mistmere thank you! i'll try and clear my vite cache and see if it sorts out the problem!
