### ISSUE TITLE
[Icon-Request] TV-Play to describe OTT, live TV

### ISSUE THREAD

**Issue by nabanita-sarkar** [lucide-icons/lucide#2075]
### Icon name

tv-play

### Use cases

To denote OTT, live tv etc. 

### Design ideas

Lucide already has a modern tv in `tv-2` and `monitor-play`. I believe simply combining these 2 would do the job perfectly.

<img width="99" alt="image" src="https://github.com/lucide-icons/lucide/assets/36895154/e2e10405-d427-451b-9a1b-c78b432c98fc">

<img width="96" alt="image" src="https://github.com/lucide-icons/lucide/assets/36895154/de05e36b-1bc9-4f3d-a9fd-8af91a368775">

**My proposal would be this**
 
<img width="100" alt="image" src="https://github.com/lucide-icons/lucide/assets/36895154/07bbf995-1910-4ca8-b02e-864d51c53cb1">

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by nabanita-sarkar** [comment]
I have contributed to lucide in the past. If the use case and idea sounds legit, then I can make this. Please let me know of your thoughts @ericfennis

**Comment by jguddas** [comment]
I have #2063 that could affect this.

**Comment by nabanita-sarkar** [comment]
@jguddas Got it. Once that is merged, only then I will go forward

**Comment by ericfennis** [comment]
@nabanita-sarkar Nice request!
