### ISSUE TITLE
[icon-request] blur

### ISSUE THREAD

**Issue by chessurisme** [lucide-icons/lucide#2076]
### Icon name

`blur`

### Use cases

- blurring photos or videos in photo editing or vide editing

### Design ideas

Which is which is better?

![image](https://github.com/lucide-icons/lucide/assets/137697011/96358055-2202-4513-bcd8-709816079761)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
I'm not really a fan of either of these designs. The last one would be the most recognisable, but I'm not really into adding four of those 1px radius circles, especially since we're trying to phase them out of Lucide as a legit design element anyway. 🫤

**Comment by chessurisme** [comment]
Understandable.
