### ISSUE TITLE
icon square-percent has wrong import namein docs

### ISSUE THREAD

**Issue by fedasevich** [lucide-icons/lucide#2077]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.368

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

In official docs site icon named square-percent has wrong name for react
docs:
![image](https://github.com/lucide-icons/lucide/assets/61708790/c27d03f2-4d46-4291-875c-2102be280549)
vsc:
![image](https://github.com/lucide-icons/lucide/assets/61708790/baf42809-c1b0-48d0-bca2-b42030a014f9)

![image](https://github.com/lucide-icons/lucide/assets/61708790/5d963316-01a9-4732-b7df-2af5ae26b482)

### Steps to reproduce

1. Click "Copy jsx" on official docs on https://lucide.dev/icons/square-percent page
2. Paste copied code to IDE
3. The import error appears

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Can you make sure that you're actually on v0.368.0?
I've checked and that version of `lucide-react` very definitely has this export.

**Comment by fedasevich** [comment]
Oh, i'm sorry i checked it up and i had 0.324 installed and it has this problem newest one have it fixed
