### ISSUE TITLE
Find icon by name

### ISSUE THREAD

**Issue by bernaferrari** [lucide-icons/lucide#2091]
### Package

- [X] lucide

### Description

I wish I could do:

```ts
if (iconStr in icons) {
  return icons[iconStr];
}
```
or
```ts
icons.findName(d)
```

Maybe you could expose an array in `lucide-static`, a json file, or something else that made easy for me.

From the own docs, it says:

> JavaScript library containing strings of SVGs

Yet I don't know how to get "all strings of svgs" all it once in a single place.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by ericfennis** [comment]
Does this not work for you?

```ts
import * as icons from "lucide-static";

const iconsArray = Object.values(icons)
```

What is the exact usecase?

**Comment by bernaferrari** [comment]
I'm going to sound extremely dumb, but that worked... I tried before (multiple times) but somehow I was getting wrong types and stuff. Thanks a lot.

**Comment by bernaferrari** [comment]
It is on the server, so it is fine.

**Comment by bernaferrari** [comment]
I've been doing


```ts
import dynamicIconImports from "lucide-react/dynamicIconImports";

dynamicIconImports[props.leading.iconName as keyof typeof dynamicIconImports]
```
and then

```ts
const iconCache: { [key: string]: any } = {};

const getCachedIcon = (name: keyof typeof dynamicIconImports) => {
  if (!iconCache[name]) {
    iconCache[name] = dynamic(dynamicIconImports[name]);
  }
  return iconCache[name];
};

interface IconProps extends LucideProps {
  name: keyof typeof dynamicIconImports;
}

export const CachedLucideIcon = ({ name, ...props }: IconProps) => {
  const LucideIcon = getCachedIcon(name);
  return <LucideIcon {...props} />;
};
```

The issue is that `dynamicIconImports`  makes NextJS import 4000 modules, and causes Hot Refresh to basically die (goes from 600ms to 8s). Is there a way to query a list of all Lucide icons (in a JSON or something super basic) so that I can then get them lazily?

**Comment by hitecSmartHome** [comment]
I would also want to create an icon picker for my users and would really need this list somehow.
