### ISSUE TITLE
[Angular] Standalone component compatibility

### ISSUE THREAD

**Issue by hakimio** [lucide-icons/lucide#2097]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Standalone component API is now stable in Angular. However, `lucide-angular` is not compatible with Angular `standalone` applications which results in a bad DX.

1. `LucideAngularModule.pick()` can only be used with the `importProvidersFrom()` compatibility function:
```ts
export const appConfig: ApplicationConfig = {
    providers: [
        importProvidersFrom(
            LucideAngularModule.pick(appIcons)
       )
    ]
};
```
Instead of having dedicated `provideLucideIcons()` provider function like most libraries have nowadays:
```ts
export const appConfig: ApplicationConfig = {
    providers: [
        provideLucideIcons(appIcons)
    ]
};
```
2. It's not possible to import Lucide icons in standalone component `imports` to have a local set of icons. The following code throws an error:
```ts
@Component({
    selector: 'app-root',
    standalone: true,
    imports: [
        LucideAngularModule.pick(appIcons)
    ],
    templateUrl: './app.component.html'
})
export class AppComponent {}
```
There should be a way to select icons in standalone components like it's now possible when using [Ionic icons](https://ionicframework.com/docs/angular/build-options#:~:text=%7B%7D%0A%7D-,Icons,-The%20icon%20SVG).

### Use cases

Standalone component compatibility.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
This isn't Lucide, this is just how Angular works. Standalone components have no support for `ModuleWithProvider`, if you want to use Lucide with standalone components, you already can do it, see: https://github.com/lucide-icons/lucide/issues/1288#issuecomment-1701754200

Of course it would be best if we could provide a standalone component, but we can't as long as we want to retain backwards compatibility with previous versions.

**Comment by hakimio** [comment]
Using `importProvidersFrom()` is not a proper solution. That's just a workaround.
You can provide your own `provideLucideIcons(appIcons)` at least in addition to `LucideAngularModule.pick()`. It wouldn't break anything.

**Comment by hakimio** [comment]
Also, you can release a new major version of `lucide-angular` with breaking changes. I don't understand why in more than 3 years you haven't released any major version and kept going with `0.x` releases.

**Comment by karsa-mistmere** [comment]
> Using importProvidersFrom() is not a proper solution. That's just a workaround. You can provide your own provideLucideIcons(appIcons) at least in addition to LucideAngularModule.pick(). It wouldn't break anything.

`importProvidersFrom` is not something that we recommend using at all, we recommend using the dedicated injection token for this purpose as stated in https://github.com/lucide-icons/lucide/issues/1288#issuecomment-1701754200

But even more so we recommend not providing more icons than necessary, so I'd recommend using this pattern:
```tsx
import { Component } from '@angular/core';
import { ActivitySquareIcon, LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-demo',
  standalone: true,
  imports: [LucideAngularModule],
  template: `<lucide-icon [name]="ActivitySquareIcon" />`,
})
export class DemoComponent {
  protected readonly ActivitySquareIcon = ActivitySquareIcon;
}
```

> Also, you can release a new major version of lucide-angular with breaking changes.

Every icon is bundled within the package, should we release a new version with breaking changes, people using earlier versions of Angular would be hung out to dry, and if you look at the usage statistics of major versions, people do still use earlier verions, _a lot_: https://www.npmjs.com/package/@angular/core?activeTab=versions.

**Comment by hakimio** [comment]
How about decoupling the core icon package and the Angular package to make life easier?

**Comment by karsa-mistmere** [comment]
> How about decoupling the core icon package and the Angular package to make life easier?

It's planned, see https://github.com/lucide-icons/lucide/issues/1687

Once we do that, there will be nothing in the way of releasing a modern version of `lucide-angular` with proper standalone component support.

**Comment by hakimio** [comment]
Awesome 🙂
