### ISSUE TITLE
[Icon Request] "Home Plus" icon

### ISSUE THREAD

**Issue by danawoodman** [lucide-icons/lucide#2098]
### Icon name

home-plus

### Use cases

Our product has an action of "add new property" where a "plus" icon is not descriptive enough given other UI elements on the page

### Design ideas

Basically a Lucide version of https://tabler.io/icons/icon/home-plus

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
The issue #1841 might trigger a redesign of home, maybe we should do that first before adding the home-plus icon.

**Comment by danawoodman** [comment]
would be excellent if a few variations could be added at that stage, thinking off the top of my head plus, minus and delete would be useful variants!

**Comment by chessurisme** [comment]
> would be excellent if a few variations could be added at that stage, thinking off the top of my head plus, minus and delete would be useful variants!

Indeed that could be helpful, but not sure about `home-delete` since `home-minus` has the same use cases.

**Comment by danawoodman** [comment]
to be clear, i meant an x instead of a -. they could have different meanings, say "close access to property" vs "remove property entry"

**Comment by chessurisme** [comment]
Oh, that is understandable now! `home-x` could be a pretty neat to add too.

**Comment by ericfennis** [comment]
Also contributes to #114 as `home-medical`

**Comment by Vikas-singh-0** [comment]
Can i work on it??

**Comment by jguddas** [comment]
> Can i work on it??

Sure throw in some suggestions.

**Suggestion for a lucidier `home` icon:**

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+21a2+2+0+0+0+2-2V9.999a2+2+0+0+0-.772-1.578L12+2+3.772+8.421A2+2+0+0+0+3+9.999l.013+8.776a2+2+0+0+0+2+2.225z%22+/%3E%3Crect+x=%229%22+y=%2212%22+width=%226%22+height=%229%22+rx=%221%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTkgMjFhMiAyIDAgMCAwIDItMlY5Ljk5OWEyIDIgMCAwIDAtLjc3Mi0xLjU3OEwxMiAyIDMuNzcyIDguNDIxQTIgMiAwIDAgMCAzIDkuOTk5bC4wMTMgOC43NzZhMiAyIDAgMCAwIDIgMi4yMjV6IiAvPgogIDxyZWN0IHg9IjkiIHk9IjEyIiB3aWR0aD0iNiIgaGVpZ2h0PSI5IiByeD0iMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
