### ISSUE TITLE
LucideProps type not found in 'lucide-solid'

### ISSUE THREAD

**Issue by agat** [lucide-icons/lucide#2099]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.372.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [X] Other/not relevant

### Description

Hello, I use Vite and TypeScript and see that can't import `type LucideProps` from a `lucide-solid` package.

### Steps to reproduce

Example:

```tsx
import type { LucideProps } from 'lucide-solid';
// Got error here - TS2724: 'lucide-solid' has no exported member named LucideProps.
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
Thanks for reporting.
I've fixed this in [0.376.0](https://github.com/lucide-icons/lucide/releases/tag/0.376.0)
