### ISSUE TITLE
Where is @lucide/shared

### ISSUE THREAD

**Issue by MozzieMD** [lucide-icons/lucide#2106]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.376

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

[vite] Pre-transform error: Failed to load url @lucide/shared (resolved id: @lucide/shared) in .../node_modules/lucide-svelte/dist/Icon.svelte. Does the file exist?

### Steps to reproduce

!. Install, 2.Use

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by laryhills** [comment]
I have the same issue, shared folder not in node_modules

**Comment by Awesomeplayer165** [comment]
also have this problem

**Comment by Awesomeplayer165** [comment]
is there a workaround anyone has found temporarily?

**Comment by keedyc** [comment]
I also ran into this 😅

**Comment by MozzieMD** [comment]
> is there a workaround anyone has found temporarily?

Install older version )

**Comment by cliffordkleinsr** [comment]
+ 1

**Comment by rakanus** [comment]
After dedicating four hours to identifying the problem,
I discovered that the latest version of Lucide was lacking '@lucide/shared'. Indeed!

**Comment by laryhills** [comment]
> After dedicating four hours to identifying the problem, I discovered that the latest version of Lucide was lacking '@lucide/shared'. Indeed!

Which previous version has it?

**Comment by rakanus** [comment]
This fixed it for me .. 

`pnpm i lucide-svelte@0.375.0`

![CleanShot 2024-04-27 at 12 23 05](https://github.com/lucide-icons/lucide/assets/27198873/d962d310-7fbf-4173-b836-ada39a873660)

**Comment by laryhills** [comment]
> This fixed it for me ..
> 
> `pnpm i lucide-svelte@0.375.0`
> 
> ![CleanShot 2024-04-27 at 12 23 05](https://private-user-images.githubusercontent.com/27198873/326168714-d962d310-7fbf-4173-b836-ada39a873660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTA1MDAsIm5iZiI6MTcxNDIxMDIwMCwicGF0aCI6Ii8yNzE5ODg3My8zMjYxNjg3MTQtZDk2MmQzMTAtN2ZiZi00MTczLWI4MzYtYWRhMzlhODczNjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA5MzAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMjcxZTgwNWI0MmNhN2JkYjJmZTE3YTJlOTMzOTY1OTU2YmFmMDY4YmMzMmY3OGIwZTQ4MjRkM2E5OGNkM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YBkWOII6h-cqA-pwGoTumtzPtQ63ZRlOmtUbtFXRobE)

Will try out, thank you

**Comment by spidi123q** [comment]
getting same error with  lucide-svelte@0.375.0

**Comment by ericfennis** [comment]
Sorry for the inconvenience. The Svelte package has a different build system than our other packages. `@lucide/shared` was designed to be included in the code, not as a dependency. `@sveltejs/package` was not able to include this. 

I've made a fix to revert the shared package for `@lucide/shared`.

**Comment by ericfennis** [comment]
Fix published on `lucide-svelte@0.376.1`
