### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#2134]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

We should test the package in React 19 beta and, if it succeeds, accept React 19.0.0 as a peerDependency.

### Use cases

I think it requires no further explanation :)

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by oasaleh** [comment]
Is there a workaround for now?

**Comment by Oksitaine** [comment]
I have the same issue, someone get new about it ?

**Comment by wojtekmaj** [comment]
I tested the package with React 19 RC and found no issues. I think we're safe to update peerDeps.

**Comment by Gamez0** [comment]
When will support for React 19 be available? 
If it's just a matter of adding `^19.0.0` to peerDependencies in the `lucide-react/package.json`, can I submit a PR for that?

**Comment by ericfennis** [comment]
@wojtekmaj Awesome tnx for checking

**Comment by broken99records** [comment]
any update on this, thanks

**Comment by thomasbertok** [comment]
Any update on this?

**Comment by thirdygayares** [comment]
npm install lucide-react-native

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: myapp@1.0.0
npm error Found: react@19.0.0
npm error node_modules/react
npm error   react@"19.0.0" from the root project
npm error
npm error Could not resolve dependency:


any update

**Comment by mkambouay** [comment]
any update?

**Comment by ragrum** [comment]
@thirdygayares, the fix was only applied for the `lucide-react` package, but not to `lucide-react-native`. I opened a PR to fix the latter.

**Comment by thomasbertok** [comment]
I can affirm that lucide-icons works well with react 19 and react native 0.79
