### ISSUE TITLE
Module '"lucide-react"' has no exported member 'Notebook'.ts(2305)

### ISSUE THREAD

**Issue by CayllahuaPedro** [lucide-icons/lucide#2138]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.378.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

```
import {
  ActivitySquareIcon,
  FileUpIcon,
  LayoutDashboardIcon,
  BadgeDollarSign,
  Contact,
  Users,
  LayoutPanelLeft,
  Notebook,
} from "lucide-react";

```
when I tried to import some icons from the lucide-react package
I got the next error: Module '"lucide-react"' has no exported member 'Notebook'.ts(2305). Needles to say I looked in forums for similar problems. specifically I tried to downgrade to 0.263.0 version but that didn't work. 

### Steps to reproduce

1. install latest version 
1.import 'notebook' icon
2.get the error

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
[I cannot reproduce this issue](https://codesandbox.io/p/sandbox/cranky-meadow-kld89w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6og7re00063b6agj5khcip%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6og7re00023b6awptqecz9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6og7re00033b6apmt0ldmy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6og7re00053b6a8jo3q5e6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6og7re00023b6awptqecz9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6og7re00013b6abs81mjag%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsk395gd00023b6aux6779t7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr6og7re00023b6awptqecz9%2522%252C%2522activeTabId%2522%253A%2522clsk395gd00023b6aux6779t7%2522%257D%252C%2522clr6og7re00053b6a8jo3q5e6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6og7re00043b6adnlwxk12%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr6og7re00053b6a8jo3q5e6%2522%252C%2522activeTabId%2522%253A%2522clr6og7re00043b6adnlwxk12%2522%257D%252C%2522clr6og7re00033b6apmt0ldmy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr6og7re00033b6apmt0ldmy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), can you make sure an earlier version isn't stuck in some kind of cache and you're actually using v0.378.0, which [definitely has this export](https://cdn.jsdelivr.net/npm/lucide-react@0.378.0/dist/esm/icons/notebook.js)?

(.next cache, node_modules etc)

**Comment by CayllahuaPedro** [comment]
I have version 0.378 both in package.json and pnpm-lock.yaml . I tried looking into the cache but vs code wont read it

**Comment by karsa-mistmere** [comment]
Can you check if node_modules/lucide-react/dist/esm/notebook.js exists?

As for any cache, you shouldn't be looking into it, but clearing it (since you haven't provided any extra information about your frameworks, I cannot help you with how that should be done, but if it's next.js for example, you may try deleting the entire .next folder, same goes for node_modules, especially if the export above isn't there).
