### ISSUE TITLE
Git icon

### ISSUE THREAD

**Issue by rogerfar** [lucide-icons/lucide#2148]
### Icon name

git

### Use cases

Used in a git like interface. We have already git action icons, deprecated github/gitlab icons, but not the "official" git icon.

### Design ideas

https://git-scm.com/downloads/logos

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
#670

**Comment by rogerfar** [comment]
Sorry but is Git itself a brand? I'm not talking Github or Gitlab.

**Comment by karsa-mistmere** [comment]
The bigger issue here, I think, is that the Git logo is simply not very Lucide-compatible. This is the best I could come up with so far and it's nowhere near guideline compliant:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M1.777+10.125a2.652+2.652+0+0+0+0+3.75l8.348+8.348a2.652+2.652+0+0+0+3.75+0l8.348-8.348a2.652+2.652+0+0+0+0-3.75l-8.348-8.348a2.652+2.652+0+0+0-3.75+0z%22+/%3E%3Cpath+d=%22M11+7v9%22+/%3E%3Cpath+d=%22m8+4+8+8%22+/%3E%3Ccircle+cx=%2211%22+cy=%2216%22+r=%221%22+/%3E%3Ccircle+cx=%2211%22+cy=%227%22+r=%221%22+/%3E%3Ccircle+cx=%2216%22+cy=%2212%22+r=%221%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMS43NzcgMTAuMTI1YTIuNjUyIDIuNjUyIDAgMCAwIDAgMy43NWw4LjM0OCA4LjM0OGEyLjY1MiAyLjY1MiAwIDAgMCAzLjc1IDBsOC4zNDgtOC4zNDhhMi42NTIgMi42NTIgMCAwIDAgMC0zLjc1bC04LjM0OC04LjM0OGEyLjY1MiAyLjY1MiAwIDAgMC0zLjc1IDB6IiAvPgogIDxwYXRoIGQ9Ik0xMSA3djkiIC8+CiAgPHBhdGggZD0ibTggNCA4IDgiIC8+CiAgPGNpcmNsZSBjeD0iMTEiIGN5PSIxNiIgcj0iMSIgLz4KICA8Y2lyY2xlIGN4PSIxMSIgY3k9IjciIHI9IjEiIC8+CiAgPGNpcmNsZSBjeD0iMTYiIGN5PSIxMiIgcj0iMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

Feel free to use it though, just as long as you credit Jason Long, who originally designed the Git logo.

**Comment by rogerfar** [comment]
Appreciate it @karsa-mistmere, I kind of came up with the same, and it doesn't look quite right compared to the other lucide icons no.

**Comment by karsa-mistmere** [comment]
> Appreciate it @karsa-mistmere, I kind of came up with the same, and it doesn't look quite right compared to the other lucide icons no.

Yeah, that's our usual conondrum when dealing with external designs. 😕

**Comment by jguddas** [comment]
![icon (54)](https://github.com/lucide-icons/lucide/assets/25524993/c550cdd6-a498-48b4-89ce-e46da4402b5a)
