### ISSUE TITLE
Map Pin Plus

### ISSUE THREAD

**Issue by enesien** [lucide-icons/lucide#2151]
### Icon name

map-pin-plus

### Use cases

Indicates adding a new map marker/pin to an existing list/map.

### Design ideas

Center circle could be replaced with a "+" or a "+" can be added on the bottom right, similar to `mail-plus`

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
> This is a Lucide-ised redesign of our map pin icon & two separate sets with some of our common inside elements: ![image](https://private-user-images.githubusercontent.com/17746067/338483232-7f44163a-d665-45c6-9e25-0e5dadd5d0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTIwMzIsIm5iZiI6MTcxODA5MTczMiwicGF0aCI6Ii8xNzc0NjA2Ny8zMzg0ODMyMzItN2Y0NDE2M2EtZDY2NS00NWM2LTllMjUtMGU1ZGFkZDVkMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3NDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MjZjYmI1MGZmOWQ3MTZjNjFlNWI4YzUyOGYxZmE4ODNmMmIyZDg1MGIyY2MzMTNmNTMwY2M0NmRiNDdlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ghAuqpIxd6VEVA2Q20T9JhnOhKr7IQ_tba04eWUxqXA) https://www.figma.com/design/aThgThuGPzAv7SY99sn68V/lucide%2Fmap-pins?node-id=0-1&t=AfsWsBgv8BX8tuq3-1
> 
> @ericfennis & @jguddas, let me know what you think, which set would you prefer? (unless both, but then we would need to come up with descriptive names for at least one variant)

I think both variants are cute and kinda valid, the left represents to me "here is a cross", the left one represents to me a "add a pin".
