### ISSUE TITLE
List Check Icon

### ISSUE THREAD

**Issue by guanboo-yang** [lucide-icons/lucide#2155]
### Icon name

list-check

### Use cases

1. To indicate that an item has been added to a to-do list in a task management application.
2. To show that a product has been added to a user's wishlist on an e-commerce platform.

### Design ideas

I need the icon to indicate that an item is added to a list. If an item is added, I need the "list-check" icon, and if not, I need the "list-plus" icon. The current "list-plus" icon has a plus sign in the middle, which suggests "insert inside" the list. However, I want another icon where the plus sign is at the right bottom to indicate "append" to the list. Similarly, the check sign in the "list-check" icon should be at the right bottom. Both icons should have a minimalistic design with a list outline just like other list-related icons.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by guanboo-yang** [comment]
Try modify from other icons:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+18H3%22+/%3E%3Cpath+d=%22m15+18+2+2+4-4%22+/%3E%3Cpath+d=%22M16+12H3%22+/%3E%3Cpath+d=%22M16+6H3%22+/%3E&name=list-check&dialog=false"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMThIMyIgLz4KICA8cGF0aCBkPSJtMTUgMTggMiAyIDQtNCIgLz4KICA8cGF0aCBkPSJNMTYgMTJIMyIgLz4KICA8cGF0aCBkPSJNMTYgNkgzIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+18H3%22+/%3E%3Cpath+d=%22M16+12H3%22+/%3E%3Cpath+d=%22M16+6H3%22+/%3E%3Cpath+d=%22M18+15v6%22+/%3E%3Cpath+d=%22M21+18h-6%22+/%3E&name=list-check&dialog=false"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMThIMyIgLz4KICA8cGF0aCBkPSJNMTYgMTJIMyIgLz4KICA8cGF0aCBkPSJNMTYgNkgzIiAvPgogIDxwYXRoIGQ9Ik0xOCAxNXY2IiAvPgogIDxwYXRoIGQ9Ik0yMSAxOGgtNiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
@guanboo-yang Cool idea!

**Comment by programmer-rahul** [comment]
Should I start creating this icon in Illustrator? I have knowledge and confidence in using Illustrator, and I have read the contribution guidelines for new icons. Additionally, this is my first time contributing. Should I proceed?

**Comment by karsa-mistmere** [comment]
> Should I start creating this icon in Illustrator? I have knowledge and confidence in using Illustrator, and I have read the contribution guidelines for new icons. Additionally, this is my first time contributing. Should I proceed?

The icons are already there in https://github.com/lucide-icons/lucide/issues/2155#issuecomment-2111659458

**Comment by jguddas** [comment]
> Should I start creating this icon in Illustrator? I have knowledge and confidence in using Illustrator, and I have read the contribution guidelines for new icons. Additionally, this is my first time contributing. Should I proceed?

You can absolutely build something and just post theme here or even make a PR directly. 
You can also use https://lucide-studio.vercel.app to share and optimize your icon if you like to.

**Comment by programmer-rahul** [comment]
Thank you both for your feedback!

 @karsa-mistmere : Thanks for letting me know

@jguddas: Thanks for the encouragement and the tip about Lucide Studio! I'll look at the existing icons first. If I decide to make new ones, I'll use Lucide Studio to optimize and share them. I'll either post them here or make a PR directly.

Thanks again for your support!

**Comment by guanboo-yang** [comment]
If this icon is needed, I would be happy to create the PR myself.

**Comment by programmer-rahul** [comment]
@guanboo-yang ok

**Comment by ericfennis** [comment]
Closes by #2291
