### ISSUE TITLE
Figma plugin keeps loading and won't run 

### ISSUE THREAD

**Issue by aycandoganlar** [lucide-icons/lucide#2156]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [X] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

latest

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

It gets stuck like this when I try to run it
<img width="350" alt="image" src="https://github.com/lucide-icons/lucide/assets/101369017/a53f26b7-5d86-4374-b865-c7dd6abf3e26">

### Steps to reproduce

Run the plugin from Figma

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by eduzrdo** [comment]
The plugin **opens in Opera GX**, but the bug stills persists in Chrome.

![image](https://github.com/lucide-icons/lucide/assets/43072438/31ced574-a6c8-457c-ac77-59dcb523b785)

**Comment by admin-boclar** [comment]
I have the same issue in the Figma app. Hope it gets fixed soon.

**Comment by karsa-mistmere** [comment]
Hey everyone,

We've just published a new version that hopefully fixes this startup issue, can you let us know if it truly has been resolved?
If not, can you please provide additional information context and maybe check the console for error messages?

**Comment by eduzrdo** [comment]
![Screenshot_3](https://github.com/lucide-icons/lucide/assets/43072438/cb51cb2b-da9a-4d0b-9671-1489d8999253)

The new version fixed the issue here. 👏🏼👏🏼

**Comment by aycandoganlar** [comment]
fixed, amazing!! 🚀🙏 :)

**Comment by karsa-mistmere** [comment]
Thanks for the feedback! 🎉

**Comment by Konstaphy** [comment]
<img width="303" alt="image" src="https://github.com/lucide-icons/lucide/assets/58948535/6f16fbd4-39fb-4fdd-961c-fdff7d1dd747">
Hey, update-icon plugin gets stuck as well :(

Mac-os, web version and desktop app also
