### ISSUE TITLE
X-(Twiiter) New Logo

### ISSUE THREAD

**Issue by just-abdullah-dev** [lucide-icons/lucide#2159]
### Icon name

X

### Use cases

I need X Twiiter new logo for my social media links icons in website.

### Design ideas

same as original 

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
#670 #1468 #1528 #1561 #1717 #1985 et cetera

**Comment by muhsinaltintop** [comment]
I need to remove lucide from my project as it use old logo of X. Why don't you change it? It's been ages.
