### ISSUE TITLE
[Icon Request] Onion

### ISSUE THREAD

**Issue by shahradelahi** [lucide-icons/lucide#2170]
### Icon name

Onion

### Use cases

It's an onion icon. It would be amazing if it looks similar to the Tor onion icon.

I understand that this request looks like a brand icon request, but it's just a simple onion icon. By the way, there is an FAQ about the right to use the Tor logo [HERE](https://www.torproject.org/about/trademark/#trademark-faq-2).

### Design ideas

https://fontawesome.com/icons/onion?f=classic&s=regular

https://styleguide.torproject.org/brand-assets/

![logo-onion](https://github.com/lucide-icons/lucide/assets/17948260/3caa9bc7-e5e1-4542-8675-4c36183eaec3)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
Do you have some use cases besides the brand?

**Comment by chessurisme** [comment]
Use cases are:
- for root spices
- for cooking, gardening, farming

**Comment by jguddas** [comment]
> Use cases are:
> - for root spices
> - for cooking, gardening, farming

- For warning people with onion allergies.

Onion emoji proposal spec:
https://www.unicode.org/L2/L2018/18077-onion-emoji.pdf

**Comment by karsa-mistmere** [comment]
Also note that this icon has already been added to our `lab` branch, however, I still think that that design is less than optimal, see https://github.com/lucide-icons/lucide/pull/1306#discussion_r1317822069

**Comment by jguddas** [comment]
> Also note that this icon has already been added to our `lab` branch, however, I still think that that design is less than optimal, see [#1306 (comment)](https://github.com/lucide-icons/lucide/pull/1306#discussion_r1317822069)

![image](https://github.com/lucide-icons/lucide/assets/25524993/c065f70e-f352-4049-a5b3-0a9719089365)

Can you share those designs as https://lucide-studio.vercel.app links?

**Comment by karsa-mistmere** [comment]
> Can you share those designs as https://lucide-studio.vercel.app links?

Nah, there are way too many draft for that, but here's a Figma link:
https://www.figma.com/design/vFf6vIocN22jfDFCJFRdg5/lucide%2Fonion?node-id=0-1&t=jjoAgHQgOAA0zGFX-1

**Comment by jguddas** [comment]
> > Can you share those designs as https://lucide-studio.vercel.app links?
> 
> Nah, there are way too many drafts for that, but here's a Figma link: https://www.figma.com/design/vFf6vIocN22jfDFCJFRdg5/lucide%2Fonion?node-id=0-1&t=jjoAgHQgOAA0zGFX-1

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M18+20v2%22+/%3E%3Cpath+d=%22M2.8+8.1a10+10+0+1+0+5.3-5.3C5+4+3+2+3+2L2+3s2+2+.8+5.1%22+/%3E%3Cpath+d=%22m21+21-1.9-1.9%22+/%3E%3Cpath+d=%22M22+18h-2%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%222%22+/%3E%3Ccircle+cx=%2212%22+cy=%2212%22+r=%226%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTggMjB2MiIgLz4KICA8cGF0aCBkPSJNMi44IDguMWExMCAxMCAwIDEgMCA1LjMtNS4zQzUgNCAzIDIgMyAyTDIgM3MyIDIgLjggNS4xIiAvPgogIDxwYXRoIGQ9Im0yMSAyMS0xLjktMS45IiAvPgogIDxwYXRoIGQ9Ik0yMiAxOGgtMiIgLz4KICA8Y2lyY2xlIGN4PSIxMiIgY3k9IjEyIiByPSIyIiAvPgogIDxjaXJjbGUgY3g9IjEyIiBjeT0iMTIiIHI9IjYiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11.5+6c3.5.5+9.5+6.5+7.5+13-7.5+1.5-12.557-3.188-13-7.5%22+/%3E%3Cpath+d=%22M17.994+22v-2%22+/%3E%3Cpath+d=%22M19+19+8+8%22+/%3E%3Cpath+d=%22M19.994+18h2%22+/%3E%3Cpath+d=%22M20.29+6.415a10+10+0+0+1-7.331+15.545c-2.31.222-4.693-.272-6.55-1.663C-2+14+6.516+6.516+2+2c4.516+4.516+11.5-3.5+18.29+4.415%22+/%3E%3Cpath+d=%22m20.994+21-1.9-1.9%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEuNSA2YzMuNS41IDkuNSA2LjUgNy41IDEzLTcuNSAxLjUtMTIuNTU3LTMuMTg4LTEzLTcuNSIgLz4KICA8cGF0aCBkPSJNMTcuOTk0IDIydi0yIiAvPgogIDxwYXRoIGQ9Ik0xOSAxOSA4IDgiIC8+CiAgPHBhdGggZD0iTTE5Ljk5NCAxOGgyIiAvPgogIDxwYXRoIGQ9Ik0yMC4yOSA2LjQxNWExMCAxMCAwIDAgMS03LjMzMSAxNS41NDVjLTIuMzEuMjIyLTQuNjkzLS4yNzItNi41NS0xLjY2M0MtMiAxNCA2LjUxNiA2LjUxNiAyIDJjNC41MTYgNC41MTYgMTEuNS0zLjUgMTguMjkgNC40MTUiIC8+CiAgPHBhdGggZD0ibTIwLjk5NCAyMS0xLjktMS45IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17.994+22v-2%22+/%3E%3Cpath+d=%22M19+19+2+2%22+/%3E%3Cpath+d=%22M19+19c-4+1.5-8.543-.388-10.5-2.5C5.5+13.262+5+7.5+2+2c5+2.5+11.294+3.852+14.5+7+2.494+2.448+4+6+2.5+10%22+/%3E%3Cpath+d=%22M19.994+18h2%22+/%3E%3Cpath+d=%22M2+2c3+4.5-3.389+14+4.5+18.5+4.383+2.5+9.07+2.078+12.571-1.423+2.377-2.377+3.307-5.555+2.833-8.577C19.5-1.5+9.5+5+2+2%22+/%3E%3Cpath+d=%22m20.994+21-1.9-1.9%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcuOTk0IDIydi0yIiAvPgogIDxwYXRoIGQ9Ik0xOSAxOSAyIDIiIC8+CiAgPHBhdGggZD0iTTE5IDE5Yy00IDEuNS04LjU0My0uMzg4LTEwLjUtMi41QzUuNSAxMy4yNjIgNSA3LjUgMiAyYzUgMi41IDExLjI5NCAzLjg1MiAxNC41IDcgMi40OTQgMi40NDggNCA2IDIuNSAxMCIgLz4KICA8cGF0aCBkPSJNMTkuOTk0IDE4aDIiIC8+CiAgPHBhdGggZD0iTTIgMmMzIDQuNS0zLjM4OSAxNCA0LjUgMTguNSA0LjM4MyAyLjUgOS4wNyAyLjA3OCAxMi41NzEtMS40MjMgMi4zNzctMi4zNzcgMy4zMDctNS41NTUgMi44MzMtOC41NzdDMTkuNS0xLjUgOS41IDUgMiAyIiAvPgogIDxwYXRoIGQ9Im0yMC45OTQgMjEtMS45LTEuOSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M17+19C21+14.5+5+7+4+3%22+/%3E%3Cpath+d=%22M17.994+22v-2%22+/%3E%3Cpath+d=%22M19.994+18h2%22+/%3E%3Cpath+d=%22M2+4c5.5+5+4+16+15.5+14.5%22+/%3E%3Cpath+d=%22m20.994+21-1.9-1.9%22+/%3E%3Cpath+d=%22M4+2c4.677+4.392+17+3+16+14%22+/%3E%3Cpath+d=%22M4+4H2l.422+4.645a6.68+6.68+0+0+1-.063+1.702l-.218+1.308a7.833+7.833+0+0+0+2.04+6.675+9.257+9.257+0+0+0+13.036.4l2.183-2.037a8.781+8.781+0+0+0+.725-12.075+7.43+7.43+0+0+0-6.665-2.58l-2.623.35a7.797+7.797+0+0+1-1.678.042L4+2z%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTcgMTlDMjEgMTQuNSA1IDcgNCAzIiAvPgogIDxwYXRoIGQ9Ik0xNy45OTQgMjJ2LTIiIC8+CiAgPHBhdGggZD0iTTE5Ljk5NCAxOGgyIiAvPgogIDxwYXRoIGQ9Ik0yIDRjNS41IDUgNCAxNiAxNS41IDE0LjUiIC8+CiAgPHBhdGggZD0ibTIwLjk5NCAyMS0xLjktMS45IiAvPgogIDxwYXRoIGQ9Ik00IDJjNC42NzcgNC4zOTIgMTcgMyAxNiAxNCIgLz4KICA8cGF0aCBkPSJNNCA0SDJsLjQyMiA0LjY0NWE2LjY4IDYuNjggMCAwIDEtLjA2MyAxLjcwMmwtLjIxOCAxLjMwOGE3LjgzMyA3LjgzMyAwIDAgMCAyLjA0IDYuNjc1IDkuMjU3IDkuMjU3IDAgMCAwIDEzLjAzNi40bDIuMTgzLTIuMDM3YTguNzgxIDguNzgxIDAgMCAwIC43MjUtMTIuMDc1IDcuNDMgNy40MyAwIDAgMC02LjY2NS0yLjU4bC0yLjYyMy4zNWE3Ljc5NyA3Ljc5NyAwIDAgMS0xLjY3OC4wNDJMNCAyeiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M16+8.682c2.407+2.454+4.24+6.29+3+10.318-4.798.96-8.596-.613-10.826-3%22+/%3E%3Cpath+d=%22M17.994+22v-2%22+/%3E%3Cpath+d=%22m19+19-8-8%22+/%3E%3Cpath+d=%22M19.994+18h2%22+/%3E%3Cpath+d=%22M20.29+6.415a10+10+0+0+1-7.331+15.545c-2.31.222-4.693-.272-6.55-1.663C-2+14+6.516+6.516+2+2c4.516+4.516+11.5-3.5+18.29+4.415%22+/%3E%3Cpath+d=%22m20.994+21-1.9-1.9%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTYgOC42ODJjMi40MDcgMi40NTQgNC4yNCA2LjI5IDMgMTAuMzE4LTQuNzk4Ljk2LTguNTk2LS42MTMtMTAuODI2LTMiIC8+CiAgPHBhdGggZD0iTTE3Ljk5NCAyMnYtMiIgLz4KICA8cGF0aCBkPSJtMTkgMTktOC04IiAvPgogIDxwYXRoIGQ9Ik0xOS45OTQgMThoMiIgLz4KICA8cGF0aCBkPSJNMjAuMjkgNi40MTVhMTAgMTAgMCAwIDEtNy4zMzEgMTUuNTQ1Yy0yLjMxLjIyMi00LjY5My0uMjcyLTYuNTUtMS42NjNDLTIgMTQgNi41MTYgNi41MTYgMiAyYzQuNTE2IDQuNTE2IDExLjUtMy41IDE4LjI5IDQuNDE1IiAvPgogIDxwYXRoIGQ9Im0yMC45OTQgMjEtMS45LTEuOSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+14c0-4.018.5-7.5+2.046-12C13.5+6.5+14+10.442+14+14c0+3.314-.895+6-2+6s-2-2.686-2-6%22+/%3E%3Cpath+d=%22m10+20.5-1+1%22+/%3E%3Cpath+d=%22M12+20c5.523+0+10-3.134+10-7+0-6.692-7.5-6.5-10-11C9.5+6.5+2+6.329+2+13c0+3.866+4.477+7+10+7%22+/%3E%3Cpath+d=%22M12+22v-1%22+/%3E%3Cpath+d=%22m14+20.5+1+1%22+/%3E%3Cpath+d=%22M6+13c0-4.5+5.5-8+6-11+.5+3+6+6.5+6+11+0+3.866-2.686+7-6+7s-6-3.134-6-7%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAgMTRjMC00LjAxOC41LTcuNSAyLjA0Ni0xMkMxMy41IDYuNSAxNCAxMC40NDIgMTQgMTRjMCAzLjMxNC0uODk1IDYtMiA2cy0yLTIuNjg2LTItNiIgLz4KICA8cGF0aCBkPSJtMTAgMjAuNS0xIDEiIC8+CiAgPHBhdGggZD0iTTEyIDIwYzUuNTIzIDAgMTAtMy4xMzQgMTAtNyAwLTYuNjkyLTcuNS02LjUtMTAtMTFDOS41IDYuNSAyIDYuMzI5IDIgMTNjMCAzLjg2NiA0LjQ3NyA3IDEwIDciIC8+CiAgPHBhdGggZD0iTTEyIDIydi0xIiAvPgogIDxwYXRoIGQ9Im0xNCAyMC41IDEgMSIgLz4KICA8cGF0aCBkPSJNNiAxM2MwLTQuNSA1LjUtOCA2LTExIC41IDMgNiA2LjUgNiAxMSAwIDMuODY2LTIuNjg2IDctNiA3cy02LTMuMTM0LTYtNyIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m10+20.5-1+1%22+/%3E%3Cpath+d=%22M10.198+10A37.66+37.66+0+0+0+10+14c0+3.314.895+6+2+6s2-2.686+2-6a37+37+0+0+0-.216-4%22+/%3E%3Cpath+d=%22M12+20c5.523+0+10-3.134+10-7+0-6.692-7.5-6.5-10-11C9.5+6.5+2+6.329+2+13c0+3.866+4.477+7+10+7%22+/%3E%3Cpath+d=%22M12+22v-1%22+/%3E%3Cpath+d=%22m14+20.5+1+1%22+/%3E%3Cpath+d=%22M6+13c0+3.866+2.686+7+6+7s6-3.134+6-7%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTAgMjAuNS0xIDEiIC8+CiAgPHBhdGggZD0iTTEwLjE5OCAxMEEzNy42NiAzNy42NiAwIDAgMCAxMCAxNGMwIDMuMzE0Ljg5NSA2IDIgNnMyLTIuNjg2IDItNmEzNyAzNyAwIDAgMC0uMjE2LTQiIC8+CiAgPHBhdGggZD0iTTEyIDIwYzUuNTIzIDAgMTAtMy4xMzQgMTAtNyAwLTYuNjkyLTcuNS02LjUtMTAtMTFDOS41IDYuNSAyIDYuMzI5IDIgMTNjMCAzLjg2NiA0LjQ3NyA3IDEwIDciIC8+CiAgPHBhdGggZD0iTTEyIDIydi0xIiAvPgogIDxwYXRoIGQ9Im0xNCAyMC41IDEgMSIgLz4KICA8cGF0aCBkPSJNNiAxM2MwIDMuODY2IDIuNjg2IDcgNiA3czYtMy4xMzQgNi03IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m10+20.5-1+1%22+/%3E%3Cpath+d=%22M12+20c5.523+0+10-3.134+10-7+0-6.692-7.5-6.5-10-11C9.5+6.5+2+6.329+2+13c0+3.866+4.477+7+10+7%22+/%3E%3Cpath+d=%22M12+22V2%22+/%3E%3Cpath+d=%22m14+20.5+1+1%22+/%3E%3Cpath+d=%22M7+13c0-4.5+4.583-8+5-11+.417+3+5+6.5+5+11+0+3.866-2.239+7-5+7s-5-3.134-5-7%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTAgMjAuNS0xIDEiIC8+CiAgPHBhdGggZD0iTTEyIDIwYzUuNTIzIDAgMTAtMy4xMzQgMTAtNyAwLTYuNjkyLTcuNS02LjUtMTAtMTFDOS41IDYuNSAyIDYuMzI5IDIgMTNjMCAzLjg2NiA0LjQ3NyA3IDEwIDciIC8+CiAgPHBhdGggZD0iTTEyIDIyVjIiIC8+CiAgPHBhdGggZD0ibTE0IDIwLjUgMSAxIiAvPgogIDxwYXRoIGQ9Ik03IDEzYzAtNC41IDQuNTgzLTggNS0xMSAuNDE3IDMgNSA2LjUgNSAxMSAwIDMuODY2LTIuMjM5IDctNSA3cy01LTMuMTM0LTUtNyIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m10+20.5-1+1%22+/%3E%3Cpath+d=%22M12+20c5.523+0+10-3.134+10-7+0-6.692-7.5-6.5-10-11C9.5+6.5+2+6.329+2+13c0+3.866+4.477+7+10+7%22+/%3E%3Cpath+d=%22M12+22V8%22+/%3E%3Cpath+d=%22m14+20.5+1+1%22+/%3E%3Cpath+d=%22M16.573+10.566A7.502+7.502+0+0+1+17+13c0+3.866-2.239+7-5+7s-5-3.134-5-7a7.494+7.494+0+0+1+.423-2.422%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTAgMjAuNS0xIDEiIC8+CiAgPHBhdGggZD0iTTEyIDIwYzUuNTIzIDAgMTAtMy4xMzQgMTAtNyAwLTYuNjkyLTcuNS02LjUtMTAtMTFDOS41IDYuNSAyIDYuMzI5IDIgMTNjMCAzLjg2NiA0LjQ3NyA3IDEwIDciIC8+CiAgPHBhdGggZD0iTTEyIDIyVjgiIC8+CiAgPHBhdGggZD0ibTE0IDIwLjUgMSAxIiAvPgogIDxwYXRoIGQ9Ik0xNi41NzMgMTAuNTY2QTcuNTAyIDcuNTAyIDAgMCAxIDE3IDEzYzAgMy44NjYtMi4yMzkgNy01IDdzLTUtMy4xMzQtNS03YTcuNDk0IDcuNDk0IDAgMCAxIC40MjMtMi40MjIiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
Lack of use-cases. A brand is not a valid use-case. If you want the union checkout the [icon](https://lucide.dev/icons/lab/onion) from the Lab project

**Comment by waterplea** [comment]
@ericfennis, out of curiocity why is brand not a valid use-case but lucide has github, facebook, twitter, chrome (which is also a browser) etc?

**Comment by karsa-mistmere** [comment]
> [@ericfennis](https://github.com/ericfennis), out of curiocity why is brand not a valid use-case but lucide has github, facebook, twitter, chrome (which is also a browser) etc?

They're deprecated and marked for eventual removal for a reason.

**Comment by waterplea** [comment]
@karsa-mistmere can I read about it somewhere? Sorry for my ignorance, I'm not familiar with the rules of this pack, I've been reading guide:
https://lucide.dev/guide/#complete-set-of-icons
"Complete set of icons" definitely needs brand icons as well, this section should probably have some disclaimer regarding that. Are they planned for removal for copyright/law reasons?

**Comment by karsa-mistmere** [comment]
> [@karsa-mistmere](https://github.com/karsa-mistmere) can I read about it somewhere?

It’s explained in detail in our pinned GitHub issue (#670), but here’s the short version — otherwise you’ll end up digging into the history of Feather and Material Icons as well. (Fun fact: Google’s icon set used to contain brand logos, but it no longer does, largely for the same reasons described below.)

> "Complete set of icons" definitely needs brand icons as well

Brand logos aren’t really “icons” in the same sense as Lucide’s designs — they’re protected brand assets.

> Sorry for my ignorance, I'm not familiar with the rules of this pack

It’s less about our internal rules and more about what’s legally allowed.

> Are they planned for removal for copyright/law reasons?

Exactly. Almost every brand logo is protected by trademark or copyright, often with detailed brand guidelines that forbid modifications. Since Lucide has its own design language, most brand logos would need to be altered to fit, which would be a violation. That’s why we can’t include them — doing so could result in the same kinds of problems documented in [this Simple Icons issue](https://github.com/simple-icons/simple-icons/issues/11236).

> I've been reading guide: https://lucide.dev/guide/#complete-set-of-icons , this section should probably have some disclaimer regarding that. 

We’re not planning to add such a section, as we don’t want to give the impression that including protected brand logos is a normal or acceptable option. That said, I’m planning to update or replace our pinned issue so the reasons are clearer up front.

**Comment by waterplea** [comment]
Thank you very much for clarifying

**Comment by karsa-mistmere** [comment]
> Thank you very much for clarifying

Thank you for the query, it was truly super useful, as I've now used it as a jumping-off point to draft up an official statement that consolidates every bit of context regarding this matter in #3541
