### ISSUE TITLE
Pill Container

### ISSUE THREAD

**Issue by lilouartz** [lucide-icons/lucide#2173]
### Icon name

Pill Container

### Use cases

Would love to use it as a symbol in place of the word container in the context of supplement data, e.g. https://pillser.com/search?q=vitamin+A&s=2184

### Design ideas

https://zindee.com/wp-content/uploads/2023/10/Pill-Bottle-SS-3.jpg

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
You're not gonna believe this but I was just about to submit a pill bottle PR. 😆
![image](https://github.com/lucide-icons/lucide/assets/17746067/dc11ffbd-2b91-4f81-a00b-8c6da176395b)

**Comment by jguddas** [comment]
@karsa-mistmere your one looks better, but it's distinctly American.
![icon (56)](https://github.com/lucide-icons/lucide/assets/25524993/474c24be-76a8-45bf-9ccb-68562363b1da)
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+15.5h4%22+/%3E%3Cpath+d=%22M12+13.5v4%22+/%3E%3Cpath+d=%22M16+5h1a1+1+0+0+1+1+1v15a1+1+0+0+1-1+1H7a1+1+0+0+1-1-1V6a1+1+0+0+1+1-1h1V3a1+1+0+0+1+1-1h6a1+1+0+0+1+1+1z%22+/%3E%3Cpath+d=%22M6+9h12%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAgMTUuNWg0IiAvPgogIDxwYXRoIGQ9Ik0xMiAxMy41djQiIC8+CiAgPHBhdGggZD0iTTE2IDVoMWExIDEgMCAwIDEgMSAxdjE1YTEgMSAwIDAgMS0xIDFIN2ExIDEgMCAwIDEtMS0xVjZhMSAxIDAgMCAxIDEtMWgxVjNhMSAxIDAgMCAxIDEtMWg2YTEgMSAwIDAgMSAxIDF6IiAvPgogIDxwYXRoIGQ9Ik02IDloMTIiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>
