### ISSUE TITLE
Sort by date icons

### ISSUE THREAD

**Issue by msamiluludag** [lucide-icons/lucide#2177]
### Icon name

arrow-down-clock, arrow-up-clock

### Use cases

It can be used to sort by date added. 

### Design ideas

| ![image](https://github.com/lucide-icons/lucide/assets/23271600/812d77bf-0596-4f89-b3cc-423b5c0a8155) | ![image](https://github.com/lucide-icons/lucide/assets/23271600/11756781-d842-4f21-ac75-47c0ef377199) |
|-------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|
| ![image](https://github.com/lucide-icons/lucide/assets/23271600/51abbd44-caeb-4e32-b8be-4b7e848ab68e) | ![image](https://github.com/lucide-icons/lucide/assets/23271600/a89455f7-85c4-4f7b-a5c1-148dccb31d68) |

![image](https://github.com/lucide-icons/lucide/assets/23271600/d4e3f991-4d42-446d-baa6-694b6afb715e)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
I think these could work:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6v6l1.562.781%22+/%3E%3Cpath+d=%22m14+18+4-4+4+4%22+/%3E%3Cpath+d=%22M18+22v-8%22+/%3E%3Cpath+d=%22M22+12a10+10+0+1+0-10+10%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNnY2bDEuNTYyLjc4MSIgLz4KICA8cGF0aCBkPSJtMTQgMTggNC00IDQgNCIgLz4KICA8cGF0aCBkPSJNMTggMjJ2LTgiIC8+CiAgPHBhdGggZD0iTTIyIDEyYTEwIDEwIDAgMSAwLTEwIDEwIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12+6v6l2+1%22+/%3E%3Cpath+d=%22m14+18+4+4+4-4%22+/%3E%3Cpath+d=%22M18+14v8%22+/%3E%3Cpath+d=%22M22+12a10+10+0+1+0-10+10%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIgNnY2bDIgMSIgLz4KICA8cGF0aCBkPSJtMTQgMTggNCA0IDQtNCIgLz4KICA8cGF0aCBkPSJNMTggMTR2OCIgLz4KICA8cGF0aCBkPSJNMjIgMTJhMTAgMTAgMCAxIDAtMTAgMTAiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m14+18+4-4+4+4%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22M18+22v-8%22+/%3E%3Cpath+d=%22M21+11.5V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h9%22+/%3E%3Cpath+d=%22M3+10h18%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTQgMTggNC00IDQgNCIgLz4KICA8cGF0aCBkPSJNMTYgMnY0IiAvPgogIDxwYXRoIGQ9Ik0xOCAyMnYtOCIgLz4KICA8cGF0aCBkPSJNMjEgMTEuNVY2YTIgMiAwIDAgMC0yLTJINWEyIDIgMCAwIDAtMiAydjE0YTIgMiAwIDAgMCAyIDJoOSIgLz4KICA8cGF0aCBkPSJNMyAxMGgxOCIgLz4KICA8cGF0aCBkPSJNOCAydjQiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m14+18+4+4+4-4%22+/%3E%3Cpath+d=%22M16+2v4%22+/%3E%3Cpath+d=%22M18+14v8%22+/%3E%3Cpath+d=%22M21+11V6a2+2+0+0+0-2-2H5a2+2+0+0+0-2+2v14a2+2+0+0+0+2+2h7%22+/%3E%3Cpath+d=%22M3+10h18%22+/%3E%3Cpath+d=%22M8+2v4%22+/%3E&name=image"><img alt="icons" width="400" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTQgMTggNCA0IDQtNCIgLz4KICA8cGF0aCBkPSJNMTYgMnY0IiAvPgogIDxwYXRoIGQ9Ik0xOCAxNHY4IiAvPgogIDxwYXRoIGQ9Ik0yMSAxMVY2YTIgMiAwIDAgMC0yLTJINWEyIDIgMCAwIDAtMiAydjE0YTIgMiAwIDAgMCAyIDJoNyIgLz4KICA8cGF0aCBkPSJNMyAxMGgxOCIgLz4KICA8cGF0aCBkPSJNOCAydjQiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by NicoToff** [comment]
Looks great! I've used clock plus an arrow so far, instead.
