### ISSUE TITLE
`pencil-off` icon

### ISSUE THREAD

**Issue by Jishai** [lucide-icons/lucide#2178]
### Icon name

pencil-off

### Use cases

For a button that disables editing (Disable user edits) 

### Design ideas

the pencil icon with a diagonal line through it would be great! Similar to eye-off, nabigation-off etc

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Hi @Jishai, I'm happy to report that this just went live in [v0.392.0](https://github.com/lucide-icons/lucide/releases/tag/0.392.0).

Sorry it took us so long, the request itself was pretty straightforward (and a bit of a no-brainer to add), but it did require us to rethink and modernise our pen/pencil icons to make them conform more to our design guidelines.

**Comment by Jishai** [comment]
@karsa-mistmere thanks, that's so awesome!
