### ISSUE TITLE
Package that only includes icons postfixed with "Icon"

### ISSUE THREAD

**Issue by nebrelbug** [lucide-icons/lucide#2193]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

For importing icons, I always use the variant of the import that ends in `Icon`. Ex. `import {LoaderIcon} from "lucide-react"` instead of `import {Loader} from "lucide-react"`.

Making this the default -- or at least publishing a package variant -- would simplify imports and reduce confusion between components.

### Use cases

Every time I type in `<Link>` in my Next.js project, VSCode automatically recommends the Link component from "lucide-react" rather than the Link from "next/link".

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by ericfennis** [comment]
Thanks for your idea.
This is already suggested in #1830, I've also posted a possible solution.

I close this as duplicated.
