### ISSUE TITLE
React icon names wrong

### ISSUE THREAD

**Issue by Daedalusia** [lucide-icons/lucide#2201]
### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

In the Lucide docs, for example https://lucide.dev/icons/square-x under React
It says `<SquareX />`, but it's actually `<XSquare />`.
![image](https://github.com/lucide-icons/lucide/assets/6629056/ae99b70b-0f58-456d-9557-d2be6eb9d245)
![image](https://github.com/lucide-icons/lucide/assets/6629056/9b377557-c989-4185-bc4a-4d2f0f560687)

### Steps to reproduce

As above.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
You haven't provided the version, but based on the bug report above, I'd give it a 99.99% chance that you're using an outdated package, please upgrade.
