### ISSUE TITLE
Sticker icon doesn't have eyes

### ISSUE THREAD

**Issue by Oluwademiladeak** [lucide-icons/lucide#2203]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [X] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.390.0

### Can you reproduce this in the latest version?

- [ ] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When I insert the sticker icon from the Figma plugin, it doesn't include the eye; just the mouth.

### Steps to reproduce

1. Import "lucide/sticker" icon from the Figma plugin.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hi @Oluwademiladeak, thanks for submitting this bug report, we have now resolved this issue, and the fix will be live in [v0.391.0](https://github.com/lucide-icons/lucide/releases/tag/0.391.0) hopefully in a couple of minutes.
