### ISSUE TITLE
Text logs icon

### ISSUE THREAD

**Issue by GRA0007** [lucide-icons/lucide#2214]
### Icon name

text-log

### Use cases

A button to show a list of logs from an application

### Design ideas

Vercel's log icon:
<img width="75" alt="image" src="https://github.com/lucide-icons/lucide/assets/8862273/644e94ca-5f2e-44e3-bba0-35db6097b514">

The `list` icon is what I'm using currently, but it's a little too generic to elicit "logs".

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+10h5%22+/%3E%3Cpath+d=%22M14+14h5%22+/%3E%3Cpath+d=%22M14+18h5%22+/%3E%3Cpath+d=%22M14+6h5%22+/%3E%3Cpath+d=%22M5+10h.01%22+/%3E%3Cpath+d=%22M5+14h.01%22+/%3E%3Cpath+d=%22M5+18h.01%22+/%3E%3Cpath+d=%22M5+6h.01%22+/%3E%3Cpath+d=%22M9+10h1%22+/%3E%3Cpath+d=%22M9+14h1%22+/%3E%3Cpath+d=%22M9+18h1%22+/%3E%3Cpath+d=%22M9+6h1%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTQgMTBoNSIgLz4KICA8cGF0aCBkPSJNMTQgMTRoNSIgLz4KICA8cGF0aCBkPSJNMTQgMThoNSIgLz4KICA8cGF0aCBkPSJNMTQgNmg1IiAvPgogIDxwYXRoIGQ9Ik01IDEwaC4wMSIgLz4KICA8cGF0aCBkPSJNNSAxNGguMDEiIC8+CiAgPHBhdGggZD0iTTUgMThoLjAxIiAvPgogIDxwYXRoIGQ9Ik01IDZoLjAxIiAvPgogIDxwYXRoIGQ9Ik05IDEwaDEiIC8+CiAgPHBhdGggZD0iTTkgMTRoMSIgLz4KICA8cGF0aCBkPSJNOSAxOGgxIiAvPgogIDxwYXRoIGQ9Ik05IDZoMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

or

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M14+10h6%22+/%3E%3Cpath+d=%22M14+14h6%22+/%3E%3Cpath+d=%22M14+18h6%22+/%3E%3Cpath+d=%22M14+6h6%22+/%3E%3Cpath+d=%22M5+10H4%22+/%3E%3Cpath+d=%22M5+14H4%22+/%3E%3Cpath+d=%22M5+18H4%22+/%3E%3Cpath+d=%22M5+6H4%22+/%3E%3Cpath+d=%22M9+10h1%22+/%3E%3Cpath+d=%22M9+14h1%22+/%3E%3Cpath+d=%22M9+18h1%22+/%3E%3Cpath+d=%22M9+6h1%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTQgMTBoNiIgLz4KICA8cGF0aCBkPSJNMTQgMTRoNiIgLz4KICA8cGF0aCBkPSJNMTQgMThoNiIgLz4KICA8cGF0aCBkPSJNMTQgNmg2IiAvPgogIDxwYXRoIGQ9Ik01IDEwSDQiIC8+CiAgPHBhdGggZD0iTTUgMTRINCIgLz4KICA8cGF0aCBkPSJNNSAxOEg0IiAvPgogIDxwYXRoIGQ9Ik01IDZINCIgLz4KICA8cGF0aCBkPSJNOSAxMGgxIiAvPgogIDxwYXRoIGQ9Ik05IDE0aDEiIC8+CiAgPHBhdGggZD0iTTkgMThoMSIgLz4KICA8cGF0aCBkPSJNOSA2aDEiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M10+12H4%22+/%3E%3Cpath+d=%22M14+4h6%22+/%3E%3Cpath+d=%22M15+12h-1%22+/%3E%3Cpath+d=%22M15+16H9%22+/%3E%3Cpath+d=%22M15+20H4%22+/%3E%3Cpath+d=%22M19+12h1%22+/%3E%3Cpath+d=%22M20+16h-1%22+/%3E%3Cpath+d=%22M20+20h-1%22+/%3E%3Cpath+d=%22M5+16H4%22+/%3E%3Cpath+d=%22M5+4H4%22+/%3E%3Cpath+d=%22M5+8H4%22+/%3E%3Cpath+d=%22M9+4h1%22+/%3E%3Cpath+d=%22M9+8h11%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTAgMTJINCIgLz4KICA8cGF0aCBkPSJNMTQgNGg2IiAvPgogIDxwYXRoIGQ9Ik0xNSAxMmgtMSIgLz4KICA8cGF0aCBkPSJNMTUgMTZIOSIgLz4KICA8cGF0aCBkPSJNMTUgMjBINCIgLz4KICA8cGF0aCBkPSJNMTkgMTJoMSIgLz4KICA8cGF0aCBkPSJNMjAgMTZoLTEiIC8+CiAgPHBhdGggZD0iTTIwIDIwaC0xIiAvPgogIDxwYXRoIGQ9Ik01IDE2SDQiIC8+CiAgPHBhdGggZD0iTTUgNEg0IiAvPgogIDxwYXRoIGQ9Ik01IDhINCIgLz4KICA8cGF0aCBkPSJNOSA0aDEiIC8+CiAgPHBhdGggZD0iTTkgOGgxMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

I also came up with this one, but I don't think this represents "logs" too much, it feels like just text

**Comment by GRA0007** [comment]
Thanks @AndreasSas, my preference is the second option. I've tried both the second and third in context, and while the third icon is technically square, it seems a little too tall.

Forgive my lack of knowledge about the specifics of the lucide guidelines, but I almost prefer the second option if it's a little more spaced out like so:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M+14+14.5+L+20+14.5%22+/%3E%3Cpath+d=%22M+14+19.5+L+20+19.5%22+/%3E%3Cpath+d=%22M+14+4.5+L+20+4.5%22+/%3E%3Cpath+d=%22M+14+9.5+L+20+9.5%22+/%3E%3Cpath+d=%22M+5+14.5+L+4+14.5%22+/%3E%3Cpath+d=%22M+5+19.5+L+4+19.5%22+/%3E%3Cpath+d=%22M+5+4.5+L+4+4.5%22+/%3E%3Cpath+d=%22M+5+9.5+L+4+9.5%22+/%3E%3Cpath+d=%22M+9+14.5+L+10+14.5%22+/%3E%3Cpath+d=%22M+9+19.5+L+10+19.5%22+/%3E%3Cpath+d=%22M+9+4.5+L+10+4.5%22+/%3E%3Cpath+d=%22M+9+9.5+L+10+9.5%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNIDE0IDE0LjUgTCAyMCAxNC41IiAvPgogIDxwYXRoIGQ9Ik0gMTQgMTkuNSBMIDIwIDE5LjUiIC8+CiAgPHBhdGggZD0iTSAxNCA0LjUgTCAyMCA0LjUiIC8+CiAgPHBhdGggZD0iTSAxNCA5LjUgTCAyMCA5LjUiIC8+CiAgPHBhdGggZD0iTSA1IDE0LjUgTCA0IDE0LjUiIC8+CiAgPHBhdGggZD0iTSA1IDE5LjUgTCA0IDE5LjUiIC8+CiAgPHBhdGggZD0iTSA1IDQuNSBMIDQgNC41IiAvPgogIDxwYXRoIGQ9Ik0gNSA5LjUgTCA0IDkuNSIgLz4KICA8cGF0aCBkPSJNIDkgMTQuNSBMIDEwIDE0LjUiIC8+CiAgPHBhdGggZD0iTSA5IDE5LjUgTCAxMCAxOS41IiAvPgogIDxwYXRoIGQ9Ik0gOSA0LjUgTCAxMCA0LjUiIC8+CiAgPHBhdGggZD0iTSA5IDkuNSBMIDEwIDkuNSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Comment by AndreasSas** [comment]
> Thanks @AndreasSas, my preference is the second option. I've tried both the second and third in context, and while the third icon is technically square, it seems a little too tall.
> 
> Forgive my lack of knowledge about the specifics of the lucide guidelines, but I almost prefer the second option if it's a little more spaced out like so:
> 
> [<img alt="icons" width="120" src="https://camo.githubusercontent.com/e561aef301a0817f4b39c535aa463cd6feb3ba716431f4784441048231d31c98/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e49444530494445304c6a5567544341794d4341784e4334314969417650676f67494478775958526f49475139496b30674d5451674d546b754e53424d49444977494445354c6a55694943382b4369416750484268644767675a443069545341784e4341304c6a5567544341794d4341304c6a55694943382b4369416750484268644767675a443069545341784e4341354c6a5567544341794d4341354c6a55694943382b4369416750484268644767675a44306954534131494445304c6a556754434130494445304c6a55694943382b4369416750484268644767675a44306954534131494445354c6a556754434130494445354c6a55694943382b4369416750484268644767675a44306954534131494451754e53424d494451674e4334314969417650676f67494478775958526f49475139496b30674e5341354c6a55675443413049446b754e5349674c7a344b49434138634746306143426b50534a4e49446b674d5451754e53424d49444577494445304c6a55694943382b4369416750484268644767675a44306954534135494445354c6a5567544341784d4341784f5334314969417650676f67494478775958526f49475139496b30674f5341304c6a5567544341784d4341304c6a55694943382b4369416750484268644767675a4430695453413549446b754e53424d4944457749446b754e5349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M+14+14.5+L+20+14.5%22+/%3E%3Cpath+d=%22M+14+19.5+L+20+19.5%22+/%3E%3Cpath+d=%22M+14+4.5+L+20+4.5%22+/%3E%3Cpath+d=%22M+14+9.5+L+20+9.5%22+/%3E%3Cpath+d=%22M+5+14.5+L+4+14.5%22+/%3E%3Cpath+d=%22M+5+19.5+L+4+19.5%22+/%3E%3Cpath+d=%22M+5+4.5+L+4+4.5%22+/%3E%3Cpath+d=%22M+5+9.5+L+4+9.5%22+/%3E%3Cpath+d=%22M+9+14.5+L+10+14.5%22+/%3E%3Cpath+d=%22M+9+19.5+L+10+19.5%22+/%3E%3Cpath+d=%22M+9+4.5+L+10+4.5%22+/%3E%3Cpath+d=%22M+9+9.5+L+10+9.5%22+/%3E)

Yeah I see what you mean with the rhird icon feeling too tall.
I don't know if the extra spacing you introduced is up to the guidelines, given [rule 8](https://lucide.dev/guide/design/icon-design-guide#_8-distinct-elements-must-have-2-pixels-of-spacing-between-each-other) but haven't contributed much so far, so I don't know if that would count here as well

**Comment by GRA0007** [comment]
Ah yeah thanks for linking that rule. This icon feels very similar to the list icon though, which also appears to break that rule:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cline+x1=%223%22+y1=%2212%22+x2=%223.01%22+y2=%2212%22+/%3E%3Cline+x1=%223%22+y1=%2218%22+x2=%223.01%22+y2=%2218%22+/%3E%3Cline+x1=%223%22+y1=%226%22+x2=%223.01%22+y2=%226%22+/%3E%3Cline+x1=%228%22+y1=%2212%22+x2=%2221%22+y2=%2212%22+/%3E%3Cline+x1=%228%22+y1=%2218%22+x2=%2221%22+y2=%2218%22+/%3E%3Cline+x1=%228%22+y1=%226%22+x2=%2221%22+y2=%226%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8bGluZSB4MT0iMyIgeTE9IjEyIiB4Mj0iMy4wMSIgeTI9IjEyIiAvPgogIDxsaW5lIHgxPSIzIiB5MT0iMTgiIHgyPSIzLjAxIiB5Mj0iMTgiIC8+CiAgPGxpbmUgeDE9IjMiIHkxPSI2IiB4Mj0iMy4wMSIgeTI9IjYiIC8+CiAgPGxpbmUgeDE9IjgiIHkxPSIxMiIgeDI9IjIxIiB5Mj0iMTIiIC8+CiAgPGxpbmUgeDE9IjgiIHkxPSIxOCIgeDI9IjIxIiB5Mj0iMTgiIC8+CiAgPGxpbmUgeDE9IjgiIHkxPSI2IiB4Mj0iMjEiIHkyPSI2IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

But yeah, that also feels like it might not apply here.

**Comment by ericfennis** [comment]
It would be nice if it matches the `list` icon.

**Comment by GRA0007** [comment]
In that case, maybe something like this would be more appropriate:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13+12h8%22+/%3E%3Cpath+d=%22M13+18h8%22+/%3E%3Cpath+d=%22M13+6h8%22+/%3E%3Cpath+d=%22M3+12h1%22+/%3E%3Cpath+d=%22M3+18h1%22+/%3E%3Cpath+d=%22M3+6h1%22+/%3E%3Cpath+d=%22M8+12h1%22+/%3E%3Cpath+d=%22M8+18h1%22+/%3E%3Cpath+d=%22M8+6h1%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMgMTJoOCIgLz4KICA8cGF0aCBkPSJNMTMgMThoOCIgLz4KICA8cGF0aCBkPSJNMTMgNmg4IiAvPgogIDxwYXRoIGQ9Ik0zIDEyaDEiIC8+CiAgPHBhdGggZD0iTTMgMThoMSIgLz4KICA8cGF0aCBkPSJNMyA2aDEiIC8+CiAgPHBhdGggZD0iTTggMTJoMSIgLz4KICA8cGF0aCBkPSJNOCAxOGgxIiAvPgogIDxwYXRoIGQ9Ik04IDZoMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
@GRA0007 To me that does not look that bad.

**Comment by GRA0007** [comment]
What do you think @AndreasSas? If you're happy with it do you want to open a PR?
