### ISSUE TITLE
Install error in react 19 (next 15)

### ISSUE THREAD

**Issue by chakeawx** [lucide-icons/lucide#2216]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.394.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

```bash
$ npm i lucide-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@19.0.0-rc.0
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.1 || ^17.0.0 || ^18.0.0" from lucide-react@0.394.0
npm ERR! node_modules/lucide-react
npm ERR!   lucide-react@"^0.394.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\chakeawx\AppData\Local\npm-cache\_logs\2024-06-12T09_23_37_917Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\chakeawx\AppData\Local\npm-cache\_logs\2024-06-12T09_23_37_917Z-debug-0.log
```

### Steps to reproduce

1. init nextjs (version 15)
2. install lucide-react

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by mongkunkham92-svg** [comment]
npm i lucide-react --legacy-peer-deps

**Comment by mongkunkham92-svg** [comment]
install lucide-react

**Comment by mongkunkham92-svg** [comment]
npm create vite@latest

**Comment by karsa-mistmere** [comment]
> ### Version
> 
> 0.394.0

This is your real issue, that version is _ancient_, just use the latest https://github.com/lucide-icons/lucide/releases/tag/0.536.0
