### ISSUE TITLE
Raindrop Percentage Icon

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [lucide-icons/lucide#2217]
### Icon name

Raindrop Percentage / Droplet Percentage

### Use cases

For showing humidity in my weather app

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/77451351/73f79119-9f59-4f7b-a343-d69828aaaadb)
![image](https://github.com/lucide-icons/lucide/assets/77451351/7b12fe2f-3580-4269-b34d-43d0b36d8301)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by ericfennis** [comment]
@FleetAdmiralJakob Why not just use the drop icon?

**Comment by ericfennis** [comment]
Sorry, we are not going to add this one. From a design perspective, it is a bit unlogical to add a percentage symbol, since in the usecase for example humidity the percentage symbol will always be shown together with the metric. However, if more people want this for some reason we can reconsider this.

**Comment by karsa-mistmere** [comment]
I kinda agree with Eric here, but I'm leaving these alternate `droplet` & `droplet-percentage` icons here anyway:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M4+14C4+9.007+9.539+3.807+11.399+2.2a1+1+0+0+1+1.202+0C14.461+3.808+20+9.008+20+14a8+8+0+0+1-16+0%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNNCAxNEM0IDkuMDA3IDkuNTM5IDMuODA3IDExLjM5OSAyLjJhMSAxIDAgMCAxIDEuMjAyIDBDMTQuNDYxIDMuODA4IDIwIDkuMDA4IDIwIDE0YTggOCAwIDAgMS0xNiAwIiAvPgo8L3N2Zz4=.svg"/></a> <a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22m15+11-6+6%22+/%3E%3Cpath+d=%22M15+17h.01%22+/%3E%3Cpath+d=%22M4+14C4+9.007+9.539+3.807+11.399+2.2a1+1+0+0+1+1.202+0C14.461+3.808+20+9.008+20+14a8+8+0+0+1-16+0%22+/%3E%3Cpath+d=%22M9+11h.01%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJtMTUgMTEtNiA2IiAvPgogIDxwYXRoIGQ9Ik0xNSAxN2guMDEiIC8+CiAgPHBhdGggZD0iTTQgMTRDNCA5LjAwNyA5LjUzOSAzLjgwNyAxMS4zOTkgMi4yYTEgMSAwIDAgMSAxLjIwMiAwQzE0LjQ2MSAzLjgwOCAyMCA5LjAwOCAyMCAxNGE4IDggMCAwIDEtMTYgMCIgLz4KICA8cGF0aCBkPSJNOSAxMWguMDEiIC8+Cjwvc3ZnPg==.svg"/></a>
