### ISSUE TITLE
Missing icon "contact-round"

### ISSUE THREAD

**Issue by Thoufak** [lucide-icons/lucide#2222]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.350.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When I try to use the icon "contact-round" I get this warning in the browser console:
`<i data-lucide="contact-round" class="me-2"></i> icon name was not found in the provided icons object.`

This is how I render the icons:
```
import {createIcons, icons} from "lucide";
createIcons({icons})
```

Also, when I search for "contact-round" and "ContactRound" in the `node_modules/lucide/`I can't find anything. There's only "Contact" and "Contact2".

Please note that I've also seen this happening with some other icons.

### Steps to reproduce

1. Use HTML: `<i data-lucide="contact-round" class="me-2"></i>`
2. Use JS: `import {createIcons, icons} from "lucide";` and then `createIcons({icons})`

The icon doesn't show up, and there's a warning in the console.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
What version?

**Comment by Thoufak** [comment]
lucide@0.395.0

**Comment by Thoufak** [comment]
Sorry, I wasn't using the latest version. Updating helped.
