### ISSUE TITLE
In JavaScript, `Infinity` is a reserved word.

### ISSUE THREAD

**Issue by hirotomoyamada** [lucide-icons/lucide#2226]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [X] lucide-preact
- [X] lucide-react
- [X] lucide-react-native
- [X] lucide-solid
- [X] lucide-svelte
- [X] lucide-vue
- [X] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.395.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

In JavaScript, Infinity is after reserved. So you cannot use `Infinity` in the name of an icon.

### Steps to reproduce

Writing the documentation site example to a file causes an error.

```tsx
import { Infinity } from 'lucide-react';

const App = () => {
  return (
    <Infinity />
  );
};

export default App;
```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Can't reproduce.

<img width="1189" alt="image" src="https://github.com/lucide-icons/lucide/assets/25524993/2fca0ac6-e476-42a7-b940-037eda447e1a">

**Comment by hirotomoyamada** [comment]
Sorry. It seems I was mistaken. :(
