### ISSUE TITLE
save-off

### ISSUE THREAD

**Issue by schnuet** [lucide-icons/lucide#2227]
### Icon name

save-off

### Use cases

This icon could indicate that saving is disallowed, deactivated or impossible.

**Examples**
* Button for autosaving a file: icon "save" for activated status, icon "save-off" for inactive status
* Indicator icon in a offline-synchronizing list: entries with the save icon have been synchronized, entries with the save-off icon could not be saved
* Deactivated save button in a user interface: the save-off icon can indicate that saving the file is not currently possible.

Using the save-off icon instead of simply greying off a save icon could provide a clearer meaning to users.

### Design ideas

Like the other *-off variants (eye-off, pen-off, star-off, ...), the save-off icon should be based on the base icon (save) with a line striking it through.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by AndreasSas** [comment]
![save-off](https://github.com/lucide-icons/lucide/assets/74367457/a04ef7d9-74b2-4b63-8f3a-ddb6f01b16a4)
I tried to adhere as much as I could to the other `*-off` icons, but the little tab at the top of the icon is almost completely removed by the spacing around the diagonal strike-through.

**Comment by jguddas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13+13H8a1+1+0+0+0-1+1v7%22+/%3E%3Cpath+d=%22M17+21v-4%22+/%3E%3Cpath+d=%22m2+2+20+20%22+/%3E%3Cpath+d=%22M20.418+20.41a2+2+0+0+1-1.41.59H5a2+2+0+0+1-2-2V5a2+2+0+0+1+.59-1.41%22+/%3E%3Cpath+d=%22M8+8h7%22+/%3E%3Cpath+d=%22M8.5+3h6.7a2+2+0+0+1+1.4.6l3.8+3.8a2+2+0+0+1+.6+1.4v6.7%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMgMTNIOGExIDEgMCAwIDAtMSAxdjciIC8+CiAgPHBhdGggZD0iTTE3IDIxdi00IiAvPgogIDxwYXRoIGQ9Im0yIDIgMjAgMjAiIC8+CiAgPHBhdGggZD0iTTIwLjQxOCAyMC40MWEyIDIgMCAwIDEtMS40MS41OUg1YTIgMiAwIDAgMS0yLTJWNWEyIDIgMCAwIDEgLjU5LTEuNDEiIC8+CiAgPHBhdGggZD0iTTggOGg3IiAvPgogIDxwYXRoIGQ9Ik04LjUgM2g2LjdhMiAyIDAgMCAxIDEuNC42bDMuOCAzLjhhMiAyIDAgMCAxIC42IDEuNHY2LjciIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M12,3v4c0,.55.45,1,1,1h2%22+/%3E%3Cpath+d=%22M13,13h-5c-.55,0-1,.45-1,1v7%22+/%3E%3Cpath+d=%22M17,21v-4%22+/%3E%3Cpath+d=%22M2,2l20,20%22+/%3E%3Cpath+d=%22M20.41,20.41c-.36.36-.86.59-1.41.59H5c-1.1,0-2-.9-2-2V5c0-.55.22-1.05.59-1.41%22+/%3E%3Cpath+d=%22M9,3h6.2c.53,0,1.03.22,1.4.6l3.8,3.8c.38.37.59.87.6,1.4v6.2%22+/%3E&dialog=false&name=save-off"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTIsM3Y0YzAsLjU1LjQ1LDEsMSwxaDIiIC8+CiAgPHBhdGggZD0iTTEzLDEzaC01Yy0uNTUsMC0xLC40NS0xLDF2NyIgLz4KICA8cGF0aCBkPSJNMTcsMjF2LTQiIC8+CiAgPHBhdGggZD0iTTIsMmwyMCwyMCIgLz4KICA8cGF0aCBkPSJNMjAuNDEsMjAuNDFjLS4zNi4zNi0uODYuNTktMS40MS41OUg1Yy0xLjEsMC0yLS45LTItMlY1YzAtLjU1LjIyLTEuMDUuNTktMS40MSIgLz4KICA8cGF0aCBkPSJNOSwzaDYuMmMuNTMsMCwxLjAzLjIyLDEuNC42bDMuOCwzLjhjLjM4LjM3LjU5Ljg3LjYsMS40djYuMiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Comment by ericfennis** [comment]
I think the variant of @jguddas is the right fit

**Comment by ericfennis** [comment]
@zoharma hmm true. Why not just a little dot, or does it look weird?

**Comment by AndreasSas** [comment]
> @zoharma hmm true. Why not just a little dot, or does it look weird?

small dot:
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13+13H8a1+1+0+0+0-1+1v7%22+/%3E%3Cpath+d=%22M15+8h.01%22+/%3E%3Cpath+d=%22M17+21v-4%22+/%3E%3Cpath+d=%22m2+2+20+20%22+/%3E%3Cpath+d=%22M20.41+20.41A2+2+0+0+1+19+21H5a2+2+0+0+1-2-2V5a2+2+0+0+1+.59-1.41%22+/%3E%3Cpath+d=%22M29.5+11.5s5+5+4+5%22+/%3E%3Cpath+d=%22M9+3h6.2a2+2+0+0+1+1.4.6l3.8+3.8a2+2+0+0+1+.6+1.4V15%22+/%3E&dialog=false&name=save-off"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMgMTNIOGExIDEgMCAwIDAtMSAxdjciIC8+CiAgPHBhdGggZD0iTTE1IDhoLjAxIiAvPgogIDxwYXRoIGQ9Ik0xNyAyMXYtNCIgLz4KICA8cGF0aCBkPSJtMiAyIDIwIDIwIiAvPgogIDxwYXRoIGQ9Ik0yMC40MSAyMC40MUEyIDIgMCAwIDEgMTkgMjFINWEyIDIgMCAwIDEtMi0yVjVhMiAyIDAgMCAxIC41OS0xLjQxIiAvPgogIDxwYXRoIGQ9Ik0yOS41IDExLjVzNSA1IDQgNSIgLz4KICA8cGF0aCBkPSJNOSAzaDYuMmEyIDIgMCAwIDEgMS40LjZsMy44IDMuOGEyIDIgMCAwIDEgLjYgMS40VjE1IiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

tiny line:
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M13+13H8a1+1+0+0+0-1+1v7%22+/%3E%3Cpath+d=%22M14+8h1%22+/%3E%3Cpath+d=%22M17+21v-4%22+/%3E%3Cpath+d=%22m2+2+20+20%22+/%3E%3Cpath+d=%22M20.41+20.41A2+2+0+0+1+19+21H5a2+2+0+0+1-2-2V5a2+2+0+0+1+.59-1.41%22+/%3E%3Cpath+d=%22M29.5+11.5s5+5+4+5%22+/%3E%3Cpath+d=%22M9+3h6.2a2+2+0+0+1+1.4.6l3.8+3.8a2+2+0+0+1+.6+1.4V15%22+/%3E&dialog=false&name=save-off"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTMgMTNIOGExIDEgMCAwIDAtMSAxdjciIC8+CiAgPHBhdGggZD0iTTE0IDhoMSIgLz4KICA8cGF0aCBkPSJNMTcgMjF2LTQiIC8+CiAgPHBhdGggZD0ibTIgMiAyMCAyMCIgLz4KICA8cGF0aCBkPSJNMjAuNDEgMjAuNDFBMiAyIDAgMCAxIDE5IDIxSDVhMiAyIDAgMCAxLTItMlY1YTIgMiAwIDAgMSAuNTktMS40MSIgLz4KICA8cGF0aCBkPSJNMjkuNSAxMS41czUgNSA0IDUiIC8+CiAgPHBhdGggZD0iTTkgM2g2LjJhMiAyIDAgMCAxIDEuNC42bDMuOCAzLjhhMiAyIDAgMCAxIC42IDEuNFYxNSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

I honestly don't know which one looks better. My preference goes to the tiny line version

**Comment by ericfennis** [comment]
I agree with @zoharma !
