### ISSUE TITLE
Philippine Peso Icon

### ISSUE THREAD

**Issue by kasutu** [lucide-icons/lucide#2230]
### Icon name

philippine-peso

### Use cases

The popularity of t3 stack is helpful to us filipino developers and designers. It would be great if we can have something to represent the philippine currency for localized commercial/hobby apps as other SVG icons did not match with the lucide aesthetic.

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/64959978/cb702e61-8208-4413-9a97-b17c75bce0db)

the lucide-dollar sign width looks great on "P"

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
![icon (61)](https://github.com/lucide-icons/lucide/assets/25524993/78fc447b-fdb8-494a-a172-14b64ef90e29)
