### ISSUE TITLE
Home icon is documented as House

### ISSUE THREAD

**Issue by lukeojones** [lucide-icons/lucide#2255]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.396.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

The documentation of the 'Home' icon suggests that the icon is called 'House' but this is not exported from the lucide-react module. Importing the 'Home' icon works as expected and appears to match the 'House' icon on the [lucide website](https://lucide.dev/icons/house).

### Steps to reproduce

1. Import 'House' from 'lucide-react'.
2. Transpiler error showing that 'lucide-react' has no export named 'House'.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by liydaco** [comment]
Same problem, weird error

**Comment by karsa-mistmere** [comment]
This was recently renamed to better confine to our guidelines. Please upgrade to the latest version.

**Comment by kasperadk** [comment]
@karsa-mistmere The docs still list this as `<House />`: https://lucide.dev/icons/house

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere The docs still list this as `<House />`: https://lucide.dev/icons/house

It is `<House />`, so that is correct.

**Comment by jguddas** [comment]
I guess @kasperadk is talking about the category bellow the name.

**Comment by kasperadk** [comment]
Okay, but in the `lucide-react` package (version 0.453.0) it still refers to it as `<Home />` and also links to a 404-page.

![image](https://github.com/user-attachments/assets/78ab5740-de6a-49be-b3a3-b9c4a83b1cf3)

**Comment by karsa-mistmere** [comment]
> Okay, but in the `lucide-react` package (version 0.453.0) it still refers to it as `<Home />` and also links to a 404-page.
> 
> ![image](https://private-user-images.githubusercontent.com/79222410/380095415-78ab5740-de6a-49be-b3a3-b9c4a83b1cf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDg0NTYsIm5iZiI6MTcyOTg0ODE1NiwicGF0aCI6Ii83OTIyMjQxMC8zODAwOTU0MTUtNzhhYjU3NDAtZGU2YS00OWJlLWIzYTMtYjljNGE4M2IxY2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA5MjIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTVlOWMyOGM4MjY5MWM5ZjQ4NmVjMjMyZTY1MTMwNTNmYzAwYWYxNWNiNzI0ZWViYTIzYjE0MDc5ZDgyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZPeXOc6p8Kw3ghDjg2WPNQgt8xwImWiJFHs5V5y0-ww)

This is just a backwards compatible reexport of `House`.

We might need to add redirects for old names on the site though, I though that was already fixed.

**Comment by kasperadk** [comment]
@karsa-mistmere Ah, I can see it works now, it's just the types that are complaining. Maybe something needs to be updated here?
![image](https://github.com/user-attachments/assets/06d95716-dda9-46aa-bbe8-42c72a299187)

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere Ah, I can see it works now, it's just the types that are complaining. Maybe something needs to be updated here?

I cannot reproduce this error, maybe you have a peer dependency on an earlier version of Lucide somewhere or some custom `types` configuration in your tsconfig.json? Can you check if you have anything out of the ordinary there and run `npm ls lucide-react`?

**Comment by kasperadk** [comment]
@karsa-mistmere Sorry! It was my TS server that was bugging after update. All is good now. My apologies.
