### ISSUE TITLE
Typescript typing

### ISSUE THREAD

**Issue by Aviortheking** [lucide-icons/lucide#226]
## Prerequisites

* Version: lucide-react 0.13
* Are you running from source/master: nop
* Are you using a released build: yes
* Operating system: don't matter
* Bits:

Adding Typing for Typescript would be awesome as it is the only thing that don't move me from `react-feather` to `lucid-react` :D

**Comment by ericfennis** [comment]
Thanks for posting this @Aviortheking, this is high on my list! Will look in to it soon!
