### ISSUE TITLE
Using it in astro.js

### ISSUE THREAD

**Issue by TheMikeyRoss** [lucide-icons/lucide#2268]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.399.0

### Can you reproduce this in the latest version?

- [ ] Yes
- [X] No

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [X] Safari
- [X] Edge
- [X] iOS Safari
- [X] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

I'm having a hard time getting it to work on Astro even after following the "vanilla" section of the docs.

Is it possible to make it work similar to how ionic icons does it ? https://github.com/ionic-team/ionicons?tab=readme-ov-file#basic-usage

Where I can just add the unpkg script and then use a html elemnt like
 ```
<lucide-icon name="menu"/>
```

### Steps to reproduce

1. Create a new astro.js site
2. Following the Lucide instruction for the vanilla section
3. You won't see the icon you're trying to use

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by FleetAdmiralJakob** [comment]
Do you have any problems with using this project: https://github.com/dzeiocom/lucide-astro ?

**Comment by TheMikeyRoss** [comment]
> Do you have any problems with using this project: https://github.com/dzeiocom/lucide-astro ?

No, I've been using it actually. I just forgot to close this issue. Thanks.
