### ISSUE TITLE
Flutter package is not being maintained?

### ISSUE THREAD

**Issue by Kvarzsiev** [lucide-icons/lucide#2270]
### Package

- [ ] lucide
- [ ] lucide-angular
- [X] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.257.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

I need to use icons present in the newer versions of Lucide, but Flutter's package has not been updated since last year or so.

I'm sorry if this is not the right way to open this request. I can change it upon further guidance.

### Steps to reproduce

https://pub.dev/packages/lucide_icons/versions

Just try to use an icon that was added on any version bigger than 0.257.0

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
See #1692
