### ISSUE TITLE
copy-save

### ISSUE THREAD

**Issue by schnuet** [lucide-icons/lucide#2286]
### Icon name

copy-save

### Use cases

* Saving a copy of a currently open file
* This could be used for "save as" functions

### Design ideas

I thought a merge of the copy-* icons style and the save icon should do the trick - when we're saving a new file, we're basically creating a copy of the open file and saving over that copy.

So, something like this:
![copy-save](https://github.com/lucide-icons/lucide/assets/7512320/a843b0a2-aaba-4558-8e09-a2472c9a2bb8)
?

Not sure if copy-save is the right name. Could also be copy-floppy-disk or save-as?

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
We already have [`save-all`](https://lucide.dev/icons/save-all), which looks practically identical.
