### ISSUE TITLE
Add Slack icon

### ISSUE THREAD

**Issue by Abhrajitdas02** [lucide-icons/lucide#2288]
### Icon name

Slack

### Use cases

I need to use it in rated system

### Design ideas

Simple like the original slack icon according to the original app

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
We already have a [`slack`](https://lucide.dev/icons/slack) icon, but keep in mind, that it's deprecated and will be removed in v1.0, see #94 #670
