### ISSUE TITLE
Feature : Add filled prop for filled icons

### ISSUE THREAD

**Issue by alamenai** [lucide-icons/lucide#2290]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Lucide icons are good for web development, but sometimes we need some filled icons instead of the outline. Currently, we have color, size, strokeSize. I would suggest to add `type` prop which allow us to choose between the `outline` or `filled` icons.

### Use cases

1. Using the icon as an interactive component.
2. When changing or indicating the status of the component.
3. Primary actions.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
See discussions in #458 and https://lucide.dev/guide/advanced/filled-icons
