### ISSUE TITLE
Horizontal Icons are spelled wrong

### ISSUE THREAD

**Issue by ThomasBouasli** [lucide-icons/lucide#2296]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.401.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

There are some icons with **Horizontal** spelled as **Horizonal**, such as:

- SendHorizonal
- BetweenHorizonalEnd
- BetweenHorizonalStart
- LucideSendHorizonal

Not a huge issue but it does mess up local spell checkers.

### Steps to reproduce

import any of the previously mentioned components.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
See the explanation in #2297 

Just use the new, fixed names, these ones are marked as deprecated.
