### ISSUE TITLE
Some ellipsis icons are missing the "more" label

### ISSUE THREAD

**Issue by msamiluludag** [lucide-icons/lucide#2309]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [X] site

### Description

I think the `more` tag should be added to all ellipsis icons. 

Current:

![image](https://github.com/lucide-icons/lucide/assets/23271600/193c470b-a27f-4752-bdad-511bd1d540c5)

### Use cases

It can be used for menu.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by Jay-Karia** [comment]
I agree
