### ISSUE TITLE
Request: Add anything

### ISSUE THREAD

**Issue by selfagency** [lucide-icons/lucide#2313]
### Icon name

Literally anything

### Use cases

![Bluesky Image](https://github.com/user-attachments/assets/ce9cb64c-d0c3-4f0d-9d32-7549b74a990a)

Currently your library has 1488 icons. 1488 is a well-known white supremacist code for "The 14 Words," which is a statement about "preserving the white future" and 88 being the eighth letter of the alphabet twice, ie., HH, which you can I'm sure deduce the meaning of. So I'm asking you to add literally ANYTHING to bump that number up to 1489 so I, a grandchild of four Holocaust survivors, don't have to stare at that number every time I search for an icon on your website.

### Design ideas

How about a cash register? 

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols. ← **Quite the opposite, in fact**
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
Ohhhh, that's absolutely unacceptable.
Thank you for reporting this, let me get this fixed ASAP.

**Comment by Cyberes** [comment]
Cash register?

**Comment by kewldan** [comment]
now is 1489, so problem is solved!

**Comment by selfagency** [comment]
I'm glad you racist assholes are having a fun time.
