### ISSUE TITLE
'LockKeyholeOpenIcon' is not exported 

### ISSUE THREAD

**Issue by whyte25** [lucide-icons/lucide#2314]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.408.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

I tried to import LockKeyholeOpenIcon from lucide-react, but I got the following error:

Attempted import error: 'LockKeyholeOpenIcon' is not exported from '__barrel_optimize__?names=BadgeCheck,LockKeyhole,LockKeyholeOpenIcon!=!lucide-react' (imported as 'LockKeyholeOpenIcon').

### Steps to reproduce

import {  LockKeyholeOpen } from "lucide-react";

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Please update your package and come back to tell us if that helped :)

**Comment by emmyoh** [comment]
Getting the same thing. Putting it on its own import line was the only fix. This seems like a Next.js bug?
