### ISSUE TITLE
Dynamic color update not working in Angular 18.1 with property binding

### ISSUE THREAD

**Issue by koddist** [lucide-icons/lucide#2315]
### Package

- [ ] lucide
- [X] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.407.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When using Lucide icons in Angular 18.1, dynamically updating the icon color using property binding `[color]="dynamicColorValue"` does not work as expected. The color attribute is updated in the DOM, but the icon's color does not change visually. This appears to be a compatibility issue between Lucide icons and Angular 18.1.

### Steps to reproduce

1. In a component template, add a Lucide icon with dynamic color binding:
```html
<lucide-icon size="20" class="centered-icon" name="credit-card" [color]="dynamicColorValue"/>
```
2. In the component's TypeScript file, define dynamicColorValue and update it based on some logic:
```typescript
dynamicColorValue: string = 'black';

changeColor() {
  this.dynamicColorValue = 'red';
}
```
3. Trigger the color change (e.g., by calling `changeColor()` method).
4. Observe that while the color attribute in the DOM is updated, the icon's visual color remains unchanged.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hey @koddist,

This is unfortunately not just the case for Angular 18.1, but also all earlier versions, I've submitted a PR fixing this issue.
Thanks for bringing this to my attention.
