### ISSUE TITLE
Multiple icon request

### ISSUE THREAD

**Issue by majorisgit** [lucide-icons/lucide#2339]
### Icon name

Gender icons, galaxy, constellation and zodiac icons

### Use cases

Gender icons - male, female. These critical items are missing. 
Add cloud save icon; cloud with a tray with a down arrow. 
Add galaxy, constellation, zodiac icons.

### Design ideas

Should be of same as the current style

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Please submit these separately and double check if they already have been requested.

We already have #560 #1581 #2240 #712

**Comment by majorisgit** [comment]
I do not see zodiac signs on https://lucide.dev/icons/
The Cloud-download or cloud-upload icon are not intuitive for cloud save. A new icon for cloud Save can be combination of two - https://lucide.dev/icons/download and https://lucide.dev/icons/cloud

**Comment by karsa-mistmere** [comment]
> I do not see zodiac signs on https://lucide.dev/icons/

We have a – for now – closed pull request with them, as I've already linked above: #712 
Feel free to extend this pull request with additional valid use cases - the lack of which resulted in the closing of this PR.

> The Cloud-download or cloud-upload icon are not intuitive for cloud save. A new icon for cloud Save can be combination of two - https://lucide.dev/icons/download and https://lucide.dev/icons/cloud

A straight up combination of these is not feasible, as it would not fit within a 24 by 24 pixel grid. Clouds with arrows are very commonly used to represent upload/download to a cloud, can you find any precedent of what you're describing?

**Comment by majorisgit** [comment]
Take a look at this cloud save https://iconscout.com/icon/cloud-save-4173273
Similar to this by aligning cloud and tray level with a down arrow.
