### ISSUE TITLE
Menu collapse/expand

### ISSUE THREAD

**Issue by kemie** [lucide-icons/lucide#2345]
### Icon name

menu-collapse, menu-expand

### Use cases

Commonly used for collapsing menus/panels, especially sidebars

### Design ideas

could be a list with arrows, or more specifically a sidebar:
![image](https://github.com/user-attachments/assets/b1f69a45-5ef9-43aa-bcdd-5f4da2890cdf)
![image](https://github.com/user-attachments/assets/380176be-71ff-4ed1-b537-4f42c6a270a0)

I'll give this a shot, but wanted to post issue first. 

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
We have these already:

- https://lucide.dev/icons/panel-left-close
- https://lucide.dev/icons/panel-left-open
- https://lucide.dev/icons/panel-right-close
- https://lucide.dev/icons/panel-right-open

**Comment by kemie** [comment]
oooh, i saw them now! they should probably be tagged with expand /collapse too. thanks!
