### ISSUE TITLE
Layout shifts on icon page

### ISSUE THREAD

**Issue by Jay-Karia** [lucide-icons/lucide#2356]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

On the specific icon page, under the code block section.
On clicking `"Vanilla"` tab and `"React"` tab, the layout tends to shift.
This decreases UX

### Steps to reproduce

1. Go to any icon page (say: https://lucide.dev/icons/bug)
2. Navigate to Code Section
3. Click on "Vanilla" tab.
4. Click on "React" tab.

The layout shifts!

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by eugene4545** [comment]
hello, could I work on this issue. I'm thinking we could add padding to the smaller code snippets or set a minimum height so everything is even across the board.
