### ISSUE TITLE
Googe icon request

### ISSUE THREAD

**Issue by harshsbhat** [lucide-icons/lucide#2370]
### Icon name

Google icon

### Use cases

Can be used for authentications

### Design ideas

I am not a designer. I use lucide react and wanted to use Google icon but it was unavailable

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by harshsbhat** [comment]
hey @karsa-mistmere why not?

**Comment by karsa-mistmere** [comment]
> hey @karsa-mistmere why not?

Let me break it up for you:

>  I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

There are actually not just one, but many: #2237 #512 #627 #1679 #1694 #1727 #1613 

>  I am not requesting a brand logo and the art is not protected by copyright.

You actually are requesting one, and [it actually _is_ protected](https://about.google/brand-resource-center/rules/).

---

Apart from these, you've also failed to register the following warning when submitting the issue:

> Important note: No new brand logos are allowed, see https://github.com/lucide-icons/lucide/issues/670.
> Existing brand icons will also be phased out. For brand icons, consider using https://simpleicons.org/, which offers purpose-built SVGs that are also on a 24×24px grid.

**Comment by harshsbhat** [comment]
> > hey @karsa-mistmere why not?
> 
> Let me break it down for you:
> 
> > I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
> 
> There are actually not just one, but many: #2237 #512 #627 #1679 #1694 #1727 #1613
> 
> > I am not requesting a brand logo and the art is not protected by copyright.
> 
> You actually are requesting one, and [it actually _is_ protected](https://about.google/brand-resource-center/rules/).
> 
> Apart from these, you've also failed to register the following warning when submitting the issue:
> 
> > Important note: No new brand logos are allowed, see #670.
> > Existing brand icons will also be phased out. For brand icons, consider using https://simpleicons.org/, which offers purpose-built SVGs that are also on a 24×24px grid.

Yes. I should have read the things I am ticking. How are react-icons providing us with a lot of google icons then? https://react-icons.github.io/react-icons/search/#q=google. But anyway thanks for breaking it down for me, I should have read the checkboxes. I am sorry!

**Comment by karsa-mistmere** [comment]
> How are react-icons providing us with a lot of google icons then?

That's not really our concern, but to put it simply, most of these probably infringe on Google's copyright.

**Comment by harshsbhat** [comment]
> > How are react-icons providing us with a lot of google icons then?
> 
> That's not really our concern, but to put it simply, most of these probably infringe on Google's copyright.

Alright! Thanks for taking the time to answer my queries! Have a great rest of the day!
