### ISSUE TITLE
Terrible Performance on lucide-solid library

### ISSUE THREAD

**Issue by FelipeEmos** [lucide-icons/lucide#2371]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.427.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

The `lucide-solid` lib is with a terrible performance because it is loading all the icons instead of only the ones the project is using...

I created 2 repos to compare both `lucide-solid` and `lucide-react` and the performance difference is really big.

These repos were set up the same way, I used `bun create vite@latest`, deleted everything in the `App.tsx` and just added one icon.

### Results

|Benchmark Repo|[Lucide React](https://github.com/FelipeEmos/lucide-react-test)|[Lucide Solid](https://github.com/FelipeEmos/lucide-solid-test)|
|---|---|---|
|Time| 250 ms | 3500 ms |
|Amount of Icons being loaded|1|all of them|
|Screenshots|![REACT](https://raw.githubusercontent.com/FelipeEmos/lucide-solid-test/main/docs/react.png)|![SOLID](https://raw.githubusercontent.com/FelipeEmos/lucide-solid-test/main/docs/solid.png)|

### Steps to reproduce

Just import any icon in a Vite SolidJS project from the `lucide-solid` library and see the Lighthouse Network tab

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by FelipeEmos** [comment]
Oh, I've just realized after continuing my search about the topic that this is probably a known issue... there's a section in the docs where it says 

> Tree-shaking is only available in these packages: [lucide](https://lucide.dev/guide/packages/lucide), [lucide-react](https://lucide.dev/guide/packages/lucide-react), [lucide-vue](https://lucide.dev/guide/packages/lucide-vue), [lucide-vue-next](https://lucide.dev/guide/packages/lucide-vue-next), [lucide-angular](https://lucide.dev/guide/packages/lucide-angular), [lucide-preact](https://lucide.dev/guide/packages/lucide-preact)

I'm assuming that's exactly what's going on here... anyhow, is it too difficult to implement? Maybe I could give it a shot...

Any tips or resources would be appreciated.

**Comment by jamiemlaw** [comment]
There is an article at https://christopher.engineering/en/blog/lucide-icons-with-vite-dev-server/ that proposes a workaround. Hope it helps.

**Comment by FelipeEmos** [comment]
@jamiemlaw thank you for the amazing resource!
I had no idea this was a Vite's deliberate feature not to Tree Shake when on DEV mode... ok then.

Although the workaround the article suggested works, it unfortunately breaks Typescript so I'm not considering it seriously. I'd rather do the manual boring work of copy pasting the SVG's I need and maintain my own icon components.

And there's a real opportunity to help the library with this issue.
I'm really curious on how the `lucide-react` side of things works 🤔

Cus if it's a VITE problem (and apparently on `lucide-react` it's been fixed by using some clever code generation technique), then there is no reason why almost the same approach wouldn't work for `lucide-solid`.

Porting the newest version of `lucide-react` to `lucide-solid` seems something I could do. Maybe by the time `lucide-solid` was ported this tree shaking thing was still an issue?

**Comment by ericfennis** [comment]
@jamiemlaw 
Maybe something has changed on the Vite side, not sure.
`lucide-solid` can't be directly compared to `lucide-react` since Solid is a compiled framework like Svelte. This means that the compiler can't handle pre-transpiled script files like React does, and all the files that shipped with this package are uncompiled. Also Solid Start uses different script files then normal Solid+Vite setup what it made it even more complicated.

Our build process is based on the [`rollup-preset-solid`](https://github.com/solidjs-community/rollup-preset-solid), but looks like we might go even more custom on this.

Thanks for reporting. I'm looking into it.

**Comment by vincehi** [comment]
> lucide-solid

Me to

**Comment by vincehi** [comment]
Me to

**Comment by jguddas** [comment]
Might be interesting, the vite peopel are working on a rewrite of the bundler, it's called [rolldown](https://rolldown.rs) and will hopefully fix a lot of those bundling performance problems.

Maybe someone wants to give it a try, maybe we don't have the issue with vite-rolldown?

There was also a good talk about the internal reworkings of the bundlers at viteconf https://youtu.be/IjV0tLysXc0

**Comment by spyshower** [comment]
2025, soon 2026, the performance is still terrible.

**Comment by FelipeEmos** [comment]
I've opened a new issue for this because now I understand here wasn't stated the best way.
- https://github.com/lucide-icons/lucide/issues/4435

🚀  Also, here's a workaround vite plugin for userland!
https://gist.github.com/FelipeEmos/297b15a9bfa8fcddd57ff0d8e2b6a737

cc:
@spyshower @jguddas @vincehi
