### ISSUE TITLE
Icon Name Inconsistency: CircleHelp vs HelpCircle

### ISSUE THREAD

**Issue by R1013-T** [lucide-icons/lucide#2373]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

There appears to be an inconsistency between the icon names `CircleHelp` and `HelpCircle`. This inconsistency can lead to confusion for developers trying to use the icon, potentially causing errors in their code or requiring additional time to find the correct component name.

### Steps to reproduce

1. Attempt to import and use `<CircleHelp />` in a React project.
2. Encounter an error due to the component not existing.
3. Discover that the correct component name is `<HelpCircle />`.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Please upgrade your packages, as they are outdated.
