### ISSUE TITLE
Add file of icons' tags and category in package

### ISSUE THREAD

**Issue by Ganany** [lucide-icons/lucide#2396]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [X] lucide-vue
- [X] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

Could you please add a JSON file with tags and category info in the packages?  Here is an example of another icon package. https://github.com/bytedance/IconPark/blob/master/packages/vue-next/icons.json 

Thanks!

### Use cases

With this JSON file, the users of my project can quickly search icons using related info and make icon choices by themselves. 

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by jguddas** [comment]
It's available as `lucide-static/tags.json` https://unpkg.com/lucide-static/tags.json

**Comment by Ganany** [comment]
Thank you!
