### ISSUE TITLE
Longer ToolTips are cutoff by sidebar

### ISSUE THREAD

**Issue by ieedan** [lucide-icons/lucide#2412]
### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

![image](https://github.com/user-attachments/assets/977316ec-3314-473d-b60c-d064b7663af6)

Kinda an edge case because it would assume your search results in the long tooltip. But when certain icons with long names end up on the left side of the ui their tooltip will be cut off.

### Steps to reproduce

Type `graph` in the search. (There will be other cases but this is what I did)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ieedan** [comment]
> can i take this up?

If you are asking me go ahead I unfortunately don't have enough time for this rn

**Comment by jguddas** [comment]
> can i take this up?

Feel free to create a PR any time.

**Comment by mohit-nagaraj** [comment]
@jguddas hey i have raised a pr for this, could you review it and also add `hacktoberfest` label as it would be helpful to me as well
