### ISSUE TITLE
Broom 

### ISSUE THREAD

**Issue by fereinaux** [lucide-icons/lucide#2415]
### Icon name

Broom

### Use cases

To categorize volunteers in cleanning section

### Design ideas

![image](https://github.com/user-attachments/assets/2661e9f4-f4c2-416e-a589-39d39a2fcfa0)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jamiemlaw** [comment]
There's a [broom icon](https://lucide.dev/icons/lab/broom) already, but it's in the `lab` branch (you need to check 'Include external libs > Lab' checkbox when searching for icons in order for it to show up).

![image](https://github.com/user-attachments/assets/02cafcd0-5277-42f0-8cba-b8408b9339b9)
