### ISSUE TITLE
question - strokeWidth prop in React component

### ISSUE THREAD

**Issue by llaenowyd** [lucide-icons/lucide#242]
Noticed [the `strokeWidth` prop in the React component](https://github.com/lucide-icons/lucide/blob/87ab0bfb626df8b267e81cc419475e41d699f127/packages/lucide-react/src/createReactComponent.js#L6), is not listed in the `propTypes`, is there any reason it shouldn't be used?

In my case I'm using this React component for inspiration as I'm writing some app code and curious to know if there's a problem with passing a `strokeWidth ≠ 2`.

@ericfennis

thanks

**Comment by ericfennis** [comment]
@llaenowyd thanks for noticing this. I think renamed something lately, but forgot to update the proptypes. 
I will create a hotfix for that!

**Comment by ericfennis** [comment]
Fixed with hotfix: https://github.com/lucide-icons/lucide/releases/tag/v0.14.1

**Comment by llaenowyd** [comment]
I see, ok - thanks!
