### ISSUE TITLE
Request: Gradient

### ISSUE THREAD

**Issue by justboereh** [lucide-icons/lucide#2449]
### Icon name

gradient-sqaure, gradient-rectangle

### Use cases

A tool for making gradients, like in design software.

### Design ideas

![gradient-rectangle](https://github.com/user-attachments/assets/9bdd95e4-9f59-41ba-a58b-f8371b797f05)
![gradient-sqaure](https://github.com/user-attachments/assets/e460e0cc-5a9d-4a88-aa40-09921adb36f5)
designed in Figma.

The icons is breaking the Pixel Perfect rule. Although it could be an exception because when zoomed out, the icon can still be a gradient tool.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [x] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
I'm afraid this isn't feasible with fixed width strokes only.

**Comment by jguddas** [comment]
Related to #1441
