### ISSUE TITLE
Stroke Width

### ISSUE THREAD

**Issue by jorgedanisc** [lucide-icons/lucide#2461]
### Icon name

stroke-width, thickness, line-width, line-thickness

### Use cases

Could be used on a app where it is needed to adjust the thickness of a line or stroke

### Design ideas

![thickness](https://github.com/user-attachments/assets/76d59d0e-aaab-442e-b1c9-97ac78e44ee5)
![Screenshot 2024-09-15 at 15 10 35](https://github.com/user-attachments/assets/dc188d97-d70e-497e-be26-04410f357f88)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
We do not support blocky shapes, we have a 2px gap rule which makes icons like this impossible.

**Comment by jorgedanisc** [comment]
I am sorry to ear that, I don't know what blocky shapes means.
Talking about the 2px gap rule, would this fix it?
![thickness](https://github.com/user-attachments/assets/5b98a1e1-82de-4114-8197-358b7d899741)
![Screenshot 2024-09-15 at 15 19 39](https://github.com/user-attachments/assets/c2d763c8-3bea-4347-b9ab-781bcec48bc2)

**Comment by karsa-mistmere** [comment]
> I am sorry to ear that, I don't know what blocky shapes means. Talking about the 2px gap rule, would this fix it? ![thickness](https://private-user-images.githubusercontent.com/103663493/367588002-5b98a1e1-82de-4114-8197-358b7d899741.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTMzMzYsIm5iZiI6MTcyNjQxMzAzNiwicGF0aCI6Ii8xMDM2NjM0OTMvMzY3NTg4MDAyLTViOThhMWUxLTgyZGUtNDExNC04MTk3LTM1OGI3ZDg5OTc0MS5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNTEwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzY3NzljODBmNWU0ZTJjMzljNmZhNTU4NGQ3NTUxZWUwYzFlY2JiNzg4YTc1NTAwZjNmMDc3MjBmNWRjZWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.48qPzR9sf_MGpEtOOnW2Qfe-UHJWwq-LbQAtvD1-Kdg) ![Screenshot 2024-09-15 at 15 19 39](https://private-user-images.githubusercontent.com/103663493/367587990-c2d763c8-3bea-4347-b9ab-781bcec48bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTMzMzYsIm5iZiI6MTcyNjQxMzAzNiwicGF0aCI6Ii8xMDM2NjM0OTMvMzY3NTg3OTkwLWMyZDc2M2M4LTNiZWEtNDM0Ny1iOWFiLTc4MWJjZWM0OGJjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNTEwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzAyNzJhYjUwYzIwOWRmNmE5NWE3ZjRiZTljMjlkMzg0M2IzYWY0MDkxMTEwNWI2NzVlODY5NTIzMzU3ZTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IPv3wVwTkWEXv3VI_AnUlUIxFCa-vs_a_KcwbirUZXI)

No, we do not allow fills for the time being, that’s the main issue, so with no fills, the middle stroke does not fulfill our 2nd gap design guidelines.

**Comment by jorgedanisc** [comment]
Got it! Thank you for the clarification
