### ISSUE TITLE
Difference on circle icons name between website and package

### ISSUE THREAD

**Issue by MartinGbz** [lucide-icons/lucide#2486]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

There is a difference between the name of circle icons on the website and on the package. There is an inversion to be more precise.

For example: the `CircleAlert` icon, the name is `circle-alert` , when you "copy JSX" it, it gives you `<CircleAlert />` but at the end the lucide package doesn't recognize <CircleAlert />. It only recognize <AlertCircle />.
So it's either an issue from the website or from the package related to circle icons names.

If you consider the issue is on the website I think I can't help because the app seems not open source, but if it's the name of the icons in the package that need to be changed let me know, I can maybe do the PR for this :))

### Steps to reproduce

1. go to: https://lucide.dev/icons/circle-alert?search=circle
2. click on "copy JSX"
3. now you have <CircleAlert /> in your clipboard instead of <AlertCircle />

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hey @MartinGbz,

Can you please confirm which package exactly are we talking about here?

I've checked, and every single one of our JSX packages do actually use `<CircleAlert />` (and even in Angular and Svelte, all of our icon exports are in this naming format).

**Comment by karsa-mistmere** [comment]
No response in two weeks, closing this for now.
