### ISSUE TITLE
'Icon' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Ehesp** [lucide-icons/lucide#2488]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.445.0

React Version: 18.3.0-canary-bb0944fe5-20240313

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

I'm using lucide-react in a NextJS project, with typescript 5.6.2.

All icons are showing the same TS error when rendered, e.g.

```
'PencilIcon' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not assignable to type 'ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
```

tsconfig is

```json
{
  "compilerOptions": {
    "target": "ES2018",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

### Steps to reproduce

```jsx
import { PencilIcon } from "lucide-react";
```

```jsx
export function Edit() {
  return (
    <div className="flex justify-end mb-2">
        <PencilIcon
          size={16}
          className="opacity-50 transition-all group-hover:opacity-75"
        />
    </div>
  );
}

```

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by zocsen** [comment]
Adding `"react": ["./node_modules/@types/react"]` to my tsconfig.json "path" solved it for me.

`
{
  "extends": "@repo/typescript-config/react-library.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@repo/ui/*": ["./src/*"],
      "react": ["./node_modules/@types/react"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules"]
}
`

**Comment by Ehesp** [comment]
@zocsen Thanks a bunch, that solved my issue but then actually pin pointed what my actual problem was. I have a mono-repo with two slightly out of sync react versions. I synced them up and no longer had any issues.

**Comment by Westernwells** [comment]
> [@zocsen](https://github.com/zocsen) Thanks a bunch, that solved my issue but then actually pin pointed what my actual problem was. I have a mono-repo with two slightly out of sync react versions. I synced them up and no longer had any issues.

Had the same issue using Turborepo which is a monorepo also, syncing up as you mentioned here saved me couple of hours.

**Comment by vishwas-babar** [comment]
thanks @zocsen your solution worked for me

**Comment by chauvanphuoc** [comment]
many thanks @zocsen , totally worked for me

**Comment by bodasooqa** [comment]
What helped me was adding a `@types/node` package.

**Comment by Hamziss** [comment]
> [@zocsen](https://github.com/zocsen) Thanks a bunch, that solved my issue but then actually pin pointed what my actual problem was. I have a mono-repo with two slightly out of sync react versions. I synced them up and no longer had any issues.

holy you just saved me few hours. THANKS

**Comment by morganfeeney** [comment]
WTH, this just happened to me, out of nowhere, if it wasn't for this issue I would have lost a serious amount of productivity.
