### ISSUE TITLE
Spider Icon

### ISSUE THREAD

**Issue by alanliveseo** [lucide-icons/lucide#2497]
### Icon name

Spider

### Use cases

To identify that one site is tracking another.

https://en.wikipedia.org/wiki/Spider_trap

### Design ideas

https://fontawesome.com/icons/spider?f=classic&s=solid

![spider-solid](https://github.com/user-attachments/assets/529688d8-982f-49cf-9056-ef3667448bce)
![Screenshot_3](https://github.com/user-attachments/assets/414d692f-237b-4005-8887-e0a337912793)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Hey @alanliveseo,

We already have a spider icon in `lab`:
https://lucide.dev/icons/lab/spider

**Comment by alanliveseo** [comment]
Thank you

**Comment by alanliveseo** [comment]
Thank you

**Comment by alanliveseo** [comment]
I hadn't found the icon, @karsa-mistmere  helped me
