### ISSUE TITLE
Inconsistent Naming for All Icons with '2x2': Should Be '2X2' Instead of '2x2'

### ISSUE THREAD

**Issue by LaythAlqadhi** [lucide-icons/lucide#2507]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.446.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

The icons 'Grid2X2Check', 'Grid2X2Plus', and others with '2X2' are incorrectly exported as 'Grid2x2Check' and 'Grid2x2Plus' (with a lowercase 'x'). However, they are displayed correctly on the website as 'Grid2X2Check' and 'Grid2X2Plus'.

### Steps to reproduce

Visit the website and look for anything with '2X2', then check the usage example for it. Try to replicate the example on your machine. You will notice that the import is incorrect, and if you're using TypeScript, it will give you an error message like '"lucide-react"' has no exported member named 'Grid2X2X'. Did you mean 'Grid2x2X'?

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
To fix this you could set `["grid-2-x-2"]` as the `grid-2x2.json` alias field.

I'm not convinced tho that this is really a bug.

**Comment by karsa-mistmere** [comment]
I think `2x2` is better than `2X2` in this context.

If nothing else, it's a much better scenario if we only have to fix the site to use the correct names and no breaking changes are introduced to the packages. :)

**Comment by LaythAlqadhi** [comment]
I'd prefer '2X2' to stay consistent with other icons like 'Link2Off' and 'Axis3D', where numbers are followed by uppercase letters.

**Comment by karsa-mistmere** [comment]
That should also be `Axis3d` IMO.

`Link2Off` is different, it comes from `link-2-off`, but should become `link-horizontal-off`/`LinkHorizontalOff` anyway.

**Comment by karsa-mistmere** [comment]
> That should also be `Axis3d` IMO.

And it actually canonically is:
<img width="410" alt="image" src="https://github.com/user-attachments/assets/e66891cb-c4e5-4da3-98a2-87a7cba58c2b">

We do have an `Axis3D` export as well though, because of a Vercel issue.
