### ISSUE TITLE
Is icon available in package or not?

### ISSUE THREAD

**Issue by mittalyashu** [lucide-icons/lucide#252]
Show some kind of badge or text to represent if the respective icon is available in the react/vue package or not.

**Comment by locness3** [comment]
How would the website know that

**Comment by ericfennis** [comment]
I think we should go to a CI solution, for every push to master we create a new version. I think if we implement that, this is also not a problem.

**Comment by mittalyashu** [comment]
@ericfennis @locness3 How to release icon on website only when they’re included in the package.

**Comment by ericfennis** [comment]
@mittalyashu I think the ideal solution is Continuous integration, with that building this is not even needed.

I'm working on a CI workflow for icons. So if icons are pushed to master. We create new tag and build new packages. So the icons in the packages will be the same as on the site.

**Comment by ericfennis** [comment]
This one can be closed, I wrote a github action workflow that automatically builds new packages when a icon is merged. 
So for each icon that's merged the icon should be in the latest packages as well
https://github.com/lucide-icons/lucide/blob/master/.github/workflows/ci.yml
https://github.com/lucide-icons/lucide/blob/master/.github/workflows/release.yml
