### ISSUE TITLE
Swimming pool

### ISSUE THREAD

**Issue by kimstrigl** [lucide-icons/lucide#2526]
### Icon name

Swimming pool

### Use cases

This week I twice needed an icon to indicate that there is an swimming pool.

Case 1: A map that shows the kind of sport locations in the area. Gym, Running track and also: Swimming pools.
Case 2: Kind of an hotel overview page that indicated if the hotel had a pool. Similar to airbnb, booking etc.

### Design ideas

I created something that fit the rest of the icons for my use cases. It contains the waves from the "waves" icon. With a pool ladder on top.
![Screenshot 2024-10-09 at 16 04 38](https://github.com/user-attachments/assets/678e241e-1830-4f2c-94a8-90f935140b01)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Based on `waves`:

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+5a2+2+0+0+0-2+2v11%22+/%3E%3Cpath+d=%22M2+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M7+13h10%22+/%3E%3Cpath+d=%22M7+9h10%22+/%3E%3Cpath+d=%22M9+5a2+2+0+0+0-2+2v11%22+/%3E"><img alt="icons" width="400px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTkgNWEyIDIgMCAwIDAtMiAydjExIiAvPgogIDxwYXRoIGQ9Ik0yIDE4Yy42LjUgMS4yIDEgMi41IDEgMi41IDAgMi41LTIgNS0yIDIuNiAwIDIuNCAyIDUgMiAyLjUgMCAyLjUtMiA1LTIgMS4zIDAgMS45LjUgMi41IDEiIC8+CiAgPHBhdGggZD0iTTcgMTNoMTAiIC8+CiAgPHBhdGggZD0iTTcgOWgxMCIgLz4KICA8cGF0aCBkPSJNOSA1YTIgMiAwIDAgMC0yIDJ2MTEiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

**Comment by jguddas** [comment]
Double wave fits, only barely tho.
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+2a2+2+0+0+0-2+2v11%22+/%3E%3Cpath+d=%22M2+15c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+20c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M7+10h10%22+/%3E%3Cpath+d=%22M7+6h10%22+/%3E%3Cpath+d=%22M9+2a2+2+0+0+0-2+2v11%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTkgMmEyIDIgMCAwIDAtMiAydjExIiAvPgogIDxwYXRoIGQ9Ik0yIDE1Yy42LjUgMS4yIDEgMi41IDEgMi41IDAgMi41LTIgNS0yIDIuNiAwIDIuNCAyIDUgMiAyLjUgMCAyLjUtMiA1LTIgMS4zIDAgMS45LjUgMi41IDEiIC8+CiAgPHBhdGggZD0iTTIgMjBjLjYuNSAxLjIgMSAyLjUgMSAyLjUgMCAyLjUtMiA1LTIgMi42IDAgMi40IDIgNSAyIDIuNSAwIDIuNS0yIDUtMiAxLjMgMCAxLjkuNSAyLjUgMSIgLz4KICA8cGF0aCBkPSJNNyAxMGgxMCIgLz4KICA8cGF0aCBkPSJNNyA2aDEwIiAvPgogIDxwYXRoIGQ9Ik05IDJhMiAyIDAgMCAwLTIgMnYxMSIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> Double wave fits, only barely tho. [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/579edb7ea394d8d42c36ba20bcee3799dd8cf86c62a9c13bba59140a765f15d8/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d546b674d6d4579494449674d434177494441744d694179646a45784969417650676f67494478775958526f49475139496b307949444531597934324c6a55674d533479494445674d693431494445674d693431494441674d6934314c5449674e533079494449754e694177494449754e434179494455674d6941794c6a55674d4341794c6a55744d6941314c5449674d53347a494441674d5334354c6a55674d693431494445694943382b4369416750484268644767675a443069545449674d6a426a4c6a59754e5341784c6a49674d5341794c6a55674d5341794c6a55674d4341794c6a55744d6941314c5449674d693432494441674d693430494449674e534179494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4e7941784d4767784d4349674c7a344b49434138634746306143426b50534a4e4e794132614445774969417650676f67494478775958526f49475139496b303549444a684d694179494441674d4341774c5449674d6e59784d5349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+2a2+2+0+0+0-2+2v11%22+/%3E%3Cpath+d=%22M2+15c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+20c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M7+10h10%22+/%3E%3Cpath+d=%22M7+6h10%22+/%3E%3Cpath+d=%22M9+2a2+2+0+0+0-2+2v11%22+/%3E)

That's why I stuck with one wave only, & to keep them as consistent as possible.

**Comment by jguddas** [comment]
> > Double wave fits, only barely tho. [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/579edb7ea394d8d42c36ba20bcee3799dd8cf86c62a9c13bba59140a765f15d8/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d546b674d6d4579494449674d434177494441744d694179646a45784969417650676f67494478775958526f49475139496b307949444531597934324c6a55674d533479494445674d693431494445674d693431494441674d6934314c5449674e533079494449754e694177494449754e434179494455674d6941794c6a55674d4341794c6a55744d6941314c5449674d53347a494441674d5334354c6a55674d693431494445694943382b4369416750484268644767675a443069545449674d6a426a4c6a59754e5341784c6a49674d5341794c6a55674d5341794c6a55674d4341794c6a55744d6941314c5449674d693432494441674d693430494449674e534179494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4e7941784d4767784d4349674c7a344b49434138634746306143426b50534a4e4e794132614445774969417650676f67494478775958526f49475139496b303549444a684d694179494441674d4341774c5449674d6e59784d5349674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+2a2+2+0+0+0-2+2v11%22+/%3E%3Cpath+d=%22M2+15c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+20c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M7+10h10%22+/%3E%3Cpath+d=%22M7+6h10%22+/%3E%3Cpath+d=%22M9+2a2+2+0+0+0-2+2v11%22+/%3E)
> 
> That's why I stuck with one wave only, & to keep them as consistent as possible.

Your one feels a bit small tho.

**Comment by jguddas** [comment]
Uglier but maybe better size wise?
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M19+3a2+2+0+0+0-2+2v15%22+/%3E%3Cpath+d=%22M2+20c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+2.6+0+2.4+2+5+2+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M7+11h10%22+/%3E%3Cpath+d=%22M7+15h10%22+/%3E%3Cpath+d=%22M7+7h10%22+/%3E%3Cpath+d=%22M9+3a2+2+0+0+0-2+2v15%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTkgM2EyIDIgMCAwIDAtMiAydjE1IiAvPgogIDxwYXRoIGQ9Ik0yIDIwYy42LjUgMS4yIDEgMi41IDEgMi41IDAgMi41LTIgNS0yIDIuNiAwIDIuNCAyIDUgMiAyLjUgMCAyLjUtMiA1LTIgMS4zIDAgMS45LjUgMi41IDEiIC8+CiAgPHBhdGggZD0iTTcgMTFoMTAiIC8+CiAgPHBhdGggZD0iTTcgMTVoMTAiIC8+CiAgPHBhdGggZD0iTTcgN2gxMCIgLz4KICA8cGF0aCBkPSJNOSAzYTIgMiAwIDAgMC0yIDJ2MTUiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>
