### ISSUE TITLE
Strokes look inconsistent in Safari at 0.5px

### ISSUE THREAD

**Issue by HassanAzzam** [lucide-icons/lucide#2527]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

latest

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [X] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

Take a look at this screenshot, strokes look inconsistent and the curves look bolder.
![image](https://github.com/user-attachments/assets/825627cb-0a57-456b-becd-56cf7165b3ba)

### Steps to reproduce

1. Navigate to https://lucide.dev/icons.
2. Apply the same configuration as the above screenshot.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hi @HassanAzzam,

I think this is just a rendering issue in Safari, there isn't much we can do about that, I'm afraid.

We could set the minimum stroke width as 1px. 🙃

**Comment by HassanAzzam** [comment]
Raising the stroke width solved most of it, but look at this one:
![image](https://github.com/user-attachments/assets/5233d1e1-08e8-4f9c-bb67-344592e65cf3)


The rounded corners look bolder. This seems as an anti-aliasing issue. Any ideas how to fix that?

**Comment by karsa-mistmere** [comment]
> The rounded corners look bolder. This seems as an anti-aliasing issue. Any ideas how to fix that?

As I've said, this a Safari issue, we cannot solve it I'm afraid.

**Comment by HassanAzzam** [comment]
@jguddas 
Thanks for help! But it didn't solve my problem.
I'm not using it in 0.5px stroke width in action, I've used it just to illustrate my problem which is having bolder corners.

**Comment by HassanAzzam** [comment]
> ![image](https://private-user-images.githubusercontent.com/9885144/375378103-5233d1e1-08e8-4f9c-bb67-344592e65cf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NzAzMzAsIm5iZiI6MTcyODU3MDAzMCwicGF0aCI6Ii85ODg1MTQ0LzM3NTM3ODEwMy01MjMzZDFlMS0wOGU4LTRmOWMtYmI2Ny0zNDQ1OTJlNjVjZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMTQyMDMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhmODNjNmEwYzFkZTIzMjA0NmYzNWNjNGNkYWU1ZTFmNTZiZGM3NDhhNThlMmEwZjExYWZkMTRlOTkwZWFjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.a6hfTAI1t7fhT2M6RBpuVGoQVtpjXhSlqi511KWqpXA)

Note the straight strokes here, they have got a semi-transparent outline, but the corners not.

**Comment by ericfennis** [comment]
@HassanAzzam The opacity problem probably will be solved with #2135.
Unfortunately, we can't do much about the rendering issues in Safari, I close this one for now.
