### ISSUE TITLE
Fix render Icon component for react

### ISSUE THREAD

**Issue by StKostyantin** [lucide-icons/lucide#2550]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.453.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [X] Safari
- [X] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

I have custom icons on my project, but I want the API for all icons to be the same. so I created a script that generates an IconNode from my custom icons and creates icons with the same API as lucide

for example

```
import { FC } from 'react';
import { Icon, LucideProps, IconNode } from 'lucide-react';


export const allTypes: IconNode = [...];

export const AllTypesIcon: FC<LucideProps> = ({ viewBox = '0 0 24 24', strokeWidth = 0, ...props }) => {
  return <Icon viewBox={viewBox} strokeWidth={strokeWidth} iconNode={allTypes} {...props} />;
};
```

But there is a nuance when you have a map in this [line of code](https://github.com/lucide-icons/lucide/blob/757bf0fb85ff049299e6095095bc99f87b63d3dc/packages/lucide-react/src/Icon.ts#L52C1-L52C70), the keys can be repeated when creating elements. 

And I get errors: "Each child in a list should have a unique 'key' prop". 

### Steps to reproduce

add your own icon, I can't give my example due to NDA

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by aoun-mustafa** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jguddas** [comment]
Can't reproduce.
