### ISSUE TITLE
Render Icon component in vue SFC

### ISSUE THREAD

**Issue by emololftw** [lucide-icons/lucide#2551]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [X] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.453.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [X] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

In vue component like:

```vue
<script setup lang="ts">
import { Icon } from 'lucide-vue-next';

const props = withDefaults(
	defineProps<{ highlight: boolean, icon: string }>(),
	{
		highlight: false,
		icon: undefined
	}
);
</script>

<template>
	<li class="nav-item">
		<a
			class="nav-link flex gap-2 items-center"
			:class="[ Boolean(highlight) && 'active' ]"
			v-bind="$attrs"
		>
			<Icon name="Airplay" v-if="icon" />
			<slot />
		</a>
	</li>
</template>
```

i got this error:

```console
chunk-VJDM2DWH.js?v=edbf37e5:1585 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Icon (chunk-VJDM2DWH.js?v=edbf37e5:1585:18)
    at renderComponentRoot (chunk-CTNY2BLM.js?v=edbf37e5:7518:31)
    at ReactiveEffect.componentUpdateFn [as fn] (
```

### Steps to reproduce

add import { Icon } from 'lucide-vue-next'; into every vue SFC

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by aoun-mustafa** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by ericfennis** [comment]
The `Icon` component that is exported is not accepting the `name` prop. 
You could create you own see docs: [Create one generic icon component](https://lucide.dev/guide/packages/lucide-vue-next#one-generic-icon-component)

The `Icon` component is internally used to display icon, which accepts a `iconNode`. We also use it when using the lab branch. See docs: [Using Lucide lab](https://lucide.dev/guide/packages/lucide-vue-next#with-lucide-lab-or-custom-icons)
