### ISSUE TITLE
Laptop with a check on its screen

### ISSUE THREAD

**Issue by MadeInPierre** [lucide-icons/lucide#2562]
### Icon name

`laptop-minimal-check`

### Use cases

I'd like to have a sync status icon in my app that needs to work offline. I need these states:
- Synced: Lucide has the `cloud` icon
- Syncing: Lucide has the `refresh-ccw` icon
- Offline: Lucide has the `cloud-off`
- Saved locally: I found no icon that depicts data being stored locally.

Hence, I'd like a laptop icon with a checkmark inside the screen.

### Design ideas

Here's an icon used by Google Docs:

![image](https://github.com/user-attachments/assets/2d95f9cb-a452-4d71-ace5-395938423914)

Lucide already has a `laptop-minimal` icon, it should be simple to add a checkmark variant. Variants such as `laptop-minimal-x` could also be created while we're at it.

Thank you!

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by aoun-mustafa** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
