### ISSUE TITLE
Max-width limits the card to expand

### ISSUE THREAD

**Issue by chessurisme** [lucide-icons/lucide#2566]
### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [X] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [X] Android
- [ ] Other/not relevant

### Description

Initially, the "Style as you please" card' elements looks a uncentered. A small tweak can be made for it to fix.

## Suggestion how to fix
The `max-width` made the card's element limits its width. Removing the `max-width` using [`@media` rule](https://www.w3schools.com/cssref/css3_pr_mediaquery.php) when the screen width is below 640px solves the problem.

See the developer console as the max-width is present:
**BEFORE:**
![image](https://github.com/user-attachments/assets/a40b3dc2-e01f-432b-a701-bca34236e122)
**AFTER:**
![image](https://github.com/user-attachments/assets/f9c55b4b-57ec-482e-9e7a-6f37f39cfd9c)

### Steps to reproduce

1. Open Lucide site in any browser.
2. If in PC, minimize the browser's width until the site looks like in phone.
3. Scroll until section "Style as you please".
4. Look how the elements arranged.
![image](https://github.com/user-attachments/assets/75603fed-4c9d-4113-aad6-29771f6d5f54)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by aoun-mustafa** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
