### ISSUE TITLE
Rename icon by adding "Icon" at the end of each component

### ISSUE THREAD

**Issue by gdamou** [lucide-icons/lucide#2573]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

I don't really found any issue opened about this (sorry if it is already the case) but I am using pandacss as style library in my React applications and whenever I try to import <Box /> component I am importing the "Box" from lucide-dev.

Why icon doesn't have simply the "icon" word at the end of them ? Is there any technical reason that motivated you to name them like other components ?

### Use cases

Making icon import only when we really need them and avoid any conflict with other components in react app.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
There's an open PR about this. We aren't going to drop previous export names for sake of backward compatibility, but we're working on developers being able to customise what exports they would like to use: https://github.com/lucide-icons/lucide/pull/2328
