### ISSUE TITLE
Slow page loading due to lucide load all icons in dev mode

### ISSUE THREAD

**Issue by corentingosselin** [lucide-icons/lucide#2583]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.454.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

My network inspector when the page is loading
<img width="733" alt="Capture d’écran 2024-11-04 à 09 46 51" src="https://github.com/user-attachments/assets/cd146a9c-9305-4bfa-840f-a63e8e7cc26c">

I saw [here](https://christopher.engineering/en/blog/lucide-icons-with-vite-dev-server/) in dev mode, vite does not use tree shaking.

I tried this fix on my nx mono repo setup but I can't import the icon:

10:04:34 [vite] Internal server error: Failed to resolve import "lucide-react/Save" from "src/components/HotelConfigurationComponent.tsx". Does the file exist?

Is there any way to make it works ?

### Steps to reproduce

Just import any icon

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Closing in favor of #1944
