### ISSUE TITLE
Approximately Icon

### ISSUE THREAD

**Issue by wladpaiva** [lucide-icons/lucide#2586]
### Icon name

Approximately

### Use cases

_Approximately_ is a pretty handy symbol when working with computed values specially in the Bitcoin world where the value of the bitcoin is always an approximation in a given currency.

### Design ideas

![Screenshot 2024-11-06 at 10 40 58](https://github.com/user-attachments/assets/28c4b328-9923-44eb-92f5-4383dfd7d886)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by ksk3110** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M5+15a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E%3Cpath+d=%22M5+9a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E"><img alt="icons" width="200px" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNNSAxNWE2LjUgNi41IDAgMCAxIDcgMCA2LjUgNi41IDAgMCAwIDcgMCIgLz4KICA8cGF0aCBkPSJNNSA5YTYuNSA2LjUgMCAwIDEgNyAwIDYuNSA2LjUgMCAwIDAgNyAwIiAvPgo8L3N2Zz4=.svg"/><br/>Open lucide studio</a>

**Comment by karsa-mistmere** [comment]
> [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/95f0a53fd217d555aa14ddb8bedd93388e8a5680670d0482f500f8bb0c9921c9/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4e5341784e5745324c6a55674e693431494441674d434178494463674d4341324c6a55674e693431494441674d434177494463674d4349674c7a344b49434138634746306143426b50534a4e4e534135595459754e5341324c6a55674d434177494445674e794177494459754e5341324c6a55674d434177494441674e7941774969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M5+15a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E%3Cpath+d=%22M5+9a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E)

That seems like a perfect solution to me. :)

**Comment by ksk3110** [comment]
> That seems like a perfect solution to me. :)

Thank you :-)
How do I go about adding this icon?
I am new to this.

**Comment by ksk3110** [comment]
> > [<img alt="icons" width="200px" src="https://camo.githubusercontent.com/95f0a53fd217d555aa14ddb8bedd93388e8a5680670d0482f500f8bb0c9921c9/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4e5341784e5745324c6a55674e693431494441674d434178494463674d4341324c6a55674e693431494441674d434177494463674d4349674c7a344b49434138634746306143426b50534a4e4e534135595459754e5341324c6a55674d434177494445674e794177494459754e5341324c6a55674d434177494441674e7941774969417650676f384c334e325a7a343d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M5+15a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E%3Cpath+d=%22M5+9a6.5+6.5+0+0+1+7+0+6.5+6.5+0+0+0+7+0%22+/%3E)
> 
> That seems like a perfect solution to me. :)

Thank you :-)
How do I go about adding this icon?
I am new to this.
