### ISSUE TITLE
Unable to Run Locally - Need Help Setting Up the Project

### ISSUE THREAD

**Issue by epifaniofrancisco** [lucide-icons/lucide#2591]
Hello,

I'm interested in contributing to the Lucide project, specifically by improving the design. However, I'm currently unable to run the project on my local machine to preview the website and test my changes. 

I have followed the instructions in the README file, but I seem to be facing some issues during the setup process. Could someone please help me with the following?

1. What are the exact steps needed to run the project locally?
2. Are there any specific dependencies or configurations I need to be aware of to successfully launch the website on my local machine?
3. Is there any common troubleshooting advice for setting up this project?

I would greatly appreciate any guidance or instructions on how to get the project running locally.

Thank you!

**Comment by jamiemlaw** [comment]
The standard question to ask in this position is, what specific error are you getting?

I assume from your question that you're looking to update the design or functionality of the docs website, not the icons themselves.

I had a go at trying to run the website locally (something I haven't done before). So I did:

1. `cd docs`
2. `pnpm install`
3. `pnpm docs:dev`

And the site was up and running on `localhost`.

You have to make sure you're using pnpm, not npm. That's the only gotcha I can think of.

**Comment by epifaniofrancisco** [comment]
Thank you very much, it was really helpful! The issue was that I wasn't running the cd docs command first; I was just trying to run pnpm docs:dev directly from the project root.
