### ISSUE TITLE
Upgrade to 0.458.0 from 0.457.0 breaks: Could not resolve "../icons/alarm-check.ts" from .. aliases.js"

### ISSUE THREAD

**Issue by kyle-leonhard** [lucide-icons/lucide#2614]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.458.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

After upgrading to 0.458.0, my build breaks with: `Could not resolve "../icons/alarm-check.ts" from "node_modules/.pnpm/lucide-svelte@0.458.0_svelte@5.2.0/node_modules/lucide-svelte/dist/aliases/aliases.js"`. Despite not importing that icon anywhere.

https://github.com/lucide-icons/lucide/pull/2584 stands out as potentially related. @ericfennis, fyi, in  case this rings a bell.

### Steps to reproduce

TODO: I have my repo, but not a minimal repro.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by aunumever** [comment]
Happening to me as well. It's referencing a .ts file, but there are only .js files.

**Comment by dongumayagay** [comment]
having this issue as well

**Comment by wiesson** [comment]
Same here, also 

https://lucide.dev/guide/advanced/aliased-names#create-a-custom-module-declaration-file is missing svelte

**Comment by ericfennis** [comment]
Working on a fix!

**Comment by ericfennis** [comment]
It is fixed in `lucide-svelte@0.460.1`. 
Sorry for the inconvenience.

**Comment by ericfennis** [comment]
@kyle-leonhard Thank you for letting us know!
