### ISSUE TITLE
Icon is abnormal in windows explorer.

### ISSUE THREAD

**Issue by SMAH1** [lucide-icons/lucide#263]
## Prerequisites

Version: 0.14.0
Install: by npm
Operating system: Windows 10
Bits: 64 bits

## Description
When see large icon in windows explorer, some of icon is abnormal. like `alert-triangle`.

![diff-alert-triangle](https://user-images.githubusercontent.com/21136680/111294630-c4668400-865f-11eb-8f8b-e3bbf264bd41.png)

But it works in Firefox, edge, chrome, gimp, inkscape.

I check detail in `feather` and `lucide` for `alert-triangle`:

```
lucide : ... <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" /> ...
feather: ... <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"> ...
```

**Comment by locness3** [comment]
yeah just switch to linux

**Comment by ericfennis** [comment]
Hmm interesting, I think this has something to do with SVGO optimisations, I think windows doesn't support the short syntax. Do you use additional plugins in windows explorer to display svgs or is it natively supported?

**Comment by SMAH1** [comment]
I use default config in windows. but set `Open with` for `Microsoft Edge`

**Comment by locness3** [comment]
Doesn't it use IE to render those though?

**Comment by SMAH1** [comment]
It does not matter what it opens with
![Untitled](https://user-images.githubusercontent.com/21136680/111777155-25909080-88c8-11eb-8cf1-8439c8de2cd4.png)

**Comment by locness3** [comment]
I think we can say this is not our fault, and a windows bug - this doesn't happen anywhere else.
