### ISSUE TITLE
IdCard icon can't be imported

### ISSUE THREAD

**Issue by lyolkinn** [lucide-icons/lucide#2631]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.217.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

When I try importing IdCard I see the error 

> Module '"lucide-react"' has no exported member 'IdCard'.ts(2305)

I can also see that it is missed in the source code's "dynamicIconImports" files.

### Steps to reproduce

`import { IdCard } from "lucide-react";`

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
`id-card` was only added in v0.418.0

<img width="658" alt="image" src="https://github.com/user-attachments/assets/2281f9c7-8b70-46e0-a0c0-40e025f6cbc7">

Please upgrade your packages, 0.217.0 is ancient.
