### ISSUE TITLE
Consider making the default lucide-react icon size 1em instead of 24px

### ISSUE THREAD

**Issue by chris-orgorg** [lucide-icons/lucide#2636]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

I would like to be able to use the icons with a default size of 1em e.g. <Info /> would be width/height: 1em instead of 24px.  I could add a global css rule .lucide for this, but then I'm unable to override this style with custom sizes like <Info size={30} />

### Use cases

I would like to be able to use the icons with a default size of 1em e.g. <Info /> would be width/height: 1em instead of 24px.  I could add a global css rule .lucide for this, but then I'm unable to override this style with custom sizes like <Info size={30} />

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by karsa-mistmere** [comment]
`em` is not a valid dimension unit for SVG elements, this would require CSS anyway and would lead to icon dimensions becoming completely unpredictable.

Overriding sizes with CSS to 1em is completely feasible already: https://jsfiddle.net/xf1zryvw/
