### ISSUE TITLE
Wrong version number in js files

### ISSUE THREAD

**Issue by SMAH1** [lucide-icons/lucide#264]
## Prerequisites

Version: 0.14.0
Install: by npm
Operating system: Windows 10
Bits: 64 bits

## Description

In begin of files:
```
dist\cjs\lucide.js
dist\umd\lucide.js
dist\umd\lucide.min.js
```

see:

```
/**
 * lucide v0.13.0 - ISC
 */
```

**Comment by ericfennis** [comment]
@SMAH1 I Found the issue, in the release workflow for github actions. I create a new version after the build.
I will move that step to beginning. Thanks for reporting this issue. Will be fixed in the next release.
