### ISSUE TITLE
Getting 404

### ISSUE THREAD

**Issue by samnayakawadi** [lucide-icons/lucide#2647]
### Package

- [X] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.462.0

### Can you reproduce this in the latest version?

- [ ] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [X] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

https://lucide.dev/icons/
https://lucide.dev/icons/?focus

Getting 404 | Not Found

### Steps to reproduce

https://lucide.dev/icons/
https://lucide.dev/icons/?focus

Visit these pages

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by ericfennis** [comment]
@samnayakawadi Works on my machine. Is this still happening?

**Comment by samnayakawadi** [comment]
Now started working. Still I recommend you should look into this matter.

**Comment by jguddas** [comment]
I can see the 404 screen flashing when I load the page but then it get's populated with icons.
