### ISSUE TITLE
Clock icons are referenced incorecctly

### ISSUE THREAD

**Issue by JakubGluszek** [lucide-icons/lucide#2649]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.451.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Description

'ClockArrowDownIcon' renders 'Clock'
'ClockArrowUpIcon' renders 'ArrowUp'

### Steps to reproduce

1. Import `ClockArrowDownIcon` icon
2. Add to a React component/view
3. Run the react app
4. Notice that the `ClockArrowDownIcon` is rendering the 'Clock' icon

Same goes for 'ClockArrowUpIcon', but it's rendering the 'ArrowUp' icon.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
I cannot reproduce this error:
https://codesandbox.io/p/sandbox/hardcore-wave-8wsdkj?workspaceId=4ddbaddd-ab88-4029-91a2-e5be8ed85e45

Can you share more of your code? (Maybe your imports, or any import overrides you might have)

**Comment by epifaniofrancisco** [comment]
I cannot reproduce this error too.
Check again your code.

**Comment by karsa-mistmere** [comment]
Closing since no response was given.
