### ISSUE TITLE
lucide-vue in npm is 0.14.0

### ISSUE THREAD

**Issue by SMAH1** [lucide-icons/lucide#266]
## Prerequisites

Version: lucide-vue 0.14.0
Install: from npm
Operating system: Windows
Bits: 64 bits

## Description
last version of `lucide-vue` is `0.14.0` (this [link](https://www.npmjs.com/package/lucide-vue)) but last version of `lucide` and `lucide-react` is `0.14.1` (this [link](https://www.npmjs.com/package/lucide-react)).

**Comment by ericfennis** [comment]
@SMAH1 No last version of [lucide](https://www.npmjs.com/package/lucide) is `0.14.0`. It's correct that `lucide-react` is on `0.14.1`, because it got an hotfix. See [release notes](https://github.com/lucide-icons/lucide/releases/tag/v0.14.1)
