### ISSUE TITLE
lucide-react has not index.d.ts

### ISSUE THREAD

**Issue by SMAH1** [lucide-icons/lucide#267]
## Prerequisites

Version: lucide-react 0.14.1
Install: npm & build
Operating system: Widows & linux
Bits: 64 bits

## Description

When install by `npm`, there are not any 'd.ts' files in /node_modules/lucide-react.
When `build` in ubuntu from source, create `index.d.ts` in dist folder of lucide-react.

**Comment by ericfennis** [comment]
@SMAH1 First of all welcome to the Lucice community!

Thanks for this issue. We are working on this. Yesterday I merged #243, this will be included in the next release!
