### ISSUE TITLE
Rename the "Link" export?

### ISSUE THREAD

**Issue by yekta** [lucide-icons/lucide#2678]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] all JS packages
- [ ] site

### Description

NextJS is one of the most used JS UI frameworks, and it is the most used React framework. It has a `Link` component. Lucide's `Link` icon is constantly racing with it for the import on VS Code. I imported Lucide's `Link` at least 10 times by mistake in the last month on a large codebase. I have also seen people (I'm guessing relatively newer to coding) doing the same and opening GitHub issues asking what's going on with their code even though it's just the wrong import. I recheck each time I import Link, and fix if required. It seems like an unnecessary overhead for using an icon library (even though an awesome one). `LinkIcon` is no problem but unfortunately (maybe fortunately for some) Lucide also exports these without the `Icon` suffix. I'm guessing there is a good reason for this but I figured I would ask anyways. Would you considering renaming the `Link` export?

### Use cases

I simply don't want to mistakingly import Lucide's `Link` instead of NextJS's `Link`.

### Checklist

- [X] I have searched the existing issues to make sure this bug has not already been reported.

**Comment by jguddas** [comment]
We can't remove exports without introducing a breaking change.

You can however remove them locally.

https://lucide.dev/guide/advanced/aliased-names#choosing-import-name-style

**Comment by yekta** [comment]
I've tried that for 20 minutes and couldn't get it to work as well. Maybe I'm misunderstanding something. If I remove the `.suffixed` part everything seems to work, autocomplete kicks in.


![Screenshot 2024-12-09 at 00 59 03](https://github.com/user-attachments/assets/50a379ec-ac59-42ed-b3a7-12ac8de52ecf)
![Screenshot 2024-12-09 at 01 00 16](https://github.com/user-attachments/assets/ea4bad95-2594-4446-a985-9c48fa8fca1d)
