### ISSUE TITLE
Design discussion(/bug?): `download-cloud` & `upload-cloud`

### ISSUE THREAD

**Issue by wayne-shih** [lucide-icons/lucide#268]
wondering if `download-cloud` and `upload-cloud` is the wrong way round? 
If not, what was the intention behind it? 

<img width="365" alt="Screen Shot 2021-03-18 at 10 53 26 PM" src="https://user-images.githubusercontent.com/51947763/111607141-d9e4d500-883c-11eb-8b6b-cccb22b55e95.png"> <img width="361" alt="Screen Shot 2021-03-18 at 10 53 42 PM" src="https://user-images.githubusercontent.com/51947763/111607152-dc472f00-883c-11eb-9071-2769b9a4a201.png">

rel: #246 
cc: @ericfennis

**Comment by ericfennis** [comment]
@wayne-shih Welcome to the lucide project, thanks for this issue.

You're totally right, I think I switched them. Lucky we didn't released the new cloud icons yet. 
I will create PR for it soon. Thanks!
