### ISSUE TITLE
SquareDashed is not exported in lucide-react package

### ISSUE THREAD

**Issue by ThomasAribart** [lucide-icons/lucide#2700]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [X] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.469.0

### Can you reproduce this in the latest version?

- [X] Yes
- [ ] No

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Description

SquareDashed is not exported in lucide-react package.

### Steps to reproduce

import { SquareDashed } from 'lucide-react'
// => Module '"lucide-react"' has no exported member 'SquareDashed'

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by jguddas** [comment]
Are you sure you are on the latest version?

**Comment by ThomasAribart** [comment]
Yes I am 🤷‍♂️

**Comment by ThomasAribart** [comment]
Sorry my bad, was on an older version

**Comment by jguddas** [comment]
No worry, happy to help 😊
