### ISSUE TITLE
Feature / Preact package

### ISSUE THREAD

**Issue by knoan** [lucide-icons/lucide#274]
Add a package for https://preactjs.com/ along the line of `lucide-react`.

**Comment by locness3** [comment]
I didn't know this, looks nice

**Comment by ericfennis** [comment]
Good idea @knoan !

**Comment by locness3** [comment]
How does lucide-react work with Preact already?

**Comment by knoan** [comment]
I guess it could work using [preact compatibility layer ](https://github.com/preactjs/preact-compat), but that would negate to some extent preact advantages.

**Comment by ericfennis** [comment]
I think it's better to create a new package. I think it's not a lot of work. Because we can use a lot of the `lucide-react` package.

**Comment by mittalyashu** [comment]
Not sure about the compatibility.

@knoan did you tried using `lucide-react` package?

**Comment by knoan** [comment]
Preact's compatibility layer is intended to bridge React libraries, so it *should* work, but I'm just guessing :-(

**Comment by knoan** [comment]
However, my suggestion is to have a native Preact package: I'd rather stay with React than use a backward compatibility layer with Preact.

**Comment by ericfennis** [comment]
@knoan Yeah we must make it a seperate package. That's the best for preact devs.
I think I will just word the same. I think it's just not al lot of work to make it work. I will start on it soon!

**Comment by ericfennis** [comment]
Just released `lucide-preact@0.15.1-beta.1` with typescript support.
For documentation see [docs](https://github.com/lucide-icons/lucide/blob/9e891f9a5f68cde5e19b3d8c8d1e28ca4c276f28/packages/lucide-preact/README.md)(temporary).
It works the same as the `lucide-react` package.

Testing is welcome, if you find something please post it in #291 .

**Comment by knoan** [comment]
@ericfennis kudos
