### ISSUE TITLE
Icon Request: Signal level

### ISSUE THREAD

**Issue by cvialard-astro** [lucide-icons/lucide#283]
Name : Signal 1,2,3,4, no-signal, signal-research
Is it possible to have something like that : 
![signal-indicator](https://user-images.githubusercontent.com/82038049/113715366-b7323780-96e9-11eb-833f-1513eeb5f596.jpg)

Thank you for your help

**Comment by delnyn** [comment]
This is a good idea, but I don't know how we could show the empty bars.  
I see 2 main solutions: 
1. Nothing, like in the `battery` icon  
![image](https://user-images.githubusercontent.com/45879791/127869968-f9433c15-6322-4173-b3d3-b41fc5bd6006.png)
The problem here is that the `signal-1` would be a single small bar, which isn't easily recognizable.  
2. translucent bars, like in material 
![image](https://user-images.githubusercontent.com/45879791/127870736-232a7d0e-5063-4662-b5ce-68862866be24.png)
I think this is a bad idea because no other icon is like this and the SVG color attribute could be a problem

**Comment by cvialard-astro** [comment]
Good idea!
I see a 3rd solution: the empty bars can have only the border. Something like this :
![image](https://user-images.githubusercontent.com/82038049/127872469-d5655ee2-36fd-4fe9-9814-6cd4b8c67f3a.png)
![image](https://user-images.githubusercontent.com/82038049/127872686-a127eec2-a035-41fc-bd53-c44ff60d0394.png)

What do you think?

**Comment by delnyn** [comment]
I think this is impossible because - if you take a look at other icons you will notice it - we don't fill any shape so we keep the icon pack consistent, therefore active bars will either have to be empty rectangles or simple bars

**Comment by locness3** [comment]
I think they just should be empty - don't we already have these icons?

**Comment by locness3** [comment]
> don't we already have these icons
`bar-chart` can be used for full signal.

**Comment by delnyn** [comment]
yes, we just need someone to make the other ones - but who?

**Comment by cvialard-astro** [comment]
I saw something like that :
![image](https://user-images.githubusercontent.com/82038049/127967058-83794b4f-7a0b-4852-a8df-871d670f4717.png)
What do you think?

**Comment by delnyn** [comment]
oh yes why not  
the empty bars will be dots

**Comment by LM1LC3N7** [comment]
I like this one, it is similar to the battery icon and pretty clear to understand :)

**Comment by ericfennis** [comment]
What do you think of this?
![image](https://user-images.githubusercontent.com/11825403/142267928-2b9fbcd2-67c1-4123-b1c7-156672d97985.png)

**Comment by LM1LC3N7** [comment]
This one is also pretty clear to understand but I still prefer the other one personally.

**Comment by ericfennis** [comment]
@LM1LC3N7 What do you exactly mean with the other one?

**Comment by LM1LC3N7** [comment]
This once : https://github.com/lucide-icons/lucide/issues/283#issuecomment-891565089

**Comment by ericfennis** [comment]
@LM1LC3N7 But that was not a design I think. It was some inspiration.

Here a variant with dots:
![image](https://user-images.githubusercontent.com/11825403/142777820-ae53dbab-f5bc-4607-b789-94da8f9e3605.png)

**Comment by LM1LC3N7** [comment]
Ok I didn't know!
I like the version with always dots, I found it pretty clear regarding the signal strength.
If I see two bar and then 3 dots I know for sure how the signal is received (for example), 2/5.

**Comment by delnyn** [comment]
I think we could get rid of the first dot? I think the icon looks too 'wide'. Also the first dot will always be a dot, no matter the signal intensity, so I don't think it's very useful. In my opinion

**Comment by ericfennis** [comment]
We want to keep the first dot, for the "zero" value. Also keeps consistency with the wifi icon.
I will add the signal icons without the dots, with the idea from #477 you can create the empty signal lines.
Let me know if you aren't ok with it, we can always make some changes.

**Comment by fabiendv** [comment]
@ericfennis The current signal version creates an “off-center” effect. I agree that the variant with dots would be more suitable. Would it be possible to create a new version based on the current one?
I understand that you want to keep consistency with the Wi-Fi icon, but that one is centered. The “low signal” icon is just a single dot on the left, which can create a poor UX experience for users.
