### ISSUE TITLE
Vue 3 issue when using the Vue package

### ISSUE THREAD

**Issue by AdamSGit** [lucide-icons/lucide#292]
## Prerequisites

* Version: lucide-vue@0.15.1
* Are you running from source/master: No
* Are you using a released build: lucide-vue on NPM
* Operating system: MacOs 10.15.7
* Bits: 64bits

## Step to reproduce

- Install a test Vue 3 repo with vitejs ([instructions here](https://vitejs.dev/guide/))
- install lucide-vue with `npm install --save lucide-vue`
- Create a dummy vue component
- Import and use any icon, with example code provided on this repo

## Any message or error

It will throw the following error : `[plugin:vite:vue] Cannot read property 'line' of undefined`
`line` is this example can be as well `color`, or others properties, depending on the icon you try yo import

My guess being that Vue3 change the way the render function work. Can't do much to help, as I'm not sure to understand why this is happening

## Resources

Please see the following screenshot

<img width="591" alt="Screenshot" src="https://user-images.githubusercontent.com/6126439/115142123-50454480-a040-11eb-96e2-02175a00f80b.png">

**Comment by ericfennis** [comment]
@AdamSGit I came across this issue as well. The vue functions from vue 2 are not compatible with vue 3. 
I'm working on a separate package for vue 3.

**Comment by AdamSGit** [comment]
Sound promising. Tried to hack around the `createVueComponent.js` to get it to work, I would say that I had mixed result. Gonna wait for the package then 😄
