### ISSUE TITLE
Feature Request: SVG Sprites

### ISSUE THREAD

**Issue by jessuni** [lucide-icons/lucide#313]
This is not a bug report but I can't find any templates that could address to feature requests so...

Ever consider supporting svg sprite? Spriting is also a common way to use svg icons. Could be as simple as a svg file like the one provided by Feather Icons [here](https://unpkg.com/feather-icons@4.28.0/dist/feather-sprite.svg). Let me know if there's anything I could help to make it happen.

Just found out this repo and I really appreciate that the community is maintaining and growing the original icon set. In fact I switched from Feathers to Lucide:) Great work, thanks again.

**Comment by ericfennis** [comment]
@jessuni Thanks for this issue. Good idea!
I'm thinking of adding this to a new package called: `lucide-static`.  Were we also can include: icon-fonts and the svgs.

Also thanks for the credits, welcome to the lucide community!

**Comment by jessuni** [comment]
Wonderful. The sprite file could be auto-generated with a script at build time, since it only requires some concatenation of HTML strings. Let me know when you need help :)

**Comment by jessuni** [comment]
I usually save the sprite as a static asset, import it as a template HTML adjacent to the container of a single-page app, and refer to individual icons in components.

Something like this: 

```
<div id="app">
  <div class="component-a">
    <svg>
      <use href="#airplay" />
    </svg>
  </div>
</div>
<div style="display:none">
  <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
      <symbol id="airplay" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M5 17H4a2 2 0 01-2-2V5a2 2 0 012-2h16a2 2 0 012 2v10a2 2 0 01-2 2h-1"/>
        <polygon points="12 15 17 21 7 21 12 15"/>
      </symbol>
    </defs>
  </svg>
</div>
```

**Comment by jessuni** [comment]
The generated sprite file works fine with the above usage.

**Comment by abejenaru** [comment]
Hi @ericfennis, I am using your generated sprite, thanks for generating it.
Looks like styling it via CSS doesn't work, probably because the symbols include their styling inline.
I see the original feather sprite doesn't include inline styles, so this works:

```
.feather {
  width: 24px;
  height: 24px;
  stroke: currentColor;
  stroke-width: 2;
  stroke-linecap: round;
  stroke-linejoin: round;
  fill: none;
}

<svg class="feather">
  <use href="path/to/dist/feather-sprite.svg#circle"/>
</svg>
```

I also find it confusing to have one package for the JS distribution and another one for the SVG sprites - doesn't it make sense to have the SVG icons and sprite in the main package ?

**Comment by ericfennis** [comment]
@abejenaru Yes this mentioned @BinaryKitten as well. The sprite is not working well yet. I'm trying to make a fix with the feedback from @BinaryKitten in #401

**Comment by abejenaru** [comment]
> @abejenaru Yes this mentioned @BinaryKitten as well. The sprite is not working well yet. I'm trying to make a fix with the feedback from @BinaryKitten in #401

Meanwhile I build my own sprite using svg-sprite and some regex, and I think using svgo directly would allow you to clean the svgs before building the sprite.
