### ISSUE TITLE
Feature Request / Tag SVG elements with lucide-specific classes

### ISSUE THREAD

**Issue by knoan** [lucide-icons/lucide#317]
Tagging SVG icon elements with lucide specific classes like

```html
<svg class="lucide lucide-{icon-name}">…</svg>
```

would make much more easier to reference them from CSS stylesheets, in order for instance to:

* factor app-wide sizing / stroke properties
* tweak sizing / alignment for specific icons

P.S. Suggestion born from a real-world struggle in keeping icons aligned with button labels using fonts with an atypical baseline…

**Comment by ericfennis** [comment]
Should we apply this for every package?

**Comment by knoan** [comment]
Would support sensible use cases also elsewhere, imho.

**Comment by queenvictoria** [comment]
The vue/nuxt package already does `.lucide-icon`
```css
<svg class="lucide-icon">…</svg>
```

The Feature vue package does `.feather.feather-{icon-name}`
```css
<svg class="feather feather-{icon-name}">…</svg>
```

I make good use of both of these and would love that the icon-name be included across the board.

**Comment by venashial** [comment]
That looks like it would work for Vue. I tried testing it locally with `yarn link` but I couldn't get my Vue app to compile, even on the master branch.

**Comment by queenvictoria** [comment]
Thanks @venashial I'm reluctant to make a PR until I can test locally. I think I'm having the same issue as you though. I'll try a local `npm link` and try main. I think I don't understand monorepo well enough yet.

**Comment by ericfennis** [comment]
@venashial To make a locally dev environment working, you need to run `yarn lucide-vue build`(from root). It will generate the needed JavaScript files from the icons and types etc.

After that running `yarn link` from `packages/lucide-vue` should work.

**Comment by queenvictoria** [comment]
Thanks @ericfennis 

For a user new to yarn: following are complete instructions for testing a package from a monorepo.

WARNING: Apple silicon[ follow this guide](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758) first.

Outside your project
```
$ git clone git@github.com:lucide-icons/lucide.git
$ cd lucide
$ npm install --global yarn
$ yarn install # May fail on Apple silicon see warning above.
$ yarn lucide-vue build
$ cd packages/lucide-vue
$ yarn link
```
Inside your project
```
$ yarn link lucide-vue
```

**Comment by queenvictoria** [comment]
Thanks for everyone's help on this. I've added a PR #395 to support Vue. It follows the format laid out by @knoan above.

I'd like to start using this in our project. I'm not clear how I can do this without publishing an npm package. The `gitpkg.now.sh` solution doesn't seem to work for us. I've seen other solutions with `post-install` hooks. Is that the way to do it?

**Comment by queenvictoria** [comment]
Hey @ericfennis that PR only resolves this ticket for `lucide-vue`. None of the other packages (including `vue-next`). So maybe it should stay open?

**Comment by ericfennis** [comment]
@queenvictoria I added it today for the other packages as well.

**Comment by queenvictoria** [comment]
Oh sweet!
