### ISSUE TITLE
Train icon ideas

### ISSUE THREAD

**Issue by MoltenCoffee** [lucide-icons/lucide#330]
## Icon Ideas

* Icon names: train, steam train

I tried my hand at creating a train icon, basing the design off of other transport icons like car, truck and bus. I was hoping for some feedback before I submit a PR:

Open cabin:
![train-01](https://user-images.githubusercontent.com/13321277/118499868-9b2da700-b727-11eb-8d3d-a3d1c9113c34.png)
Closed cabin, small front wheel:
![train-04](https://user-images.githubusercontent.com/13321277/118499874-9bc63d80-b727-11eb-8161-a97df3ee264d.png)
Closed cabin, same size wheels:
![train-05](https://user-images.githubusercontent.com/13321277/118499878-9bc63d80-b727-11eb-907b-2f2067b0dc81.png)

I get the feeling one might mistake it for a front loader or something. 
I think a more modern looking train would fit as well, but didn't really manage to come up with something that's unmistakenly a train whilst keeping the windowless style of the existing icons:

![train-02](https://user-images.githubusercontent.com/13321277/118499872-9b2da700-b727-11eb-95ac-24bd8bf98c4d.png)

Another approach, from a different angle is also possible, but is different from the existing transport icons:

![train-06](https://user-images.githubusercontent.com/13321277/118502792-522b2200-b72a-11eb-8438-eba2a8e361b2.png)
![train-07](https://user-images.githubusercontent.com/13321277/118502794-52c3b880-b72a-11eb-842b-5ab9634c6fc8.png)
![train-09](https://user-images.githubusercontent.com/13321277/118502796-52c3b880-b72a-11eb-8e24-d5deddf8027a.png)

Would love to hear your thoughts!

**Comment by ericfennis** [comment]
@MoltenCoffee Nice work.

I think both types of icons for transportation icons are welcome.
I like the first one of the locomotives.
For the train I think a front view is very recognizable to describe transportation.
I like the way how material does it, the headlights and the track  make it really like a train. But the icon lines are very dense, maybe we can use some inspiration of this and make it more cleaner? 🤔 
![image](https://user-images.githubusercontent.com/11825403/118719474-d368de80-b828-11eb-97b2-318fe1e582ff.png)

**Comment by MoltenCoffee** [comment]
I agree! The main problem I had was the rule about having 2 points distance between separate elements, like the train and the track. Is that more a guideline then a rule?

**Comment by delnyn** [comment]
![image](https://user-images.githubusercontent.com/45879791/161402624-ffd38287-b418-4900-809f-bd75ebb1e97f.png)
here is my idea

**Comment by ericfennis** [comment]
@delnyn Nicee, can you maybe post a 100% scale image?

**Comment by delnyn** [comment]
![train](https://user-images.githubusercontent.com/45879791/161449755-5a711507-8c49-4fde-9558-6a17c95ea20b.png)
100%

**Comment by ericfennis** [comment]
@delnyn sorry for late reply. I think it looks great!

**Comment by delnyn** [comment]
ty

**Comment by ericfennis** [comment]
@delnyn Yess do!

**Comment by ericfennis** [comment]
closed by #639
