### ISSUE TITLE
Tree shaking is not implemented

### ISSUE THREAD

**Issue by TheOnlyBeardedBeast** [lucide-icons/lucide#332]
## Prerequisites

* Version:lucide-react@ 0.15.18
* Are you running from source/master: false
* Are you using a released build: true
* Operating system: mac os
* Bits: 64 bits

## Step to reproduce

Use only some icons and build your react project then analyze it, all the icons are inside the bundle what makes the bundle big.

## Resources
* Screenshots
A screenshot from my project using only a few icons from lucid-react
<img width="690" alt="Screenshot 2021-05-23 at 12 00 01" src="https://user-images.githubusercontent.com/55414686/119265037-95333c80-bbe5-11eb-954f-86d4d2edfd0d.png">
A comparision using the same icons from the react-feather library
<img width="101" alt="Screenshot 2021-05-23 at 12 00 48" src="https://user-images.githubusercontent.com/55414686/119265090-c14ebd80-bbe5-11eb-9e41-74a0f9064436.png">

## Solution
I have modified the react-feather library so it can generate lucid icons.
https://www.npmjs.com/package/lucide-icons-react , I would be happy if I could transfer the package maintanance to the lucide team if it is possible, or I can help and publish new version when needed.

**Comment by ericfennis** [comment]
@TheOnlyBeardedBeast Thanks for reporting! I will look in to it.
