### ISSUE TITLE
Zip download filename needs to be updated

### ISSUE THREAD

**Issue by mikeott** [lucide-icons/lucide#334]
This is not a big deal, but I think you might want to change the filename of the downloaded file at https://lucide.dev.

At the moment hitting the **Download All** button downloads a file called **feather.zip**, where I expected it to be **lucide.zip**.

Unless this was for some reason intentional, then feel free to close this issue.

**Comment by ericfennis** [comment]
@mikeott Thanks for reporting. No this was not intentional, I think we forgot to rename this.
