### ISSUE TITLE
Alias for icon `send`

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#339]
Sorry but this issue is not about a new icon or bug... I just want know is it a good idea that add an alias `submit` for `send`?

**Comment by PeterlitsZo** [comment]
BTW, how about add an alias `wait` for `loader` ?

**Comment by ericfennis** [comment]
@PeterlitsZo Welcome to the Lucide community. Thanks for this idea, I think that's a great idea, more tags helps searching icons.

Feel free to add those tags in the [`tags.json`](https://github.com/lucide-icons/lucide/edit/master/tags.json)!
