### ISSUE TITLE
Icon Request: fold and unfold

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#343]
Is fold and unfold is a good idea? It is useful for my website...

**Comment by PeterlitsZo** [comment]
Is `maximize-2` and `minimize-2` a good idea? If it is, I think I can add it to `tags.json`

And I also have another idea for it...
![unfold](https://user-images.githubusercontent.com/25707198/120512867-4adc6780-c3fe-11eb-8ff4-631bc08c02da.png)

**Comment by locness3** [comment]
aren't these already added/proposed?

**Comment by PeterlitsZo** [comment]
> aren't these already added/proposed?

Sorry but... where? :eyes:

**Comment by locness3** [comment]
#238

**Comment by PeterlitsZo** [comment]
Thanks! I get it.
