### ISSUE TITLE
Illustrator Icon Design Template

### ISSUE THREAD

**Issue by JanTrichter** [lucide-icons/lucide#352]
Hey,
I just created a small Illustrator template which could help new designers to better and faster implement the [icon design guidelines](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md).

I uploaded it here: [https://icedrive.net/0/94vskayEo6](https://icedrive.net/0/94vskayEo6)

I adjusted the pen tool settings and line thickness to match the requirements of the icon design guide, added a small grid and marked the recommended margin in the document. I also added an icon which demonstrates how this template could be used.

Could you check if it fulfils all the requirements from the icon design guide and tell me if you have other feedback?

Have a great day 😎

**Comment by ericfennis** [comment]
@JanTrichter Sorry for my late reply, I was off for a bit.

I checked the template, it looks great. All the the guidelines are there and nice you added the padding.
I wasn't sure about the icon you placed in the center looks a bit random but that's me.

To finish I think we can add this to the repo if it's ready, so people can download it to use it.
Overall thanks for doing this @JanTrichter , awesome work.

**Comment by JanTrichter** [comment]
> I checked the template, it looks great. All the the guidelines are there and nice you added the padding.
> I wasn't sure about the icon you placed in the center looks a bit random but that's me.

Yeah, it is a bit random but it should demonstrate all the guidelines that you cannot see on the template itself (distance between lines, round corners, etc.)

**Comment by delnyn** [comment]
So you could put this file in the repo and link it in the docs (e.g. docs/ICON_DESIGN_GUIDE.md) ?

**Comment by JanTrichter** [comment]
> So you could put this file in the repo and link it in the docs (e.g. docs/ICON_DESIGN_GUIDE.md) ?

I have a lot of projects lately so that could take some time :(

**Comment by delnyn** [comment]
No no I meant both of you (I could do it myself too)

**Comment by JanTrichter** [comment]
> No no I meant both of you (I could do it myself too)

Got Ya!
Made a PR with the template and updated the according parts in the documentation! ( #377 )

**Comment by delnyn** [comment]
Great! Thanks a lot

**Comment by JanTrichter** [comment]
Done in #377
