### ISSUE TITLE
Landmark icon

### ISSUE THREAD

**Issue by connium** [lucide-icons/lucide#358]
## Icon Request

* Icon name: bank, landmark
* Use case: bank, building, business, capitol, landmark
* _Screenshots_ of similar icons:

In #347 and #350 bank icons are provided. AFAICS the icons do not fully match the [Icon Design Guide](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md).

I adapted the proposed icons, but I'm not quite sure which one fits best. So I present them here before creating a PR. Any hints are welcome!

1) Square base, 1px spacing
![landmark-1px](https://user-images.githubusercontent.com/3909302/126034433-0c13061b-3671-48e3-95f7-7530dc703a38.png)

2) Square base, 2px spacing
![landmark-2px](https://user-images.githubusercontent.com/3909302/126034476-cf1b23bf-7595-4d50-b915-b477ae060f3a.png)

3) Single base line, 2px spacing
![landmark-base-1-2px](https://user-images.githubusercontent.com/3909302/126034485-26d0fae2-0f18-4c08-b2a8-bc2d0d03c670.png)

4) Double base line, 1px spacing
![landmark-base-2-1px](https://user-images.githubusercontent.com/3909302/126034494-01ed5137-54fc-418f-887f-3d60d124f4b7.png)

5) Double base line, 2px spacing
![landmark-base-2-2px](https://user-images.githubusercontent.com/3909302/126034500-695a39af-3602-4679-93ec-9b0de88a8bdf.png)

6) Double base line, 2px spacing, 1px baseline spacing (one could argue that the two base lines belong to the same structural element)
![landmark-base-2-1px-2px](https://user-images.githubusercontent.com/3909302/126034561-763128b4-14fa-4d48-b9e5-5d4af1ca24b2.png)

Please let me know for which one I should create a PR.

**Comment by BeezBeez** [comment]
Thanks for the time spent on the bank icon !

**Comment by BeezBeez** [comment]
I personally prefer the 4th icon (Double base line, 1px spacing)

**Comment by delnyn** [comment]
the icon guidelines actually say that 
> Distinct elements must have 2 pixels of spacing between each other.  

so I would go with the 5

**Comment by ericfennis** [comment]
I like number 4th or the 5th one the most.

**Comment by Tummerhore** [comment]
I like number **6** the most.

**Comment by delnyn** [comment]
but the 1, the 4 and the 6 break the 2px spacing rule

**Comment by connium** [comment]
The guidelines say that
> Distinct elements must have 2 pixels of spacing between each other.

I created the 1px versions because to me it is not clear what is meant with "distinct elements".

- If each SVG element, that does not touch another element, counts as a distinct element, then 2, 3, 5 are the only valid ones.
- If base, pillars and roof of the building count as distinct elements, then 2, 3, 5, 6 are valid.
- If the building itself is a distinct element (in this case a building and a mountain in the same icon are two distinct elements), then all variants adhere to the guidelines.

Since I am unsure what is meant to be a distinct element and which is the best variant, I leave the decision to the community ;-)

**Comment by delnyn** [comment]
I think that each path that does not touch another element counts as a distinct element

**Comment by ericfennis** [comment]
What @delnyn says. So 2,3 and 5 are valid according to the guidelines. Maybe 6 can be allowed (because the stairs)🤔 , but that's only if it is a 'better' option.

**Comment by ericfennis** [comment]
Are the icons from #347 and #350 also in this list?

**Comment by delnyn** [comment]
my favorite is the 3

**Comment by connium** [comment]
> Are the icons from #347 and #350 also in this list?

Not exactly. The one from #347 is similar to 4 but doesn't use the full height of the view box. The icon from #350 is close to 2.

**Comment by connium** [comment]
Counting the votes in the comments before gives me

- 3: 1 vote
- 4: 2 votes
- 5: 1 vote
- 6: 1 vote

Considering that icon 4 is not a valid option, I still don't know for which icon I should create a PR :confused:

**Comment by delnyn** [comment]
I really think the 3 fits better with the rest of the set

**Comment by ericfennis** [comment]
@connium We discussed this in the discord channel, and we're in for number 3. You okay with that?

**Comment by connium** [comment]
@ericfennis I'm totally fine with this decision. Thanks for taking care of it!

I just created a pull request for the icon.
