### ISSUE TITLE
Headings icon(s)

### ISSUE THREAD

**Issue by btzr-io** [lucide-icons/lucide#363]
## Icon Request
I think a simple "H" will do it like the bold icon, but it can also have some variants for different headings levels.

* Icon name: Heading / Header
* Use case: Text editors.
* _Screenshots_ of similar icons:

Lucide (current icons ):

![image](https://user-images.githubusercontent.com/14793624/126822266-0495fc7f-04bc-4ef0-92b6-bcea78ea9bfb.png)

![image](https://user-images.githubusercontent.com/14793624/126822312-8fc47b71-4eb1-4a60-9740-822a01fa1d6d.png)

Github comments editor:

![image](https://user-images.githubusercontent.com/14793624/126822971-e8930668-8c07-47fd-a358-07545d5fc61a.png)

Material design icons (community ):

![image](https://user-images.githubusercontent.com/14793624/126821948-5dc888d8-cd0a-4913-9c03-71d4c8cd6cd3.png)

**Comment by locness3** [comment]
H

**Comment by delnyn** [comment]
I think a simple "H" shape will do the job?  
What do you think?

**Comment by ericfennis** [comment]
Yes or/and for each heading one h icon, or is that to much?
I think for a lot WYSIWYG editors they like to have all these heading icons.

Related icon requests:
- https://github.com/feathericons/feather/issues/355
- https://github.com/feathericons/feather/issues/855
- https://github.com/feathericons/feather/issues/766

**Comment by ericfennis** [comment]
What do you think? 
![image](https://user-images.githubusercontent.com/11825403/152010591-57de2241-54e5-4277-8cb2-2e38e2352670.png)

**Comment by locness3** [comment]
h

**Comment by delnyn** [comment]
LGTM
