### ISSUE TITLE
Add a link to project website in readme file

### ISSUE THREAD

**Issue by Tummerhore** [lucide-icons/lucide#366]
It would be nice to have a link to the project website [lucide.dev](lucide.dev) in the readme file. Especially since there is the list of all exisiting icons.

**Comment by marchellodev** [comment]
It is displayed on the side bar, so I don't think that's necessary

![image](https://user-images.githubusercontent.com/61112084/128408937-7232c4e7-6e4a-44aa-9d27-b384be2521d7.png)

**Comment by Tummerhore** [comment]
Oh you're right. Didn't notice it the first time. In that case, I guess I can close this issue.
