### ISSUE TITLE
Icon Request: `cross`

### ISSUE THREAD

**Issue by lscheibel** [lucide-icons/lucide#37]
## Icon Request

* Icon name: cross
* Use case: health or pharmacies
* Screenshots of done icon:

![image](https://user-images.githubusercontent.com/44374653/85950015-71766080-b95a-11ea-84f1-fac46df02ca8.png)

Could submit this as a PR

**Comment by lscheibel** [comment]
Will submit as soon as I can 👍

**Comment by ericfennis** [comment]
Any progress on this @lscheibel

**Comment by lscheibel** [comment]
Hey, sorry for being inactive for so long. I sorta forgot about this 😅 

![image](https://user-images.githubusercontent.com/44374653/103922802-91aa8780-5114-11eb-848a-f519d9871fb9.png)

I prefer B with a border-radius of 1 px on the outer edges. What do you think?

**Comment by locness3** [comment]
I prefer A

**Comment by ericfennis** [comment]
I prefer B

**Comment by lscheibel** [comment]
100% View
![image](https://user-images.githubusercontent.com/44374653/104165117-3e2c8800-53f9-11eb-9e3d-49af2d52616d.png)

Pixel preview
![image](https://user-images.githubusercontent.com/44374653/104165173-4e446780-53f9-11eb-87ad-be3d09517cf7.png)

Maybe this helps with deciding 😄

**Comment by ericfennis** [comment]
@lscheibel Nice thanks for sharing. I think A or B.
What's your own opinion?

**Comment by lscheibel** [comment]
~~I think B~~ actually I changed my mind to A. While B imo preserves the "cross" a bit better, the more round one seems to fit a bit better in the overall asthetic? Everytime I look at it my opinion changes 😄 

![image](https://user-images.githubusercontent.com/44374653/104239225-744e2400-545a-11eb-82c4-8cbcb9ab7486.png)

**Comment by ericfennis** [comment]
I'm with you, both looks have their advantages.
I let you choose which one you want to add!

**Comment by lscheibel** [comment]
Choose A now and updated the PR
