### ISSUE TITLE
Adding lucide.zip to release files

### ISSUE THREAD

**Issue by marchellodev** [lucide-icons/lucide#370]
As far as I understand, right now there are two ways to download all the files: via website and via github actions (artifacts).
Can we please make it, so that lucide.zip file is attached to releases as well?

**Comment by ericfennis** [comment]
@marchellodev Good idea, I was thinking to add it as a static package as well.

**Comment by marchellodev** [comment]
@ericfennis Why was this closed? :)

**Comment by ericfennis** [comment]
Is now added to the release pages. https://github.com/lucide-icons/lucide/releases/tag/v0.16.19
