### ISSUE TITLE
folder-open

### ISSUE THREAD

**Issue by kctdfh** [lucide-icons/lucide#381]
## Icon Request

* Icon name: folder-open
* Use case: Tree views usually need a way to show that an item has sub-items and whether or not an item is open. The "folder" icon is good for showing the existence of child items. When that list is opened, it'd be nice to have a "folder-open" icon to show the state. "folder-open" has many more use-cases but this is my specific use-case.
* _Screenshots_ of similar icons:
![2021-08-12 14_44_19](https://user-images.githubusercontent.com/28873487/129251458-1ef043fd-7de4-460d-b560-69d1fe1e9d7e.jpg)

**Comment by kctdfh** [comment]
Not a vector/icon designer but made something as a start.

I don't think the skew angle is enough because it looks messy when the icon is smaller than 18px. On top of that, my vector lines don't meet so changing the stroke width messes with the alignment.

I'll put it here in case someone else wants to take a stab at it.

[folder-open.zip](https://github.com/lucide-icons/lucide/files/6977982/folder-open.zip)

**Comment by JanTrichter** [comment]
Great idea!

Here are my proposals:

1.
![grafik](https://user-images.githubusercontent.com/72730682/129484618-75ed5d2c-1c8c-4e1f-91a1-2a33c7914df2.png)

2.
![grafik](https://user-images.githubusercontent.com/72730682/129484641-1b949ce2-2724-47c5-bcf8-59905f48767a.png)

**Comment by ericfennis** [comment]
Nice designs, can we make this icon similar with the current folder icon?

**Comment by JanTrichter** [comment]
> 
> 
> Nice designs, can we make this icon similar with the current folder icon?

Yeah sure.

**Comment by kctdfh** [comment]
Try the zip I posted earlier. That one is an SVG based off of the folder icon. I made it in Figma and there are some path issues but Figma SVG exports are really clean now and you should be able to work off of that. Also maybe try an online SVG to EPS converter. I haven't tried but maybe the compression recommended in the contribution docs makes the final SVGs incompatible with Illustrator.

**Comment by ericfennis** [comment]
@JanTrichter Maybe you have some problems with you graphics card in illustrator?
You can also try searching the icon on [lucide.dev](https://lucide.dev/), if you click in icon you have a button to copy the svg.

**Comment by JanTrichter** [comment]
> 
> 
> Try the zip I posted earlier. That one is an SVG based off of the folder icon. I made it in Figma and there are some path issues but Figma SVG exports are really clean now and you should be able to work off of that. Also maybe try an online SVG to EPS converter. I haven't tried but maybe the compression recommended in the contribution docs makes the final SVGs incompatible with Illustrator.

Converting it to EPS and then importing it in Illustrator worked, although I am not sure if the dimensions are correct. But importing your svg seems to work properly. Thanks a lot :)

**Comment by JanTrichter** [comment]
Alright, here are my drafts based on the original folder icon:

1. Closed variant
![Zeichenfläche 1@10_1x](https://user-images.githubusercontent.com/72730682/130060242-50aa6926-991b-4e45-9ba1-68a5b057199e.png)

2. Open variant
![Zeichenfläche 1@10_2x](https://user-images.githubusercontent.com/72730682/130060256-f0d2d486-bc9e-44d3-bf28-e5b8bb09eaba.png)

Any thoughts on that?

**Comment by ericfennis** [comment]
Nice I like it.
Can you provider both icons side by side in 100%, 24px.
I think a closed variant is not needed, because the normal folder icon is sort of "closed".

**Comment by JanTrichter** [comment]
> Nice I like it.
> Can you provider both icons side by side in 100%, 24px.
> I think a closed variant is not needed, because the normal folder icon is sort of "closed".

Sorry that I am late but I had plenty to do.
I made the comparison here: https://folder-comparison-fdav2qpv3-jantrichter.vercel.app/

**Comment by ericfennis** [comment]
Like this :)
![image](https://user-images.githubusercontent.com/11825403/131264437-4e9aca08-0b8d-4492-9573-270db1ed6b07.png)

**Comment by ericfennis** [comment]
Is the right one, but then with an open path

**Comment by JanTrichter** [comment]
I prefer the closed version.

**Comment by ericfennis** [comment]
Ok alright.
I but I think we should match the icon with the current folder icon. So can you make a version with the same height?
![image](https://user-images.githubusercontent.com/11825403/131561112-49569444-26d5-4e02-895d-7b4e17280c62.png)

**Comment by JanTrichter** [comment]
> 
> 
> Ok alright.
> I but I think we should match the icon with the current folder icon. So can you make a version with the same height?
> ![image](https://user-images.githubusercontent.com/11825403/131561112-49569444-26d5-4e02-895d-7b4e17280c62.png)

Kind of weird but In my Illustrator file it looks quite different than what you sent. Could you try to do this? doesn't seem to work with my Illustrator file.

**Comment by JanTrichter** [comment]
@ericfennis Could you do this? the dimensions in my file seem to be off but I don't know how I could adjust it acordingly.

**Comment by ericfennis** [comment]
@JanTrichter Yess of course I can fix it for you!

**Comment by JanTrichter** [comment]
@ericfennis that would be great! I don't know what has happened to my file but it looks weird when I adjust it and it doesn't match the height as it has the perfect height in my IL file :(

**Comment by ericfennis** [comment]
@JanTrichter 

Here you go:
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="m6 17 2-5h14l-3 8a2 2 0 0 1-2 1H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v4" />
</svg>
```

**Comment by JanTrichter** [comment]
@ericfennis does this solve the problem? I thought I had to adjust something in the icon? 🤔

**Comment by ericfennis** [comment]
Yeah it the height was different the current height icon, so I moved up the top line and the top line of the front flap.

**Comment by JanTrichter** [comment]
Looks good to me. Should we create a PR?

**Comment by ericfennis** [comment]
@JanTrichter yess do!
