### ISSUE TITLE
CSS stylesheet + font for web

### ISSUE THREAD

**Issue by marchellodev** [lucide-icons/lucide#392]
When an icon is treated as a character, browser will do a lot of cool stuff to make it look ok, such as adjust the icon size and set the icon color. Can we have this as an alternative to the svg approach for web?

**Comment by VonOx** [comment]
W

**Comment by ericfennis** [comment]
Is now added in Lucide static and you can download the zips of the build on the release page:
https://github.com/lucide-icons/lucide/releases/tag/v0.16.19
