### ISSUE TITLE
Documentation on how to use npm package in development

### ISSUE THREAD

**Issue by queenvictoria** [lucide-icons/lucide#398]
Hi there. I'm wondering if others have this issue: we fork lucide, create a branch, make a new icon, and, possibly, submit a PR.

Regardless of whether we think the icon has wider appeal, we now need to start using the new package.

As a monorepo, with intermediate build steps, it wasn't clear to me how to go about using the new package (`lucide-vue` in our case). I've been around the world in the last week trying different methods to get this working. 

_What doesn't work_

- Adding the git repo to `package.json`. For example `npm install queenvictoria/lucide#cool-icon`. As there is no build step and the package is nested into `packages/lucide-vue`.
- Using [gitpkg](https://gitpkg.now.sh/) service on the sub directory as the build steps occur in the root directory of lucide.

_What does work-ish_

Add a `postinstall` step to your projects `package.json` (and removing `lucide-vue` from dependencies). I read this [StackOverflow answer](https://stackoverflow.com/questions/39194648/npm-install-package-from-github-repo-subfolder#answer-39195334) right at the very beginning of this journey and dismissed it as too complicated. However it does work and, in the end, not so complicated.

```json
  "scripts": {
    "build:lucide-vue": "mkdir build_modules && cd build_modules && git clone git@github.com:queenvictoria/lucide.git && cd lucide && git checkout cool-icon && yarn install && yarn workspace lucide build && yarn workspace lucide-vue build && cd ../../ && npm install build_modules/lucide/packages/lucide-vue",
    "postinstall": "npm run build:lucide-vue"
  },
```

_Why -ish?_

So this works well locally. I am still working on our deploy system to to bring it in to production. There are currently a couple of failures:

1. `npm WARN lifecycle [repo]@[version]~postinstall: cannot run in wd [repo]@[version] npm run build:lucide-vue (wd=/usr/src/app)`
2. ` WARN  Module lucide-vue/nuxt not found. Please ensure lucide-vue/nuxt is in devDependencies and installed. HINT: During build step, for npm/yarn, NODE_ENV=production or --production should NOT be used.`

To resolve 1) I've added (to our Dockerfile) `RUN npm set unsafe-perm true`. Now it looks like `build:lucide-vue` gets called many times (possibly in a loop) which causes a timeout during our build step (currently 20 minutes)

_What next?_

I'd really like to understand if there is a proscribed method for doing this. And or that this be added to the documentation (perhaps in contributing). Or, if it's already there, apologies!

**Comment by Rogdham** [comment]
A possible solution would be to use the [`patch-package`](https://www.npmjs.com/package/patch-package) lib if the changes are not too big. Probably not the answer you were looking for, but a workaround.

It goes like this: you commit patches fo some libraries into your repo, and patch-package makes sure to apply the patches when needed (e.g. during install).
