### ISSUE TITLE
Add to playlist icon

### ISSUE THREAD

**Issue by prateekmedia** [lucide-icons/lucide#408]
## Icon Request

* Icon name: playlist_add
* Use case: For creating a playlist in a web app there can be icon, this can be similar to youtube's add playlist icon as attached below.
* _Screenshots_ of similar icons:
![Screenshot from 2021-09-23 13-03-05](https://user-images.githubusercontent.com/41370460/134469911-84f423da-44e8-4ee7-9f5a-71a0a47cd020.png)

**Comment by ericfennis** [comment]
Good suggestion!

**Comment by ericfennis** [comment]
`list-plus`

![image](https://user-images.githubusercontent.com/11825403/134821208-b9bf1d5f-3a7e-4a7e-8611-ca438fb6cf9a.png)

100%
![Frame](https://user-images.githubusercontent.com/11825403/134821186-d5456996-3598-4729-acde-725c090cceec.png)
