### ISSUE TITLE
Add `parser` icon

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#409]
## Icon Request

* Icon name: parser
* Use case: A tool that can parse one thing to another (for example, Rust code to runable program)
* _Screenshots_ of similar icons:
None. But I draw one. It looks not good:

![Screenshot from 2021-09-26 23-05-22](https://user-images.githubusercontent.com/25707198/134813372-82a0724a-a3fa-49e9-be40-1787415af1cb.png)

**Comment by delnyn** [comment]
uhm I think this icon is kind of hard to understand - also when you say  
> Rust code to runable program

it makes me think that you probably mean 'compiler' and not 'parser' (that's not exactly the same thing)

**Comment by locness3** [comment]
That's also a very specific need IMO

**Comment by PeterlitsZo** [comment]
> That's also a very specific need IMO

Sorry but what is IMO?

**Comment by PeterlitsZo** [comment]
I do think you are right. I find another icon to use. Although I forget what I choose...

The "command" icon or a triangle icon is also a nice idea to replace it.

**Comment by PeterlitsZo** [comment]
Need I close it?

**Comment by ericfennis** [comment]
I agree, "parser" icon is too specific, `command`, `code-2` or other icons are suitable for this use case .

**Comment by delnyn** [comment]
or `binary`
