### ISSUE TITLE
Medical icons

### ISSUE THREAD

**Issue by PodaruDragos** [lucide-icons/lucide#424]
Just found out about feathers and the I was inclined to check lucide. I always wanted to find a library like this ( very very nice icons ), And like every other developer with specific needs at specific times I would like to propose adding some medical icons to the library. Here are some 

* Icon name: medical icons
* Use case: medical related applications
* _Screenshots_ of similar icons:

Added some screenshots from [font-awesome-medic-icons](https://fontawesome.com/v5.15/icons/stethoscope?style=duotone)

![image](https://user-images.githubusercontent.com/6929749/137354606-f0890842-05d4-4f68-8337-f42bb2bb8ccc.png)
![image](https://user-images.githubusercontent.com/6929749/137354794-620571f8-4e14-430e-b1c2-db80bfe5374b.png)
![image](https://user-images.githubusercontent.com/6929749/137354979-18f03a49-1fc1-4188-97f1-c4bd11b2c2ca.png)
![image](https://user-images.githubusercontent.com/6929749/137355022-ccc74379-aff1-4b5c-adb7-016d3bcf0689.png)

**Comment by locness3** [comment]
> with specific needs at specific times

Not the purpose of Lucide, IMO.

**Comment by PodaruDragos** [comment]
@locness3 I totally agree. I was just saying those are some icons that I would love to have in lucide so I don't import multiple icons libraries

**Comment by PodaruDragos** [comment]
@ericfennis great, looking forward to those 2

**Comment by wojtekmaj** [comment]
What do you guys think about these?

`syringe`
![syringe svg](https://user-images.githubusercontent.com/5426427/143949750-6096dfc4-9289-41d0-8ffe-285771b03446.png)
```xml
<svg
  width="24"
  height="24"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="1"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <line x1="18" y1="2" x2="22" y2="6" />
  <line x1="17" y1="7" x2="20" y2="4" />
  <path d="M7 21l12-12l-4-4l-12 12z" />
  <path d="M6 14l2 2zm3-3l2 2zm3-3l2 2z" />
  <line x1="5" y1="19" x2="2" y2="22" />
</svg>

```

`syringe-2`
![syringe-2 svg](https://user-images.githubusercontent.com/5426427/143949776-3e07e09d-53c6-4713-b2bd-5ea514468796.png)
```xml
<svg
  width="24"
  height="24"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="1"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <line x1="18" y1="2" x2="22" y2="6" />
  <line x1="17" y1="7" x2="20" y2="4" />
  <path d="M9 19l10 -10l-4-4l-10 10l-0.5 4.5z" />
  <path d="M6.5 13.5l2 2zm3-3l2 2zm3-3l2 2z" />
  <line x1="4.5" y1="19.5" x2="2" y2="22" />
</svg>

```

**Comment by ericfennis** [comment]
@wojtekmaj The base looks good but.. When setting the stroke-width to 2 it looks a bit too tight.
With that it is not matching the [guidelines](https://github.com/lucide-icons/lucide/blob/master/docs/ICON_DESIGN_GUIDE.md). 
![image](https://user-images.githubusercontent.com/11825403/144887664-e9c09301-5925-46fd-914c-c71beb28caf9.png)

**Comment by Bowero** [comment]
I tried to work on the stethoscope, but I'm not a designer. Feedback is welcome.

![stethoscope](https://user-images.githubusercontent.com/14151691/159129408-a6e493e6-5863-4e17-b9c3-c5b6f90d1260.svg)

<img width="353" alt="Screenshot 2022-03-19 at 17 20 30" src="https://user-images.githubusercontent.com/14151691/159129431-c73ebe40-95ba-4ed7-aad5-a1a32f70c6a9.png">

**Comment by delnyn** [comment]
![image](https://user-images.githubusercontent.com/45879791/161403305-2d7a0fed-4685-44ea-b7c1-b1b43e51b4f6.png)
the stethoscope with geometrical shapes

**Comment by ericfennis** [comment]
@delnyn nice!

**Comment by delnyn** [comment]
thanks :)

**Comment by karsa-mistmere** [comment]
@wojtekmaj: While we could adjust the markings on the syringes to comply with the guides, I'd propose to get rid of them altogether:
 
![image](https://user-images.githubusercontent.com/17746067/162709844-6f764948-3406-4037-8edf-372e01237559.png)
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M18 2L22 6"/>
  <path d="M17 7L20 4"/>
  <path d="M9 19L19 9L15 5L5 15V19H9Z"/>
  <path d="M8 12L12 16"/>
  <path d="M5 19L2 22"/>
</svg>
```

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M18 2L22 6"/>
  <path d="M17 7L20 4"/>
  <path d="M19 9L9 19H5V15L15 5"/>
  <path d="M8 12L12 16"/>
  <path d="M5 19L2 22"/>
  <path d="M14 4L20 10"/>
</svg>
```

**Comment by delnyn** [comment]
last one is the best imo

**Comment by karsa-mistmere** [comment]
Yeah, I second that, I think the notches are definitely a bit too much, and the third one maybe looks a bit more like a bicycle pump than it does a syringe.

**Comment by ericfennis** [comment]
@karsa-mistmere @delnyn I agree last one looks the best. 

Feel free to open a PR!

**Comment by delnyn** [comment]
Will do!
