### ISSUE TITLE
Icon request: Subscript

### ISSUE THREAD

**Issue by nabanita-sarkar** [lucide-icons/lucide#431]
## Icon Request

* Icon name: `subscript`
* Use case: Various text editors
* _Screenshots_ of similar icons: https://github.com/feathericons/feather/issues/511#issue-389037358 

I saw this icon request in original feather repo and also found it is open in https://github.com/lucide-icons/lucide/issues/119#issue-733720662 . So I brainstormed and made these two variants - 
![image](https://user-images.githubusercontent.com/36895154/140747013-2549a9c8-8123-44fe-b11e-926aef82da2e.png)
![image](https://user-images.githubusercontent.com/36895154/140747064-8311d0dd-beb3-4dab-8071-87e8a6df77ce.png)

I think first one is more in line with feathers' minimalistic design

**Comment by nabanita-sarkar** [comment]
Is there anything that I need to change or I can create a pull request?

**Comment by delnyn** [comment]
> Is there anything that I need to change or I can create a pull request?

if everyone is okay with the first one - I like the first one more too - you can go ahead and create a pull request

**Comment by ericfennis** [comment]
First one is nice!

**Comment by nabanita-sarkar** [comment]
Great then. I will create a pr
