### ISSUE TITLE
Icon Request: Superscript

### ISSUE THREAD

**Issue by nabanita-sarkar** [lucide-icons/lucide#460]
## Icon Request

* Icon name: `superscript`
* Use case: Wysiwyg editors, markdown editors etc.
* _Screenshots_ of similar icons: https://github.com/feathericons/feather/issues/510#issue-389037247

I created a superscript icon similar to the subscript one that I made - 
![image](https://user-images.githubusercontent.com/36895154/147455419-a77295a9-49d5-46ae-aa69-76f03d76da67.png)

**Subscript Icon** 
https://github.com/lucide-icons/lucide/pull/459#issue-1089081929

**Comment by Andreto** [comment]
@nabanita-sarkar 
I don't think there is that much to discuss since it's so close to the `subscript` icon.
You can probably make a pr right away.

One thing though.
Perhaps add "exponent" as a tag.

**Comment by nabanita-sarkar** [comment]
Got it. I will do that
