### ISSUE TITLE
Feature Request: Link to icon

### ISSUE THREAD

**Issue by SamuelStevenson** [lucide-icons/lucide#461]
Is there any chance that we could get an option to copy a link to the icon with the currently set colour? I've been using the original Feather Icons in my Notion database and would love to be able to use the Lucide icons instead. Thanks!

**Comment by ericfennis** [comment]
@SamuelStevenson I'm don't think I totally understand what you want to accomplish. The way how we create the svg files is exactly the same as Feather Icons. So the color of each icon is set to "currentColor" that's the font size color of the document. 
Can you explain how you use feather inside notion? Maybe we can make lucide work their too.

**Comment by locness3** [comment]
I believe they want a feature to copy a link from the website, which would show a particular icon with the color selected in the customize dialog.

**Comment by karsa-mistmere** [comment]
They want a copyable URL which would return as a response the SVG source of a certain icon with the current customization options which they could then insert into Notion's custom icon dropdown:
![image](https://user-images.githubusercontent.com/17746067/234892459-be14dcbb-53e5-43fd-9a5b-64c53e04ed4b.png)

I think a better solution would be to what Simple.ink does and allow copying a data URI which would be a much more generic solution: https://notionicons.simple.ink/

**Comment by ericfennis** [comment]
I've in the new website, created an endpoint for directly requesting icons.

This will be an example of a request URL. 
`http://lucide.dev/api/icons/airplay?strokeWidth=1&color=ff0`
This API will be running on the edge and aggressively cached. 

@karsa-mistmere For the data url, I think aslo nice idea to add to website

**Comment by locness3** [comment]
what does "the edge" mean here?

**Comment by karsa-mistmere** [comment]
> what does "the edge" mean here?

[Vercel's Edge Network.](https://vercel.com/features/edge-functions)

**Comment by ericfennis** [comment]
The new website is live, and the endpoint from my latest comment is available. So have fun!

```
http://lucide.dev/api/icons/airplay?strokeWidth=1&color=ff0
```

**Comment by jguddas** [comment]
`Copy Data Url` also works with Notion.

![image](https://github.com/lucide-icons/lucide/assets/25524993/1b509c45-3919-4008-b6f1-188688f714f6)

**Comment by SamuelStevenson** [comment]
Amazing! It works beautifully. Thanks so much for the added functionality!
