### ISSUE TITLE
Something related to strokes

### ISSUE THREAD

**Issue by aigoya** [lucide-icons/lucide#473]
## Prerequisites

* Version: 
* Are you running from source/master: 
* Are you using a released build: 
* Operating system: windows
* Bits:

## Step to reproduce

*(Type here)*

## Any message or error

Strokes get ignored when generating fonts. You can convert them to fills to prevent this.

## Resources

* Links
* Screenshots
![image](https://user-images.githubusercontent.com/61224462/149515223-42fbce94-81d2-4540-9269-a08d7c640a61.png)

Here is what a great bug report would look like:

```
## Prerequisites

Version: Release v3.1.0
Running from: Import using webpack
Operating system: Mac OSX
Bits: 64 bits

## Step to reproduce

 - Import `check` icon
 - Add to a React component/view
 - Run the react app
 - Notice that the `check` isn't rendering correctly which seems a encoding problem
 
### Actual behavior:

 - Import `check` icon
 - Add to a React component/view
 - Run the react app
 - Check is displayed with correct encoding (e.g UTF-8)

## Any message or error

No console output
...

## Resources

No resources
...
```

**Comment by locness3** [comment]
Ok
