### ISSUE TITLE
I would like a Discord icon

### ISSUE THREAD

**Issue by wringit** [lucide-icons/lucide#478]
Hello. Thy selection of ikcons suck. Here is my Discord icon. 
![E27F3B90-A841-4A6B-950A-339FDBE6BF6A](https://user-images.githubusercontent.com/78825478/150143883-1664a3cf-62b2-42a3-9556-a355977c8118.jpeg)

Blarhgh

**Comment by locness3** [comment]
Hi! We really appreciate your contribution, however brand-related icons are deprecated and we are not adding new ones, as discussed in https://github.com/feathericons/feather/issues/763.

**Comment by ericfennis** [comment]
What @locness3 said, nice art btw!

**Comment by ericfennis** [comment]
@wringit If you need a brand icon like discord checkout: https://github.com/simple-icons/simple-icons
