### ISSUE TITLE
Request for svg sprite which can be used with <use xlink:href

### ISSUE THREAD

**Issue by boscharun** [lucide-icons/lucide#489]
Hi devs, is it possible to create an svg file as part of release in format -

```
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <symbol id="activity" viewBox="0 0 24 24">
      <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
    </symbol>
   ...
  </defs>
</svg>
```

This will allow adding an icon similar to this feather request - https://github.com/feathericons/feather/pull/319

**Comment by ericfennis** [comment]
@boscharun Welcome to the Lucide Project!
Yess we have an SVG sprite available, but it is included in the Lucide Static package.
https://www.jsdelivr.com/package/npm/lucide-static

**Comment by boscharun** [comment]
Thanks @ericfennis for the quick response, this is excellent. Would you please consider adding this in readme. The more obvious svg sprite inside the release zip files is different.

**Comment by PeterlitsZo** [comment]
Sorry, @boscharun , do svg sprite need load an large svg file? or need a lot of request? I think that use lucide with Vue/React/... is a better idea...

Just question >_<

**Comment by boscharun** [comment]
@PeterlitsZo , I have a python/django based project and don't use Vue/React. The full sprite is ~100Kb but is only 22Kb with zipped transfer which is very acceptable and much faster than individual svgs or our usecase. Thanks.

**Comment by ericfennis** [comment]
Added it to the Readme file!
