### ISSUE TITLE
Nuxt auto-importing generates too many files

### ISSUE THREAD

**Issue by arraintxo** [lucide-icons/lucide#497]
When using nuxt auto-importing feature a js file is generated per icon and all of them are downloaded on first page load, this means that more than 500 petitions are sent to the server on page load. This seems to much for any application...

## Prerequisites

* Version: 0.16.26
* Used on Nuxt with: lucide-vue/nuxt
* Operating system: Linux
* Bits:  64 bits

## Step to reproduce

Add "lucide-vue/nuxt" to buildModules on nuxt.config.js

### Actual behavior

When app is built a js file is generated for each icon. When page is loaded all this js are downloaded so more than 500 petitions are made to the server on first load.

## Resources

Build process generates a file per icon:
![imagen](https://user-images.githubusercontent.com/1630107/152804667-d89fba54-fa78-48e4-9f1e-faabafb49187.png)

Then all this files are downloaded on page load:
![imagen](https://user-images.githubusercontent.com/1630107/152804923-ec1205c3-6ed7-445c-aef5-814c7d223b3a.png)

```

**Comment by ericfennis** [comment]
@arraintxo Thanks for reporting, will take a look!

**Comment by EzequielRamis** [comment]
Hi @ericfennis, it also happens when running astro in dev mode with lucid-solid.
![image](https://user-images.githubusercontent.com/44057100/224555768-b0233c78-39cc-4839-bdfa-a0742c09b3c1.png)

**Comment by MrMelon54** [comment]
I use svelte and decided it was easier to just copy each icon into my project manually instead of using the library, because of this exact issue.

**Comment by ericfennis** [comment]
@MrMelon54 hmm that should be not the case anymore with the latest version of `svelte` `vite` and `lucide-svelte`.
This is what I just tested.
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/11825403/224575001-051ab10b-2a27-40c4-804f-ed877ace980b.png">

On which version are you?

**Comment by MrMelon54** [comment]
Last version I tested on was 0.102.0 since then I just haven't used the library

**Comment by ericfennis** [comment]
@MrMelon54 al lright good to know. Thanks for checking!

**Comment by ericfennis** [comment]
I'm going to close this since Vue 2 will be EOF end of this year.
