### ISSUE TITLE
Cookie icon

### ISSUE THREAD

**Issue by it-is-not** [lucide-icons/lucide#502]
I think a cookie icon might be helpful when people are making cookie popups and cookie settings.

## Icon Request

* Icon name: cookie
* Use case: in cookie settings, popups, etc
* _Screenshots_ of similar icons: <img width="24" alt="cookie icon" src="https://user-images.githubusercontent.com/72697755/154089770-c0fa7230-8233-41b6-9ddc-0726557186b2.png"> - I made this earlier but it probably needs changing a bit (I can give code if you want)

**Comment by ericfennis** [comment]
@it-is-not Cool idea!

**Comment by it-is-not** [comment]
Thank you, should I submit a pull request or do something else?

(I'm new to contributing here so I'm not really sure how this works)

**Comment by ericfennis** [comment]
@it-is-not open a PR if you want!

Please take a look at the [icon design guide](https://lucide.dev/docs/icon-design-guide) to make sure everything is right.

Let me know if you need any help.
