### ISSUE TITLE
Backup icon

### ISSUE THREAD

**Issue by hornta** [lucide-icons/lucide#503]
## Icon Request

* Icon name: backup
* Use case: Action to take a backup. The database icon doesn't convey a backup on it's own.
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/4553604/154135372-d611f00d-6a02-4e34-b84a-b320d76de440.png)

**Comment by ericfennis** [comment]
@hornta Nice idea!

**Comment by karsa-mistmere** [comment]
Due to design guide constrictions, I do not think the concept icon is feasible, similar ideas might be:
![image](https://user-images.githubusercontent.com/17746067/162701908-289d22b2-ba24-426f-b70e-90d5622c529f.png)

**Comment by ericfennis** [comment]
Here is my shot.
<img width="138" alt="image" src="https://user-images.githubusercontent.com/11825403/196053644-d63f4a17-7877-4ff3-966e-eb3a4d77f366.png">
