### ISSUE TITLE
Google Icon

### ISSUE THREAD

**Issue by PodaruDragos** [lucide-icons/lucide#512]
## Icon Request

* Google icon
* Usage: for social authentications

Just like the great facebook icon that we already have in lucide.

**Comment by ericfennis** [comment]
Sorry we aren't adding any more brand icons.
See original thread in [feather/#763](https://github.com/feathericons/feather/issues/763)

We recommend using: https://github.com/simple-icons/simple-icons

**Comment by PodaruDragos** [comment]
Thanks for the link, much appreciated.
