### ISSUE TITLE
Fork icon

### ISSUE THREAD

**Issue by czQery** [lucide-icons/lucide#521]
## Icon Request

* Icon name: fork or git-fork
* Use case: Fork counter/indicator
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/60880179/156922101-a5275a4b-e07c-4a6c-aab3-6f258a669472.png)

**Comment by ericfennis** [comment]
oh lol, I thought we had already one. But not. Good request!

**Comment by ericfennis** [comment]
I created 4 variants, what do you think?
<img width="126" alt="image" src="https://user-images.githubusercontent.com/11825403/157097564-b45bb4fb-128e-4324-a863-4fb4bdfdb879.png">

**Comment by czQery** [comment]
I like the second and third variants.

**Comment by mittalyashu** [comment]
I also like 2 and 3 icon.

**Comment by karsa-mistmere** [comment]
![image](https://user-images.githubusercontent.com/17746067/162728177-12da34f1-d9f2-406a-8d53-db33a4529a7f.png)

@ericfennis How about also adding matching git merge, pull and push icons?

**Comment by ericfennis** [comment]
@karsa-mistmere yeah why not!
