### ISSUE TITLE
Some icons

### ISSUE THREAD

**Issue by raphael141714** [lucide-icons/lucide#527]
## Icon Request(s)

Hello everyone.  

I made a while back quite a lot of icons in the style of feather-icons.  
They are available [here](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=0%3A1) and [here.](https://github.com/raphael141714/penguin-feather-library)  

Are you willing to accept this many icons?  
Many of them are brand icons, because the original plan was to create a Linux icon theme.  
But that went nowhere, as I don't have much free time at all.  

So here it is, I guess : My first batch of icon requests.

* *Category* : computer hardware
* *Use case* : some website about computer hardware, or the icons for an app that deals with computer settings.
* *icons* : 
  * [chip](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3574%3A388), a computer chip, like for robots and things
  * [pc-case](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3570%3A1), a pc case for external sensors like rgb and fan control; uses the same rectangle as the one for credit-card.
  * [pc-fan](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3572%3A8), a representation of a computer fan. Not fond of this design, I think it might violate the design rules.
  * [pcie-card](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3574%3A397), for GPUs
  * [memory-stick](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3577%3A386), a stick of RAM.
  * [touchpad](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3578%3A94)
  * [touchpad-off](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3578%3A104)
  * [amp](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3524%3A330)
  * [satelite](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3569%3A385)
  * [headphones-off](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3480%3A372), for things like "deafen" in discord
  * [ethernet](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3469%3A6)
  * [ethernet-off](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3471%3A158) for when you're disconnected
  * [ethernet-error](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3471%3A161) for when you're connected but not able to reach the internet
  * [ethernet-question-mark](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3471%3A212) for when you're not connected but there are available networks
  * [ethernet-connecting](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3471%3A201) 
  * (I also have two other ethernet icons with little notification dots, but they are so little I doubt they're even readable)
  * [gauge-2](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3492%3A93)
  * [headphones-with-mic](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3604%3A449)
  * [mouse](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3486%3A2)
  * [smartphone-off](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3675%3A477)
  * [tablet-off](https://www.figma.com/file/HpxOU06lL2ueyY1PHek2WN/Penguin-Feather?node-id=3680%3A536)

I'm willing to create many many many PRs, if that's ok.

**Comment by ericfennis** [comment]
Really nice icons, create PR's if you want! 
It is ok if you have multiple icons in one PR, but group them by type. Like all the 'ethernet' icons for example. 

There are some icons need to be checked before you want to submit them. I doubt they match the [guidelines](https://lucide.dev/docs/icon-design-guide):
- pc-case
- pc-fan
- touchpad
- touchpad-off
- memory-stick

And I think some are to specific for lucide, like `pcie-card`. But I wonder what the rest of the community things.

**Comment by karsa-mistmere** [comment]
I think `touchpad` + `touchpad-off` should be okay, they use the same dimensions as `credit-card` does, the same goes for the outer rectangle of `pc-case`: https://lucide.dev/icon/credit-card

I've made some fixed versions of the others: https://www.figma.com/file/oTmEVB7gbX8426Dh474A5z/%23527?node-id=0%3A1

**Comment by JamiltonMacedo** [comment]
> @raphael141714 Really nice icons, create PR's if you want! It is ok if you have multiple icons in one PR, but group them by type. Like all the 'ethernet' icons for example.
> 
> There are some icons need to be checked before you want to submit them. I doubt they match the [guidelines](https://lucide.dev/docs/icon-design-guide):
> 
> * pc-case
> * pc-fan
> * touchpad
> * touchpad-off
> * memory-stick
> 
> And I think some are to specific for lucide, like `pcie-card`. But I wonder what the rest of the community things.

I think PCI CARDs are usable for various pc components

**Comment by karsa-mistmere** [comment]
Also added an alternate memory icon to the Figma file as designed by @Kaladii (with a few tweaks by myself), see the third one:
![memory-3](https://user-images.githubusercontent.com/17746067/216549468-62aac06f-c492-40b6-bc90-310c9cfce10a.svg)

**Comment by ericfennis** [comment]
@karsa-mistmere Looking good!
