### ISSUE TITLE
Component Icon

### ISSUE THREAD

**Issue by jaspervermeulen** [lucide-icons/lucide#529]
## Icon Request

* Icon name: Component
* Use case: Creating a component/displaying that something is a component.
* _Screenshots_ of similar icons:

<img width="33" alt="Screenshot 2022-03-18 at 13 28 43" src="https://user-images.githubusercontent.com/56585012/159003671-d55c5c63-dc29-4526-b49d-94c44d3842d7.png">
<img width="537" alt="Screenshot 2022-03-18 at 13 35 28" src="https://user-images.githubusercontent.com/56585012/159004004-977e35e7-f8ed-4d2e-a2bf-a51ae04f2f32.png">

**Comment by jaspervermeulen** [comment]
https://www.figma.com/file/fSM8zuFMb8zk9oUPp1GQBI/Component-Icon?node-id=0%3A1

**Comment by ericfennis** [comment]
Nice idea!
I think this nice addition.

If you want to submit the icon you self. Please read the [Icon design guide](https://lucide.dev/docs/icon-design-guide) to make sure everything in line with the other icons

**Comment by delnyn** [comment]
also maybe a more literal name (for the possible future naming guidelines), e.g squares or something like that

**Comment by karsa-mistmere** [comment]
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M5.5 8.5L9 12L5.5 15.5L2 12L5.5 8.5Z"/>
  <path d="M12 2L15.5 5.5L12 9L8.5 5.5L12 2Z"/>
  <path d="M18.5 8.5L22 12L18.5 15.5L15 12L18.5 8.5Z"/>
  <path d="M12 15L15.5 18.5L12 22L8.5 18.5L12 15Z"/>
</svg>
```
![image](https://user-images.githubusercontent.com/17746067/162697034-23865d42-de77-475b-8373-bc777cec3930.png)

I think this more or less abides by all of the design guides, apart from the 2px rounded corners, which should be okay, since e.g. layout grid also does not have rounded corners: https://lucide.dev/icon/layout-grid

**Comment by delnyn** [comment]
maybe pixel perfect is better, to make sure it's well rendered everywhere

**Comment by ericfennis** [comment]
@karsa-mistmere @delnyn I'm fine with both of them. 
Maybe post a 100% of it, and also place it side by side with other icons. Can we compare and choose.

**Comment by karsa-mistmere** [comment]
![component](https://user-images.githubusercontent.com/17746067/167402556-368a319a-ee80-4b26-a5f4-dd71fbce92bb.png)

Here's the 100% view. Truth be told, I don't think either work amazingly well. 😅

**Comment by karsa-mistmere** [comment]
Yeah, I guess so too, the blurriness is a bit uneven between inner and outer sides, but it's not that horrible (and definitely has a visual weight that's much more consistent with the other icons). PR coming up soon.
