### ISSUE TITLE
Frame icon

### ISSUE THREAD

**Issue by Bowero** [lucide-icons/lucide#531]
## Icon Request

* Icon name: frame
* Use case: This icon would be mostly used by designers to explain features
* _Screenshots_ of similar icons:
<img width="475" alt="Screenshot 2022-03-19 at 14 56 26" src="https://user-images.githubusercontent.com/14151691/159123946-3849cb58-8653-4bb8-82f6-6f4f6315dd42.png">

## Proposals
<img width="926" alt="Screenshot 2022-03-19 at 14 54 38" src="https://user-images.githubusercontent.com/14151691/159123906-3cc5e0ba-9d9b-4c26-bb8f-8a5c7a0e809b.png">

I would love to hear your opinions on my proposals! I am leaning most towards option 3 myself.

If you agree, I'll create a PR for this.

**Comment by delnyn** [comment]
the first one seems to be the best, imo

**Comment by ericfennis** [comment]
I agree with @delnyn !

**Comment by karsa-mistmere** [comment]
I think all of these have too little visual weight compared to current icons, I'd suggest a slight increase in size as highlighted below:
![image](https://user-images.githubusercontent.com/17746067/162698805-b65a84a2-d0ad-4776-94f0-86c78c5ef8dd.png)
(square and frame-1 for comparison).

**Comment by karsa-mistmere** [comment]
Upon further consideration, `frame` should probably have the same dimensions as `crop` (making it even larger in essence):
![image](https://user-images.githubusercontent.com/17746067/162748680-3d9c4d45-f0e9-4bd7-ba2a-815c38898fdf.png)

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <line x1="6" y1="1" x2="6" y2="23"/>
  <line x1="18" y1="1" x2="18" y2="23"/>
  <line x1="23" y1="6" x2="1" y2="6"/>
  <line x1="23" y1="18" x2="1" y2="18"/>
</svg>
```

**Comment by ericfennis** [comment]
@karsa-mistmere Nope,we should resize the crop icon. The current crop icon is not matching the [Icon Design Guidelines](https://lucide.dev/docs/icon-design-guide). See issue #349 
But I agree with would be nice if they match.
