### ISSUE TITLE
Memory/Ram Icon

### ISSUE THREAD

**Issue by YesImSevy** [lucide-icons/lucide#542]
## Icon Request

* Icon name: Ram/Memory
* Use case: Show ram amount on a server, etc
* _Screenshots_ of similar icons:
https://fontawesome.com/icons/memory?s=solid

**Comment by delnyn** [comment]
that's a good idea, but recreating the one you sent while respecting the guidelines seems impossible. we would need to make some exploration

**Comment by ericfennis** [comment]
@raphael141714 created on in #527 , but it does need some refactoring to match the guidelines.

**Comment by YesImSevy** [comment]
> 

I mean it looks pretty much exactly like a stick of ram just not as wide when you look at like thin for example

**Comment by karsa-mistmere** [comment]
Closed as duplicate of #527
