### ISSUE TITLE
Circle Notch

### ISSUE THREAD

**Issue by YesImSevy** [lucide-icons/lucide#543]
## Icon Request

* Icon name: Circle Notch
* Use case: Use for like a spinning circle with a notch
* _Screenshots_ of similar icons:
https://fontawesome.com/icons/circle-notch?s=solid

**Comment by ericfennis** [comment]
@YesImSevy welcome to lucide. 
Thanks for the request, I think we already have something like this.
[`loader-2`](https://lucide.dev/icon/loader-2?search=loader) looks similar, does it work for you?

**Comment by YesImSevy** [comment]
> @YesImSevy welcome to lucide. Thanks for the request, I think we already have something like this. [`loader-2`](https://lucide.dev/icon/loader-2?search=loader) looks similar, does it work for you?

Oh I didn't think to search loading maybe on the website add that as a key word it shows up under?

**Comment by ericfennis** [comment]
Good one, I will add it as a tag!
