### ISSUE TITLE
Typescript annotation in Vue 3 with Vite

### ISSUE THREAD

**Issue by MLoth** [lucide-icons/lucide#548]
## Prerequisites

* Version: `"lucide-vue-next": "^0.16.29",`
* Operating system: `node v16.14.0`, `"typescript": "^4.4.3",`

## Step to reproduce

1. Create [a Vite project with the Vue 3 template](https://vitejs.dev/guide/#scaffolding-your-first-vite-project).
2. Install the Vue 3 lucide package (`npm install lucide-vue-next`).
3. Use an icon somewhere (with or without the setup function).
4. Build the app (`npm run build`) <- **this fails**.

## Any message or error

```
node_modules/lucide-vue-next/dist/lucide-vue-next.d.ts:548:48 - error TS2304: Cannot find name 'FunctionalComponent'.
export declare const SomeIcon: (props: SVGProps) => FunctionalComponent<SVGProps>;
                                                   ~~~~~~~~~~~~~~~~~~~
```

## Resources

No resources.

**Comment by MLoth** [comment]
I tried to manually import `FunctionalComponent` from vue in `lucide-vue-next.d.ts`. Afterwards the following error occurs:
```
node_modules/lucide-vue-next/dist/lucide-vue-next.d.ts: - error TS0000: Cannot find name 'FunctionalComponent'.
export declare const SomeIcon: (props: SVGProps) => FunctionalComponent<SVGProps>;
                                                       ~~~~~~~~~~~~~~~~~~~
```

**Comment by ericfennis** [comment]
Tnx for reporting, I will take a look!

**Comment by zoedsoupe** [comment]
that's the whole error:
```
'__VLS_templateComponents.LogIn' cannot be used as a JSX component.
  Its return type 'FunctionalComponent<SVGProps, {}>' is not a valid JSX element.ts(2786)
```

**Comment by ericfennis** [comment]
Tnx for reporting. I will reopen this issue.

**Comment by ericfennis** [comment]
Don't have this problem with the latest version.

**Comment by mezg0** [comment]
I'm having this problem on `0.252.0`

```
'ChevronRight' cannot be used as a JSX component.
Its return type 'FunctionalComponent<SVGProps, {}, any>' is not a valid JSX element.
Type 'FunctionalComponent<SVGProps, {}, any>' is missing the following properties from type 'VNode<RendererNode, RendererElement, { [key: string]: any; }>': type, key, ref, scopeId, and 12 more.
```

**Comment by ericfennis** [comment]
Reopening again then 😅
