### ISSUE TITLE
Telegram Icon

### ISSUE THREAD

**Issue by Teraskull** [lucide-icons/lucide#552]
## Icon Request

https://telegram.org/

* Icon name: Telegram
* Use case: Account link

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated, see: #94 
https://lucide.dev/icon/send?search=send is pretty similar, the addition of anything more similar to the actual Telegram logo is unlikely, due to #73

**Comment by ericfennis** [comment]
@karsa-mistmere is right, maybe take a look at [simple-icons](https://github.com/simple-icons/simple-icons)
