### ISSUE TITLE
Add tag for grip

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#595]
## Add tags for grip

I think `dots` is a good tags for `grip`, and `drag` and `move` is also good for `grip-vertical`.

How do you think so? It is OK, I will send a PR :)

**Comment by ericfennis** [comment]
@PeterlitsZo yess I agree with you. Don't hesitate to create a PR!

**Comment by PeterlitsZo** [comment]
See #598 please.
