### ISSUE TITLE
[Icon Requests from Feather] Food icons

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#596]
As per #119 and https://github.com/feathericons/feather/issues/32 here are a few suggestions:

![image](https://user-images.githubusercontent.com/17746067/163974049-b33ebc99-360d-47d7-a071-17168d5aa5d3.png)

I think `cloche` is maybe just not recognisable enough for what it is, `plate` is just too generic of a shape without additional context, but chef's hat and croissant seem like strong contenders.

**Comment by ericfennis** [comment]
@karsa-mistmere I agree with you on you're comment in the bottom. But the the 
chef's hat and the croissant are really well designed!

**Comment by lscheibel** [comment]
I really like the chefs hat.
