### ISSUE TITLE
[Icon Requests from Feather] Utensils

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#597]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/552:
![image](https://user-images.githubusercontent.com/17746067/163957992-76097899-1aae-4209-8aee-89da3b8d4a35.png)

![utensils](https://user-images.githubusercontent.com/17746067/163957910-68ad8f82-883f-42dd-8e22-60428514bf46.png)

**Comment by ericfennis** [comment]
@karsa-mistmere I think the length of the fork and the knife are a bit too long.

**Comment by karsa-mistmere** [comment]
Yeah, I've made an obscene amount of drafts before I stuck with these, as opposed to (some of) the others:
![image](https://user-images.githubusercontent.com/17746067/164200527-f95eadbd-3664-4974-82c1-5c518a911953.png)

I think if decreased in length the fork just looks way too much like a pitchfork. :)

**Comment by ericfennis** [comment]
@karsa-mistmere I understand what you mean.
Can you maybe post a side by side comparison in 100%, that's maybe a bit easier to judge

**Comment by karsa-mistmere** [comment]
1x + 2x view:
![utelsils-100p](https://user-images.githubusercontent.com/17746067/164619816-41d1589c-1bcd-40fe-a7ae-ce260f3e5828.png)
![utelsils-200p](https://user-images.githubusercontent.com/17746067/164619893-3940ef52-f874-4325-b92c-d0cb46baca4b.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Hmm I think the icons from the second row looks the best.

**Comment by ericfennis** [comment]
Found it in the TripAdvisor app. Maybe this also an idea. But I think this should be a second utensils icons. ![Screenshot_20220424-125016.jpg](https://user-images.githubusercontent.com/11825403/164972978-5efd83cf-f248-4e31-a34d-fe9c2c3afb87.jpg)

**Comment by karsa-mistmere** [comment]
![image](https://user-images.githubusercontent.com/17746067/165086049-4a4cac4f-c1be-4f32-89f2-b55f6e754100.png)

Respecting the design guidelines this is best I could come up with. Looks the pitchforkiest of them all to me. 😅

**Comment by ericfennis** [comment]
@karsa-mistmere Yeah I know, I don't think it is really of a problem. I think it will work fine :) 
What do you think crossed or side by side utensils?

**Comment by karsa-mistmere** [comment]
@ericfennis: I think we could easily have both, so people can choose what better suits their use case.

**Comment by ericfennis** [comment]
@karsa-mistmere yeah good idea! Let's add both.
