### ISSUE TITLE
Decentralize the tags

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#60]
We currently have a tags.json file in the root, containing tags for each icons.
This to improve searching on the [site](https://featherity.netlify.app/).

The problem with adding new icons is that we often forget to update this file.
So I thought maybe we can define it also in the svg file, when opening new PRs we can submit suggestions on the svgIcon.

```svg
<svg
  width="24"
  height="24"
  viewBox="0 0 24 24"
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  tags="read, dictionary, booklet, magazine, library"
>
  ...
</svg>

```

**Comment by delnyn** [comment]
That would be a lot of work

**Comment by ericfennis** [comment]
That's, still thinking if it's a good idea or not.

**Comment by Andreto** [comment]
That would benefit the icon submission greatly. How does the search work on the page? I have little experience with react and had a hard time following the code flow. If that stuff can be dealt with, then I would happily cook together a python script that updates the SVG files.

**Comment by ericfennis** [comment]
I revised this idea, I agree it will benefit the submissions, but there are some downsides.

It increases the file size.
For example the `square-x` icon is by the default 349 bytes, when adding the tags it is 402 bytes. 
An increase of 53 bytes, quite a lot for a file-size that small. Imagine using 100 icons. 
It is also not usable in an project if you using the svgs, the tags are only used in the site.
