### ISSUE TITLE
[Icon Requests from Feather] `bath`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#600]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/70:
![image](https://user-images.githubusercontent.com/17746067/164631114-7412a23f-9983-40eb-b0b8-ab835084a16a.png)
![bathtub](https://user-images.githubusercontent.com/17746067/164631193-329eae34-b50e-4755-9748-85580373283a.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice love it. On 100% is hard to tell the difference.
