### ISSUE TITLE
[Icon Requests from Feather] `cake`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#601]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/149:
![image](https://user-images.githubusercontent.com/17746067/164633230-c4314f80-8e51-4b7f-8ea6-e04ff7c94dcd.png)
![cake](https://user-images.githubusercontent.com/17746067/164633298-f92bc884-fedc-4220-81a9-38193358e13d.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice ? I like the first one, but curious what others think.

**Comment by karsa-mistmere** [comment]
I'm also partial to the first.

**Comment by JamiltonMacedo** [comment]
I prefer one single candle. The Third one.
