### ISSUE TITLE
[Icon Requests from Feather] `fax`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#602]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/210:

![image](https://user-images.githubusercontent.com/17746067/164634989-078a3371-0e90-40df-a350-fad3ecc97e69.png)
![fax](https://user-images.githubusercontent.com/17746067/164635081-1fdbd342-6fbc-47f9-bc64-cbcb10f4218a.png)
(printer for comparison)

**Comment by ericfennis** [comment]
Hmm not sure if this icon is still needed in 2022 🤔

**Comment by karsa-mistmere** [comment]
Yeah, I'm not sure either. While I know for a fact some people around are to this day hell bent on using fax vs. e-mail (🙄), I think in most cases the printer icon can easily be used to represent fax, as there is very little chance of having to use print AND fax in the same context.

Anyway, I'll leave the source code here for posterity, just in case anyone is in dire need of this icon. :D
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <rect x="6" y="10" width="16" height="12" rx="2" />
  <rect x="2" y="10" width="4" height="12" rx="2" />
  <polyline points="8 10 8 3 20 3 20 10" />
  <path d="M10 14H10.01" />
  <path d="M10 18H10.01" />
  <path d="M18 14H18.01" />
  <path d="M18 18H18.01" />
  <path d="M14 14H14.01" />
  <path d="M14 18H14.01" />
  <path d="M8 10V3H20V10" />
</svg>
```

**Comment by ericfennis** [comment]
Yeah I think the printer will work fine for the people who still needs an fax icon.
