### ISSUE TITLE
[Icon Requests from Feather] `sword`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#603]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/220:

![image](https://user-images.githubusercontent.com/17746067/164639943-7418d5fa-e612-4695-8a1e-52c06e6431d7.png)
![sword](https://user-images.githubusercontent.com/17746067/164640184-539c2e5b-22ad-4352-af9e-d7e699ca4b12.png)

**Comment by ericfennis** [comment]
Nice! I would say the right row!

**Comment by JamiltonMacedo** [comment]
The first on bottom looks like a syringe.

So a prefer the first one for `sword` and the second one for `Battle`.

**Comment by karsa-mistmere** [comment]
Yeah, and the third column is also the one most in line with the Lucide aesthetic, so I think I'll make a PR.
