### ISSUE TITLE
[Icon Requests from Feather] `camera-lens`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#604]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/221:

![image](https://user-images.githubusercontent.com/17746067/164642846-a723cdc2-e6b0-4436-9b61-aa2e5315c883.png)
![lens](https://user-images.githubusercontent.com/17746067/164642862-8210694e-2c33-48f4-9c23-a90062c25ca1.png)

First is the original suggestion, I think that looks a bit too much like an orb as opposed to lens.
Personally not sure whether this icon is needed at all, all in all, I prefer the simplicity of the last one, albeit named `focus` instead of lens.

**Comment by ericfennis** [comment]
I understand your concerns. I agree. Let go with focus!
