### ISSUE TITLE
[Icon Requests from Feather] `pill`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#605]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/264:

![image](https://user-images.githubusercontent.com/17746067/164643389-9907c3f8-e5cf-4003-86a0-daa38bfa820e.png)
![pill](https://user-images.githubusercontent.com/17746067/164643462-0a6d19bb-d830-4184-bfe9-766213c1b0bd.png)

**Comment by lscheibel** [comment]
I like the right one!

Alternatively I could submit one of these two:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/44374653/166152822-1d5677ab-a1c3-4080-b1cf-eba93a43c301.png">

<img width="56" alt="image" src="https://user-images.githubusercontent.com/44374653/166152827-906f6f09-4341-4719-b186-14b6fa19eed0.png">
<img width="29" alt="image" src="https://user-images.githubusercontent.com/44374653/166152857-e44b15af-1989-403e-80d7-24cfdc3c71a1.png">

**Comment by karsa-mistmere** [comment]
Not sure about the first, the 100% view looks a bit like a Croc or a sandal to me, and there's also not a big enough gap between the outer line and the rightmost dot.
