### ISSUE TITLE
[Icon Requests from Feather] `file-zip`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#606]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/339:

![image](https://user-images.githubusercontent.com/17746067/164643967-9f52e982-dc26-4254-82d5-4a5281e48bb7.png)
![file-zip](https://user-images.githubusercontent.com/17746067/164644071-c04d6195-87da-4a18-a636-8306db2efa54.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice, I think the zipper can be bigger. Maybe somethink like the github icons? 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/11825403/164973556-414d63d5-5290-48d1-8f76-cd3b038441ad.png">

**Comment by karsa-mistmere** [comment]
Yeah, the github icon looks nice, but doesn't quite fit well with the rest of the file icons.

**Comment by karsa-mistmere** [comment]
Here are the latest drafts. I think the best solution may very well be the simplest?...
![image](https://user-images.githubusercontent.com/17746067/168759431-663717a4-e803-48ec-bb99-bb0aa8e8e4e0.png)
![image](https://user-images.githubusercontent.com/17746067/168759479-b20170c3-1a7e-4aae-8d8f-d43b1028045c.png)

**Comment by ericfennis** [comment]
@karsa-mistmere What do you think of these ones?
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11825403/171026491-fc04f706-3bad-4f2e-9b34-179b575f8918.png">
<img width="76" alt="image" src="https://user-images.githubusercontent.com/11825403/171026828-c4ff2d57-feb6-4472-a2f8-60f3ecb94908.png">

**Comment by karsa-mistmere** [comment]
All the rest of the file icons use a straight line in case an inset item breaks the outline (e.g. `file-digit` or `file-search`), I think we should keep that uniform between file icons.
I like the first, but I'd either keep the slider rectancular or maybe even completely round?
![image](https://user-images.githubusercontent.com/17746067/171029767-bb2483a8-c164-4bc5-9cea-29a58606276f.png)
![zip](https://user-images.githubusercontent.com/17746067/171029950-6a393b1f-ef1e-4dc6-8820-f65e06dd3960.png)

I'm not really into breaking the guidelines, but I actually think maybe out of all of these many many icons so far, it's the third one that looks best. 😅

**Comment by ericfennis** [comment]
Yeah I had something like this as well, but the bottom left corner bothered me a bit. But maybe that's me.
I think I like the first one and the second one the most.

So maybe we need a second opinion. 😛

**Comment by karsa-mistmere** [comment]
Or we could split the difference and go with the 2nd, since that seems to be the most common ground so far. :)
