### ISSUE TITLE
[Icon Requests from Feather] `newspaper`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#607]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/459:

![image](https://user-images.githubusercontent.com/17746067/164644251-46a9a221-19dd-4f34-86cf-9812b808bd46.png)
![newspaper](https://user-images.githubusercontent.com/17746067/164644533-e19615c2-d43d-49f4-828f-e9f59a6c9af2.png)

**Comment by ericfennis** [comment]
What do you think of this? 
<img width="252" alt="image" src="https://user-images.githubusercontent.com/11825403/167260880-e2f7fb09-6d98-4544-a139-837d62aafc78.png">

**Comment by karsa-mistmere** [comment]
Hm... Not sure, on 100% it looks really similar to `building-2`.

**Comment by karsa-mistmere** [comment]
I have two alternate ideas:
![image](https://user-images.githubusercontent.com/17746067/167396136-571aeb57-9a7d-442f-9ca5-8a54e900c460.png)
![newspaper](https://user-images.githubusercontent.com/17746067/167396150-c95e6b64-6625-4ddc-ab4b-a166df987cf8.png)

I think the first one works pretty nice, the second is quite similar to Google's News icon.

**Comment by ericfennis** [comment]
Hmm, Can you post the svgs of the first you submitted. I want to try something.

**Comment by karsa-mistmere** [comment]
I put all my drafts in this Figma file: https://www.figma.com/file/HGBdDhJfh7VQMrykh3zKFJ/lucide%2Fnewspaper?node-id=0%3A1

**Comment by karsa-mistmere** [comment]
Also came up with a new design which I think also works OK:
![image](https://user-images.githubusercontent.com/17746067/171374405-5e68f1af-e014-471f-bf71-05a901a519fc.png)

**Comment by ericfennis** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/11825403/174476580-863a8160-c46a-423f-b2b5-9d2bc636309e.png">

**Comment by karsa-mistmere** [comment]
Yeah, that looks like kind of an optimal amalgamation of all previous sketches, I think it should work nicely. :)

**Comment by ericfennis** [comment]
Tnx! will create PR.
