### ISSUE TITLE
[Icon Requests from Feather] `handshake`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#608]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/444 and https://github.com/feathericons/feather/issues/486:

![image](https://user-images.githubusercontent.com/17746067/164644726-ead6b93b-7178-4199-8eae-1e96c32a12d9.png)
![handshake](https://user-images.githubusercontent.com/17746067/164644906-864b6fc4-7e59-4e7c-9ef5-111841890d4b.png)

**Comment by ericfennis** [comment]
Nice, Can image this is really hard one to design.
But I think the sleeves are missing to recognise the handshake.

**Comment by karsa-mistmere** [comment]
I just don't think there's enough place to fit in sleeves. We could add an extra line at the wrists, but I'm not sure if it's super helpful:
![image](https://user-images.githubusercontent.com/17746067/164983575-7df591c9-ff13-47cc-b27b-966f6b01b8f5.png)

**Comment by lvauvillier** [comment]
@karsa-mistmere nice work! Are those icons available in your repo? Or can you share the svg while waiting them to be officially supported?
Thanks a lot!

**Comment by jguddas** [comment]
Can we get something that is in the style of the other hand icons, maybe using negative space ![Frame 2 (1)](https://github.com/lucide-icons/lucide/assets/25524993/3c26ddd9-271d-4799-8aef-86ff5c41c987)?

**Comment by TheMikeyRoss** [comment]
> I just don't think there's enough place to fit in sleeves. We could add an extra line at the wrists, but I'm not sure if it's super helpful: ![image](https://user-images.githubusercontent.com/17746067/166889741-fcac3576-ad90-4bf4-9027-22888f77a7c0.png) ![handshake](https://user-images.githubusercontent.com/17746067/166889778-ff33c3d5-98e9-4441-a4cd-22a9934f96c6.png) ![handshake](https://user-images.githubusercontent.com/17746067/164644906-864b6fc4-7e59-4e7c-9ef5-111841890d4b.png)

These look nice, we can have 2 version a horizontal and a diagonal

**Comment by karsa-mistmere** [comment]
Here are two newly designed, slightly more geometrical and larger variants that I think are both definite improvements upon my earlier designs:
![image](https://github.com/lucide-icons/lucide/assets/17746067/0e0b9855-02be-475b-86da-f353469d1d3f)

<img width="850" alt="image" src="https://github.com/lucide-icons/lucide/assets/17746067/7a23f153-3a3a-4957-806b-325d16aa0f15">
