### ISSUE TITLE
[Icon Requests from Feather] `bird`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#610]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/472:

![image](https://user-images.githubusercontent.com/17746067/164645156-f87b2cb3-d49f-43e8-8d36-e04b7b7a3acb.png)
![bird](https://user-images.githubusercontent.com/17746067/164645228-f752115b-c772-4b98-8000-bd9731bfd191.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Really cute, I would say the most simple one. The first.

**Comment by karsa-mistmere** [comment]
@ericfennis: Thanks. I also really really like the last one, and that's maybe also more in line with original use case as outlined by @matthias-t. :D 
Maybe add both?

**Comment by JamiltonMacedo** [comment]
@karsa-mistmere I most Liked the last one too. The first looks like a litle chick

**Comment by lscheibel** [comment]
I love the last one too! Maybe we can remove the wing for it though?

**Comment by karsa-mistmere** [comment]
@lscheibel Here it is with and without wing.
![image](https://user-images.githubusercontent.com/17746067/166193819-0cc49ca2-ff06-4e17-999a-ed5f1e9db0e4.png)
![image](https://user-images.githubusercontent.com/17746067/166193852-2f231103-3d11-4a1a-ac49-367cf6299771.png)

I guess it's not too bad without, but the wing does add that little finishing touch for me, granted, it's maybe a bit too much detail compared to most other icons we have.

**Comment by JamiltonMacedo** [comment]
Vote to keep the wing detail

**Comment by ericfennis** [comment]
I vote for the one without the wing 😛 . I think the left one looks a bit too dense.
