### ISSUE TITLE
[Icon Requests from Feather] `puzzle`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#611]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/473:

![image](https://user-images.githubusercontent.com/17746067/164646180-71757c98-ff33-4084-92fa-53380b0f2366.png)
![puzzle](https://user-images.githubusercontent.com/17746067/164646162-a3492127-eb8c-428d-a2bb-092f9f558a6c.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice love the left one. The right one looks a bit weird to me without context.
