### ISSUE TITLE
[Icon Requests from Feather] `brain`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#612]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/509:

![image](https://user-images.githubusercontent.com/17746067/164647046-e6f5a49c-06bd-4a8e-a84d-7951c3cddcb9.png)
![brain](https://user-images.githubusercontent.com/17746067/164647062-3fdddfd3-0038-4156-8f02-799e481be5e6.png)

**Comment by ericfennis** [comment]
Can you try making one with some little waves?

**Comment by karsa-mistmere** [comment]
I also made this draft, but decided against it, since it doesn't fit with the design guidelines:
![image](https://user-images.githubusercontent.com/17746067/164982526-fe4b2593-7e71-47b7-9b20-7c54baa9fe27.png)
![brain](https://user-images.githubusercontent.com/17746067/164982611-4a3f3fc7-c549-4f81-a509-09dbf3360354.png)

I can't really see any way we could add more nuance without violating the guidelines. :(

**Comment by ericfennis** [comment]
hmm okay, I see.
I little-bit doubting the use case of this icon. Looking at the original request the use case was for AI. I'm not sure if this will full-fill this use case with a brain icon. Is using a CPU icons not enough. 🤔

**Comment by karsa-mistmere** [comment]
Yeah, brain is more generic, although I think a brain could work well for either a medical use case or for deep learning.

Here are a few extra drafts for the AI/deep learning use case:
![image](https://user-images.githubusercontent.com/17746067/167393154-ba945ea9-d0bb-4d98-b72b-b082d63551b5.png)
![brain n ai](https://user-images.githubusercontent.com/17746067/167393241-aebfefec-37a9-42fd-a15e-b7cf66921e7f.png)
