### ISSUE TITLE
[Icon Requests from Feather] `mask`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#613]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/514:

![image](https://user-images.githubusercontent.com/17746067/164647201-b0576cc8-39c2-4d41-9987-d7378be0402e.png)
![mask](https://user-images.githubusercontent.com/17746067/164647209-6c033b45-2a9c-4cb9-9f68-90ca681eb971.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice love the icon!
For naming , I think we should use an other name, maybe `carnival-mask` or `venetian-mask`. For the the word `mask` can also considered to other things, like medical masks and masking in design applications.

**Comment by lscheibel** [comment]
Personally I like the Spy/Agent style a bit better.

**Comment by karsa-mistmere** [comment]
@lscheibel I think there's definitely space for a separate spy / agent icon, I've just been unable to fit that within our 24x24 grid... yet. :)

Here are a few rough ideas:
![image](https://user-images.githubusercontent.com/17746067/166195931-7e1bd1c7-76a4-4b81-96e5-5fc9eb56ca65.png)
![spy](https://user-images.githubusercontent.com/17746067/166195984-a776bdaa-d999-4748-94c8-1ad4836b2969.png)
