### ISSUE TITLE
[Icon Requests from Feather] `helping-hand`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#614]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/831:

![image](https://user-images.githubusercontent.com/17746067/164739002-6d536653-12f7-45e5-85b8-5266749d4c42.png)

![helping-hand](https://user-images.githubusercontent.com/17746067/164739012-872680b6-a8c2-46dc-bb45-8331f7d92e71.png)

**Comment by lscheibel** [comment]
I like the third one
