### ISSUE TITLE
[Icon Requests from Feather] `boat` / `ship`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#616]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/631:

![image](https://user-images.githubusercontent.com/17746067/164648238-a3a4c02b-ea13-45be-8106-fa7181502927.png)
![boat](https://user-images.githubusercontent.com/17746067/164648253-62834dbe-cfd6-47cc-bf55-195894906cd1.png)

**Comment by ericfennis** [comment]
@karsa-mistmere I think the left one is not really in the "lucide" style. The left sail of the second one looks a bit too dense i think.

**Comment by karsa-mistmere** [comment]
Yeah, you're probably right in both cases, here's a looser version of sailboat:
![image](https://user-images.githubusercontent.com/17746067/164982261-e6c3eca6-5a23-4570-a4d0-be861405eb01.png)
![sailboat](https://user-images.githubusercontent.com/17746067/164982272-24af32d7-23b6-485d-ae45-26a9c00f80ab.png)

**Comment by Taimar** [comment]
Suggesting a few modifications:
- If the two sails are distinguished from each other by their size (which means the boat now has a moving direction from right to left), I feel it would be nice to distinguish the front and the rear of the boat as well. The front is pointier, the rear is usually dull or flat.
- I also adjusted the size of the larger sail to have nicer proportions.

<img width="480" src="https://user-images.githubusercontent.com/236343/170493158-3e08ea12-9d86-4932-92b8-15a2d2f371d6.png">
![sailboat](https://user-images.githubusercontent.com/236343/170493309-d7b6e1ab-820d-4956-845d-51c37a699007.svg)
