### ISSUE TITLE
[Icon Requests from Feather] `fence`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#618]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/697:

![image](https://user-images.githubusercontent.com/17746067/164648596-d1568f65-9697-45d6-8e95-f9df136cf9c5.png)
![fence](https://user-images.githubusercontent.com/17746067/164648611-bc9b304b-2e1c-46da-af1d-e2364ca45d97.png)

**Comment by ericfennis** [comment]
I like the icon, but I'm not sure about the usecase.

**Comment by ericfennis** [comment]
Also in the original PR there is no description of it. @mittalyashu Do you remember what your use case was?

**Comment by mittalyashu** [comment]
There is no specific use-case comes to my mind, except for using it in gardening website or privacy/security firms website stating to keep the bugs away 😂

**Comment by ericfennis** [comment]
For privacy or security I would say use the shield or lock icon.
But only a fence for a gardening website is I think too specific.

**Comment by ericfennis** [comment]
Need more reasons to add this icons.
