### ISSUE TITLE
[Icon Requests from Feather] `fuel`

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#620]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/879:

![image](https://user-images.githubusercontent.com/17746067/164648844-df68209b-dda8-4d14-9f7d-c8fc676237ed.png)
![fuel](https://user-images.githubusercontent.com/17746067/164648894-a0fb5fab-4367-4480-86cb-822c63f21fde.png)

**Comment by ericfennis** [comment]
I like both.

**Comment by JamiltonMacedo** [comment]
What about the oil barrel?
![image](https://user-images.githubusercontent.com/104264784/165198774-a2e8f3d0-c232-4519-82d0-0578cf051274.png)
![oil](https://user-images.githubusercontent.com/104264784/165198982-e28ae2e8-d2ea-4436-913a-ac96d827caf9.png)

**Comment by karsa-mistmere** [comment]
@JamiltonMacedo Personally not really a fan of the barrel shape itself, looks more like a spool to me.
Maybe something like one of these?
![image](https://user-images.githubusercontent.com/17746067/166196885-fdcfc5fc-d589-44a9-baa7-9f74aeade33d.png)
