### ISSUE TITLE
[Icon Requests from Feather] drink icons

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#621]
As per https://github.com/lucide-icons/lucide/issues/119 and https://github.com/feathericons/feather/issues/965:

![image](https://user-images.githubusercontent.com/17746067/164650795-0293fe95-172c-4be0-83b6-471e1b49ac86.png)
![drink](https://user-images.githubusercontent.com/17746067/164650803-75de188c-1417-4059-8f0e-9e72c80b3064.png)

**Comment by ericfennis** [comment]
Nice icons, love them.
I think we should not too go to specific with some icons. So I would say. Beer wine and one normal glass.

**Comment by karsa-mistmere** [comment]
Thanks, and you're right, one icon per type is plenty.
