### ISSUE TITLE
Google ICON

### ISSUE THREAD

**Issue by bauhuynhdev** [lucide-icons/lucide#627]
## Icon Request

* Icon name: Google
* Use case: Login with Google
* _Screenshots_ of similar icons:

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated, see #73 as well as https://github.com/feathericons/feather/issues/763.
Even still, it also goes against [Google's own guidelines](https://developers.google.com/identity/branding-guidelines) to use the Google icon by itself for this use case.

**Comment by tzeller** [comment]
as per date google is using its brand as icons - so please add google icon
https://about.google/brand-resource-center/logos-list/
