### ISSUE TITLE
Icon Update Request: GitLab

### ISSUE THREAD

**Issue by wj25czxj47bu6q** [lucide-icons/lucide#638]
As of yesterday, [GitLab changed their logo](https://about.gitlab.com/blog/2022/04/27/devops-is-at-the-center-of-gitlab/). As such,  the [GitLab icon](https://github.com/lucide-icons/lucide/blob/master/icons/gitlab.svg) no longer matches GitLab's logo.

Since this is an existing deprecated brand icon, I am not sure of Lucide's official stance on updating it. My personal opinion is that the icon should be deleted if the official stance is to reject the update.

**Comment by karsa-mistmere** [comment]
Damn, and I've just fixed this too. A new version would be:
![image](https://user-images.githubusercontent.com/17746067/166192992-9527119d-6c67-4935-8d67-e1a163ec993f.png)
```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M21.72,10.16l0,.07a4.46,4.46,0,0,1,.14,3,4.64,4.64,0,0,1-1.81,2.47h0L15.9,18.62h0L12.59,21a.85.85,0,0,1-.37.15h-.14a.86.86,0,0,1-.51-.16L8.28,18.62l-4.15-2.9,0,0h0a4.76,4.76,0,0,1-1.81-2.46,4.45,4.45,0,0,1,.14-3l0-.07L5.17,3.53a.65.65,0,0,1,.28-.31.81.81,0,0,1,.43-.11.76.76,0,0,1,.41.15.67.67,0,0,1,.24.34L8.59,9.11h7L17.64,3.6a.69.69,0,0,1,.25-.34.73.73,0,0,1,.41-.15.76.76,0,0,1,.42.11.6.6,0,0,1,.28.31Z" />
</svg>
```
I'll let others decide what to do with this one, as per #94 this redesign might be needed for a separate lucide-brand package.

**Comment by WfKe9vLwSvv7rN** [comment]
> Damn, and I've just fixed this too. A new version would be:
> ```
> <svg
>   xmlns="http://www.w3.org/2000/svg"
>   width="24"
>   height="24"
>   viewBox="0 0 24 24"
>   fill="none"
>   stroke="currentColor"
>   stroke-width="2"
>   stroke-linecap="round"
>   stroke-linejoin="round"
> >
>   <path d="M21.8 13.1a4.36 4.36 0 0 0-.14-3l-2.73-6.68a.72.72 0 0 0-.7-.42.73.73 0 0 0-.66.49L15.52 9h-7l-2.1-5.51a.74.74 0 0 0-1.36-.07l-2.72 6.71a4.36 4.36 0 0 0-.14 3A4.71 4.71 0 0 0 4 15.58l4.17 2.89 3.3 2.37A.94.94 0 0 0 12 21a.87.87 0 0 0 .5-.15l3.32-2.38L20 15.56a4.56 4.56 0 0 0 1.8-2.46Z" />
> </svg>
> ```

@karsa-mistmere For now, while this issue is in flux, do you have any objection to the use of your new design? (In accordance with the [Lucide license](https://github.com/lucide-icons/lucide#license) or another license of your choosing)

**Comment by karsa-mistmere** [comment]
Sure, go ahead, that's why I shared the source code. :)

**Comment by mittalyashu** [comment]
Sorry for burst the bubble. 

But, https://github.com/lucide-icons/lucide/issues/670

**Comment by ericfennis** [comment]
We will drop the support of brand icons after Lucide 1.0. So I close this one
