### ISSUE TITLE
[Icon Request] Magnet

### ISSUE THREAD

**Issue by SnoutBug** [lucide-icons/lucide#640]
## Icon Request

* Icon name: Magnet
* Use case: Grid Snapping
* _Screenshots_ of similar icons: 
![blender](https://user-images.githubusercontent.com/71790678/166144544-50574043-9a62-4286-a171-b85a80331c97.png) Icon in Blender

**Comment by SnoutBug** [comment]
Additionally separate icons displaying a grid and a magnet combined could make sense - perhaps even for rotation snapping?

**Comment by karsa-mistmere** [comment]
Magnet seems nice to have, here are a few proposals. Not quite sure about an icon depicting a grid+magnet, that seems a bit too detailed and too specific.
![image](https://user-images.githubusercontent.com/17746067/166192317-e06634ea-95b1-4856-a8cd-1ebc46b3263d.png)
![magnet](https://user-images.githubusercontent.com/17746067/166192329-517a74d2-9312-4565-85ee-c5231b487e21.png)

**Comment by SnoutBug** [comment]
I think no. 4 looks the best

**Comment by ericfennis** [comment]
@SnoutBug Nice request.
@karsa-mistmere I agree with @SnoutBug the 4th one looks the best I think.

**Comment by JamiltonMacedo** [comment]
Agree with the last one.

**Comment by karsa-mistmere** [comment]
Thanks for the feedback, I've created a PR.
