### ISSUE TITLE
New lucide.dev homepage design request

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#649]
We need a new homepage design. And I'm curious how others think about this.

## The problem
The current one is fine but performance is getting worse. 
The lighthouse insight is ranking us lower because the current homepage DOM size is to big. 
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/11825403/166317396-1ac22801-bc7d-4bbd-bc28-e07d9b3629ec.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/11825403/166317715-bf2564d5-7cc7-414c-874a-ae6d4a5f2ad3.png">
That's because we render all the icons on the homepage. So my Idea is to move the icons page to his own page, keeping the homepage fast and we can also reorder the homepages more focusing on more info e.g. add some more info about Lucide and the community.

## New Icons page
I started with the icons page already, also added categories so you can also view all the icons by category. We can also expand this with more features.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/11825403/166316961-020bf2c6-6c86-404f-be36-364645f5976f.png">

# What we need, a new design!

A new homepage design, designed in Figma or other design program, would be nice to view it online with public link.

The design should contain:
- link to icons page
- Github link
- download icons button?
- all the platforms we support, (we currently have all those icons above the buttons).
- maybe comparison things

It's a homepage so it can something cool and special, so be creative. Would be nice if it matches the current style and component library we use (ChakraUI).

Ideas are welcome!, Please leave comments below so we can discuss them!

**Comment by karsa-mistmere** [comment]
Yeah, I think load time is definitely an issue, and in the long run we're probably going to have to let go of the whole concept of having all icons visible on a single page.

As for categories: I really like the general idea, but I'm not quite sure if grouping by categories is the way to go (since, as I've already said in #94, categories have significant overlaps), I'd probably opt for a faceted search.

Here's a pretty rough first draft of what I imagine the front page and the icons page could look like:
https://www.figma.com/proto/MAGha7ERy1Suu2scKvRw1Q/lucide%2Fhomepage?page-id=0%3A1&node-id=2%3A196&viewport=242%2C48%2C0.58&scaling=min-zoom

**Comment by ericfennis** [comment]
@karsa-mistmere Woww that's loooks really lit :fire:, nice work!!
Really like customization panel, shows you what you can do with it.

Yeah for the categories I think would be nice to make it optional. Would be nice if the site can play a nice role as sort of tool. I think we can build a icon detail page as well. Feather icon tried to make one, really like this one: https://feathericons.dev/airplay. Maybe we can make tabs for each package so you can easily copy the code you need.

**Comment by karsa-mistmere** [comment]
Thanks. As for an icon detail page... hmm... not quite sure. Love all the added detail and the general idea of having an extra tool, but from a UX point of view I think it's problematic to heavily detach icon details from the list / overview. How about a larger modal instead of the current preview and a separate maximized detail page behind a maximize button?
https://www.figma.com/proto/MAGha7ERy1Suu2scKvRw1Q/lucide%2Fhomepage?page-id=0%3A1&node-id=46%3A24070&viewport=242%2C48%2C0.58&scaling=min-zoom

**Comment by it-is-not** [comment]
I like the prototypes a lot, but (just to suggest some more ideas to consider) I think maybe we could take everything from the modal and put it into a sidebar, and put everything in the sidebar above the icons. This would make it so you can browse icons and get the code at the same time, which is a bit similar to what what Material Icons does.
![image](https://user-images.githubusercontent.com/72697755/166997783-8d844151-5a33-4f14-92b9-2f1d4d4f19c4.png)

This is _very_ quickly made, and definitely needs changing quite a bit, but something like this might be good to consider:
![image](https://user-images.githubusercontent.com/72697755/167004496-0b313ddd-5afb-46e3-ac69-a5dbdd55db1e.png)

**Comment by it-is-not** [comment]
@karsa-mistmere I like all of those ideas but I agree - the last one would probably be best (people are used to it anyway).

Also, I've had a few other ideas (some better than others):

- when the search doesn't have any results, maybe it could have a link to [the icon request page](https://github.com/lucide-icons/lucide/issues/new?assignees=&labels=%F0%9F%99%8C+icon+request&template=icon_request.md)
- <kbd>shift</kbd> and click should copy the icon like it does at the moment (this isn't an idea, but it's easily forgotten)
- maybe we could have a shortcut to download it without having to find the download button or a shortcut to view the icon's preview page, and we could maybe write these shortcuts down somewhere
- the customize menu should keep its reset button and the color should default to `currentcolor` (this will make sure it works with all our users' projects)

**Comment by karsa-mistmere** [comment]
1. Love the empty search fallback idea
2. I actually had no idea shift click copied the icon.  We should probably add a help text stating this?
3. How about a context menu? Right click and a few preset options: copy name, copy svg, download, link to details page?
4. For sure, `currentColor` should definitely be thed efault.

**Comment by mittalyashu** [comment]
@ericfennis As for the performance issue for loading all the icons.

We can fetch the icons using an internal API and using pagination. That could resolve the issue.
And since, we're already using Vercel, they'll handling the cacheing of API response.

**Comment by locness3** [comment]
@karsa-mistmere I really like your mockups.

I am just not sure about this being a single column of text :
![image](https://user-images.githubusercontent.com/37651007/185784374-c0c48749-e50d-4b1b-93bc-7bf416fef219.png)

**Comment by Comprehensive-Jason** [comment]
Hopping in this issue to add another suggestion. Please add some way to filter icons by version, or add a small bit of text for each icon stating which version they were added. Most software is not up to date with the latest lucide version, so being able to check which icons are available would be a great help.

**Comment by karsa-mistmere** [comment]
@Comprehensive-Jason: you're kicking at an open door, we'll definitely have a version badge in the details overlay. :)
