### ISSUE TITLE
[Icon Request] Integrations/Plugins

### ISSUE THREAD

**Issue by outbackStack** [lucide-icons/lucide#651]
## Icon Request

* Icon name: Plugins/Integrations
* Use case: Menu for all plugins available in an app
* _Screenshots_ of similar ic
<img width="42" alt="Screen Shot 2022-05-04 at 5 14 56 pm" src="https://user-images.githubusercontent.com/16639496/166637118-d21507da-134e-46f2-a683-2703fd127594.png">

<img width="93" alt="Screen Shot 2022-05-04 at 5 14 05 pm" src="https://user-images.githubusercontent.com/16639496/166637015-f66333d9-bf44-4dab-947f-7dc803323b6a.png">
<img width="101" alt="Screen Shot 2022-05-04 at 5 13 53 pm" src="https://user-images.githubusercontent.com/16639496/166637035-db8b4899-756f-49e0-b9c7-e93dd4c9d1a5.png">

<img width="82" alt="Screen Shot 2022-05-04 at 5 15 44 pm" src="https://user-images.githubusercontent.com/16639496/166637218-c0406bf2-85e3-4408-8467-03392b213372.png">
<img width="75" alt="Screen Shot 2022-05-04 at 5 15 35 pm" src="https://user-images.githubusercontent.com/16639496/166637226-cd2f8ce0-e859-4f07-b554-0491b8272a3e.png">

**Comment by karsa-mistmere** [comment]
`puzzle` is already being added: #633 

As for electric plug, here is my take:
![image](https://user-images.githubusercontent.com/17746067/166668937-91831701-ab7a-4a84-a3fc-354edb614d0e.png)

Not sure about the lego piece, I think in most cases either `puzzle` of [`package`](https://lucide.dev/icon/package) can be used.

**Comment by ericfennis** [comment]
Really like the `plug` design from @mittalyashu for this one. He posted this one discord.
![image](https://user-images.githubusercontent.com/11825403/166693465-08bb0451-ffb9-4935-8872-55d0d83d2be0.png)

**Comment by outbackStack** [comment]
Thanks so much! They both look great! I guess we should stick with the square design to keep it consistent with our `plug-zap`?

<img width="276" alt="Screen Shot 2022-05-04 at 11 50 26 pm" src="https://user-images.githubusercontent.com/16639496/166695400-2fd9b4af-d3d7-48af-889e-88cdf4f2c21d.png">

**Comment by karsa-mistmere** [comment]
Yeah, it would be nice to be consistent, but I think it needs extra visual weight, maybe?
![image](https://user-images.githubusercontent.com/17746067/166696296-26f294db-6f9c-4d38-9dc2-8a5d38e1c846.png)

**Comment by outbackStack** [comment]
I like the second one at a 45deg angle @karsa-mistmere 👍

**Comment by karsa-mistmere** [comment]
Also, I think `plug-zap` might need a bit of tweaking, I think the zap itself is pretty illegible on low dpi:
![plug](https://user-images.githubusercontent.com/17746067/166701058-36e4ec08-9155-4ed5-9de8-9ef8b4551fed.png)

**Comment by karsa-mistmere** [comment]
Dunno... I've been doodling around, and I'm not quite sure what to think yet:
![image](https://user-images.githubusercontent.com/17746067/166875960-d2500389-4249-4ff5-b8c0-b9f577e653a7.png)
![plug](https://user-images.githubusercontent.com/17746067/166876007-8b278066-c72c-4f55-a473-96944b04ea80.png)

Column A is what we have right now (square for comparison only).
Column B is @mittalyashu's original proposal.
The rest are stuff I've been playing around with.

My issues:
- B1 is too small 
- C1 is large enough, but doesn't really look like a plug
- D1 looks OK-ish, but the orientation is not consistent between it and A1/E1
- E1 and E2 are too small
- F1 and F2 are large enough (and can use the same spark shape as our other icons), but maybe look less professional.

In general, Row 1 fits the Lucide style better but without the context of a spark I think it has much worse recognisability, especially in case of C1, D1 where for added visual weight the cord part had to be shortened, so would I not know it was an electric plug, it could be pretty much anything (C1 especially looks like a simplified robot head).

I'd prefer to keep the orientation the same between `plug-spark` and `plug`, but it simply doesn't seem feasible while also keeping it consistent in size with the rest of our icons.

All things considered, I think Row 2 would be a better option.

**Comment by outbackStack** [comment]
A challenge like working with icons in a small area is always fun, @karsa-mistmere 😀
Let's go with C2 and D1. This gives people a few options to choose from.

**Comment by ericfennis** [comment]
Can you maybe try make one little bit between `B` and `C` ?

**Comment by karsa-mistmere** [comment]
@ericfennis: Sure!
![image](https://user-images.githubusercontent.com/17746067/167382827-dbaaf8b7-9f51-4f9a-b7da-e8fdf5b79372.png)

**Comment by mittalyashu** [comment]
My thoughts

![CleanShot 2022-05-15 at 12 18 07](https://user-images.githubusercontent.com/29014463/168460862-01dd2a3d-50c2-4e1c-98d0-b7d6067d0bd2.png)

**1st icon**

* The length of the tail is big.

**2nd icon**

* I think we should decrease the distance of the pins by `1px` or `2px`

**3rd icon**

The icon does looks good, but it gives the retro/old feeling _(like the one's used in 90's)_

**Comment by karsa-mistmere** [comment]
As for the 3rd: in quite a few parts of the world (I think pretty much all of mainland Europe) almost all electric plugs (apart from phone charger adapters etc) look exactly like this to this very day.

**Comment by ericfennis** [comment]
@mittalyashu can you post icons on 100%.

**Comment by ericfennis** [comment]
Added in https://github.com/lucide-icons/lucide/releases/tag/v0.89.0
