### ISSUE TITLE
Alternate style for user icons

### ISSUE THREAD

**Issue by karsa-mistmere** [lucide-icons/lucide#657]
What do you think about adding an alternate user icon set?
I like the current one, but I think this rounded version would fit certain designs better and is a pretty conventional style:

![image](https://user-images.githubusercontent.com/17746067/167371222-99367a83-0c89-4750-a21c-1fe94c727179.png)
![user-alt](https://user-images.githubusercontent.com/17746067/167371234-3eb4bedf-5ac9-4ae4-9102-2b54ee1a99d2.png)

**Comment by shawarmaz** [comment]
Vote +1
