### ISSUE TITLE
How can I use "rem" as size unit?

### ISSUE THREAD

**Issue by lkj4** [lucide-icons/lucide#659]
Neither a bug nor an icon request. I'd like to use `rem` instead of pixel to size the icons. Reason: They scale when changing the html's `font-size` in contrast to a pixel unit. Is there a way I might have missed? I am using the Svelte package, fwiw.

**Comment by ericfennis** [comment]
@lkj4 Yes you can, you can use css for it, like @karsa-mistmere mentioned.
I created a CodeSansbox for you, check App.css.
The `.lucide` class is set on every lucide icon, so that one can use to style the icons.

https://codesandbox.io/s/svelte-style-with-rem-wdmozc
