### ISSUE TITLE
Backspace icon

### ISSUE THREAD

**Issue by hornta** [lucide-icons/lucide#672]
## Icon Request

* Icon name: backspace
* Use case: For on-screen keyboards like wordle games:
![image](https://user-images.githubusercontent.com/4553604/168465582-76f762bb-6a9f-468b-a4ba-e042403ba4b6.png)

* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/4553604/168465597-38967178-28b6-4ac2-91eb-95eb5a984117.png)

**Comment by karsa-mistmere** [comment]
There already is a [`delete`](https://lucide.dev/icon/delete) icon! :)

**Comment by ericfennis** [comment]
@BinaryKitten good idea!

**Comment by hornta** [comment]
Great, thanks :)

**Comment by BinaryKitten** [comment]
> @BinaryKitten good idea!

thanks for the kudos - not sure why i got it though.

good idea @hornta  :+1:
