### ISSUE TITLE
[Icon Request] Spline/Curve

### ISSUE THREAD

**Issue by SnoutBug** [lucide-icons/lucide#679]
## Icon Request

* Icon name: Spline/Bezier Curve
* Use case: When wanting to draw a spline or curve
* _Screenshots_ of similar icons: 
Blender: ![Blender](https://user-images.githubusercontent.com/71790678/169666501-b8d7fba7-5927-4374-adff-effd23c10090.png)
Libre Office: ![Libre Office](https://user-images.githubusercontent.com/71790678/169666486-1ff0ab50-d1eb-46f5-a9ce-447d8b4e1d89.png)
Inkscape:![inkscape](https://user-images.githubusercontent.com/71790678/169666713-a7924fa9-7dae-4905-a692-cbf25c963466.png)![inkscape](https://user-images.githubusercontent.com/71790678/169666743-f352c5cc-809a-4145-9cab-7f49603b5b0e.png)

`git-merge` looks similar

**Comment by karsa-mistmere** [comment]
How about?
![image](https://user-images.githubusercontent.com/17746067/169765423-ef608c12-1883-46ff-9398-77f1ca51dd8c.png)
![image](https://user-images.githubusercontent.com/17746067/169765439-1a708032-58d0-451b-88a3-81077a4462a2.png)

**Comment by SnoutBug** [comment]
I don't know how to describe this, but it looks a tad too spacious to me
maybe something more like this?
![image](https://user-images.githubusercontent.com/71790678/169830249-d40fa58d-d41d-488c-b095-d6087e41e327.png)
![image](https://user-images.githubusercontent.com/71790678/169827635-5378c008-d4ef-41e5-9480-d4d2f92da83a.png)
![image](https://user-images.githubusercontent.com/71790678/169830094-99d9d77d-da69-4fb0-8b5b-b8f122a9352a.png)
![image](https://user-images.githubusercontent.com/71790678/169828978-75cf7744-9704-4e09-995f-01cdd325b130.png)
![image](https://user-images.githubusercontent.com/71790678/169829913-111de944-f724-4de8-8310-22e88b8eceb1.png)
![image](https://user-images.githubusercontent.com/71790678/169829652-caeb670f-68e6-4fe3-8465-b0985e135061.png)

**Comment by karsa-mistmere** [comment]
Dunno, they look pretty funky on 100% because of they're off grid.
How about?
![image](https://user-images.githubusercontent.com/17746067/169834066-9a766c7f-a98a-4286-a148-bf440d3d6230.png)
![spline](https://user-images.githubusercontent.com/17746067/169834131-028940be-9de9-4d76-9f8c-5f6da22c2b55.png)

**Comment by SnoutBug** [comment]
That looks nice!

My last try without the .5px funkiness
![image](https://user-images.githubusercontent.com/71790678/169838165-36731e0c-d908-4232-a4cd-c4d3cbf8b52d.png)
![image](https://user-images.githubusercontent.com/71790678/169839297-0568e5bc-dc8b-42ea-ba74-c88d5ac55a7a.png)
