### ISSUE TITLE
Siren icon

### ISSUE THREAD

**Issue by safazi** [lucide-icons/lucide#686]
## Icon Request

* Icon name: siren
* Use case: Trigger alarm, serious alert, etc
* _Screenshots_ of similar icons: 
![image](https://user-images.githubusercontent.com/16279574/170836896-6efbceb1-9486-47c8-980c-9dc808e4918e.png)
![image](https://user-images.githubusercontent.com/16279574/170836913-ff184163-7058-4fda-a044-1f93986af969.png)
![image](https://user-images.githubusercontent.com/16279574/170836960-afa20e64-7ae2-400c-a91d-4dfb1d980292.png)

**Comment by karsa-mistmere** [comment]
I designed this a few weeks ago, let me know what you think:
![5B6099CA-CE80-4BAD-935C-7E9355985215](https://user-images.githubusercontent.com/17746067/170838069-1ede252c-1274-4d1d-830a-8bce782f7aca.jpeg)

**Comment by safazi** [comment]
The light dashes are perfect, but the body feels too round compared to other icons.
Maybe more in this direction? (excuse poor craftsmanship)
![image](https://user-images.githubusercontent.com/16279574/170849492-0954efb2-f70b-4f5a-87df-00358f0d0980.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice icon!

**Comment by karsa-mistmere** [comment]
Thanks, @ericfennis.
Here are a few variations, @safazi.
![image](https://user-images.githubusercontent.com/17746067/170931813-eeead0b2-f231-48a0-9ecc-4db462aa3ae7.png)
![image](https://user-images.githubusercontent.com/17746067/170931983-baefb267-05e2-4bd4-a821-91e69c31bdbf.png)

**Comment by safazi** [comment]
Icons 2 and 4 are the winners in my book - I would have never though of flattening the bottom like that.
Great stuff!

**Comment by karsa-mistmere** [comment]
@safazi: Thanks! I also think 2 and 4 are the most legible and I'd probably stick with 2, since I think it matches the Lucide style somewhat better. I'll make a PR soon.
