### ISSUE TITLE
Update CONTRIBUTING file with rule for one PR for each icon or icon series.

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#70]
Regarding to the thread in #57 @llaenowyd said this:

> I think after re-reading the submission guidelines , maybe there should be one PR for each icon.

I certain way I think this is a good idea to write this down in CONTRIBUTING file.
For me it's a little-bit of an unwritten rule that you need to submit icons or "icon series" in separate pull-requests for several reasons:

- It's easier to review
- Keeps the discussions and reviews about the icon(s) scoped and in one thread.
- All points above contribute to less time to merge PR's

I'm curious what you think.

**Comment by llaenowyd** [comment]
I like the "icon series" aspect, kind of a middle ground that would make it easier to get consistency, esp when there's a common use case they could be likely to show up next to each other on screen in an app.
