### ISSUE TITLE
Sustainabilty icons

### ISSUE THREAD

**Issue by pcout** [lucide-icons/lucide#701]
Can you please add sustainability related icons ?
Things like carbon footprint, energy saving, water saving, biomass, grey waters, waste, plants, ecology, environment related motives, solar panels, wind turbines, etc.

Thanks.

**Comment by pcout** [comment]
on a quick google search:

![image](https://user-images.githubusercontent.com/687515/171662581-27484663-e54d-4778-bd06-d6a423e3b769.png)
![image](https://user-images.githubusercontent.com/687515/171662652-3955f78b-6506-44c9-8c42-65b76ae1edc6.png)

**Comment by karsa-mistmere** [comment]
@pcout: Could you please provide a complete checklist of icons you need similar to what you can find in #683?

**Comment by ericfennis** [comment]
@pcout I think some of these icons are a bit too specific for this icon pack.
But we already have : [`sprout`](https://lucide.dev/icon/sprout).
The icons that are interesting to add are I think:

- `recycle` (recycling in general, pretty common used icon)
- `leaf` (also used for vegetarian food or things about nature)
- `flower` (used for gardens, botatic gardens, gardening, parks)

> Please next time use our [Icon Request Template](https://github.com/lucide-icons/lucide/issues/new&labels=%F0%9F%99%8C+icon+request&template=icon_request.md) for new issues for icons.
