### ISSUE TITLE
tally and counter icons

### ISSUE THREAD

**Issue by JordanGistLens** [lucide-icons/lucide#752]
## Icon Request

* Icon name: tally / counter
* Use case: a way to describe a total or a count of something, a tally or counter icon would make sense to display that something is be summed up or calculated.
* _Screenshots_ of similar icons:

![image](https://user-images.githubusercontent.com/78777027/178449163-2dc80525-b7af-45ff-84c6-a0375f0e1552.png)

![image](https://user-images.githubusercontent.com/78777027/178449466-0443c39b-c183-4aba-a49d-038c05b202f8.png)

**Comment by karsa-mistmere** [comment]
Tally marks are easy, but I'm not quite sure if we should keep them horizontally aligned or not.
I don't really think a counter icon like the one above is feasible within the bounds of Lucide's design guidelines, these are the best ones I could come up with right now, but I'm not really happy with the results.
![image](https://user-images.githubusercontent.com/17746067/178465702-aa4222a3-18ec-41b6-915d-ac262824bb6d.png)
![image](https://user-images.githubusercontent.com/17746067/178465641-0c1ae516-7305-4ac9-aaa3-4571c245f6a9.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Can you provide the last 4 icons in 100% scale?

**Comment by karsa-mistmere** [comment]
![counter](https://user-images.githubusercontent.com/17746067/180149758-20e5a2c5-9b56-4847-8866-5142ec39ec1d.png)

**Comment by tryoxiss** [comment]
Visually: I think the centered tally marks work far better, but mechanically to how tally's work I think left-aligned is more accurate. 

Since icons are, well, inherntly visual, I would say the centered icons are preferable but thats just my two cents on the matter.
