### ISSUE TITLE
Icon request: `laptop`

### ISSUE THREAD

**Issue by delnyn** [lucide-icons/lucide#77]
## Icon Request

* Icon name: laptop
* Use case: for laptop computers
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/45879791/93717282-1a58e400-fb75-11ea-9eb1-92472801373b.png)
  
*I created the icon on my own, I can send the SVG file*

**Comment by ericfennis** [comment]
@delnyn Welcome to featherity!
Nice request, we will look in to it!

**Comment by locness3** [comment]
Nice to see you here @delnyn ! Please do send the svg :)

**Comment by delnyn** [comment]
Thanks!  
Sadly GitHub doesn't support svg file...
So I just put it in a my website's [repo](https://delnyn.github.io/laptop.svg) so you can download it.

**Comment by ericfennis** [comment]
What do think of this?
![image](https://user-images.githubusercontent.com/11825403/93816713-2d90b000-fc58-11ea-9354-475364096a4d.png)

100% 
![image](https://user-images.githubusercontent.com/11825403/93816733-35e8eb00-fc58-11ea-874b-ca918dd82684.png)

**Comment by delnyn** [comment]
The tablet and the laptop are new?

**Comment by ericfennis** [comment]
i totally agree to explore more things and decide which one fits the best, but following the guidelines is necessary to match it with the other icons. So please follow them.
Also I recommend you to try your icon design next to the existing device icons, like I post here above.

Feel free to post your progress in our [discord channel](https://discord.gg/EH6nSts) to get more direct feedback from the community.

**Comment by delnyn** [comment]
@ericfennis Thank you very much!

**Comment by delnyn** [comment]
I had this idea but I'm not sure about it
![image](https://user-images.githubusercontent.com/45879791/94962484-d5c73400-04f6-11eb-93b4-dc328feffdd3.png)

**Comment by locness3** [comment]
It looks more in line with Feather if distinct elements have some spacing between them

**Comment by delnyn** [comment]
@locness3 Well, those are not supposed to be distinct elements (cf inbox and hard drive icons)

**Comment by delnyn** [comment]
What about this? 
![image](https://user-images.githubusercontent.com/45879791/94993761-83882080-0593-11eb-9b30-85d5ac666aac.png)

**Comment by ericfennis** [comment]
Nice work. I like this one better, can you post an image next to the other device?Like I posted before. So we can check if it match with the devices 😀

**Comment by delnyn** [comment]
![image](https://user-images.githubusercontent.com/45879791/95000562-4edf8d80-05c2-11eb-8aba-46b838898b99.png)

**Comment by ericfennis** [comment]
Nice work! I think the screen height can a bit higher 🤔

**Comment by delnyn** [comment]
1px higher  
![image](https://user-images.githubusercontent.com/45879791/95363293-91a9aa00-08cf-11eb-890e-7b87c72a06b6.png)

**Comment by ericfennis** [comment]
Nice I think this looks better!
Can you make a pull-request?

_If you're not familiar with that progress, just say we can help you!_

**Comment by locness3** [comment]
You mean "process"?

**Comment by delnyn** [comment]
#88
