### ISSUE TITLE
Unicorn icon request

### ISSUE THREAD

**Issue by jahirfiquitiva** [lucide-icons/lucide#772]
## Icon Request

* Icon name: Unicorn
* Use case: sites like [unicorn-utterances.com](https://unicorn-utterances.com)
* _Screenshots_ of similar icons:

<img width="644" alt="Shot 2022-07-20 at 00 08 14@2x" src="https://user-images.githubusercontent.com/10360816/179901446-0d0ab3b8-612f-4e4d-9824-9d28c09bc6bf.png">

**Comment by karsa-mistmere** [comment]
Frankly, this seems like a brand icon request in disguise. :)
Can you provide alternate use cases that aren't brand related?

**Comment by bleonard252** [comment]
> Can you provide alternate use cases that aren't brand related?
Dev.to's "unicorn" reaction comes to mind.
