### ISSUE TITLE
Ship Icon

### ISSUE THREAD

**Issue by mayurrawte** [lucide-icons/lucide#778]
## Icon Request

* Icon name: Ship
* Use case: Usecase in logistics-related apps 

Screenshots
<img width="228" alt="Screenshot 2022-08-02 at 10 26 30 AM" src="https://user-images.githubusercontent.com/32830023/182294918-09eeca6a-250f-45d0-bf1f-1228fdafdd43.png">

**Comment by jguddas** [comment]
![image](https://user-images.githubusercontent.com/25524993/214315876-c1cad579-421d-4984-b6b7-80faccf89a64.png)

**Comment by ericfennis** [comment]
@jguddas That looks really nice!
Feel free to open a PR.
