### ISSUE TITLE
Airplane Mode Icon

### ISSUE THREAD

**Issue by mayurrawte** [lucide-icons/lucide#779]
## Icon Request

* Icon name: Airplane
* Use case: Airplane Mode Icon for mobile

<img width="238" alt="Screenshot 2022-08-02 at 10 25 33 AM" src="https://user-images.githubusercontent.com/32830023/182295142-0d5a91dc-58fe-4640-a9f0-d8ac44381229.png">

**Comment by karsa-mistmere** [comment]
@mayurrawte: We actually already have an airplane icon: https://lucide.dev/icon/plane?search=plane

It was under the name "plane" and missing the tag airplane, so thanks for bringing that to our attention, I've added the tag so that people will find it easier in the future. :)
