### ISSUE TITLE
Building icon

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#78]
## Icon Request

* Icon name:
building
* Use case:
For organisations

**Comment by delnyn** [comment]
I just made that  
![image](https://user-images.githubusercontent.com/45879791/95368621-a473ad00-08d6-11eb-9dfc-77238646b56d.png)

**Comment by locness3** [comment]
Not sure that's what was meant 😅

**Comment by locness3** [comment]
![image](https://user-images.githubusercontent.com/37651007/95369462-c02b8300-08d7-11eb-8db1-95765cbff7a5.png)
I think this is is what's being requested (from octicons)

**Comment by delnyn** [comment]
oh

**Comment by delnyn** [comment]
4 different icons  
![image](https://user-images.githubusercontent.com/45879791/95420565-f6025300-093b-11eb-9837-55e2b0652a94.png)

**Comment by ericfennis** [comment]
🤩 nice, love your work! 
I think it should match with the home icon. 
So number two or number 3 I think.
![image](https://user-images.githubusercontent.com/11825403/95430224-c0fdfc80-094b-11eb-9ef2-b83a1756d8e9.png)

**Comment by locness3** [comment]
I like number 3

**Comment by delnyn** [comment]
remade them from the `home` icon
![image](https://user-images.githubusercontent.com/45879791/95495716-16fc8f80-09a0-11eb-950e-4f91eeb49ea0.png)

**Comment by locness3** [comment]
they're thicc

**Comment by ericfennis** [comment]
Nice, good work @delnyn 🔥
I love this version, I like the left one.

Can you try shrinking it 1 px. So the dots have the same padding of 2px as the top?

**Comment by delnyn** [comment]
Like this?  
![image](https://user-images.githubusercontent.com/45879791/95498341-f5050c00-09a3-11eb-9eae-0eaf01341846.png)

**Comment by ericfennis** [comment]
yesh!!, I like it!

**Comment by delnyn** [comment]
Great! Do I PR?

**Comment by johnletey** [comment]
@delnyn Go for it!
