### ISSUE TITLE
Tower-control Icon

### ISSUE THREAD

**Issue by jis3r** [lucide-icons/lucide#784]
## Icon Request

* Icon name: tower-control
* Use case: Airport and travel related websites/tools
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/72663107/183767569-b1671640-e353-44c7-8b46-40e1ef43b975.png)
![image](https://user-images.githubusercontent.com/72663107/183767645-985aca5f-c152-4c74-9947-844271c36359.png)

**Comment by jis3r** [comment]
I drafted three variants of the icon, happy to recieve improvement suggestions :)

![image](https://user-images.githubusercontent.com/72663107/183767980-30642013-0c32-426b-89b9-0782a8832a89.png)

**Comment by karsa-mistmere** [comment]
The top looks far too dense in each iteration (there should be a 2px gap between all distinct elements), I think we'll have to stick with a single vertical line in the middle like in the first similar icon, maybe something like this:
![image](https://user-images.githubusercontent.com/17746067/183831602-47bd4508-5eee-4eca-86c4-492adb43020f.png)
![image](https://user-images.githubusercontent.com/17746067/183832462-6aeb9d5b-e352-410a-a41e-e5b378717e2c.png)

(The bottom rounding is also something that we probably shouldn't go with, as it makes it look too much like it's a detached piece of equipment, like some kind of steampunk-ish medieval torch).

**Comment by jis3r** [comment]
You'r totally right about density, I forgot about the 2px distance, sorry.😅

What do you think of this more "zoomed in" approach?
![image](https://user-images.githubusercontent.com/72663107/183848106-5422b401-051d-4691-960e-9dc5092100a2.png)
My personal favourite would be the right variant. I think one could omit the bottom of the tower and get more detailed at the top for better recognition.

**Comment by karsa-mistmere** [comment]
Not bad, although these parts do go against our guidelines I think:
![image](https://user-images.githubusercontent.com/17746067/183864568-0ad66a89-154c-469d-acd3-9fcf7be60514.png)

**Comment by jis3r** [comment]
Under what circumstances could one deviate from the rules? Because I personally think that it looks better with that extra element:
![image](https://user-images.githubusercontent.com/72663107/183872339-64bf41b9-e3c8-41ee-8ff2-6909124d2909.png)

**Comment by jis3r** [comment]
Any updates on this? :)

As I said, I think that it looks slightly better with the extra element on the left, but the right version would also fullfill all rules and does not go against the guidelines.

**Comment by ericfennis** [comment]
@jis3r Sorry for late reply.
Can you post a 100%(24x24px) scale comparison?
I think you probably won't see the little line. Or the average person won't see it.

**Comment by jis3r** [comment]
What do you mean by scale comparison? The images I posted should both be 24x24px.

**Comment by karsa-mistmere** [comment]
By 100% we mean an image where the icons actually take up a 24 by 24 pixel space, e.g.:
![tower control](https://user-images.githubusercontent.com/17746067/201060095-8fd4abf4-d665-4d73-b442-fcd59ccbc9d0.png)

The third one is an alternate suggestion (the line at the bottom suggests that the tower ends there making it look comically short and the overall weight of the icon is maybe a bit too small).

**Comment by ericfennis** [comment]
I think the third option looks more like a tower
