### ISSUE TITLE
Icon for plain language - book-open-check

### ISSUE THREAD

**Issue by schmidt-oliver** [lucide-icons/lucide#789]
## Icon Request

Icon name: `book-open-check`

Use case: 
- Plain language
- Finished reading a book

In Germany, websites of public institutions must have a page with plain language. Currently there is no suitable icon for this use case. Because of the naming conventions, I would give it the name `book-open-check`.

This is my suggestion:
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M2 3h6c2.2 0 4 1.8 4 4v14c0-1.7-1.3-3-3-3H2V3z"></path>
    <path d="m16 12 2 2 4-4"></path>
    <path d="M18 18h-3c-1.7 0-3 1.3-3 3v-9m10-6h0V3h-6c-2.2 0-4 1.8-4 4v5m6 6h4v-2.3"></path>
</svg>
```

![book-open-check](https://user-images.githubusercontent.com/33413922/186127680-e3a763a6-ef5d-4f87-a70b-6531d6ba1d73.svg)
![preview](https://user-images.githubusercontent.com/33413922/186129062-3493541e-6cc4-48a2-b800-ddebe3c679c2.png)

**Comment by ericfennis** [comment]
@schmidt-oliver Nice icon!
If you want you can open a pull request.
