### ISSUE TITLE
Files/Documents

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#79]
Similar: [#579](https://github.com/feathericons/feather/pull/579) 

## Icon Request

* Icon name:
files
* Use case:
For multiple files/documents

**Comment by delnyn** [comment]
![files](https://user-images.githubusercontent.com/45879791/96405855-7481af00-11de-11eb-961e-f5b3e459075f.png)

**Comment by locness3** [comment]
This more feels like Copy to me

**Comment by ericfennis** [comment]
I agree, I think that's because the line is at the bottom.
I like the approach, maybe it work better if we turn it around. First the file and then line in the background (top-right), so it looks more like a pile of papers.

**Comment by delnyn** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/45879791/96426092-11534500-11fd-11eb-8b40-2cb0a967da07.png)
100% 
![files(1)](https://user-images.githubusercontent.com/45879791/96426113-187a5300-11fd-11eb-80eb-48dfb78a960a.png)

**Comment by ericfennis** [comment]
hmm, not sure about this either 🤔 
Maybe the first is better, vscode uses that one as well.

**Comment by ericfennis** [comment]
This was the one I mentioned in the PR.
https://github.com/feathericons/feather/pull/579/commits/ea52c0d07e1ac0e5d65473cc843d53bcaa9a8784?short_path=a5783ec#diff-a5783ecdd13105936d5ddfa29892c48be4b0f88910052c5e6126c2fbd3320ed8

**Comment by delnyn** [comment]
*what the hell have I done*
![image](https://user-images.githubusercontent.com/45879791/96776775-c4809180-13e9-11eb-9667-30b3b9041857.png)

**Comment by ericfennis** [comment]
hmm, oke I after looking at the other options I think your first one is maybe the best choice, I can't think of better options. I agree I maybe looks a bit like 'copy files' as wel, but maybe we can embrace that with a tag: "copy files". So people can use it for both 🤷‍♂️?

**Comment by delnyn** [comment]
uhm well... You opened the issue so if you're satisfied just take it.
