### ISSUE TITLE
`ear`, `ear-off` Icon

### ISSUE THREAD

**Issue by schmidt-oliver** [lucide-icons/lucide#791]
Searched for an icon for sign language but didn't find a suitable for this use case. Tried designing an icon with two hands like `hands`, `hands-asl-interpreting` in [font awesome](https://fontawesome.com/icons/categories/accessibility)  or other icon sets, but can't get it. So I decided to do design `ear-off` as alternative and `ear` for completeness.

## Icon Request

Icon name: `ear`

Use case: 
- ?

_Screenshots_ of similar icons:

![image](https://user-images.githubusercontent.com/33413922/186408609-5c5c4897-53a4-4fc9-98fe-3de58f125a47.png)

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M12 6c-1.1 0-2 .9-2 2M14 8c0-1.1-.9-2-2-2M12 2C8.7 2 6 4.7 6 8M12 2c3.3 0 6 2.7 6 6M6 19c0 1.7 1.3 3 3 3M9 22c1.7 0 3-1.3 3-3M12 19c0-3.1 6-7.9 6-11"/>
</svg>
```

## Icon Request

Icon name: `ear-off`

Use case: 
- Information for people who can't hear, as an alternative icon for sign language

_Screenshots_ of similar icons:

![image](https://user-images.githubusercontent.com/33413922/186408778-97dbd878-860e-4caa-9352-662f7ecf738d.png)

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="m2 2 20 20M11.7 6h.3M14 8c0-1.1-.9-2-2-2M8.7 3c1-.6 2.1-1 3.3-1M12 2c3.3 0 6 2.7 6 6M9 22c-1.7 0-3-1.3-3-3M12 19c0 1.7-1.3 3-3 3M12.2 17.9c-.1.4-.2.7-.2 1.1M16.7 11.1C17.5 10 18 8.9 18 8M6.3 6.3C6.1 6.8 6 7.4 6 8M14.4 14.4c-.9 1.2-1.8 2.4-2.1 3.5"/>
</svg>
```

Any suggestions for improvement? By the way, I found an other icon set called [Tablar Icons](https://tabler-icons.io/) which is similar to Lucide. Sometimes it could be helpfull for designing.

**Comment by karsa-mistmere** [comment]
Nice one, it's be great to have an ear icon.

The line I've circled in red looks a bit wonky though, it could look a bit cleaner and continuous, maybe something like the second one (although I think we could easily fit in the tragus and make the icon more legible as illustrated in the 3rd and 4th icons):
![image](https://user-images.githubusercontent.com/17746067/186630283-ae3d80aa-e7eb-4991-be0f-03c24edca08d.png)
![image](https://user-images.githubusercontent.com/17746067/186630960-4bcb3b55-e18e-48f7-80f9-cfcc63f254fe.png)

Here's a Figma file:
https://www.figma.com/file/uPY3b73RiqFmUhKRIUA9lg/lucide%2Fear?node-id=0%3A1

**Comment by schmidt-oliver** [comment]
Thanks. Great advice. Have reworked it with a little improvement: I centered it horizontally.

Now it looks like:

![image](https://user-images.githubusercontent.com/33413922/186702336-e5552543-5a09-4d8d-aa89-1d0d611453a8.png)

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M12 6c-1.7 0-3 1.3-3 3M15 9c0-1.7-1.3-3-3-3M12 2C8.1 2 5 5.1 5 9M12 2c3.9 0 7 3.1 7 7M5 18c0 2.2 1.8 4 4 4M9 22c2.2 0 4-1.8 4-4M11 11.7c0-1-.9-1.7-2-1.7M9 13.5c1.1 0 2-.8 2-1.8M13 18c0-5 6-4 6-9M9 9v1"/>
</svg>
```

![image](https://user-images.githubusercontent.com/33413922/186702063-a2fb4026-e79c-4615-8323-d19da71f0ab2.png)

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="m2 2 20 20M11.7 6h.3M15 9c0-1.7-1.3-3-3-3M5 9c0-1.2.3-2.2.8-3.2M8.6 2.9c1-.6 2.1-.9 3.4-.9M12 2c3.9 0 7 3.1 7 7M9 22c-2.2 0-4-1.8-4-4M12.9 18.6C12.6 20.5 11 22 9 22M12.9 18.6c0-.2.1-.4.1-.6M11 11.7c0-1-.9-1.7-2-1.7M11 11.7c0 1-.9 1.8-2 1.8M14.6 14.6c-.9.7-1.6 1.7-1.6 3.4M17.8 12.1c.7-.7 1.2-1.7 1.2-3.1M9 9v1"/>
</svg>
```

**Comment by karsa-mistmere** [comment]
Not sure about the tragus, it seems a just bit too tight, but I think we need a second opinion from @ericfennis.

I've tried to align it by centre of gravity rather than bounding box, but I guess the truth would be somewhere inbetween, so how about bringing down the size a notch so that it's closer?

![image](https://user-images.githubusercontent.com/17746067/186705687-0875a1ec-17b8-45bc-8776-a029b3c75361.png)
![image](https://user-images.githubusercontent.com/17746067/186705719-435c44dd-59b4-42c3-a9b7-1408f35f87bb.png)

Here's a comparison:
1st row: your latest - slightly off to the left
3rd row:  this new one
5th row: my original - slightly off the the right

![image](https://user-images.githubusercontent.com/17746067/186707219-1a92a77e-3595-4be0-989c-ac5f8cce5319.png)

**Comment by schmidt-oliver** [comment]
> I've tried to align it by centre of gravity rather than bounding box, but I guess the truth would be somewhere in-between, so how about bringing down the size a notch so that it's closer to that?

Great idea. On direct comparison your new version looks cleaner and less clunky. Thank you for the review. I really like your improvements. By the way: I love how actively you work together with the community.

**Comment by ericfennis** [comment]
@schmidt-oliver Great icon request I think this is nice icon to add to the library.
And welcome to the community!

@karsa-mistmere I like the third column of icons. It has a simple and recognizable design.
