### ISSUE TITLE
Generic icon component with typescript

### ISSUE THREAD

**Issue by rizkimuhammada** [lucide-icons/lucide#794]
## Prerequisites

* Version: ^0.88.0
* Are you running from source/main: No
* Are you using a released build: No
* Operating system: macOS
* Bits: 64 bits

## Step to reproduce
I am using the example code from Lucide React to make a generic icon component.
<pre>
<code>
import * as icons from 'lucide-react';

const Icon = ({name, color, size}) => {
  const LucideIcon = icons[name];

  return <LucideIcon color={color} size={size} />
};

export default Icon;
</code>
</pre>

It's working very well. But now, we are trying to use typescript and React `createElement` to return the element.
<pre>
<code>
import React, { createElement } from "react";
import * as lucideIcons from "lucide-react";
import PropTypes from "prop-types";

interface LucideProps {
  icon: keyof typeof lucideIcons;
  className: string;
}

function Lucide(props: LucideProps) {
  try {
    const { icon, className, ...computedProps } = props;
    if (lucideIcons[props.icon] !== undefined) {
/*
* No overload matches this call.
*   The last overload gave the following error.
*     Argument of type '((iconName: string, iconNode: any[]) => (props: LucideProps) => Element) | ((props: LucideProps) => Element) | ((props: LucideProps) => Element) | ... 828 more ... | ((props: LucideProps) => Element)' is not assignable to parameter * of type 'string | FunctionComponent<string> | ComponentClass<string, any>'.
*       Type '(iconName: string, iconNode: any[]) => (props: LucideProps) => Element' is not assignable to type 'string | FunctionComponent<string> | ComponentClass<string, any>'.
*         Type '(iconName: string, iconNode: any[]) => (props: LucideProps) => Element' is not assignable to type 'FunctionComponent<string>'.
*           Type '(props: LucideProps) => Element' is not assignable to type 'ReactElement<any, any>'.ts(2769)
*/
      return createElement(lucideIcons[props.icon], {
        ...computedProps,
        className: `lucide ${props.className}`,
      });
    } else {
      throw props.icon;
    }
  } catch (err) {
    throw `Lucide icon '${props.icon}' not found.`;
  }
}

Lucide.propTypes = {
  icon: PropTypes.string,
  className: PropTypes.string,
};

Lucide.defaultProps = {
  icon: "",
  className: "",
};

export default Lucide;
</code>
</pre>

Is there a way to use Lucide React with `createElement` and typescript?

**Comment by johndmguerrero** [comment]
Hello looking for solution for this one also
