### ISSUE TITLE
[Icon Request] Dumbbell Icon - Possible to get?

### ISSUE THREAD

**Issue by karwan-ali** [lucide-icons/lucide#802]
## Icon Request

* Icon name: dumbbell
* Use case: Workout page with a workout library. Icon is needed for this use case.
* _Screenshots_ of similar icons:
<img width="67" alt="Screenshot 2022-09-25 at 00 42 59" src="https://user-images.githubusercontent.com/38838635/192121145-61ac5733-ae22-4d1c-8f5c-052ad1ce0132.png">
<img width="492" alt="Screenshot 2022-09-25 at 00 45 02" src="https://user-images.githubusercontent.com/38838635/192121168-fc049a0b-23f0-46e2-b4e7-862dee1ca27f.png">

**Comment by karsa-mistmere** [comment]
I've tried, but I couldn't really get this to work with our design guidelines.
A horizontal version proved to be simply too tight, even a diagonal version has very little space to fit in more than one weight per side, and at one weight per side, it doesn't quite look like a dumbbell anymore.

Here are a few versions:
![image](https://user-images.githubusercontent.com/17746067/193552968-aa579be3-8e99-436c-a3f5-328fd635d4c1.png)
![dumbbell](https://user-images.githubusercontent.com/17746067/193553013-a73b32ce-42c5-470c-a3af-714e9423d85c.png)

**Comment by karwan-ali** [comment]
I think you've made a very good job considering the guidelines 😊

The third one seems like a good option. What do you think about it?
Is there a possibility to try to add a "hollow weight" in between the spaces on that dumbbell to see how it looks like?

**Comment by ericfennis** [comment]
@karwan-ali @karsa-mistmere Like the third one!
