### ISSUE TITLE
Sort ascending for smaller screens

### ISSUE THREAD

**Issue by lukesmurray** [lucide-icons/lucide#805]
## Icon Request

On smaller screens, the difference between the bars in `sort-asc` and `sort-desc` are hard if not impossible to see.
I propose an alternative `sort-asc` which changes the direction of the arrow and the location of the bars.

* Icon name: `sort-asc`
* Use case: Smaller screens where the lines stack is hard to see.

## Proposed Icon

SVG Preview:

![ASC NEW](https://user-images.githubusercontent.com/34020210/193612379-24313cde-2283-4be2-9461-262f0059a279.svg)

PNG Preview:

![ASC NEW](https://user-images.githubusercontent.com/34020210/193612662-b1fd0b42-0fea-4453-8876-214d9b528b4c.png)

Source: 
```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11 11H15" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11 15H18" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11 19H21" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M9 7L6 4L3 7" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M6 6L6 20" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

## Current Icons

These are almost impossible to differentiate

![sort-desc](https://user-images.githubusercontent.com/34020210/193612961-ef68fd40-9d13-4509-bd15-8e20ad886897.svg) ![sort-asc](https://user-images.githubusercontent.com/34020210/193612971-e207c530-8918-4846-a006-feecc0d4f3c4.svg)

## New Icons

These are much easier to differentiate 

![sort-desc](https://user-images.githubusercontent.com/34020210/193612961-ef68fd40-9d13-4509-bd15-8e20ad886897.svg) ![ASC NEW](https://user-images.githubusercontent.com/34020210/193612379-24313cde-2283-4be2-9461-262f0059a279.svg)

**Comment by ericfennis** [comment]
Hmm I agree on this.
What do you think @karsa-mistmere ?

**Comment by lukesmurray** [comment]
If anyone gives me the go ahead I can submit a PR.

**Comment by ericfennis** [comment]
@lukesmurray Yeah go ahead!

**Comment by lukesmurray** [comment]
Added a PR in #819
