### ISSUE TITLE
[Icon Request] Indian Rupee

### ISSUE THREAD

**Issue by solaremperor** [lucide-icons/lucide#813]
## Icon Request

* Icon name: Indian Rupee
* Use case: Currency
* _Screenshot_ of similar icons from ([Wikipedia/Indian Rupee Sign](https://en.wikipedia.org/wiki/Indian_rupee_sign)):
![Indian Rupee Sign](https://upload.wikimedia.org/wikipedia/commons/e/ee/Indian_Rupee_symbol.svg)

**Comment by ericfennis** [comment]
@solaremperor We already have this icon 😉
https://lucide.dev/icon/indian-rupee
