### ISSUE TITLE
Download icon when click on GitHub button

### ISSUE THREAD

**Issue by heyfirst** [lucide-icons/lucide#814]
Hey Great works! by the way, I love all icons you made!

I have one curious thing about https://lucide.dev/. So when I click GitHub button it seems download the `lucid.zip` automatically.

It also seems the code in this line was added `onClick={downloadAllIcons}` as well. Should this be considered a bug, or is it intended to do so?

https://github.com/lucide-icons/lucide/blob/aa524c65a059ae802752c84f860b17cc3fa30977/site/src/components/Header.tsx#L179-L188

if this an unintentional code, It's just one line of code, either you can easily remove it or I can open the PR

## Step to reproduce
1. https://lucide.dev/
2. Click on GitHub button
3. Accidentally download `lucid.zip` and go to https://github.com/lucide-icons/

### Actual behavior

1. https://lucide.dev/
2. Click on GitHub button
3. Go to https://github.com/lucide-icons/

## Any message or error

No console output
...

## Resources

No resources
...

**Comment by ericfennis** [comment]
Hmm I think it is a bug, thank for reporting!
