### ISSUE TITLE
[Icon Request] Separate togglable icons

### ISSUE THREAD

**Issue by shawarmaz** [lucide-icons/lucide#815]
## Icon Request

* Icon name: filled(`heart`, `thumbs-up`, `star`,  maybe others)
* Use case: To toggle them on/off on platforms that don't easily allow svg filling. 

Type any of the icon names into [this popular icon lib index](https://oblador.github.io/react-native-vector-icons/) 

There are a ton of other icons that would be awesome to get filled and are easily fillable without redesign (e.g. `check-circle-2`, clocks, compass, alerts, arrow-circles, etc)... But I do get that it still is work, so I'll just leave the idea out there and take this opportunity to thank you guys for your ongoing contributions to this project

**Comment by jguddas** [comment]
Duplicate newer issue https://github.com/lucide-icons/lucide/issues/893

**Comment by ericfennis** [comment]
This one was created first but there is some more discussion going on in #893. I close this because of duplication.
