### ISSUE TITLE
Add better tags

### ISSUE THREAD

**Issue by ANTARCTUS** [lucide-icons/lucide#822]
Some tags are redundant, while others are missing.
We could add the tag "logo" to "chrome" and "trello".
Add the tag "math" to the different operators and to the "sigma".
Add the tag "shape" to the triangle, the square...
Combine the tags "social" and "social media". While adding this tag to "YouTube" and "twich".

If you want, I can push [my fork which contains these additions.](https://github.com/ANTARCTUS/lucide)

**Comment by ericfennis** [comment]
@ANTARCTUS welcome to lucide community.

Thanks for noticing this. Yes we have probably a lot of tags that can be improved. This will help the search of icons on the website.

Feel free to open a PR.

**Comment by ANTARCTUS** [comment]
I do it with this PR : #827

**Comment by ANTARCTUS** [comment]
And the PR is merged !
I will do another PR with others upgrades in this week.
