### ISSUE TITLE
Update to person-standing and person-walking

### ISSUE THREAD

**Issue by kemie** [lucide-icons/lucide#829]
Not really an icon request, but a proposal for an update:
I think person-standing and person-walking  #609 could use a redesign to make them more dimensional, less slim, and match user/person icons better
new icons proposal:
<img width="940" alt="illustrator_template ai2 @ 2969 99  (RGBPreview)   2022-10-20 at 091929@2x" src="https://user-images.githubusercontent.com/1877967/196882221-69c9ca04-8c49-4efb-b0e2-6f40c4434f5f.png">
here are the old ones: 
![image](https://user-images.githubusercontent.com/1877967/196881548-f60cf153-6d79-490d-ad0d-0f75402a6a63.png)

**Comment by ericfennis** [comment]
@kemie Can you post this in #609. This way we keep everything in one thread.
