### ISSUE TITLE
Icon request: file-code

### ISSUE THREAD

**Issue by jerelmiller** [lucide-icons/lucide#83]
## Icon Request

* Icon name: file-code
* Use case: source code files
* Screenshots of similar icons:

<img width="123" alt="Screen Shot 2020-10-05 at 8 59 27 PM" src="https://user-images.githubusercontent.com/565661/95157372-acecac00-074d-11eb-83b3-a87bb9feffb1.png">

(source: https://fontawesome.com/icons?d=gallery&q=file-code)

Hey there 👋 

I'm working on the team in the process of migrating a website from one tech stack to another. In the process, we are migrating from font-awesome to feather icons. I see a lot of `file` type icons, but would also love one that looks similar to the screenshot above.

I'd PR this myself, but as an engineer and non-designer, I can't say I know the toolset well enough to know where to begin 😅 . Thanks for the help ahead of time!

**Comment by ericfennis** [comment]
@jerelmiller Welcome to Lucide (before: featherity)!

Nice first issue, I think we can make this one and add it 😊.

**Comment by johnletey** [comment]
Here are the icons from [Octicons](https://primer.style/octicons) @ericfennis, that I personally think look really nice!

<img width="183" alt="Screenshot 2020-10-06 at 20 42 27" src="https://user-images.githubusercontent.com/62398724/95252123-7463d580-0814-11eb-820a-8662612453cb.png"> <img width="182" alt="Screenshot 2020-10-06 at 20 42 50" src="https://user-images.githubusercontent.com/62398724/95252160-80e82e00-0814-11eb-82ae-0888276004bd.png">

**Comment by ericfennis** [comment]
@johnletey Nice suggestions!

**Comment by ericfennis** [comment]
![image](https://user-images.githubusercontent.com/11825403/95261774-42aa3900-082b-11eb-9bba-5402ffb03b43.png)
