### ISSUE TITLE
`svelte2tsx` peer dep is out of date

### ISSUE THREAD

**Issue by FractalHQ** [lucide-icons/lucide#831]
It would be great if `svelte2tsx` had a major version bump!

## Prerequisites

* Version: `v0.92.0`
* Running from: Installed with `pnpm` into a `vite` project.
* Operating system: MacOS

## Step to reproduce

Install `lucide-svelte` and `svelte2tsx`

## Any message or error

`unmet peer svelte2tsx@^0.4.12: found 0.5.20`

## Resources

This error appears everytime I install or run a project with `pnpm` and `lucide-svelte`

![Screenshot 2022-10-20 at 10 31 16 AM](https://user-images.githubusercontent.com/55504972/196978346-b3308dc5-d123-41a5-b9de-35bff28187c9.png)

**Comment by ericfennis** [comment]
Tnx, I wil give a bump!

**Comment by ericfennis** [comment]
Created a fix in #877. Beta release is released under `lucide-svelte@0.104.0-beta.6`

**Comment by ericfennis** [comment]
fixed in #877
