### ISSUE TITLE
[Icon request] Vegan, gluten free, sugar free, alcohol free

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#859]
## Icon Request

* Icon name: Vegan
* Use case:
* _Screenshots_ of similar icons:
<img src="https://user-images.githubusercontent.com/5426427/198110690-c45562e9-22ee-4217-8418-eb75b0093bf7.png" width="128" />

* Icon name: Gluten free
* Use case:
* _Screenshots_ of similar icons:
<img src="https://user-images.githubusercontent.com/5426427/198110867-fb6f82db-844c-4947-ba79-2e16a9506c53.png" width="128" />

* Icon name: Sugar free
* Use case:
* _Screenshots_ of similar icons:
<img src="https://user-images.githubusercontent.com/5426427/198110597-83f211a5-63fe-4fe8-affc-e7c86d1b964f.png" width="128" />

* Icon name: Alcohol free
* Use case:
* _Screenshots_ of similar icons:
<img src="https://user-images.githubusercontent.com/5426427/198111026-65412c5a-e75c-4b98-8488-359c265c77d7.png" width="128" />

**Comment by karsa-mistmere** [comment]
What about these? I've been so bold as to add some more common food intolerances:
![image](https://user-images.githubusercontent.com/17746067/198236638-36523d80-642a-4a5d-9f0d-e64477b01be1.png)
![food-intolerance](https://user-images.githubusercontent.com/17746067/198236795-9145471e-4cc3-43e0-8cca-0ee271c5dca4.png)

I don't think adding a circle-slash around the icons is quite feasible, there's just too much detail to fit into a 12px diameter circle (that would be our working area, lol), but people could always draw the circle-slash literally around the icons instead, e.g.:
![image](https://user-images.githubusercontent.com/17746067/198238670-c135523e-84bd-4bf1-8480-3dbcaf82b139.png)
![image](https://user-images.githubusercontent.com/17746067/198238693-5a075fdc-632f-402b-93a1-18a6187a3c53.png)


Here are my drafts:
https://www.figma.com/file/VAfwPOga8PdE60ve2sDepx/lucide%2Ffood-intolerance?node-id=0%3A1

**Comment by karsa-mistmere** [comment]
Maybe for GMO free a DNA icon like this would be better:
![image](https://user-images.githubusercontent.com/17746067/198255550-c5feb89e-0555-4f4c-ba37-9dc210110815.png)

**Comment by karsa-mistmere** [comment]
Also, I think instead of adding a dedicated `vegan` icon maybe either sprout or leaf could be used in this context?

**Comment by wojtekmaj** [comment]
The vegan V is pretty distinctive and widely recognized, I'd go for it
