### ISSUE TITLE
Lucide Angular does not work with Angular 13 and 14

### ISSUE THREAD

**Issue by danielradstrom** [lucide-icons/lucide#865]
* Version:0.93.0
* Are you running from source/main:
* Are you using a released build: Yes
* Operating system: Mac OS
* Bits:

### Actual behavior
Lucide Angular does not work with Angular 13 and 14. I tried to import but angular does not see the library.
I have the library installed in my project.

* Links
* Screenshots
* 
<img width="1057" alt="Screenshot 2022-11-01 at 10 58 26" src="https://user-images.githubusercontent.com/107171455/199208767-a7b6fc08-d636-4b2e-b775-f9282e78b6bb.png">

**Comment by ericfennis** [comment]
@danielradstrom Can you check if this is fixed. @ekowbaah made some fixes.

**Comment by ekowbaah** [comment]
@ericfennis I did make the fixes, but the angular build we had was not working and that has been fixed in the last pr but it has not been released yet.
@danielradstrom this should work in the next release.

**Comment by ericfennis** [comment]
We released a new version. https://www.npmjs.com/package/lucide-angular

**Comment by danielradstrom** [comment]
Awesome! works now! Thanks @ekowbaah @ericfennis
