### ISSUE TITLE
Using React Context to set default attributes for all child icons

### ISSUE THREAD

**Issue by ajmnz** [lucide-icons/lucide#879]
Hi 👋

Are there any plans for providing something like `LucideContext` where one can set default attributes for all child icons? Something similar to what [react-icons provides](https://github.com/react-icons/react-icons#configuration).

```tsx
import { LucideContext, AlertCircle } from "lucide-react";

export const Component: React.FC = () => {
  return (
    <LucideContext.Provider value={{ size: 16, stroke: "#000000" }}>
      <AlertCirlce />
    </LucideContext.Provider >
  );
}
```

Shouldn't be too difficult to implement, I could open a PR if you're interested 👍🏼 

Thanks!

**Comment by ericfennis** [comment]
I thought of this idea as well. But I think a context provider is maybe too much for what you want to accomplish.
Is it not way easier to override this with a global CSS rule?

```css
.lucide {
  width: 16px;
  height: 16px;
  stroke: '#000'
}
```

**Comment by ericfennis** [comment]
I recommend using CSS. Icons should not have a dependency on a context. 
Please give a really good answer to why we should create this dependency.
I close this one for now.
