### ISSUE TITLE
Stamp icon

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#883]
## Icon Request

* Icon name: Stamp
* Use case: Stamp tool in image editors; stamp in loyalty apps
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/5426427/201750507-85a84110-896e-4d5d-88c7-5c47bab66425.png)

**Comment by karsa-mistmere** [comment]
I guess something like this could work, but I'm not quite sure it's readily recognisable:
![image](https://user-images.githubusercontent.com/17746067/201752627-07820f20-93eb-4ff5-9163-9a40680cc7b0.png)
![image](https://user-images.githubusercontent.com/17746067/201752488-af7e3980-0a34-439e-99ba-c5d328caa21a.png)

**Comment by wojtekmaj** [comment]
Looks a bit like a baby pacifier to me 🙈 Perhaps less rounded edges, kinda like in Trophy icon, could do the trick?

**Comment by karsa-mistmere** [comment]
Maybe adding an extra line also helps?

![image](https://user-images.githubusercontent.com/17746067/201756872-07dd87d7-887f-4f17-b45f-cc2f06048250.png)
![image](https://user-images.githubusercontent.com/17746067/201756810-200f4806-0f8f-4dc0-bd04-bdbe08ed7851.png)

**Comment by wojtekmaj** [comment]
The roundiness is much better now IMO! As for the line... I don't know, maybe it helps a bit?

**Comment by ericfennis** [comment]
Maybe try one with just a line at the bottom @karsa-mistmere ?

**Comment by karsa-mistmere** [comment]
I've tried that already, IMO it looks pretty OK if I violate the 2px gap guideline and a bit funny if I don't:
![image](https://user-images.githubusercontent.com/17746067/201880245-e2604b76-b031-47a3-9a2d-4a4045acf1d5.png)
![stamp](https://user-images.githubusercontent.com/17746067/201880380-c74d105e-efbb-4864-8d0c-fd1214c1db4a.png)

Again, as with people icons, maybe the guidelines need to be adjusted. Maybe we could add a clause that states a 1px gap is acceptable in instances where it is necessary to add negative space but the separate elements would also work as a single path or without a gap. Some other icons would also benefit from such allowance I think e.g.:

![dna](https://user-images.githubusercontent.com/17746067/201881556-66a72795-3bc8-4874-a8c8-56aaee44870c.png)

**Comment by ericfennis** [comment]
I think the first one is not bad if you look at the 100% version. I'm only not sure about the line in the middle, I would say keep it as simple as possible.

**Comment by wojtekmaj** [comment]
I'd vote for the version with the line, but it's not like I'm anyone you should listen to regarding design stuff :)

**Comment by karsa-mistmere** [comment]
Yeah, something completely new that I think works better than all previous ones:
![image](https://user-images.githubusercontent.com/17746067/201945471-6ee202a5-0dc2-472b-b34a-3a197e5f2dff.png)
![stamp](https://user-images.githubusercontent.com/17746067/201945495-4d82b6a4-2cb3-4e76-aedb-645b460f699f.png)

I'd vote for the first or third one (see above).

**Comment by wojtekmaj** [comment]
My favs: 
https://github.com/lucide-icons/lucide/issues/883#issuecomment-1315032498 2nd one
https://github.com/lucide-icons/lucide/issues/883#issuecomment-1315397313 1st one
