### ISSUE TITLE
Bitcoin icon is rotated - not consistent

### ISSUE THREAD

**Issue by muster-mark** [lucide-icons/lucide#887]
These icons are described as "Beautiful & consistent". However the bitcoin icon is not consistent with other icons (in particular not with the other curency icons, such as pound, dollar, euro, yen, being rotated at an angle for some reason. This would prevent it being used alongside the other currency icons without sticking out.

**Comment by karsa-mistmere** [comment]
Hi @muster-mark!

Bitcoin is in fact not just a currency, but first and foremost a brand icon and as such, it will be deprecated soon, see #94 and #670
You can see, however, that the bitcoin logo _is_ in fact rotated: https://bitcoin.org/en/

**Comment by muster-mark** [comment]
@karsa-mistmere

Ah, I didn't know that Bitcoin was a brand icon. In fact, I'm not even sure why I referred to it as a currency since

> Bitcoin appears to behave more like a speculative investment than a currency.
Source: [Science Direct](https://www.sciencedirect.com/science/article/pii/B9780128021170000023)

So just as well to remove it then!
