### ISSUE TITLE
Generic icon component with typescript

### ISSUE THREAD

**Issue by celsoft** [lucide-icons/lucide#894]
Hi. please provide an example of typescript code.

**Comment by ericfennis** [comment]
@celsoft For which package?

**Comment by celsoft** [comment]
> @celsoft For which package?

lucide-react

**Comment by ericfennis** [comment]
@celsoft I'm not sure what you exactly want. 
We have some exported type you can you use but the rest of the examples that are provided on https://lucide.dev/docs/lucide-react is also valid typescript.

Or do you mean we need to give examples how you can use lucide types in your typescript project?
If so, can you provide a use-case you currently missing in our current documentation.

This is our typescript declaration file:

```ts
import { SVGAttributes } from 'react'

declare module 'lucide-react'

// Create interface extending SVGProps
export interface LucideProps extends Partial<React.SVGProps<SVGSVGElement>> {
    size?: string | number
}

export declare const createReactComponent: (iconName: string, iconNode: any[]) => (props: LucideProps) => JSX.Element;

export type Icon = React.FC<LucideProps>;

// Generated icons
export declare const Accessibility: (props: LucideProps) => JSX.Element;
export declare const Activity: (props: LucideProps) => JSX.Element;
export declare const AirVent: (props: LucideProps) => JSX.Element;
export declare const Airplay: (props: LucideProps) => JSX.Element;
export declare const AlarmCheck: (props: LucideProps) => JSX.Element;
export declare const AlarmClockOff: (props: LucideProps) => JSX.Element;
// ... All icons
```

**Comment by celsoft** [comment]
![image](https://user-images.githubusercontent.com/5567863/205670855-4a0d6192-2084-4eb6-881b-776d9106292b.png)
Hi. I need to load icons by name in a loop.
![image](https://user-images.githubusercontent.com/5567863/205671335-519dd511-ccdc-480f-976e-98880d454c4f.png)

**Comment by celsoft** [comment]
Thank you

**Comment by MalteBoehm** [comment]
Does not work anymore: 

TS2551: Property AArrowDown does not exist on type
{     'a-arrow-down': () => Promise<typeof __icons_a_arrow_down>;     'a-arrow-up': () => Promise<typeof __icons_a_arrow_up>;     'a-large-small': () => Promise<...>;     ... 1446 more ...;     'zoom-out': () => Promise<...>; }
. Did you mean arrow-down?
