### ISSUE TITLE
Next 13 + lucide-react 0.104.0 not tree shaking properly

### ISSUE THREAD

**Issue by dgattey** [lucide-icons/lucide#897]
## Prerequisites

* Version: 0.104.0
* Running from: Installed with `pnpm` in a `next` (13.0.6) project using their `swc` compiler/bundler
* Operating system: macOS

## Step to reproduce

Run `pnpm build` in this repo or a fork of: https://github.com/dgattey/test-lucide-size.

The repo consists of a barebones Next app, with one page that renders the `Music` icon from `lucide-react`. I expect only that one icon to be pulled into my build, verified via `@next/bundle-analyzer`.

### Actual behavior

With `pnpm build`, you can see that **ALL** of `lucide-react`'s icons are pulled in for a bundle size of 303 kb. Quite clearly, tree shaking is not working properly and is including every icon in the ES bundle instead of just one. Also observing this in a production app.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/982182/205582923-85e5c94f-8550-4301-81b3-4d6ca37cb0e7.png">

**Comment by ericfennis** [comment]
Tnx for reporting!

**Comment by ericfennis** [comment]
I created a hotfix under `lucide-react@0.104.1`. 
Thanks for providing the repo, I tested it and it works again.

**Comment by dgattey** [comment]
oh woah I didn't realize you made that change just yesterday in 0.104.0! I randomly tested app size yesterday after updating, and I'm glad I did. Thanks for the quick fix.
