### ISSUE TITLE
Car Park Icon

### ISSUE THREAD

**Issue by wolmoe** [lucide-icons/lucide#901]
## Icon Request

* Icon name: Car Park, Parking Lot
* Use case: Travel Websites, Getting there sections
* _Screenshots_ of similar icons:
Sorry, my phone won't add the images - please see in the comments

**Comment by karsa-mistmere** [comment]
I'm assuming you mean something like these?

![image](https://user-images.githubusercontent.com/17746067/208236130-899a4bd5-e2eb-49d4-8ac3-90f59c76f35b.png)

**Comment by wolmoe** [comment]
![Screenshot_20221217-104207](https://user-images.githubusercontent.com/53096914/208236152-1c48af4a-0a64-40e5-a888-e80bcd0ac620.png)
![Screenshot_20221217-104139](https://user-images.githubusercontent.com/53096914/208236155-7692b1dc-a689-429e-bb52-5c59924b931a.png)
![Screenshot_20221217-104029](https://user-images.githubusercontent.com/53096914/208236156-7fc8fe6c-8233-48b9-9f47-ba7b5bcf0d70.png)

**Comment by wolmoe** [comment]
> I'm assuming you mean something like these?
> 
> ![image](https://user-images.githubusercontent.com/17746067/208236194-39c90ac0-cf9c-48de-884e-30ce01c743ea.png)
> 

Yes, that could be one way to go. Although I think it would be nice to have a car on it as well (managed to upload the images in the comments now)

**Comment by karsa-mistmere** [comment]
> Yes, that could be one way to go. Although I think it would be nice to have a car on it as well (managed to upload the images in the comments now)

I don't think we can possibly fit a car in there and keep it looking neat, we could have something like this:
![image](https://user-images.githubusercontent.com/17746067/208236372-ce66e3f2-a7ba-4626-8e2b-4e9b6a4bc3a5.png)

But altogether, I think we should just go with `parking-circle` and/or `parking-square`, they're much cleaner and simpler.

**Comment by wolmoe** [comment]
Yes, looking at the draft I agree to that. The one with the car looks too crammed in that small scale. Thanks for giving it a try though!

**Comment by wolmoe** [comment]
I played around with the existing car icon today. Would something like this possibly work?
![parking](https://user-images.githubusercontent.com/53096914/208295405-e43d6dfc-72fc-4f10-9cf4-74822fab73c1.png)

**Comment by karsa-mistmere** [comment]
I think the P itself is a bit too tight, the loop could easily be half a pixel wider, or maybe even a full pixel:
![car-park](https://user-images.githubusercontent.com/17746067/208295693-3e7df509-2389-4b78-813c-f935de15a6f2.png)

While this works quite well, I'd personally still go for just the P in a square or circle, since those also have support for depicting no parking, this one is kinda funky in either of our usual slash setups:
![car-no-parking](https://user-images.githubusercontent.com/17746067/208295854-0a8cf415-575e-4b25-b98d-21bdfb5bb0c0.png)

**Comment by karsa-mistmere** [comment]
As usual, I'd like to hear @ericfennis' two cents on this. :)
