### ISSUE TITLE
Dam Icon

### ISSUE THREAD

**Issue by raphasampaio** [lucide-icons/lucide#910]
## Icon Request

* Icon name: Dam
* Use case: For energy websites
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/11352898/212265799-4578006e-b457-4484-ab26-ebf515e5c4a4.png)
![image](https://user-images.githubusercontent.com/11352898/212265605-a9a6c4eb-9f25-4ba3-9e15-19dd3c13bfa5.png)
![image](https://user-images.githubusercontent.com/11352898/212265861-63181cb5-e937-4f3a-bfe5-b1f3d6ab82b3.png)

**Comment by ericfennis** [comment]
Can you explain more about the use case on energy websites?

**Comment by raphasampaio** [comment]
Sure, @ericfennis, this use is similar to the icon request #911. Is it to illustrate different power sources: hydroelectric electric (dams), renewable, batteries (https://lucide.dev/icon/battery-charging), ...

**Comment by karsa-mistmere** [comment]
![image](https://user-images.githubusercontent.com/17746067/213207718-92bff980-fda5-4faf-aaaa-9d65a1e69750.png)
![image](https://user-images.githubusercontent.com/17746067/213207672-ca4a2bc5-f619-4dae-be3d-ce5eae1d55bc.png)

Not sure about these design, maybe the third one is the "most Lucide-ish".

**Comment by raphasampaio** [comment]
I think something like this works:
![image](https://user-images.githubusercontent.com/11352898/213210705-530fe29f-06e9-4a22-bc72-773dc742fbd7.png)

**Comment by raphasampaio** [comment]
![image](https://user-images.githubusercontent.com/11352898/214944208-7469e56d-2f14-4a93-a5fb-f5e4005e3da2.png)
![image](https://user-images.githubusercontent.com/11352898/214944108-f8cbbc29-d928-46db-8176-d859309db27f.png)

**Comment by ericfennis** [comment]
I think would be nice if the water matches the [`waves`](https://lucide.dev/icon/waves) icon.

**Comment by AndreasSas** [comment]
<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+12h4%22+/%3E%3Cpath+d=%22M2+16h4%22+/%3E%3Cpath+d=%22M2+20h4%22+/%3E%3Cpath+d=%22M2+4h4%22+/%3E%3Cpath+d=%22M2+8h4%22+/%3E%3Cpath+d=%22M7+2c-.55+0-1+.45-1+1v18c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+3c0-.55-.45-1-1-1z%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTEuMzFjMS4xNy41NiAxLjU0IDEuNjkgMy41IDEuNjkgMi41IDAgMi41LTIgNS0yIDEuMyAwIDEuOS41IDIuNSAxIiAvPgogIDxwYXRoIGQ9Ik0xMiAxOGMuNi41IDEuMiAxIDIuNSAxIDIuNSAwIDIuNS0yIDUtMiAxLjMgMCAxLjkuNSAyLjUgMSIgLz4KICA8cGF0aCBkPSJNMiAxMmg0IiAvPgogIDxwYXRoIGQ9Ik0yIDE2aDQiIC8+CiAgPHBhdGggZD0iTTIgMjBoNCIgLz4KICA8cGF0aCBkPSJNMiA0aDQiIC8+CiAgPHBhdGggZD0iTTIgOGg0IiAvPgogIDxwYXRoIGQ9Ik03IDJjLS41NSAwLTEgLjQ1LTEgMXYxOGMwIC41NS40NSAxIDEgMWg0Yy41NSAwIDEtLjQ1IDEtMUwxMCAzYzAtLjU1LS40NS0xLTEtMXoiIC8+Cjwvc3ZnPg==.svg"/><br/>Open lucide studio</a>

I tried to match Raphasampaio's design, with the waves

**Comment by jguddas** [comment]
> [<img alt="icons" width="120" src="https://camo.githubusercontent.com/e407ea02ad1316f822548977303dd961daa5bbddcc5a57cff129214a98ee5b84/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d5445754d7a466a4d5334784e7934314e6941784c6a5530494445754e6a6b674d793431494445754e6a6b674d693431494441674d6934314c5449674e533079494445754d794177494445754f533431494449754e5341784969417650676f67494478775958526f49475139496b30784d6941784f474d754e693431494445754d694178494449754e534178494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4d6941784d6d67304969417650676f67494478775958526f49475139496b307949444532614451694943382b4369416750484268644767675a443069545449674d6a426f4e4349674c7a344b49434138634746306143426b50534a4e4d694130614451694943382b4369416750484268644767675a443069545449674f4767304969417650676f67494478775958526f49475139496b303349444a6a4c5334314e5341774c5445674c6a51314c5445674d5859784f474d77494334314e5334304e534178494445674d576730597934314e534177494445744c6a5131494445744d5577784d43417a597a41744c6a55314c5334304e5330784c5445744d586f694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+12h4%22+/%3E%3Cpath+d=%22M2+16h4%22+/%3E%3Cpath+d=%22M2+20h4%22+/%3E%3Cpath+d=%22M2+4h4%22+/%3E%3Cpath+d=%22M2+8h4%22+/%3E%3Cpath+d=%22M7+2c-.55+0-1+.45-1+1v18c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+3c0-.55-.45-1-1-1z%22+/%3E)
> 
> I tried to match Raphasampaio's design, with the waves

Probably a bit big, comparing against square and circle as a reference.

**Comment by AndreasSas** [comment]
> > [<img alt="icons" width="120" src="https://camo.githubusercontent.com/e407ea02ad1316f822548977303dd961daa5bbddcc5a57cff129214a98ee5b84/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d5445754d7a466a4d5334784e7934314e6941784c6a5530494445754e6a6b674d793431494445754e6a6b674d693431494441674d6934314c5449674e533079494445754d794177494445754f533431494449754e5341784969417650676f67494478775958526f49475139496b30784d6941784f474d754e693431494445754d694178494449754e534178494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4d6941784d6d67304969417650676f67494478775958526f49475139496b307949444532614451694943382b4369416750484268644767675a443069545449674d6a426f4e4349674c7a344b49434138634746306143426b50534a4e4d694130614451694943382b4369416750484268644767675a443069545449674f4767304969417650676f67494478775958526f49475139496b303349444a6a4c5334314e5341774c5445674c6a51314c5445674d5859784f474d77494334314e5334304e534178494445674d576730597934314e534177494445744c6a5131494445744d5577784d43417a597a41744c6a55314c5334304e5330784c5445744d586f694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+12h4%22+/%3E%3Cpath+d=%22M2+16h4%22+/%3E%3Cpath+d=%22M2+20h4%22+/%3E%3Cpath+d=%22M2+4h4%22+/%3E%3Cpath+d=%22M2+8h4%22+/%3E%3Cpath+d=%22M7+2c-.55+0-1+.45-1+1v18c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+3c0-.55-.45-1-1-1z%22+/%3E)
> > I tried to match Raphasampaio's design, with the waves
> 
> Probably a bit big, comparing against square and circle as a reference.

<a title="Open lucide studio" target="_blank" href="https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+10h4%22+/%3E%3Cpath+d=%22M2+14h4%22+/%3E%3Cpath+d=%22M2+18h4%22+/%3E%3Cpath+d=%22M2+6h4%22+/%3E%3Cpath+d=%22M7+3c-.55+0-1+.45-1+1v16c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+4c0-.55-.45-1-1-1z%22+/%3E"><img alt="icons" width="120" src="https://lucide.dev/api/gh-icon/PHN2ZwogIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICB3aWR0aD0iMjQiCiAgaGVpZ2h0PSIyNCIKICB2aWV3Qm94PSIwIDAgMjQgMjQiCiAgZmlsbD0ibm9uZSIKICBzdHJva2U9ImN1cnJlbnRDb2xvciIKICBzdHJva2Utd2lkdGg9IjIiCiAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIgogIHN0cm9rZS1saW5lam9pbj0icm91bmQiCj4KICA8cGF0aCBkPSJNMTEgMTEuMzFjMS4xNy41NiAxLjU0IDEuNjkgMy41IDEuNjkgMi41IDAgMi41LTIgNS0yIDEuMyAwIDEuOS41IDIuNSAxIiAvPgogIDxwYXRoIGQ9Ik0xMiAxOGMuNi41IDEuMiAxIDIuNSAxIDIuNSAwIDIuNS0yIDUtMiAxLjMgMCAxLjkuNSAyLjUgMSIgLz4KICA8cGF0aCBkPSJNMiAxMGg0IiAvPgogIDxwYXRoIGQ9Ik0yIDE0aDQiIC8+CiAgPHBhdGggZD0iTTIgMThoNCIgLz4KICA8cGF0aCBkPSJNMiA2aDQiIC8+CiAgPHBhdGggZD0iTTcgM2MtLjU1IDAtMSAuNDUtMSAxdjE2YzAgLjU1LjQ1IDEgMSAxaDRjLjU1IDAgMS0uNDUgMS0xTDEwIDRjMC0uNTUtLjQ1LTEtMS0xeiIgLz4KPC9zdmc+.svg"/><br/>Open lucide studio</a>

This is with a top and bottom margin of 2px and removed one of the side stripes. Indeed, THis one feels a bit less big

**Comment by jguddas** [comment]
> > > [<img alt="icons" width="120" src="https://camo.githubusercontent.com/e407ea02ad1316f822548977303dd961daa5bbddcc5a57cff129214a98ee5b84/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d5445754d7a466a4d5334784e7934314e6941784c6a5530494445754e6a6b674d793431494445754e6a6b674d693431494441674d6934314c5449674e533079494445754d794177494445754f533431494449754e5341784969417650676f67494478775958526f49475139496b30784d6941784f474d754e693431494445754d694178494449754e534178494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4d6941784d6d67304969417650676f67494478775958526f49475139496b307949444532614451694943382b4369416750484268644767675a443069545449674d6a426f4e4349674c7a344b49434138634746306143426b50534a4e4d694130614451694943382b4369416750484268644767675a443069545449674f4767304969417650676f67494478775958526f49475139496b303349444a6a4c5334314e5341774c5445674c6a51314c5445674d5859784f474d77494334314e5334304e534178494445674d576730597934314e534177494445744c6a5131494445744d5577784d43417a597a41744c6a55314c5334304e5330784c5445744d586f694943382b436a777663335a6e50673d3d2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+12h4%22+/%3E%3Cpath+d=%22M2+16h4%22+/%3E%3Cpath+d=%22M2+20h4%22+/%3E%3Cpath+d=%22M2+4h4%22+/%3E%3Cpath+d=%22M2+8h4%22+/%3E%3Cpath+d=%22M7+2c-.55+0-1+.45-1+1v18c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+3c0-.55-.45-1-1-1z%22+/%3E)
> > > I tried to match Raphasampaio's design, with the waves
> > 
> > 
> > Probably a bit big, comparing against square and circle as a reference.
> 
> [<img alt="icons" width="120" src="https://camo.githubusercontent.com/9a3413190352711fa7d14d1c3549ca183ab5880c5bb3b63aae5a42ce892da73b/68747470733a2f2f6c75636964652e6465762f6170692f67682d69636f6e2f50484e325a776f67494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a79494b4943423361575230614430694d6a516943694167614756705a326830505349794e43494b4943423261575633516d393450534977494441674d6a51674d6a5169436941675a6d6c7362443069626d39755a53494b4943427a64484a7661325539496d4e31636e4a6c626e5244623278766369494b4943427a64484a766132557464326c6b64476739496a496943694167633352796232746c4c577870626d566a59584139496e4a766457356b49676f6749484e30636d39725a5331736157356c616d3970626a3069636d3931626d5169436a344b49434138634746306143426b50534a4e4d5445674d5445754d7a466a4d5334784e7934314e6941784c6a5530494445754e6a6b674d793431494445754e6a6b674d693431494441674d6934314c5449674e533079494445754d794177494445754f533431494449754e5341784969417650676f67494478775958526f49475139496b30784d6941784f474d754e693431494445754d694178494449754e534178494449754e534177494449754e533079494455744d6941784c6a4d674d4341784c6a6b754e5341794c6a55674d5349674c7a344b49434138634746306143426b50534a4e4d6941784d4767304969417650676f67494478775958526f49475139496b307949444530614451694943382b4369416750484268644767675a443069545449674d54686f4e4349674c7a344b49434138634746306143426b50534a4e4d694132614451694943382b4369416750484268644767675a443069545463674d324d744c6a5531494441744d5341754e4455744d534178646a4532597a41674c6a55314c6a5131494445674d5341786144526a4c6a5531494441674d5330754e4455674d533078544445774944526a4d4330754e5455744c6a51314c5445744d533078656949674c7a344b5043397a646d632b2e737667">Open lucide studio](https://lucide-studio.vercel.app/edit?value=%3Cpath+d=%22M11+11.31c1.17.56+1.54+1.69+3.5+1.69+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M12+18c.6.5+1.2+1+2.5+1+2.5+0+2.5-2+5-2+1.3+0+1.9.5+2.5+1%22+/%3E%3Cpath+d=%22M2+10h4%22+/%3E%3Cpath+d=%22M2+14h4%22+/%3E%3Cpath+d=%22M2+18h4%22+/%3E%3Cpath+d=%22M2+6h4%22+/%3E%3Cpath+d=%22M7+3c-.55+0-1+.45-1+1v16c0+.55.45+1+1+1h4c.55+0+1-.45+1-1L10+4c0-.55-.45-1-1-1z%22+/%3E)
> 
> This is with a top and bottom margin of 2px and removed one of the side stripes. Indeed, This one feels a bit less big

Neat.
