### ISSUE TITLE
Blind Icon

### ISSUE THREAD

**Issue by rienkkk** [lucide-icons/lucide#912]
## Icon Request

* Icon name: Blind
* Use case: Smart Home websites, systems apps. Home decor websites/apps.
* _Screenshots_ of similar icons:
![download](https://user-images.githubusercontent.com/57758628/212333689-b2c49edc-5d8f-49f7-b172-2e5ce233a186.png)
![images](https://user-images.githubusercontent.com/57758628/212333704-6df68028-d1a6-4f11-ab0a-7bf30e2a81aa.png)

**Comment by karsa-mistmere** [comment]
I knew I had some designs already left over from #683:

![image](https://user-images.githubusercontent.com/17746067/212847564-73570179-5a3a-4fc5-82ab-fe19898e4456.png)

**Comment by karsa-mistmere** [comment]
@ericfennis: which of these would you prefer?
