### ISSUE TITLE
Aliases don't work in lucide-react-native

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#917]
## Prerequisites

* Version: 0.105.0
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system: macOS 12

## Step to reproduce

```
import { HomeIcon } from 'lucide-react-native';
```

### Actual behavior

`undefined` imported

**Comment by ericfennis** [comment]
@wojtekmaj Thanks for reporting, will check it

**Comment by ericfennis** [comment]
Hotfix released under `lucide-react-native@0.105.1`

**Comment by wojtekmaj** [comment]
Thank you! I can confirm it's working.

**Comment by itsjavi** [comment]
@wojtekmaj I confirm I also have the same problem on `0.108.0`, with `lucide-react`, React 18 & NextJS 13

**Comment by wojtekmaj** [comment]
That sounds like a completely separate issue to me.
