### ISSUE TITLE
Icon Request: blank/empty placeholder icon

### ISSUE THREAD

**Issue by jakajancar** [lucide-icons/lucide#920]
A blank/empty icon (no pixels filled) that can be used in place of a real icon:

  - In CSS, to show nothing while maintaining the exact size/positioning that the visible icon will eventually have or that other icons surrounding it have.

  - In JavaScript, to allow passing a `Lucide.Icon` without requiring the received to special-case `undefined`/`null`.

**Comment by karsa-mistmere** [comment]
While at first this seemed like a good idea, I'm struggling to find a legit use case in UI design.

1. While the visible icon has not yet loaded neither will have the empty icon.
2. The time period, while Lucide has not yet been initialized should not take more than a fraction of a second.
3. I cannot think of a single component where leaving empty space for an icon would be preferable, in any such instance I can fathom the design is objectively cleaner either by completely omitting the icon or adding an appropriate placeholder icon instead (e.g. `...` or a spinner icon).

Can you showcase a UI component where such a placeholder would be useful?

**Comment by karsa-mistmere** [comment]
I think this is easily doable by using an [appropriate grid layout](https://cssgrid-generator.netlify.app/), and is not something Lucide should be responsible for providing a workaround for.
We've agreed that this isn't something we intend to support at the present moment, but thank you for your suggestion.
