### ISSUE TITLE
Icon Request: universal access

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#921]
## Icon Request

* Icon name: universal-access
* Use case: alternative accesibility icon
* _Screenshots_ of similar icons:

![multiple circle icons like the play circle and a new icon that is the person icon inside the circle that is used by all the other circle icons](https://user-images.githubusercontent.com/25524993/214324338-f388ca89-1173-4baf-b473-debaf17c83ba.png)

---

> But the most important problem with the International Symbol of Access is this: it is exclusionary. The symbol is all about the wheelchair -- even though the majority of disabilities are not mobility-related.

> Here in Ontario, less than three per cent of the 1.8-million people with disabilities actually use wheelchairs or other mobility devices! The same small percentage applies throughout most other jurisdictions. In other words, over 97 per cent of Ontarians with a declared disability are not taken into account by any of these symbols, all of which reinforce the idea that accessibility is primarily about accommodating wheelchairs.

https://www.huffpost.com/archive/ca/entry/reimagining-accessibility-and-the-wheelchair-symbol_b_3997930

**Comment by karsa-mistmere** [comment]
We already have this: https://lucide.dev/icon/person-standing?search=accessibility

**Comment by jguddas** [comment]
I do think the wheelchair icon looks awesome, what I'm missing is a person standing inside a circle.
https://www.google.com/search?q=universal+access+icon&tbm=isch
