### ISSUE TITLE
Search dialog option icons

### ISSUE THREAD

**Issue by polyipseity** [lucide-icons/lucide#925]
## Icon Request

* Icon name: Match case, whole word (already has regex)
* Use case: Making a search dialog
* _Screenshots_ of similar icons:
  - One that I got from VSCode: ![image](https://user-images.githubusercontent.com/17660922/215114577-1ed7a853-956f-404d-9834-66c032d7cd7f.png)

**Comment by jguddas** [comment]
|Name|Icon|
|---|---|
|case-insensitive||
|whole-word||
|regexp|![icon](https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/regex.svg)|

**Comment by ericfennis** [comment]
@jguddas Nice work. I think the letters are a bit too small to read when scaled at 100%. Maybe you can try to increase it a bit.

**Comment by jguddas** [comment]
### 5px circle radius
<kbd>![case-insensitive](https://user-images.githubusercontent.com/25524993/216110330-ec38ee8f-9c3c-498d-87fb-2b3a6fa416ea.svg)</kbd> <kbd>![whole-word](https://user-images.githubusercontent.com/25524993/216112595-2f36a96c-7cd7-42bc-88da-56749f9fb2b4.svg)</kbd>

### 6px circle radius
<kbd>![case-insensitive (3)](https://user-images.githubusercontent.com/25524993/216112640-f2811775-7f01-4c07-9021-e7a33831233a.svg)</kbd> <kbd>![whole-word (1) 2](https://user-images.githubusercontent.com/25524993/216112624-116314c9-5118-4b4a-9e1b-8817a8656157.svg)</kbd>

**Comment by polyipseity** [comment]
The bigger ones look rounder and nicer to me.

**Comment by karsa-mistmere** [comment]
I think we should stay closer to the existing capital A shape as defined in baseline and use more geometric stems for lowercase letters:
![search-icons](https://user-images.githubusercontent.com/17746067/216271264-95e7fa00-ec4a-427c-93c2-654105cbf62b.svg)

**Comment by xnousnow** [comment]
oı shaped a looks best for me ✌🏻

**Comment by karsa-mistmere** [comment]
This has been solved by #1023

**Comment by polyipseity** [comment]
> This has been solved by #1023

How did you get 40 releases while I was not looking? You must have been working hard. 👀
