### ISSUE TITLE
Add `spell-check` icon

### ISSUE THREAD

**Issue by jguddas** [lucide-icons/lucide#928]
## Icon Request

* Icon name: spell-check
* Use case: to enable spell checking
* _Screenshots_ of similar icons: ![spell-check-2](https://user-images.githubusercontent.com/25524993/215265848-f6f5d53c-42d3-4037-9dfc-e280a25eaec4.svg) ![spell-check](https://user-images.githubusercontent.com/25524993/215265849-86773d57-8315-49a8-9516-97edafcf3035.svg)

**Comment by karsa-mistmere** [comment]
I think the whole icon should be centred not just the letter A, other than that the second option looks perfect:
![image](https://user-images.githubusercontent.com/17746067/216277177-dedbcbf3-8b28-4e14-9f71-2cca7ec13d4c.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Maybe place it next to some other icons. See which one is better.

**Comment by jguddas** [comment]
I think having it centered looks great.
What about a `spell-bad` variant?
![](https://user-images.githubusercontent.com/25524993/218771821-df45a145-4959-4336-9c4a-6c6bc542944b.png)

**Comment by ericfennis** [comment]
Centered is probably is also safest option. When aligning vertically.

**Comment by ericfennis** [comment]
@jguddas Looking at this I think think the first version will look a bit better.

**Comment by karsa-mistmere** [comment]
Oh, wow, I made this comparison like two weeks ago and then totally forgot to post it:

![image](https://user-images.githubusercontent.com/17746067/221869286-f89eb71b-a67d-4231-be08-9aa4e775f276.png)
