### ISSUE TITLE
John Leteys awesome icons

### ISSUE THREAD

**Issue by ericfennis** [lucide-icons/lucide#93]
@johnletey Some open/old PRs from your old account in the feather repo have some awesome icons!
I think we can add them to Lucide. 

Here is a list of the icons I think are welcome to add to the Lucide repo!
- [x] Currency icons [pr](https://github.com/feathericons/feather/pull/670)
- [ ] code-2 icon [pr](https://github.com/feathericons/feather/pull/671)
- [x] file-check, file-times , folder .. [pr](https://github.com/feathericons/feather/pull/669)
- [x] webcam [pr](https://github.com/feathericons/feather/pull/687)

More PR from [John](https://github.com/feathericons/feather/pulls/jletey)

**Comment by delnyn** [comment]
Also the `file-check, file-times , folder .. pr` is already resolved :)

**Comment by locness3** [comment]
Checked it
