### ISSUE TITLE
Better robot icon

### ISSUE THREAD

**Issue by jakajancar** [lucide-icons/lucide#934]
The bot icon is not very obvious. It could just as easily represent a joystick (from the profile) or perhaps an RC controller (from the top).

More obvious eyes, mouth, ears, neck, or body could help. Random example from a google search:

![download](https://user-images.githubusercontent.com/187741/216238981-930bd938-7d4c-4303-a3bd-5967097611c5.png)

**Comment by ericfennis** [comment]
Yeah agree on this. 
Other use cases are: AI

**Comment by karsa-mistmere** [comment]
Yeah, we can definitely improve upon it. Not sure about the example though, that'd be way to dense for Lucide, but we could use the eyes as drawn by @kemie and add a tiny little mouth such as this?
![image](https://user-images.githubusercontent.com/17746067/216263368-8a2752d6-857d-4e3b-9dd0-d855d1a216f5.png)
![bot](https://user-images.githubusercontent.com/17746067/216263412-59a0e732-7fec-4839-87d6-80d392e291b9.svg)

**Comment by ericfennis** [comment]
My take
<img width="110" alt="image" src="https://user-images.githubusercontent.com/11825403/218329167-82127597-737e-4eee-a71b-c094c15d34ae.png">

**Comment by kemie** [comment]
Some ideas in different combinations (some of these probably violate guidelines)

<img width="348" alt="Lucid  2023-02-13 at 120410@2x" src="https://user-images.githubusercontent.com/1877967/218441665-2022d1f9-8cb2-42ac-86d4-56dd5e65327a.png">

**Comment by karsa-mistmere** [comment]
@kemie: The mouth on the last one is super cute, but yeah, it doesn't follow Lucide's guidelines, I'm afraid (the round bit on top of the head is also problematic).

**Comment by xnousnow** [comment]
What about making the bot's joystick-looking thing at the head shorter and putting a cute mouth on it?

**Comment by joshmillgate** [comment]
The bot SVG doesn't currently have eyes, is that intentional?

**Comment by xnousnow** [comment]
@joshmillgate What do you mean by SVG? The icon at the site is correctly rendered.

**Comment by karsa-mistmere** [comment]
In Figma it doesn't. It's a bug, not sure if we should fix it before a new icon is added, I'm voting for @ericfennis' design from 12th Feb.

**Comment by karsa-mistmere** [comment]
Just a summary of guideline conforming designs
![image](https://user-images.githubusercontent.com/17746067/228146695-d0e1eaf4-e401-4154-8a9e-ce7ed8a46a23.png)
![image](https://user-images.githubusercontent.com/17746067/228146734-f768a0d3-d62a-403d-b2f1-d85675079e15.png)
(current > my original proposal > Eric's proposal > a mix of the two [using the same eyes as `dog` and `cat` etc.])

**Comment by KayleyHill** [comment]
Not sure if my vote counts, but love @ericfennis' design and the amended design by @karsa-mistmere (the one on the end with a mouth)

**Comment by karsa-mistmere** [comment]
> Not sure if my vote counts, but love @ericfennis' design and the amended design by @karsa-mistmere (the one on the end with a mouth)

This is an open source project with a community of contributors, every vote counts. :)

**Comment by jguddas** [comment]
> @kemie: The mouth on the last one is super cute, but yeah, it doesn't follow Lucide's guidelines, I'm afraid (the round bit on top of the head is also problematic).

Can't we still somehow put a smile on this robot's little face?

**Comment by danielbayley** [comment]
There is also some kind of *chat*bot (maybe `bot-chat`)  icon to consider (possibly/preferably using the existing [`message-square`](https://lucide.dev/icons/message-square) shape… See also #1208.

**Comment by ericfennis** [comment]
Since my design got the most thumbs up, I created a PR #1544

**Comment by KayleyHill** [comment]
Think it was a draw between yours and my amendment with a smile @ericfennis

**Comment by xnousnow** [comment]
> There is also some kind of _chat_bot (maybe `bot-chat`) icon to consider (possibly/preferably using the existing [`message-square`](https://lucide.dev/icons/message-square) shape… See also #1208.
> 
> Simple enough, if we were to stick with something like the existing `bot`…
> 
> ![preview](https://user-images.githubusercontent.com/7797479/261408004-bc919678-e239-4f02-a011-76bed1c50fca.svg)
> 
> But the more elements we add, the more awkward it gets… This is a tricky one!
> 
> Edit: Something along the lines of these…? cc: @jakajancar @ericfennis @karsa-mistmere @kemie @xnousnow @joshmillgate @KayleyHill @jguddas
> 
> ![preview](https://user-images.githubusercontent.com/7797479/261421513-3ea60257-760a-434a-b61d-66dcba5a5225.svg)

I think you could add the last one without the ears and hair of the bot, making the speech bubble with smile.

**Comment by kemie** [comment]
@xnousnow love the idea, not sure it's very clear with the speech bubble arrow pointing upwards (gives me cat vibes). I tried with the arrow pointing downwards, looks better, but then int's not aligned with the other bot- does it matter? 

![image](https://github.com/lucide-icons/lucide/assets/1877967/2639f281-730a-4deb-968b-e8b5fd918155)

**Comment by xnousnow** [comment]
@kemie I was curious about the arrow direction too. @karsa-mistmere @danielbayley do you have some opinions about this?

**Comment by danielbayley** [comment]
> I tried with the arrow pointing downwards, looks better, but then int's not aligned with the other bot

@kemie Yeah that was the only reason for trying it the other way (upside down)…

> curious about the arrow direction too. @karsa-mistmere @danielbayley do you have some opinions about this?

@xnousnow I think the normal orientation looks better, but as mentioned, makes it much smaller and inconsistent with [`bot`](https://lucide.dev/icons/bot)…

Very tricky this one—given the space constraints—trying to achieve consistency between both [`message-square`](https://lucide.dev/icons/message-square) and [`bot`](https://lucide.dev/icons/bot)…
