### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by te6-in** [lucide-icons/lucide#937]
## Step to reproduce
- Enter https://lucide.dev

## Any message or error
- Can't connect to the server

Many people including me in South Korea can't connect to lucide.dev at this moment.
It hasn't worked since 5h ago. Using VPN didn't help. I wonder if the same thing happens to anybody else here.

**Comment by wlhrtr** [comment]
Also just noticed it. Definitely down: https://isitdownorjust.me/lucide-dev/

**Comment by wojtekmaj** [comment]
Temp mirror if you need to urgently check some icons: https://github.com/lucide-icons/lucide/deployments -> View deployment

**Comment by ericfennis** [comment]
Yess, we noticed some issues with domain registration. We are currently in contact with Vercel, how to fix this. 
Temporary deployment address: https://lucide-git-main-lucide.vercel.app/

**Comment by wojtekmaj** [comment]
Working! Can be closed I guess.

**Comment by te6-in** [comment]
Nice 😆 Thank you all for all the efforts.

**Comment by ericfennis** [comment]
Yeah, we had contact with support from Vercel and we figured it out. It's now working again finally. 
Sorry for the downtime, we will make sure it won't happen again!

**Comment by eynort** [comment]
Hi, i think its down again, i cant access since this morning, i use not a long ago and it was working fine

![Image](https://github.com/user-attachments/assets/db89ef90-f4cb-4ac3-82af-492380f815b3)

**Comment by ericfennis** [comment]
@veD-tnayrB Works on my machine!

**Comment by eynort** [comment]
> [@veD-tnayrB](https://github.com/veD-tnayrB) Works on my machine!

Yeah, i just check and now it works, thank you!

![Image](https://github.com/user-attachments/assets/d0b2da50-20df-4b85-bdc4-d8da95d2bf27)
