### ISSUE TITLE
NFC / contactless payment icon

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#938]
## Icon Request

* Icon name: NFC / contactless payment
* Use case: For using NFC on the web, for marking any features involving contactless, for marking cards in banking apps
* _Screenshots_ of similar icons:
![image](https://user-images.githubusercontent.com/5426427/217518947-170b8878-eaf9-463d-9194-94692e86016b.png)
![image](https://user-images.githubusercontent.com/5426427/217518986-3f1e86da-5738-42a2-a5bf-24e8b9a9ebd0.png)

It would be nice to get "NFC off/disabled/not available" icon as well.

**Comment by karsa-mistmere** [comment]
w/ & w/o a smartphone:

![nfc-smartphone](https://user-images.githubusercontent.com/17746067/218405344-e46b6aef-3cc3-4d6f-8f43-06d499cb99ac.svg)
