### ISSUE TITLE
Construction 🚧 Icon

### ISSUE THREAD

**Issue by adiac** [lucide-icons/lucide#940]
## Icon Request

* Icon name: `construction`
* Use case: A sign used to indicate roadwork or construction. Generally shown as yellow and black diagonal stripes, and often used to physically block access to a road or area. May be used to imply a website or project in progress or under construction. ([from emojipedia.org](https://emojipedia.org/construction/))
* _Screenshots_ of similar icons: A construction site barricade 🚧

I'm surprised this icon is not yes present.

**Comment by karsa-mistmere** [comment]
> I'm surprised this icon is not yes present.

I guess it's simply that no-one has ever needed it before; we're an open source project after all, with people volunteering their free time to design stuff, so we mostly have icons someone at some point had a need of. 🤷‍♂️ 

Here's a first draft:
![construction](https://user-images.githubusercontent.com/17746067/218028655-e75acd14-cec7-4e94-a909-1e8cec18f84e.svg)

**Comment by ericfennis** [comment]
@karsa-mistmere Looks good.
Can you try one with decreased length of the two posts?

**Comment by karsa-mistmere** [comment]
Yeah, in the meantime I've already made it more centred in my drafts. :)
![construction](https://user-images.githubusercontent.com/17746067/218401852-247f6a5f-d432-49f3-b71a-1bb7b19fd36e.svg)
