### ISSUE TITLE
Router icon

### ISSUE THREAD

**Issue by MarkLyck** [lucide-icons/lucide#950]
## Icon Request

* Icon name: router
* Use case: iot, internet, device connected to the internet
* _Screenshots_ of similar icons:

<img width="844" alt="Screenshot 2023-02-15 at 17 07 44" src="https://user-images.githubusercontent.com/6841110/219084431-93172eaf-cfca-4508-811a-13d04b7cb7da.png">

**Comment by karsa-mistmere** [comment]
Nice request, we could sure do with one:
![image](https://user-images.githubusercontent.com/17746067/219105161-11d690d6-f6d7-40b5-a22f-f1bd6de179cf.png)
![image](https://user-images.githubusercontent.com/17746067/219105119-e280e393-69ea-4390-bd91-742e7e124d02.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Nice!

**Comment by ericfennis** [comment]
Closed by #957
