### ISSUE TITLE
Clipboard read icon

### ISSUE THREAD

**Issue by polyipseity** [lucide-icons/lucide#951]
## Icon Request

* Icon name: `clipboard-read`
* Use case: Reading from clipboard
* _Screenshots_ of similar icons: `clipboard-copy` with reversed arrow

**Comment by xnousnow** [comment]
![clipboard-read](https://user-images.githubusercontent.com/119923091/227765181-e43a352a-926e-406e-a4f9-60cedc50369d.svg)

I made a draft. I changed the position of the icon content so it is placed at the center of it.
