### ISSUE TITLE
Latest version of Lucide not compatible with older version of Angular

### ISSUE THREAD

**Issue by dsnoeck** [lucide-icons/lucide#976]
## Prerequisites

* Version: 0.118.0
* Are you running from source/main: no
* Are you using a released build: lucide-angular
* Operating system: Mac OSX
* Bits: 64bits

## Step to reproduce

Follow installation guide for Angular using version 13 of Angular.

### Actual behavior

ng serve not working

## Any message or error

`TypeError: Cannot create property 'message' on string '/Users/**/node_modules/lucide-angular/fesm2020/lucide-angular.mjs: This application depends upon a library published using Angular version 14.2.7, which requires Angular version 14.0.0 or newer to work correctly.`

### Expected behavior

I would love being able to use this lib with any version of Angular.

### Side note

There is no Lucide version for Angular 13. 0.93.0 is for Angular 11, 0.94.0 is for Angular 14

**Comment by karsa-mistmere** [comment]
This will be fixed by #949

**Comment by ericfennis** [comment]
@dsnoeck I released beta version of the new angular package under `lucide-angular@0.125.0-beta.0` from the changes from #949. Can you check if this version will solve your problem?

**Comment by karsa-mistmere** [comment]
@dsnoeck: Can you please confirm if v0.171.0 or later has resolved this issue?

**Comment by dsnoeck** [comment]
Version 0.190.0 working fine with Angular 13. Thank you very much for the fixes. 👏 🥳
