### ISSUE TITLE
Door related icon

### ISSUE THREAD

**Issue by WooWan** [lucide-icons/lucide#977]
## Icon Request

* Icon name:  door open, door close, emergency exit
* Use case: emergency exit or just exit for site
* _Screenshots_ of similar icons: 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/47740690/222458192-8bb57ed9-da09-49ad-9fef-10236ccd3b10.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/47740690/222458379-b945c80d-7c58-435b-89b9-0802a801fe54.png">

**Comment by karsa-mistmere** [comment]
How about?

![image](https://user-images.githubusercontent.com/17746067/223493601-4cf49b5f-2886-448c-887c-0691bc9bb333.png)
![image](https://user-images.githubusercontent.com/17746067/223493540-ff32da01-8fb9-4343-a318-bbaba3c93975.png)

Emergency exit probably depends on https://github.com/lucide-icons/lucide/issues/609

**Comment by WooWan** [comment]
nice work!

**Comment by xnousnow** [comment]
Any updates?

**Comment by DJB86** [comment]
I had a go at this, but only for the open variant as I quite like your one @karsa-mistmere
The second one I styled off the emergency exit one @WooWan posted with regards to perspective, but I think at small resolutions the first one looks more door-like.
![door-icons](https://user-images.githubusercontent.com/97555789/228055036-6b3a7102-f0e8-4705-9435-6b481d77f18b.png)
![door-icons-200](https://user-images.githubusercontent.com/97555789/228055043-a6e4789f-38f9-4c04-8206-0a94906845c0.png)
