### ISSUE TITLE
support HTML standard data-* attributes

### ISSUE THREAD

**Issue by GreenBattery** [lucide-icons/lucide#981]
Is it possible to add support for data-* attributes so that users who prefer to write standards-compliant code can use Lucide without having to add exceptions to code quality checking tools?

For example, instead of `<span icon-name='box'></span>` it should be possible to write `<span data-icon-name='box'></span>`.

The two options can co-exist if needed to maintain backward compatibility.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by GreenBattery** [comment]
slightly more thinking: attribute names could be like `data-lucide-name`, where "lucide" replaces 'icon' in today's scheme.

**Comment by ericfennis** [comment]
This is a good idea. `icon-name` attribute is not following the HTML spec this way. using `data-` fixes that. So good idea!
