### ISSUE TITLE
Aliases don't work with Jest, Vitest and Next.js

### ISSUE THREAD

**Issue by wojtekmaj** [lucide-icons/lucide#985]
## Prerequisites

* Version: 0.127.0
* Are you running from source/main: no
* Are you using a released build: yes
* Operating system: macOS 12
* Bits: 🤔 

## Step to reproduce

I have prepared a monorepo testing import aliases in a variety of different environments (Jest CJS, Jest ESM, Vitest, Vite, Next.js). Each subrepo has a "test" command that tests Home, LucideHome and HomeIcon imports. **Out of all these subrepos, only Vite passes.**

➡️ https://github.com/wojtekmaj/lucide-aliases-repro

### Actual behavior

* Home import works
* LucideHome import doesn't work
* HomeIcon import doesn't work

## Any message or error
See repro

**Comment by ericfennis** [comment]
@wojtekmaj Hmm that is unfortunate. Thanks for reporting, I will take a look!
