### ISSUE TITLE
School icon and variants

### ISSUE THREAD

**Issue by xnousnow** [lucide-icons/lucide#986]
## Icon Request

* Icon name: School building
* Use case: School selection
* _Screenshots_ of similar icons: [Font Awesome](https://fontawesome.com/icons/school?f=classic&s=solid)

Also, it would be great to have variants like lock, v, x, !, slash, etc.

**Comment by karsa-mistmere** [comment]
I already have a few building icon designs:
![image](https://user-images.githubusercontent.com/17746067/228056901-39b5e071-4422-4053-8c21-09d841cb88af.png)
![image](https://user-images.githubusercontent.com/17746067/228056952-5d5d6563-0c7b-4b73-8fd6-d5ddfa34a7f7.png)

Not sure about variants, what would be the use case for those?

**Comment by ericfennis** [comment]
@karsa-mistmere nice designs!

To me the third one is the most "school" like icon. But i think we should iterate a bit more on it. I think it has too much little details. Like the door and the roof extended edge.

**Comment by karsa-mistmere** [comment]
@ericfennis: Well, the first is a warehouse, the 2nd a store, the 4th a hotel and the 5th a monument, so of course those don't look like a school. :D 

How about this one? (existing building icons for comparison)
![image](https://user-images.githubusercontent.com/17746067/228571704-0f55f3f8-4f00-4bcf-a8ee-cd509852701b.png)

**Comment by ericfennis** [comment]
@karsa-mistmere Ah that makes sense.
Yeah I think this one is great!
Simple and clean.

**Comment by xnousnow** [comment]
<img width="375" alt="what about dis png" src="https://user-images.githubusercontent.com/119923091/228681521-6bce55f4-cd99-4258-b299-5f944a069f68.png">
Above school drawing is widely used in Korea, but I am not sure whether this design is also used in other countries.

**Comment by karsa-mistmere** [comment]
@xnousnow: I tried to abstract that design while sticking to Lucide's guidelines, but I'm afraid the princess is in another castle. 😄 
![image](https://user-images.githubusercontent.com/17746067/229139461-e6dff375-a0b1-4351-a03f-aa6f7e865b7c.png)
